### ISSUE TITLE
Profile message icon

### ISSUE THREAD

**Issue by namerci** [tabler/tabler#10]
Great work Paweł!

On the profile page https://tabler.github.io/tabler/profile.html there is a missing icon next to message input. There is element with classes `si si-camera`. Probably it should be `fa fa-camera` or `fe fe-camera`. Maybe better will be use here a `fe fe-plus` or something similar.

![image](https://user-images.githubusercontent.com/1153631/37854942-4c045806-2eed-11e8-8eaf-09739d8d71f2.png)

**Comment by codecalm** [comment]
thanks @namerci for feedback!
i've fixed it, soon will be online ;)

**Comment by codecalm** [comment]
fixed, online :)
