### ISSUE TITLE
Tabler nuget package

### ISSUE THREAD

**Issue by Hameds** [tabler/tabler#100]
I created a nuget package based on Tabler releases with sample layout based on Tabler empty page. 
nuget package repo is here https://github.com/Hameds/Tabler and with appveyor build new versions will push to nuget.org automatically.
here is a nuget badge in case you want to add it in readme
[![NuGet](https://img.shields.io/nuget/v/Tabler.svg)](https://www.nuget.org/packages/Tabler/)

**Comment by WashingtonMorais** [comment]
wow... awesome!

**Comment by Hameds** [comment]
This repo seems dead so it doesn't matter anymore
