### ISSUE TITLE
[BUG] Autoloading Webfonts

### ISSUE THREAD

**Issue by AnTheMaker** [tabler/tabler#1004]
Hi there - this is not really a "bug", but something which needs to be changed ASAP in my opinion.

I saw that Tabler autoloads webfonts from Google fonts, namely the Inter font.
The code I'm talking about can be found [here](https://github.com/tabler/tabler/blob/d2d9eb0146e54e8c4f0b671211fd97ad35b55368/src/scss/fonts/_webfonts.scss).

For privacy reasons, loading this resource directly from a 3rd-party for everyone isn't a great idea. Many people - like me - want to host all resources themselves and therefor need to remove [this line](https://github.com/tabler/tabler/blob/main/dist/css/demo.css#L10) from tabler.css and remember to do so after every upgrade.

Instead of autoloading the Inter font from Google Fonts directly in tabler.css, you could either declare Inter as the "recommended font" for Tabler and ask people to include it themselves, or you could ship the Inter font files directly with Tabler and include it locally. This would fix the privacy issue of loading the font from a 3rd-party in tabler.css without asking.

If you want, I can open a PR with this change, but it's really just a matter of not bundling the webfont scss module with the main tabler.css (and tabler.min.css) files.

Btw, I love Tabler - great job @codecalm and everyone involved!!

**Comment by baltpeter** [comment]
Personally, I would also like for the default to be changed. In the meantime, if you're using Sass, you can also use this workaround which doesn't require you to make manual changes after each update:

```scss
$google-font: false;
$font-family-sans-serif: Inter, -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;

@import '~@tabler/core/src/scss/tabler.scss';
```

This stops the Google font css from being imported:

https://github.com/tabler/tabler/blob/d2d9eb0146e54e8c4f0b671211fd97ad35b55368/src/scss/fonts/_webfonts.scss#L1-L4

**Comment by rjd22** [comment]
I'm thinking of downloading the google font and move it in the library. There is actually no reason to alway's get the font at googles servers IMO.

@codecalm what do you think?

**Comment by codecalm** [comment]
For me better idea is to load font via `<link rel="..." />` instead of css. If someone dont have `Inter` font will be loaded default system font.

**Comment by rjd22** [comment]
@codecalm I was actually thinking of just bundling the Inter font files with tabler so they are always available and can be downloaded the following helper can help us bundle them:

https://google-webfonts-helper.herokuapp.com/fonts

**Comment by codecalm** [comment]
I've changed it, now webfont is loaded locally instead of Google fonts :)

**Comment by AnTheMaker** [comment]
Perfect, thanks a lot!!

By the way: Inter provides a variable font you could use instead of loading each differnet weight. Check out the page of the creator of the font: https://rsms.me/inter/

Thanks again for the change!
