### ISSUE TITLE
[BUG] Vertical positioning on empty badges

### ISSUE THREAD

**Issue by Matt-Yorkley** [tabler/tabler#1006]
**Describe the bug**

Just a small thing; empty `badge` elements used as coloured dots don't align nicely vertically in places like tables.

**Device**

 - Browser: Firefox and Chrome
 - OS: Ubuntu LTS
 - Screen size: any

**To reproduce**

1. Go to https://preview.tabler.io/tables.html or https://preview.tabler.io/lists.html
2. Scroll down
3. See dots

**Screenshots**

![Screenshot from 2022-01-26 19-33-49](https://user-images.githubusercontent.com/9029026/151234790-ca904045-f1b0-47bc-8edf-7f8460f0feee.png)
![Screenshot from 2022-01-26 19-34-38](https://user-images.githubusercontent.com/9029026/151234793-859585f4-9188-4d93-a35b-3c662d7eae37.png)

**Potential Solution**

Adding `vertical-align: baseline` under the styles for `.badge:empty` fixes it:

 
![Screenshot from 2022-01-26 19-34-56](https://user-images.githubusercontent.com/9029026/151235408-ceb5105f-dd30-4fa9-a97a-202454352a34.png)
![Screenshot from 2022-01-26 19-35-51](https://user-images.githubusercontent.com/9029026/151235413-92b30e8d-8ec1-45dc-aff3-adf16e8b23c0.png)

**Comment by Matt-Yorkley** [comment]
What do you think? I could PR it if you like.

**Comment by rjd22** [comment]
@Matt-Yorkley looks indeed like a bug. If you could make a PR that would be awesome! Thank you!
