### ISSUE TITLE
dimmer-content opacity

### ISSUE THREAD

**Issue by johnunclesam** [tabler/tabler#101]
It seems to me too much this:

![image](https://user-images.githubusercontent.com/21275217/38902648-aa452cca-42a1-11e8-9c61-930d9d545b24.png)

Maybe this is better `opacity: .4` ?

**Comment by johnunclesam** [comment]
I made a PR just in case you agree.

https://github.com/tabler/tabler/pull/102

**Comment by codecalm** [comment]
merged, thanks!
