### ISSUE TITLE
[BUG] Card with bottom tabs has incorrect border radius

### ISSUE THREAD

**Issue by ollym** [tabler/tabler#1010]
![image](https://user-images.githubusercontent.com/143771/151667271-2eee3551-a371-4c64-bcb5-c097bb893254.png)

Bottom left of the main container has a border radius when it shouldn't

**Comment by codecalm** [comment]
thank you, I’ll check it!

**Comment by codecalm** [comment]
fixed :)

**Comment by ollym** [comment]
Almost, i think the border radius should be the same as it is on the top

![image](https://user-images.githubusercontent.com/143771/152439490-ba8d0d25-fef7-4a68-b452-d23654949d00.png)

![image](https://user-images.githubusercontent.com/143771/152439519-0633ee30-7639-4095-a41e-afc7a16bb467.png)

**Comment by codecalm** [comment]
fixed :)
