### ISSUE TITLE
[FEATURE] SASS of landing page

### ISSUE THREAD

**Issue by alighasemzadeh** [tabler/tabler#1012]
Hi
I need SASS https://tabler.io/ page.

**Comment by alighasemzadeh** [comment]
@codecalm 
Can you share https://tabler.io/ page css or scss files?

**Comment by codecalm** [comment]
I am working on a new version of the Tabler website. When it is ready I will publish its source code.

![Screenshot 2022-02-19 at 12 14 08](https://user-images.githubusercontent.com/1282324/154798556-083c067f-8a4a-4870-b2ae-52bbfa2af543.png)
