### ISSUE TITLE
[FEATURE] - adding NEW  or Updated flag in navigation menu on demo project

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1014]
nice feature will be if someone can add flag on the navigation or somewhere what was updated or added new  like this new awesome pages  

https://preview.tabler.io/uptime.html   
https://preview.tabler.io/playground-dark.html
https://preview.tabler.io/card-actions.html

Thank you very much

**Comment by codecalm** [comment]
i've fixed :)

**Comment by nejcdev** [comment]
Thats amazing!  FPR
