### ISSUE TITLE
[BUG] Dark mode issue for Tomselect

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1024]
**Describe the bug**

Some issues with Tomselect exist in dark mode at https://preview.tabler.io/form-elements.html:

- Selected text is not visible
- Not possible to identify optgroups (adding an example in one of the demo dropdowns would be great!) 

<img width="429" alt="Bildschirmfoto 2022-02-06 um 18 03 42" src="https://user-images.githubusercontent.com/533162/152692103-9aca8d35-378b-47f4-87d8-b1fc90b7e8bc.png">

**Comment by Nejcc** [comment]
Why this dropdown is not full width?

**Comment by rjd22** [comment]
@kevinpapst would it be possible to make an code example of the optgroups for me? I might fix that too.

**Comment by rjd22** [comment]
Outgroups still need to be fixed.

**Comment by kevinpapst** [comment]
Yeah sorry, didn't follow the bug. Main point is fixed. 

The optgroup is still white, but that is less problematic:

<img width="423" alt="Bildschirmfoto 2022-07-30 um 13 14 53" src="https://user-images.githubusercontent.com/533162/181908422-ca969377-e787-4244-a110-8cbf0ee49d3a.png">

**Comment by rjd22** [comment]
If you're willing and have time to make an PR for it I will gladly merge it ;).

**Comment by kevinpapst** [comment]
I'd be happy to invest more, but I am really missing the communication how the project is going forward. Is the dark mode replaced by the Bootstrap native dark mode that is now in alpha/beta? Is it even worth investing any time into the dark mode right now? 

How many breaking changes can we expect in the beta cycle (usually only used for bug fixing and not for introducing major changes) before a stable release? Not that this has anything to do with this issue right here, more of a general uncertainty that holds me back.

**Comment by rjd22** [comment]
@codecalm would be the one to answer correctly but I would guess that the original dark mode will not be replaced with Bootstrap dark mode soon.

It would be an good idea to focus releasing a stable version and improving tabler on a feature by feature basis.
