### ISSUE TITLE
[BUG] postcss-import: @charset must precede all other statements

### ISSUE THREAD

**Issue by HoseinGhanbari** [tabler/tabler#1025]
**Describe the bug**

**(tabler+angular) integration using angular.json**

```
ng serve
```

```
./node_modules/@tabler/core/dist/css/tabler.rtl.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/@tabler/core/dist/css/tabler.rtl.css - 

Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):

(9:1) postcss-import: @charset must precede all other statements
```

**Device**

 - Browser: Chrome v98
 - OS: Windows 10
 - Screen size: Laptop

**Env**
- NODE: v16.13.1
- NPM: 8.3.0
- Angular/CLI: 13.2.2

**To reproduce**

inside angular.json styles/scripts array load the tabler styles/scripts:

```
"./node_modules/@tabler/core/dist/css/tabler.rtl.css",
```

a simple fix would be commenting out `@charset`, but maybe its not the best solution out there.

**Comment by Kaylin6688** [comment]
SUN DeFi digital currency financial product with annual income up to 1440%!  !  !
 70,000 customers have used and trusted the platform
 Click the link to start the journey to get rich: 
https://www.funawealth.com?share_address=0x0E2E7bb6D1A83eDAB9C84411C018a050E7BE406C
![IMG_20220329_083442_957.jpg](https://user-images.githubusercontent.com/102297226/160789758-a8c74c59-0848-457d-9d22-bfef0ae75591.jpg)

**Comment by ronanflavio** [comment]
Is there any update?

**Comment by DarthRevanXX** [comment]
anybody

**Comment by rjd22** [comment]
Can someone confirm if this is still an issue? Else I'm closing this.

**Comment by HoseinGhanbari** [comment]
A fresh angular 17 project created using `@angular/cli` no longer produces this error. the initial bug report was for `"@tabler/core": "^1.0.0-beta8"` and today's test was for `"@tabler/core": "^1.0.0-beta20"` Happy Coding 🥳
