### ISSUE TITLE
[BUG] Inter font rendering issue

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1028]
**Describe the bug**

Since the integration of local font, I am seeing this issue for capital A & Q eg. [on this page](https://preview.tabler.io/form-elements.html): 

<img width="449" alt="Bildschirmfoto 2022-02-07 um 12 57 21" src="https://user-images.githubusercontent.com/533162/152783999-a5a43c87-d772-4fd4-805b-2bbc87a42684.png">

There is a [pretty long thread about this issue](https://github.com/google/fonts/issues/2602), so I guess you cannot fix anything.
Just wanted to raise awareness that the integration of the local font was a nice move, but caused problems as well...

This is pretty annoying in my app (German) where now 3 of 7 main menu items look strange:
<img width="892" alt="Bildschirmfoto 2022-02-07 um 13 02 34" src="https://user-images.githubusercontent.com/533162/152784609-30f06ca7-8393-4d97-8813-abcef6473dab.png">

**Device**

MacOS 10.15.7 with Safari 15.2 but also on Chrome 98.

**Comment by AnTheMaker** [comment]
That seems like an interesting bug... does this only happen with the woff2 files sourced from google fonts or also with the original font files from https://github.com/rsms/inter?
Alternatively, we could also try to use the variable font from the rsms/inter repo which shouldn't have this bug (afaik).
