### ISSUE TITLE
[FEATURE] - adding icons in navbar dropdown 

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1029]
nice feature will be to add icons to navbars dropdown menu  and sub-navbars

**Comment by KSruthiVel** [comment]
Hey! Can I work on this issue?

**Comment by kevinpapst** [comment]
Already possible (here with an example for Fontawesome):
```html
<a class="dropdown-item " href="/en/timesheet/">
  <span class="nav-link-icon d-md-none d-lg-inline-block text-center"><i class="fas fa-clock"></i></span>
  My times
</a>
```

There is even an example in the official demo:
<img width="466" alt="Bildschirmfoto 2022-07-30 um 14 25 06" src="https://user-images.githubusercontent.com/533162/181914107-136988c0-129f-4ab7-8a42-e32fa7a464cf.png">
