### ISSUE TITLE
[FEATURE] - Roadmap

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1032]
is there any roadmap for the future updates / features / visions?

Some suggestions to add
- Different auth pages (combined login / register)
- verification inputs before login. like.  4 5 6 7.   or.  G 4 K 3 3 Q q... or google authenticstion code... 
- count down screen
- subscription plans
- file manager
- galleries + lightbox?

**Comment by rjd22** [comment]
Since this theme is actually quite feature complete changes are made on what the needs of the developers are. If you want a feature feel free to contribute by sending us a PR.

Since this is a really broad issue. I'm closing this to keep track of specific requests.
