### ISSUE TITLE
'jekyll' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by SemKoolen** [tabler/tabler#104]
I am able to run jekylle from cmd with bash in an ubuntu environment but when i try to run the startup command from cmd i get this error.
I already tried to add bundle exec infront of the jekylle commands in package.json but this did not help as it just showed bundle not to be recognized

npm run serve

> tabler-ui@0.0.32 serve C:\Users\Marcel\Documents\GitHub\Tabler\tabler
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

[15:13:29] Using gulpfile ~\Documents\GitHub\Tabler\tabler\gulpfile.js
[15:13:29] Starting 'styles'...
[15:13:29] Starting 'styles-plugins'...
WARNING: The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.
         on line 10 of node_modules/bootstrap/scss/mixins/_text-hide.scss, in mixin `text-hide`
         from line 57 of node_modules/bootstrap/scss/utilities/_text.scss
         from line 14 of node_modules/bootstrap/scss/_utilities.scss
         from line 41 of node_modules/bootstrap/scss/bootstrap.scss
         from line 6 of src/assets/scss/bundle.scss

[15:13:29] Finished 'styles-plugins' after 395 ms
[15:13:30] Finished 'styles' after 1.02 s
[15:13:30] Starting 'build'...
[15:13:30] Finished 'build' after 54 μs

> tabler-ui@0.0.32 jekyll-serve C:\Users\Marcel\Documents\GitHub\Tabler\tabler
> jekyll serve --livereload

> tabler-ui@0.0.32 gulp-watch C:\Users\Marcel\Documents\GitHub\Tabler\tabler
> gulp watch

'jekyll' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 jekyll-serve: `jekyll serve --livereload`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.32 jekyll-serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marcel\AppData\Roaming\npm-cache\_logs\2018-04-19T13_13_31_230Z-debug.log
ERROR: "jekyll-serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.32 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marcel\AppData\Roaming\npm-cache\_logs\2018-04-19T13_13_31_371Z-debug.log

**Comment by beeman** [comment]
Hi @SemKoolen - have you tried the things explained on this page https://jekyllrb.com/docs/windows/ ?

**Comment by Prakkkmak** [comment]
Same here

**Comment by alihesari** [comment]
same +1

**Comment by alihesari** [comment]
@dsznajder Without any solution?

**Comment by dsznajder** [comment]
@alihesari Have you tried the explanation from page?
also, we are not using gulp anymore, so I'm pretty sure that it's related to version of it. 
If you still have issue, feel free to open a new one, with dependency versions -> (gulp, node, npm, etc.) :)

**Comment by bawantha** [comment]
same
