### ISSUE TITLE
Wrong path to compile bootstrap using esbuild

### ISSUE THREAD

**Issue by alejandrodevs** [tabler/tabler#1045]
Using rails 7 and cssbundling-rails I installed tables using `yarn add @tabler/core` and in the application.scss I imported it like this:
```
@import "@tabler/core/src/scss/tabler";
```

But I am getting the following error because of the `~` in the path:
```
Error: Can't find stylesheet to import.
@import "~bootstrap/scss/functions";
```

If I remove the ~ from paths, everything works as expected.
I found an existing issue but Im continue having the issue.
https://github.com/tabler/tabler/issues/226

Any ideas to solve this?

**Comment by FreexD** [comment]
Try using a path alias plugin for esbuild or perhaps the jsconfig will suffice - https://github.com/evanw/esbuild/issues/38

**Comment by zolzaya** [comment]
@alejandrodevs hey have you solved it?

**Comment by renancarvalhoo** [comment]
I'm facing the same issue

**Comment by sanzstez** [comment]
+1

**Comment by mkhairi** [comment]
I'm shared my minimal setup for rails 7 + esbuild + tabler starter template
repo: https://github.com/mkhairi/rails-tabler-starter (see esbuild.config.js)
demo: https://tabler.fly.dev/

**Comment by klaustopher** [comment]
@mkhairi Your example app does no longer work with [`esbuild-sass-plugin`](https://github.com/glromeo/esbuild-sass-plugin) versions `> 2.3.0`. I have extracted a sample and opened an issue over at the sass-plugin repo. See https://github.com/glromeo/esbuild-sass-plugin/issues/102

**Comment by kevinpapst** [comment]
The import path was adjusted in https://github.com/tabler/tabler/pull/1477 and released with Beta 18. 

If you still experience problems, please create a new issue.
