### ISSUE TITLE
[Feature request]: Integrating multiple fonts to choose from

### ISSUE THREAD

**Issue by rtd62** [tabler/tabler#105]
I would love it if there was a way to choose different fonts for the overall system (perhaps on the fly). As much as I like `Source Sans Pro`, I'm more keen on using `Apple System`, so I fell back to that on purpose.

**Comment by tdtgit** [comment]
I think the better way is build with Gulp as the author put it in repository (gulpfile.js). You can edit you main font in [`_variables.scss`](https://github.com/tabler/tabler/blob/dev/src/assets/scss/_variables.scss) and build your own CSS.

**Comment by dsznajder** [comment]
@rtd62 Hi, we started working on `v1` version. We will add it as a feature request and apply it before / right-after release. Stay tuned!
