### ISSUE TITLE
[BUG] Card background icon is practically invisible

### ISSUE THREAD

**Issue by diomed** [tabler/tabler#1052]
I know that background icon is supposed to be unobtrusive, but icon displayed in card with icon bg is practically invisible.
I suggest changing its color to more visible one. Such as baby blue or similar.

**Comment by kevinpapst** [comment]
Are you talking about these new styles? I find them quite appealing, but only from a visual perspective:
<img width="643" alt="Bildschirmfoto 2022-02-20 um 18 21 06" src="https://user-images.githubusercontent.com/533162/154855422-b046f30b-c3f7-443a-83ff-3a820b4dbc2c.png">

Sorry if you meant something else, but I wanted to share my 5 cents as well:

I was thinking about using them in my app and asked several people (the regular/average Joe, no techies) for their opinion and none of them identified those as clickable actions. Not a good sign from UX perspective, so I would use those buttons with caution...

**Comment by diomed** [comment]
![card with icon bg](https://user-images.githubusercontent.com/72777/154929988-e1039477-3c18-40ad-ba4a-ed6731632feb.png)

no, I'm talking about this. apparently, when you squint your eyes you'll see that this card actually has icon in its background.
should really be more noticeable.

**Comment by kevinpapst** [comment]
Ah right, hm an opacity of `.card-stamp-icon{opacity: .3;}` would indeed look better.
<img width="336" alt="Bildschirmfoto 2022-02-21 um 11 06 06" src="https://user-images.githubusercontent.com/533162/154933337-4d8d84a2-2d0c-4e15-9198-250f2ddda07e.png">
The opacity of `opacity: .075;` is [currently hardcoded](https://github.com/tabler/tabler/blob/main/src/scss/ui/_cards.scss#L69), you we can't use SASS to set the value. 
Seems you have to overwrite the rule in your project.

**Comment by codecalm** [comment]
yellow is very specific colour, so i've changed stamp opacity to `.2`. I've also added `$card-stamp-opacity` variable to config :)

**Comment by kevinpapst** [comment]
thanks @codecalm 👍
