### ISSUE TITLE
[BUG] Missing fonts in scss/fonts

### ISSUE THREAD

**Issue by ashrafkamarudin** [tabler/tabler#1056]
I tried installing Tabler with Laravel 9 and came across this error 

```
Can't resolve '../../node_modules/@tabler/core/src/scss/fonts/inter-v7-latin-ext_latin-300.woff2'
```

So I guess this is a bug?

**Comment by ashrafkamarudin** [comment]
I see. I can't find the issue so opened new one. Glad it's fixed !

**Comment by kevinpapst** [comment]
This was the PR removing the fonts: https://github.com/tabler/tabler/pull/1048
