### ISSUE TITLE
add some useful pages

### ISSUE THREAD

**Issue by miladimos** [tabler/tabler#1058]
this is good template but missing - account setting - profile page - single post page, .... pages and some landing page please add these pages

**Comment by diomed** [comment]
I think that there are various pages that you can use as single post page.

Typography / Markdown being one of them.
Even Licence page or if you want minimal just edit Terms of service page.

**Comment by rjd22** [comment]
There are some other issues that ask for these pages. I'm closing this as a duplicate.

But if you like you are free to contribute one of those pages by sending us a PR.
