### ISSUE TITLE
[Feature request]: Standalone custom select input

### ISSUE THREAD

**Issue by rtd62** [tabler/tabler#106]
So I was looking over the form components and was in need of a standalone customized select drop-down menu. I don't know enough CSS to implement something like that of my own, so I thought I could bring it up to you guys. I see customized drop-down buttons that are attached to other text inputs, but I need it to be standalone.

**Comment by dsznajder** [comment]
@rtd62 Hi, we started working on `v1` version. We will add it as a feature request and apply it before / right-after release. Stay tuned!
