### ISSUE TITLE
[BUG/MISSING] - layout-boxed missing NEW flag

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1066]
https://preview.tabler.io/layout-boxed.html :) missing NEW or Updated.  can be old one added too?

**Comment by codecalm** [comment]
fixed, thank you!

**Comment by Nejcc** [comment]
> @Nejcc what do you mean "old one too" ?

@codecalm   https://preview.tabler.io/layout-boxed.html.  without background dark?

**Comment by kevinpapst** [comment]
Adding a css rule is the option of choice I assume: 
```
.layout-boxed { background-color: #eee; }
```

**Comment by Nejcc** [comment]
> Adding a css rule is the option of choice I assume:
> 
> ```
> .layout-boxed { background-color: #eee; }
> ```

tnx :)
