### ISSUE TITLE
[BUG] - map-fullsize not working

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1068]
https://preview.tabler.io/map-fullsize.html

**Comment by fedale** [comment]
I think the problem is related not to Tabler.io map but to the "rate limit" on the counterpart API.

**Comment by novastream** [comment]
Like Tabler I had this setup:
<div class="page-wrapper page-wrapper-full">
<div class="page-body">
<div id="map" class="flex-fill">

flex-fill requires the parent element to have:
display: flex;
flex: 1;
flex-direction: column;

so just add this till fixed:
/* Tabler fixes */
.page-wrapper .page-body {
    display: flex;
    flex: 1;
    flex-direction: column;
}
