### ISSUE TITLE
[FEATURE] - profile page 

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1069]
is there any plans for profile page ?  @codecalm

**Comment by Nejcc** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/6236128/155856298-59ec254c-5f3d-482e-81fc-00d6c20b60c9.png">

**Comment by rjd22** [comment]
@Nejcc no plans yet but if you like you can contribute one to us.

**Comment by dqhung311** [comment]
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/6236128/155856298-59ec254c-5f3d-482e-81fc-00d6c20b60c9.png">
<img width="1267" alt="Screen Shot 2022-04-27 at 10 37 30" src="https://user-images.githubusercontent.com/26315867/165435325-aa8af86b-dc77-4d0e-8903-b9d7cc8ffe66.png">

**Comment by kevinpapst** [comment]
@dqhung311 can you share the css/html for the tabbed navigation in the modal? Looks really good, but I can't remember seeing something like that in the Tabler demo, so I guess it is custom project code?

**Comment by jaideepghosh** [comment]
@ rjd22 I'm working on this UI component.
Will raise a PR soon.

**Comment by rjd22** [comment]
@jaideepghosh How is it going? Do you have any update on this?

**Comment by rjd22** [comment]
This is now available at https://preview.tabler.io/settings.html
