### ISSUE TITLE
tabler.min.js:9  / Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by Bronxphoneix** [tabler/tabler#1073]
Hello, When open modan in modal, and when close it Console Error:

`Uncaught RangeError: Maximum call stack size exceeded.
    at Os._handleFocusin (tabler.min.js:9:112250)
    at HTMLDocument.<anonymous> (tabler.min.js:9:111875)
    at HTMLDocument.n (tabler.min.js:9:86335)
    at HTMLDocument.<anonymous> (modal.js:287:23)
    at HTMLDocument.n (event-handler.js:101:15)
    at Os._handleFocusin (tabler.min.js:9:112250)
    at HTMLDocument.<anonymous> (tabler.min.js:9:111875)
    at HTMLDocument.n (tabler.min.js:9:86335)
    at HTMLDocument.<anonymous> (modal.js:287:23)
    at HTMLDocument.n (event-handler.js:101:15)
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
_handleFocusin @ tabler.min.js:9
(anonim) @ tabler.min.js:9
n @ tabler.min.js:9
(anonim) @ modal.js:287
n @ event-handler.js:101
`
can you fix this

**Comment by Kaylin6688** [comment]
SUN DeFi is the safest financial product, profitable every day, every week, high deposit interest in ETH and TROX, USDT
 daily interest:
 deposit 5000usdt = 630 USDT
 deposit 30,000usdt=750 USDT
 deposit 60,000usdt= 1920 USDT
 deposit 80,000usdt= 2880 USDT
 deposit 100,000usdt = 4000USDT
 inbox for detailed advice: https://www.funawealth.com?share_address=0x0E2E7bb6D1A83eDAB9C84411C018a050E7BE406C

**Comment by Kaylin6688** [comment]
SUN DeFi digital currency financial product with annual income up to 1440%!  !  !
 70,000 customers have used and trusted the platform
 Click the link to start the journey to get rich: 
https://www.funawealth.com?share_address=0x0E2E7bb6D1A83eDAB9C84411C018a050E7BE406C
![IMG_20220329_083442_957.jpg](https://user-images.githubusercontent.com/102297226/160790035-3d11fed1-d31b-4444-b4df-e1549b08fac7.jpg)

**Comment by kevinpapst** [comment]
User @Kaylin6688 and postings reported to Github

**Comment by gladtoseeugo** [comment]
UNSCRIBE
