### ISSUE TITLE
Minor [BUG] On mozilla in Form-Select on focusing text is vanishing

### ISSUE THREAD

**Issue by Thaffa** [tabler/tabler#1079]
In mozila firefox, on the component FORM-SELECT when get focusing by press tab in previous component, the text is turning transparent, the bug/error is ocuring by

```
.form-select:-moz-focusring {
  color: transparent;
  text-shadow: 0 0 0 inherit;
}
```
on tabler css. I dont know if was proposital to get transparent on that, but only afecting on mozila, in lightmode and only plain formselect when using tomselect works fine.

 - Browser [Fiferox 97.0.1]
 - OS: [e.g. Windows 10]
 - Screen size [1920x1080]
 
 
![ColorTransparent](https://user-images.githubusercontent.com/40237385/156823816-c065aa2c-b06b-4cfd-84ee-eae0abb86860.png)

**Comment by rjd22** [comment]
@Thaffa does this fix your issue? https://github.com/tabler/tabler/pull/1085
