### ISSUE TITLE
Better file handeling

### ISSUE THREAD

**Issue by guifelix** [tabler/tabler#109]
It should be implemented a better file plugin, like [filepond](https://pqina.nl/filepond/) for example.

Here is an example that I did with some customizations:
![screenshot from 2018-04-20 17-31-27](https://user-images.githubusercontent.com/12631274/39072487-0cfa3452-44c1-11e8-8714-160ebd06dd10.png)

**Comment by ChriStef** [comment]
It will be nice if you could commit the code. Looks good.

**Comment by simioluwatomi** [comment]
You could also share a codepen snippet

**Comment by AnandChowdhary** [comment]
You can also checkout Uppload for file handling: https://github.com/elninotech/uppload

**Comment by rjd22** [comment]
Dropzone was added: https://preview.tabler.io/dropzone.html
