### ISSUE TITLE
[BUG] element tag select error

### ISSUE THREAD

**Issue by arezascarlet** [tabler/tabler#1090]
i found  the bug when i fill the form use Tab key, select tag is blank, but if we click with cursor is normally

![image](https://user-images.githubusercontent.com/49219720/159432982-1c66726a-d0ce-4275-a110-4bdb44e0d506.png)

**Comment by handsome-me** [comment]
Hello,
Can you assign this issue to me?

**Comment by arezascarlet** [comment]
> Hello, Can you assign this issue to me?

sorry i don't have permission to assign

**Comment by rjd22** [comment]
This is a duplicate of #1079 and a fix is waiting for release

**Comment by handsome-me** [comment]
I want to contribute to tabler so where can I start?
