### ISSUE TITLE
Top menu when on responsive

### ISSUE THREAD

**Issue by alexbainbridge** [tabler/tabler#11]
Hi - this looks great. Evaluating right now.

The top menu, when in small width mode, disappears and there is no alternative way of accessing the same functionality / menu links. 

Any thoughts on making the top menu have a thin width alternative?

Thanks. Alex

**Comment by codecalm** [comment]
Hi @alexbainbridge 
thanks for feedback, I've fixed it in 0ace1b8b1abc1a6b13c20d22b1de18dbce4b5ab1

**Comment by codecalm** [comment]
soon should be online

**Comment by alexbainbridge** [comment]
Great :)  

That was a little TOO quick !!

**Comment by codecalm** [comment]
@alexbainbridge I must recreate top menu, this is only fast fix. 
For few days should be better ;)

**Comment by facundofarias** [comment]
Hi there!
Already live? I cannot see the menu in mobile!

Thanks

**Comment by leandromatos** [comment]
Here the responsive menu has not yet appeared on the mobile.

**Comment by Shloken** [comment]
![nav](https://user-images.githubusercontent.com/36431703/38287206-6cf28c60-3797-11e8-9309-335a3987c1a6.png)

Can view source code: shloken.github.io

That's the best way to do it, it transitions from a standard css nav into a vertical drop-down. I'd be happy to do it for you if you want.

**Comment by Shloken** [comment]
@codecalm Made a bare bones version with just Bootstrap. This being the mobile side of the transition. Let me know if you want to collaborate. I can build you a sweet navbar and you can just throw it in whatever div container you want.

**Comment by codecalm** [comment]
@Shloken thanks for contributing. I did not expect an increase of popularity this repo, so I'm working with some bugfixes. This is the most important bug. 
I came back from vacation today, so I'm bugfixing today.

**Comment by Shloken** [comment]
@codecalm Cool just let me know what to change man I can do a lot with what you have. I need to get my commits up. I'll implement a nav menu and you can see if you like it.

**Comment by chrischu5** [comment]
Hi @codecalm , I'm trying to start contributing on open source projects and Tabler looks like a great project for me to dig into. Is this bug still live so that I could look into it? I'm still a huge beginner so any guidance would be welcome from anyone else that contributes to this! 👍

**Comment by codecalm** [comment]
fixed
