### ISSUE TITLE
jquery $ selector not work

### ISSUE THREAD

**Issue by iMohammadd** [tabler/tabler#110]
hi
i write a simple script to select parent nav-item of a dropdown-item and set it active
```javascript
$('.active').parent().parent().children(".nav-link").addClass("active");
```
but get this error
```javascript
Uncaught ReferenceError: $ is not defined
```

**Comment by ChriStef** [comment]
You seem not to have loaded first the Jquery library. Make sure you included it before the call.

**Comment by iMohammadd** [comment]
@ChriStef require.js is included on the head, i use blank page of tabler demo

**Comment by tdtgit** [comment]
Did you put your code in `require` block? Just like this:

```
require(['c3', 'jquery'], function (c3, $) {
    $(document).ready(function() {
        // Your code goes here
    });
});
```

**Comment by iMohammadd** [comment]
@tdtgit no, thank u

**Comment by tdtgit** [comment]
Glad your problem solved.
