### ISSUE TITLE
[FEATURE] Using my own brand color by replacing default color

### ISSUE THREAD

**Issue by devzakir** [tabler/tabler#1103]
## I love Tabler, I used in my many applications! One of the problem I find is changing primary and secondary color globally to match my brand color scheme

@codecalm can you guide how to change color scheme globally in tabler from scss file! 

Or can you use css variable for colors? So we can define color variable in the root and update anytime without any hassle!

**Comment by codecalm** [comment]
@devzakir collapsed sidebar and color variables are number one now in our priority list :)

**Comment by devzakir** [comment]
good to hear that, I am excited about tabler and it's feature releases!

**Comment by OgreTransporter** [comment]
Variables for the colors would be very nice. Then you could create the CSS files multiple times and create themes in different colors.

**Comment by Kerrick** [comment]
I've noticed that _some_ colors can be customized by customizing `--tblr-primary` at the `:root` level, but others (such as those [here](https://github.com/tabler/tabler/blob/dc8cad144a05afb443a10bfa8a803e430d54c8e5/src/scss/layout/_navbar.scss#L228)) cannot. I, too, would love universal support for a globally-customizable primary color (plus `--tblr-body-bg` and a few others).

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by olariuromeo** [comment]
https://getbootstrap.com/docs/5.0/customize/css-variables/

theoretically everything is possible, just add new variables and use them where you want them. Tabler is very similar to bootsrap, only maybe a little more complex
