### ISSUE TITLE
[FEATURE] search on icons view

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1105]
@codecalm  can you make search field on icons https://preview.tabler.io/icons.html#navbar-help.  will be much easier to find what you are looking for or put into groups  like u have for brands done ?  thank you

**Comment by codecalm** [comment]
search for icons is available on https://tabler-icons.io

**Comment by Nejcc** [comment]
@codecalm yeah i know there but in here   then put on help another dropdown link to this site  to not have on both sides   is there anywhere option to preselects settings of tabler theme.  proper colors light/dark. and size ?

**Comment by Nejcc** [comment]
oh the page was updated on icons :)
