### ISSUE TITLE
Form Horizontal is not working

### ISSUE THREAD

**Issue by ServerJunge** [tabler/tabler#111]
Hi,

form horizontal does not work.  ##

Greetings Serverjunge

**Comment by tdtgit** [comment]
Can you more specific? In the [demo](https://tabler.github.io/tabler/form-elements.html), the horizontal field works well.

![screen shot 2018-04-21 at 22 26 55](https://user-images.githubusercontent.com/4527866/39085858-31738b42-45b3-11e8-8275-5ddb8ed9ad0b.png)

**Comment by ServerJunge** [comment]
Hi,

shouldn't be the labels next to the input filed instead of above?

**Comment by chrisbaswell** [comment]
@ServerJunge, the layout your looking for is created using the .row, .col-sm-2 and .col-sm-10 classes.  Since Tabler is based on Bootstrap, the code you posted from Bootstrap's site will give you the desired result.  There's just not an example of it in the the Tabler demo.

**Comment by ServerJunge** [comment]
It does not work with the bootstrap code example.

https://i.imgur.com/HGflWMQ.png

**Comment by chrisbaswell** [comment]
@ServerJunge you were right...I submitted a pull request that fixes this issue

**Comment by emman355** [comment]
<form>
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="email@example.com">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
  </div>
</form>
Email

**Comment by emman355** [comment]
<form>
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="email@example.com">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
  </div>
</form>

**Comment by emman355** [comment]
`<form>
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="email@example.com">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
  </div>
</form>`

**Comment by emman355** [comment]
[https://getbootstrap.com/docs/4.0/components/forms/](url)
