### ISSUE TITLE
[FEATURE] Hello, we would like to have a Chinese version

### ISSUE THREAD

**Issue by MaoShengXiaoXiao521** [tabler/tabler#1116]
Hello, dear developers, we are a team from China.
In the process of using your UI library, because the language problem has brought us a lot of distress, we hope to launch a Chinese version.
In addition, our team can provide you with Chinese translation support, so we may need your authorization.
You can contact us by email: hello@heminran.email.cn

**Comment by diomed** [comment]
you don't need any authorisation, just fork it and make it.
project is MIT - open source - anyone can edit and do what they want with it.

https://github.com/tabler/tabler/blob/main/LICENSE
