### ISSUE TITLE
[BUG] Pricing Table on Dark Mode doesn't change separator text

### ISSUE THREAD

**Issue by redstonedesigner** [tabler/tabler#1119]
**Describe the bug**

Within the new "Pricing Table" example, the usage of Dark Mode results in the table separators showing as white bars with white text.  This does not seem like the intended behaviour, as it renders the separators completely useless.

**Device**

 - Browser: Latest Brave
 - OS: Windows 10
 - Screen size: 2560x1440

**To reproduce**

1. Go to https://preview.tabler.io/pricing-table.html
2. Observe separator changes between light and dark

**Screenshots**

If applicable, add screenshots to help explain this problem.

Light Mode:
![image](https://user-images.githubusercontent.com/29328096/167298056-d723d82c-7273-447a-bd86-b0b3cc15f906.png)

Dark Mode:
![image](https://user-images.githubusercontent.com/29328096/167298076-7ad7ea22-a249-4083-baba-c97d24927937.png)

**Comment by codecalm** [comment]
fixed :)
