### ISSUE TITLE
issue with dark mode

### ISSUE THREAD

**Issue by vogelor** [tabler/tabler#1122]
i am using a php script to generatge the html-output.
this script sets the class of the body to dark-mode. means, every page from the server has body class="theme-dark".
this works fine.
BUT when i try to print the page, the dark mode is also in the preview-window and the page is printed in dark mode.

can you please add a media query that the dark mode css is NOT PRINTED.

if you have a question or need more help - feel free to ask!

Oliver

**Comment by rjd22** [comment]
What browser are you using? Afaik this should work like you suggested because the code is there:

https://github.com/tabler/tabler/blob/5a9ae94e5824f151a3ccfb35618d73c8abe323a4/src/scss/mixins/_mixins.scss#L50

**Comment by vogelor** [comment]
Hmm - that`s really strange....
i found out, that the background is only black if i activate the printing-option "background" (or background images not really sure, because my browser is in english).
you can take a look here:

https://help.waniba.de/

BUT! you can only see the dark mode here if you activate the dark mode in your OS! i do auto-detect with javascript and php...

**Comment by rjd22** [comment]
What I do is use a cookie to store the preference of the dark-mode of the user and use that cookie to set the css `theme-dark` class in PHP.

Most likely if you do this printing will work fine because there is not much we can do about browsers ignoring our css flags.

**Comment by vogelor** [comment]
ok - if it works for you then i think this is "my problem". so i close the issue...

**Comment by gladtoseeugo** [comment]
Unscribe 
----- Original Message -----
