### ISSUE TITLE
[BUG] incorrect chart display in the mobile version

### ISSUE THREAD

**Issue by plastininikolay** [tabler/tabler#1125]
![Screenshot_2022-05-26-18-22-25-45_21da60175e70af211acc4f26191b7a77](https://user-images.githubusercontent.com/67545744/170469570-0d474355-133f-497f-9928-69bd952f1470.jpg)

**Comment by gladtoseeugo** [comment]
UNSCRIBE 


From: "Николай Пластинин" ***@***.***> 
To: "tabler/tabler" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Thursday, May 26, 2022 2:24:57 AM 
Subject: [tabler/tabler] incorrect chart display in the mobile version (Issue #1125) 





[ https://user-images.githubusercontent.com/67545744/170469570-0d474355-133f-497f-9928-69bd952f1470.jpg ]

**Comment by codecalm** [comment]
thank you for help :)
