### ISSUE TITLE
[BUG] Issues with using listjs datatable

### ISSUE THREAD

**Issue by jozefrebjak** [tabler/tabler#1126]
**Describe the bug**

@codecalm  I'm trying to use new datatable component, which is using ListJS. Sorting is working as expected, but when I'm trying to add Pagination there is an issues with class `page`. ListJS is using class `page` within `<a class="page">`and Tabler is using class `page` as a global for page. 

There is how to get working pagination
HTML

```html
<div class="card-footer d-flex align-items-center">
    <p class="m-0 text-muted listjs-showing-items-label"></p>
    <ul class="pagination mb-0 ms-auto"></ul>
</div>
```

JS 
```js
var options = {
        valueNames: ['sort-port', 'sort-status', 'sort-state'],
        page: 8,
        searchClass: 'listjs-search',
        sortClass: 'table-sort',
        listClass: 'table-tbody',
        pagination: [{
            name: 'pagination',
            paginationClass: 'pagination',
            innerWindow: 10,
            item: '<li class="page-item"><a class="page-link page" href="#"></a></li>',
        }],
    };

    var listjs = new List('listjs', options);

    // Count showing items
    function update_entries_label(listjs) {
        var total_items = listjs.items.length;
        var visible_items = listjs.visibleItems.length;
        var showing_items_label = total_items + " entries found";
        document.querySelector('.listjs-showing-items-label').innerHTML = showing_items_label;
    }

    update_entries_label(listjs);

    listjs.on('updated', function(list) {
        update_entries_label(list);
    });
``` 

As you can see we must to use class page within `item` to get correct pagination but when I use it like this we have an issue like: 
![CleanShot 2022-05-29 at 12 25 21@2x](https://user-images.githubusercontent.com/36922215/170863373-de2f908a-c4a3-4e5c-bb5e-274afc230d83.png)

because of class `page`. Within plain Bootstrap 5 it's fine, but with tabler is not.

**Comment by rjd22** [comment]
Since we don't actively support listjs I'm closing this. Most likely the situation has improved by now.
