### ISSUE TITLE
The litepicker project looks abandoned

### ISSUE THREAD

**Issue by ischaojie** [tabler/tabler#1136]
The homepage of `litepicker` say:
> Check out a new date picker: [easepick](https://easepick.com/)

The GitHub last commit at 2021.

**Comment by kikikiblue** [comment]
[air-datepicker](https://github.com/t1m0n/air-datepicker) is more active and it's documentation is better. 
I think air-datepicker is worth including in the discussion

**Comment by mholt** [comment]
I like easepick's date range UI better. (air-datepicker requires you to use 2 separate pickers)

But I like air-datepicker's singule date picker UI better, the ability to click through months and years, and also the _time picker_ is really useful.

Sigh, I wish there was a lib that merged the best of those two.

**Comment by rjd22** [comment]
@codecalm I'm thinking of reintroducing https://github.com/flatpickr/flatpickr again. It's not extremely actively developed anymore but imo that is a sign of it being quite mature. Also vue and react support is there so it has high portability.

What do you think?

**Comment by codecalm** [comment]
I've tested both `air-datepicker` and `litepicker` and have few problems:

`litepicker` uses Shadow DOM and it's very hard to styling it and extends default tabler styles
`air-datepicker` is better, but native is in russian language, and user mush include english language on each time

**Comment by rjd22** [comment]
@codecalm Wouldn't it not be better to choose a well established project? My reasoning would be that lately datapickers seem to jump out of the ground like mushrooms but when summer comes around the development seems to stop.

**Comment by mholt** [comment]
I've been playing with air-datepicker and really like it. The locale can be easily inlined, for example:

```
const picker = new AirDatepicker('#date-range', {
	locale: {
		days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
		daysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
		daysMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
		months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
		monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
		today: 'Today',
		clear: 'Clear',
		dateFormat: 'MM/dd/yyyy',
		timeFormat: 'hh:mm aa',
		firstDay: 0
	}
});
```

Customization is easy as well, it uses CSS variables. All other styles can be easily overridden with local style sheet as far as I can tell.

**Comment by slav0nic** [comment]
Litepicker author started new project https://easepick.com/

**Comment by slav0nic** [comment]
+1 for https://easepick.com/ , similar to litepicker but better with datetime support and many features
also works fine with current tabler without extra changes

**Comment by mholt** [comment]
Easepick does look nice. But FWIW, it doesn't have the features I need for my Tabler application, so I've started using air-datepicker. So, just something to keep in mind :upside_down_face:

**Comment by kevinpapst** [comment]
Unfortunately easepick (from the developer of litepicker) is GPL licensed and cannot be included in Tabler, which is MIT licensed.

I agree with @rjd22 it is really a pain that the good datepickers are always abandoned and the native HTML5 still have a terrible UX.

air-datepicker has potential and good accessibility, unfortunately also here: last commit in january...

**Comment by mholt** [comment]
If it means anything, one of those last commits (4 months ago) was to fix a bug I reported shortly before that, so a.good sign may be that the developers of air-datepicker are responsive.

**Comment by rjd22** [comment]
@kevinpapst I also feel supporting datepickers is kind of out of the scope of Tabler. Ofcourse it's great that at least one is supported and recommended but nothing is stopping you from just styling your favorite one and not using the one that is default integrated in Tabler.
