### ISSUE TITLE
[FEATURE] use li in nested menu

### ISSUE THREAD

**Issue by tacman** [tabler/tabler#1137]
**Is your feature request related to a problem? Please describe.**

I'm generating the menu dynamically, and the "leaf" links are not list item elements, which would be easier to generate and I think would be more semantically correct.
**Describe the solution you'd like**

This is the current (simplifed) menu html:
```html
<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle show" href="#navbar-help" data-bs-toggle="dropdown" data-bs-auto-close="false" role="button" aria-expanded="true">
                  <span class="nav-link-title">
                    Help
                  </span>
                </a>

                <div class="dropdown-menu show" data-bs-popper="static">
                  <a class="dropdown-item" href="./docs/index.html">
                    Documentation
                  </a>
                  <a class="dropdown-item" href="./changelog.html">
                    Changelog
                  </a>
                </div>
              </li>
```

What I'd like to see is the two dropdown-item links inside of a ul / li, with the classes attached to those elements, rather than to divs.  

```html
                <ul class="dropdown-menu show" data-bs-popper="static">
<li class="dropdown-item">

                  <a  href="./docs/index.html">
                    Documentation
                  </a>
</li>

<li class="dropdown-item">
                  <a href="./changelog.html">
                    Changelog
                  </a>
</li>
</ul>
```

I'll confess that it's easier to use this structure with rendering a knp menu, but it also does _feel_ more semantically correct.

**Describe alternatives you've considered**

I've considered creating the ul and li and adding classes to suppress indentation and formatting, but my code is still somewhat complicated by creating divs.  Because this obviously requires recursion, it gets a bit messy.  So I figured I'd ask if this is something you'd consider.

**Comment by rjd22** [comment]
Since this would be a breaking change without any big gains I would not date to touch it. sub-menu's are already something that are different from how bootstrap has intended.
