### ISSUE TITLE
[BUG] Multiple bugs after Bootstrap update

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1145]
Not sure if this is related to the "Bootstrap beta" PR, but it was working just a couple of days ago and this here was the biggest change lately. So I assume this update broke several things, one of it was modals:
https://preview.tabler.io/docs/modals.html

Unreadable in both dark and normal mode now, e.g.
<img width="883" alt="Bildschirmfoto 2022-06-07 um 21 12 56" src="https://user-images.githubusercontent.com/533162/172463535-c6c5d068-70f2-44ba-a4ec-3e89009ac710.png">

I can look for more quirks if you like. You know: I saw the PR when you opened it and was about to ask for a new release, but you were even quicker with the merge 😁 

Here is another glitch:
<img width="545" alt="Bildschirmfoto 2022-06-07 um 21 21 26" src="https://user-images.githubusercontent.com/533162/172464832-c08329e3-20e3-429f-88db-fb8a1cc83948.png">

I'd like to offer my help for the future. I don't mind if you ping me directly and call out for help with testing. I can only speak for myself, but I am available and happy to support in that way.

Or is this just a misunderstanding on my end and https://preview.tabler.io simply outdated?

_Originally posted by @kevinpapst in https://github.com/tabler/tabler/issues/1131#issuecomment-1149081320_

**Comment by dheineman** [comment]
@kevinpapst I cannot seem to reproduce the second glitch where the button text is not visible. Are you still seeing this and if so, do you have a specific way to reproduce it?

**Comment by kevinpapst** [comment]
Interesting, now that you answered I tried in other browsers (Firefox works) and maybe it is a Safari only bug.

I made this screenshot right now:
<img width="847" alt="Bildschirmfoto 2022-07-30 um 13 02 20" src="https://user-images.githubusercontent.com/533162/181908014-f798a10c-4afd-484e-9686-82cbe979c0be.png">

So nothing special, just open the page.

**Comment by kevinpapst** [comment]
Firefox says this:
<img width="546" alt="Bildschirmfoto 2022-07-30 um 13 05 02" src="https://user-images.githubusercontent.com/533162/181908080-6b66707c-290e-4603-9f10-03e1e1e58bf9.png">
Maybe the variable `--tblr-color-text` is missing and different browsers handle that problem in different ways?

**Comment by dheineman** [comment]
> Maybe the variable `--tblr-color-text` is missing and different browsers handle that problem in different ways?

yeah i just came to the same conclusion. 

It was indeed caused by the [bootstrap 5.2.0-beta1 PR ](https://github.com/tabler/tabler/pull/1131/files#diff-f98448f89da1f5adc93e201b22af74c3ca4c7739062f52f27c2cd90540fa01c3L1) but i am unsure if and where this variable should be defined so i will leave this one to @codecalm :)

**Comment by kevinpapst** [comment]
Thanks for helping to investigate the issue! I opened a follow up bug, so it is easier for @codecalm to understand it: 
https://github.com/tabler/tabler/issues/1177

I am closing here, as you fixed the modals already 😄
