### ISSUE TITLE
Beta10 not in npm packages?

### ISSUE THREAD

**Issue by yangfancn** [tabler/tabler#1147]
I see the latest version in npmjs.com/package/ is 1.0.0-beta9

**Comment by kevinpapst** [comment]
Here as well, `yarn upgrade` still installs beta9:
<img width="286" alt="Bildschirmfoto 2022-06-24 um 18 56 46" src="https://user-images.githubusercontent.com/533162/175607583-dfe8ea01-75dd-45a0-a498-ab3afd5b836b.png">

@codecalm can you push the beta-10 update to npm, so we can start testing?

**Comment by kevinpapst** [comment]
For everyone else who has hard times (like me) figuring this one out, the version is indeed available but not tagged as latest.

The website shows beta9 as latest, but if you switch to the Versions page you see beta10:
https://www.npmjs.com/package/@tabler/core?activeTab=versions

So you have to set the version in your update command:
```
npm i @tabler/core@1.0.0-beta10
```
