### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ArgeniaP** [tabler/tabler#115]
Hello, I found some error when I run `npm install`. And I take a screenshoot so you can see the problem.

![npm install error](https://user-images.githubusercontent.com/35943150/39138902-f889d0c2-474a-11e8-9d88-c12b65959070.png)

Sorry if this issue already in discussion

**Comment by nimaen** [comment]
Hi, those are warnings, not error :)

**Comment by ArgeniaP** [comment]
Sorry my fault, thank you :)
