### ISSUE TITLE
[FEATURE] Taiwan area in maps

### ISSUE THREAD

**Issue by lilidream** [tabler/tabler#1156]
It is a great project for web development, but I found that maps in Vector Maps and other map components, Taiwan area is regarded as a country. In fact, Taiwan has always been part of China and it is not a independent country.

Please put Taiwan area back into China in maps, thank you!

**Comment by kevinpapst** [comment]
This nonsense issue should be closed immediately.

**Comment by zhu0629** [comment]
Taiwan is an inalienable part of the Chinese territory.

**Comment by codecalm** [comment]
@lilidream @zhu0629 we use `jsvectormap` library, so your request is independent of us 
please ask author of this library
