### ISSUE TITLE
[BUG] Nav Logo on Vertical Layout

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#1163]
![tabler_bug](https://user-images.githubusercontent.com/8596319/177921947-ed6e3c0f-cba2-4855-8225-cfcb1fd294aa.gif)

Logo jump

build tabler last
test to browser Opera last, Edge last

and 

![image](https://user-images.githubusercontent.com/8596319/177922498-97ed3d5d-aa54-45ef-ba06-2a63c67c3d2e.png)

**Comment by ZeoNish** [comment]
fix... need use in ".dropdown-item" span.nav-link-icon and span.nav-link-title

`<a class="dropdown-item"><span class="nav-link-icon d-md-none d-lg-inline-block"><svg class="icon icon-tabler icon-tabler-math-symbols"></svg></span><span class="nav-link-title">text</span></a>`

**Comment by shakti1590** [comment]
anyone work on this issue?

**Comment by H20220009** [comment]
@ZeoNish 
can you assign this issue to me, I want to work on this issue.
