### ISSUE TITLE
[BUG] border and box shadow of toast at beta10 looks weird

### ISSUE THREAD

**Issue by kikikiblue** [tabler/tabler#1166]
**Describe the bug**

The border and box shadow css is weird. 

**Device**

 - Browser [e.g. Chrome ver.103.0.5060.114]
 - OS: [MAC OS Monterey v12.4]
 - Screen size [e.g. 1680x1050]

**To reproduce**

can be checked at Tabler sample page https://preview.tabler.io/docs/toasts.html 

**Screenshots**
<img width="455" alt="스크린샷 2022-07-18 오후 1 32 49" src="https://user-images.githubusercontent.com/481619/179445916-9c32946e-dc7d-4b09-ae75-4d2717b5e32f.png">

**Comment by dheineman** [comment]
Not sure what you find weird about the shadow that looks fine to me but the left border does look a off.

@rjd22 You specifically set the left border to be different from the rest in [#1091](https://github.com/tabler/tabler/pull/1091/files#diff-5cf19fd0bfc348d096349ef9be45d819971bb2d66a439317d71cad7d5286e657R4) was there any reasoning behind this?

**Comment by kikikiblue** [comment]
@dheineman You're right. What I find weird is the left border. I'm sorry I should have been clearer. It's because English is not my first language

**Comment by rjd22** [comment]
@dheineman I think it was copied from another boxed layout. I think we can change it.
