### ISSUE TITLE
[FEATURE] Please, avoid epilepsy-inducing white flashes when Dark mode is active

### ISSUE THREAD

**Issue by SomwareHR** [tabler/tabler#1172]
**Is your feature request related to a problem? Please describe.**
When in Dark mode - clicking on many, if not all, options first flashes short bright white page, then turns into dark mode.

**Describe the solution you'd like**
When in Dark mode - stay in dark mode. Or fade in. Or something.

**Describe alternatives you've considered**
Not many out there, true; there is a giant lack of attention to details with modern web "app" developing.

**Misc**
Tested with Edge and Firefox.

**Comment by NinadRao0707** [comment]
Hello @SomwareHR ,
If you can add this script tag at the very start after adding the body tag in the base.html, it should work. 

`<script>
const selectedTheme = localStorage.getItem('selected-theme')
document.body.classList[selectedTheme === 'dark' ? 'add' : 'remove'](darkTheme)
</script>`

Hope this solves your issue of having a white background while refreshing or clicking on some of the options on the page.
Thanks!

**Comment by rjd22** [comment]
This should be fixed now.

**Comment by gladtoseeugo** [comment]
UnSubscribed
----- Original Message -----

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by SomwareHR** [comment]
Thank you.

**Comment by gladtoseeugo** [comment]
Unscribe 
----- Original Message -----
