### ISSUE TITLE
Feature request - cross panel interactivity

### ISSUE THREAD

**Issue by voltcode** [tabler/tabler#1173]
It would be amazing if tabler supported cross panel dependencies.
For example - support clicking USA on one panel could trigger data filtering in other panels.
An example of this behavior can be seen on dc.js home page:
https://dc-js.github.io/dc.js/

I wouldn't expect tabler to implement everything though but provided essential hooks for triggering updates of other panels, or maybe made it easy to use crossfilter library or similar.

**Comment by dheineman** [comment]
I am not familiar with this library but from what i can tell by reading the documentation/examples you should already be able to implement this yourself in your application.

Tabler does not have a javascript framework from which to provide hooks or the likes and personally i do not think it should.

Take for example the ApexCharts integration: Tabler provides CSS styling that will make the charts fit better in the theme. But initialising the charts themselves is the responsibility of the end user application, whether this be trough a javascript framework or some inline script.

**Comment by rjd22** [comment]
Tabler is indeed a UI framework. We do use some vanilla js for the examples but encourage users to implement their own solutions. 

There are just so many ways of solving things in JS that we rather focus on UI side of things and less on the front end frameworks.
