### ISSUE TITLE
Issue with the bottom on small charts on dashboard

### ISSUE THREAD

**Issue by martyncoup** [tabler/tabler#1178]
I have this issue with one of the widgets on the dashboard, I can't seem to get to the bottom of it.

![image](https://user-images.githubusercontent.com/184028/182133726-f7a7b363-f39c-478c-8823-df205575ce6e.png)

Notice from the image that on the right side, the chart does not stay right at the bottom of the widget, but it does on the left. I have tried different chart types and ranges of data. The only thing I could think of was a negative value in the chart data but this does not seem to be the case.

**Comment by martyncoup** [comment]
I've solved this now, looks like a custom style was interrupting things, removed and now sorted!

**Comment by razaahmad333** [comment]
@codecalm please close this issue, 
seems resolved

**Comment by gladtoseeugo** [comment]
----- UnSubscribed -----

**Comment by gladtoseeugo** [comment]
UNSCRIBE
