### ISSUE TITLE
[Request] Please, add Modals/Dialogs component

### ISSUE THREAD

**Issue by rbqdev** [tabler/tabler#118]
Hello Guys.
Please add a Modal/Dialogs components. I really think it's very important for the project.

Thanks

**Comment by NorthFoxz** [comment]
+1

**Comment by dansen** [comment]
just add bootstrap.min.js in your page!and the modal will show.

**Comment by paulocastellano** [comment]
+1

**Comment by RishabhSinghShekhawat** [comment]
Alright. Will do it.

**Comment by akifyanbak** [comment]
+1
with fade effect please

**Comment by codecalm** [comment]
Modals/Dialogs will be in Tabler 1.0 version. Probably until end of the year.

**Comment by mcdappdev** [comment]
Hi @codecalm, big fan of your work! Thanks for the countless hours you spent crafting this framework. Do you have any prediction of when the modals will be done? For some reason I can't get any outside modals to properly display (jquery modals or bootstrap) and it's hindering the progress of our development. Any insight would be greatly appreciated :) thanks!

**Comment by zdeneksejcek** [comment]
Hi @codecalm, thanks for your work. Would be great to have dialogs, I am using your framework on my current pet project and I need on dialog only, but I can't go without it. Until you make 1.0 ready, I will have to hack it my self :)

**Comment by iDemonix** [comment]
The project I'm using tabler for needs modals now, so I'm going to hack them in. Any chance this is planned for release soon @codecalm ?

**Comment by byruddy** [comment]
+1

**Comment by codecalm** [comment]
how about that? 

<img width="1440" alt="Screenshot 2020-01-14 at 22 13 01" src="https://user-images.githubusercontent.com/1282324/72383178-33beac00-371b-11ea-9116-b2974bd95218.png">

**Comment by iDemonix** [comment]
Looks good!

**Comment by codecalm** [comment]
final version of modals:

<img width="1424" alt="Screenshot 2020-02-18 at 22 36 56" src="https://user-images.githubusercontent.com/1282324/74780318-a2a19e80-529f-11ea-86da-50c07574dbfe.png">

**Comment by codecalm** [comment]
modals are available in core branch

**Comment by codecalm** [comment]
done

**Comment by mholt** [comment]
(Sorry to comment on an old issue, but) how can modals be activated or triggered programmatically with JS?
