### ISSUE TITLE
[BUG] number input with `form-control-sm` looks weird

### ISSUE THREAD

**Issue by msayed98** [tabler/tabler#1180]
**Describe the bug**

number input with `form-control-sm` looks weird.

**Device**

 - Browser Chrome 103.0.5060.134
 - OS: Ubuntu 20.04.4 LTS
 - Screen size 1920x1080

**To reproduce**

1. Go to https://preview.tabler.io/docs/form-elements.html#input-size
2. inspect on the small input and change the type to `number`

**Screenshots**
![image](https://user-images.githubusercontent.com/101716569/182411651-67d8b4ae-4729-440c-856d-618b4ab62fce.png)

Expected behavior: bootstrap `form-control-sm` with number input
![image](https://user-images.githubusercontent.com/101716569/182411989-01b94655-3ea1-4159-aa5a-25c2ccd6861f.png)

**Comment by kevinpapst** [comment]
I can confirm in Safari 15.5:
<img width="792" alt="Bildschirmfoto 2022-08-03 um 14 06 22" src="https://user-images.githubusercontent.com/533162/182603752-7fc67e1c-7fe2-42f6-b8f9-c248e8212eb8.png">

But why do you open two issues, #1181 is the same bug.

**Comment by msayed98** [comment]
I thought they are 2 different issues, merge them if you want

**Comment by rjd22** [comment]
Looks quite ok now in Firefox. Is this still an issue?

![2022-11-09T12:07:03,032763903+01:00](https://user-images.githubusercontent.com/160743/200814457-29d3db8c-815d-4a8b-ac87-dd0a68bc57b0.png)

**Comment by kevinpapst** [comment]
Still an issue IMO.

Safari at https://preview.tabler.io/docs/form-elements.html#input-size:
<img width="846" alt="Bildschirmfoto 2022-11-09 um 12 58 16" src="https://user-images.githubusercontent.com/533162/200824721-b50b1271-6043-4ad7-9ff7-33d51b47c34c.png">

Brave / Chrome at https://preview.tabler.io/docs/form-elements.html#input-size:
<img width="838" alt="Bildschirmfoto 2022-11-09 um 12 59 00" src="https://user-images.githubusercontent.com/533162/200824838-c34937b1-cc8e-45e5-a074-75fec01aae09.png">

This is Safari (tested with 5.0 and 5.2) at https://getbootstrap.com/docs/5.2/forms/form-control/:

<img width="827" alt="Bildschirmfoto 2022-11-09 um 13 04 26" src="https://user-images.githubusercontent.com/533162/200825868-8df32c0a-a174-4518-abbe-3065b31fa451.png">

This is Chrome (tested with 5.0 and 5.2) at https://getbootstrap.com/docs/5.2/forms/form-control/:

<img width="832" alt="Bildschirmfoto 2022-11-09 um 13 02 15" src="https://user-images.githubusercontent.com/533162/200825446-77545776-507f-41de-b008-126326ad8976.png">

**Comment by codecalm** [comment]
I've fixed it in #1360
