### ISSUE TITLE
[BUG] number input in RTL mode looks weird

### ISSUE THREAD

**Issue by msayed98** [tabler/tabler#1181]
**Describe the bug**

number input in RTL mode looks weird

**Device**

 - Browser Chrome 103.0.5060.134
 - OS: Ubuntu 20.04.4 LTS
 - Screen size 1920x1080

**To reproduce**

1. Go to https://preview.tabler.io/layout-rtl.html
2. scroll to invoices section
3. inspect the input element and change the type to number, you may also remove `form-control-sm` class

**Screenshots**
![image](https://user-images.githubusercontent.com/101716569/182416073-19112d76-b7b5-405d-a415-7ad697d5055d.png)

Expected behavior: bootstrap 
![image](https://user-images.githubusercontent.com/101716569/182416213-da95f11a-54ee-4424-a278-1f789849ca81.png)

**Comment by noobyogi0010** [comment]
Hey @msayed98 
I would like to work on this issue if no one else if working on it.
Thanks!

**Comment by kevinpapst** [comment]
Just tested and this was fixed with one of the last releases, see #1180
