### ISSUE TITLE
[BUG] `datagrid` classes not rendering as expected

### ISSUE THREAD

**Issue by asharnadeem** [tabler/tabler#1187]
**Describe the bug**

The `datagrid` classes don't seem to be rendering as expected. Copy pasting the HTML from the docs results in something drastically different. I didn't find any reference to datagrid in the tabler source code either.

**Device**

Latest Chrome, MacBook Pro 2022, all screen sizes

**To reproduce**

1. Try to use `datagrid` classes in HTML 
2. See error **Screenshots**

<img width="1296" alt="Screen Shot 2022-08-04 at 9 23 51 PM" src="https://user-images.githubusercontent.com/47264377/182981805-45412929-5d94-48d6-b572-d7c82db30500.png">

**Comment by dheineman** [comment]
If you are using the latest published version on npm (`1.0.0-beta10`) than that is correct. The datagrid is recently new and has not made it into a released version yet.

The source for datagrid can be found [here](https://github.com/tabler/tabler/blob/0b76efb9e9fef7a5b14b6e54fb5f74849fa16895/src/scss/ui/_datagrid.scss) btw :)

**Comment by gladtoseeugo** [comment]
Unscribe 
----- Original Message -----
From: Ashar Nadeem ***@***.***>
To: tabler/tabler ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Thu, 04 Aug 2022 21:26:48 -0400 (EDT)
Subject: [tabler/tabler] [BUG] `datagrid` classes not rendering as expected (Issue #1187)

**Describe the bug**

The `datagrid` classes don't seem to be rendering as expected. Copy pasting the HTML from the docs results in something drastically different. I didn't find any reference to datagrid in the tabler source code either.

**Device**

Latest Chrome, MacBook Pro 2022, all screen sizes

**To reproduce**

Steps to reproduce the behavior:

1. Try to use `datagrid` classes in HTML 
2. See error **Screenshots**

<img width="1296" alt="Screen Shot 2022-08-04 at 9 23 51 PM" src="https://user-images.githubusercontent.com/47264377/182981805-45412929-5d94-48d6-b572-d7c82db30500.png">


-- 
Reply to this email directly or view it on GitHub:
https://github.com/tabler/tabler/issues/1187

**Comment by asharnadeem** [comment]
@dheineman Sounds good, thanks for that clarity! Is the same also true for the calendar component?

**Comment by dheineman** [comment]
The [calendar code](https://github.com/tabler/tabler/blob/4dff0e733b97c1baf87c80e967006f39249f47bd/src/scss/ui/_calendars.scss) was added a while ago but there does not seem to be a demo or docs page for it so i am unsure of the current status. 

@codecalm is the calendar component just missing docs/examples or was it intended to be removed and not fully cleaned up?

fyi: a new version of tabler (beta11) was released today which includes the datagrid component. So you can update to start using it.

**Comment by asharnadeem** [comment]
`beta11` looks awesome, just started using it, thank you! 

To clarify, by calendar component, I was referring to the date picker in the form components. I get the following when trying to use the inline date picker, and for the input field date pickers, nothing renders at all.

<img width="101" alt="Screen Shot 2022-08-05 at 10 19 57 PM" src="https://user-images.githubusercontent.com/47264377/183229779-8bf65fb9-6e02-43f3-ac9a-fb31b4ebe6f4.png">
I

**Comment by dheineman** [comment]
Ah that is the [litepicker](https://www.npmjs.com/package/litepicker) plugin.

It seems there is no documentation page for this on either, though given that it has been sort of superseded by [easepick](https://easepick.com/) and there is an open issue https://github.com/tabler/tabler/issues/1136 to switch it might be replaced at some point.

Either way for now, if you have the litepicker plugin installed you should be able to initialize it with something akin to this:

```html
<div class="datepicker-inline" id="datepicker-birthday"></div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
    	window.Litepicker && (new Litepicker({
    		element: document.getElementById('datepicker-birthday'),
    	}));
    });
</script>
```

If you are still running into issues I suggest creating a new Q&A [discussion](https://github.com/tabler/tabler/discussions) as I believe the original "bug" this issue was created for is resolved.

**Comment by asharnadeem** [comment]
Appreciate all the help, thank you! Closing this out for now :)
