### ISSUE TITLE
[BUG] Table colors in dark mode look too bright 

### ISSUE THREAD

**Issue by dheineman** [tabler/tabler#1193]
**Describe the bug**

The table (row) colors do not look very good/integrate properly in dark mode.

**Device**

 - Browser: Chrome Version 103.0.5060.134 (Official Build) (arm64)
 - OS: macOS 12.4 (21F79)
 - Screen size: not applicable

**To reproduce**

1. Add a table as defined in the [bootstrap docs](https://getbootstrap.com/docs/5.2/content/tables/#variants) to your page
2. Enable dark mode

**Screenshots**

![Screenshot 2022-08-08 at 09 27 54](https://user-images.githubusercontent.com/516028/183363648-689a7ac4-4523-4a65-b383-c4ed336e9644.png)

**Comment by rjd22** [comment]
@dheineman would you be willing to make a fix for this?

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by gladtoseeugo** [comment]
UNSCRIBE 



From: "Dave Heineman" ***@***.***> 
To: "tabler" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Sunday, August 7, 2022 11:37:24 PM 
Subject: [tabler/tabler] [BUG] Table colors in dark mode look too bright (Issue #1193) 





Describe the bug 

The table (row) colors do not look very good/integrate properly in dark mode. 

Device 

    * Browser: Chrome Version 103.0.5060.134 (Official Build) (arm64) 
    * OS: macOS 12.4 (21F79) 
    * Screen size: not applicable 


To reproduce 

Steps to reproduce the behavior: 

    1. Add a table as defined in the [ https://getbootstrap.com/docs/5.2/content/tables/#variants | bootstrap docs ] to your page 
    2. Enable dark mode 


Screenshots 

[ https://user-images.githubusercontent.com/516028/183363648-689a7ac4-4523-4a65-b383-c4ed336e9644.png ]

**Comment by dheineman** [comment]
I am not that good with SCSS but i gave it an attempt in https://github.com/tabler/tabler/pull/1200
