### ISSUE TITLE
[BUG] Radio button not working correctly on demo page

### ISSUE THREAD

**Issue by tbolon** [tabler/tabler#1196]
**Describe the bug**

In the [form elements](https://preview.tabler.io/form-elements.html) demonstration page, the radio buttons at the right of the page does not work correctly: previous choices remains checked and you can't uncheck them.

It's not a bug on the lib itself, but a strange behavior which could suggest a bug in the project.

You should simply add a name attribute at least for inputs Option 1 and Option 2 in "Radios" group, and another name attribute for the inputs in "Inline Radios"

**Device**

 - Browser: Chrome v104
 - OS: Win11
 - Screen size: 3840 x 2560

**To reproduce**

1. Go to [form elements](https://preview.tabler.io/form-elements.html) demonstration page,
2. Click on right radio button "Option 2"
3. Option 1 should be unchecked.

**Screenshots**

![Screenshot 2022-08-10 141726](https://user-images.githubusercontent.com/127185/183899438-da33174a-30b2-4889-9324-4926fda82382.jpg)

**Comment by gladtoseeugo** [comment]
UnSubscribed
----- Original Message -----
From: Thomas Bolon ***@***.***>
To: tabler/tabler ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Wed, 10 Aug 2022 08:24:30 -0400 (EDT)
Subject: [tabler/tabler] [BUG] Radio button not working correctly on demo page (Issue #1196)

**Describe the bug**

In the [form elements](https://preview.tabler.io/form-elements.html) demonstration page, the radio buttons at the right of the page does not work correctly: previous choices remains checked and you can't uncheck them.

It's not a bug on the lib itself, but a strange behavior which could suggest a bug in the project.

**Device**

 - Browser: Chrome v104
 - OS: Win11
 - Screen size: 3840 x 2560

**To reproduce**

Steps to reproduce the behavior:
1. Go to [form elements](https://preview.tabler.io/form-elements.html) demonstration page,
2. Click on right radio button "Option 2"
3. Option 1 should be unchecked.

**Screenshots**

![Screenshot 2022-08-10 141726](https://user-images.githubusercontent.com/127185/183899438-da33174a-30b2-4889-9324-4926fda82382.jpg)



-- 
Reply to this email directly or view it on GitHub:
https://github.com/tabler/tabler/issues/1196

**Comment by gladtoseeugo** [comment]
UNSCRIBE 



From: "Thomas Bolon" ***@***.***> 
To: "tabler" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Wednesday, August 10, 2022 4:24:30 AM 
Subject: [tabler/tabler] [BUG] Radio button not working correctly on demo page (Issue #1196) 





Describe the bug 

In the [ https://preview.tabler.io/form-elements.html | form elements ] demonstration page, the radio buttons at the right of the page does not work correctly: previous choices remains checked and you can't uncheck them. 

It's not a bug on the lib itself, but a strange behavior which could suggest a bug in the project. 

Device 

    * Browser: Chrome v104 
    * OS: Win11 
    * Screen size: 3840 x 2560 


To reproduce 

Steps to reproduce the behavior: 

    1. Go to [ https://preview.tabler.io/form-elements.html | form elements ] demonstration page, 
    2. Click on right radio button "Option 2" 
    3. Option 1 should be unchecked. 


Screenshots 

[ https://user-images.githubusercontent.com/127185/183899438-da33174a-30b2-4889-9324-4926fda82382.jpg ]
