### ISSUE TITLE
[BUG] Radio button check not centered on HiDPI

### ISSUE THREAD

**Issue by tbolon** [tabler/tabler#1197]
**Describe the bug**

When browsing the [form elements](https://preview.tabler.io/form-elements.html) demo page, the checkmark in the center of the radio button is not perfectly centered.

It seems too far on the right and to the bottom.

**Device**

 - Browser: Chrome v104
 - OS: Windows 11
 - Screen size: 3840 x 2560, 150%

**To reproduce**

1. Go to [form elements](https://preview.tabler.io/form-elements.html)

**Screenshots**

![Screenshot 2022-08-10 141726](https://user-images.githubusercontent.com/127185/183900581-533f0940-1c2a-4cb0-aa77-725d58fbe93d.jpg)

**Comment by tbolon** [comment]
(note: it seems the toggle switches have the same problem):

![Screenshot 2022-08-10 144214](https://user-images.githubusercontent.com/127185/183904023-24852d47-614a-49e4-a54a-e4b1923e72c5.jpg)

**Comment by gladtoseeugo** [comment]
0UnSubscribed
----- Original Message -----
From: Thomas Bolon ***@***.***>
To: tabler/tabler ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Wed, 10 Aug 2022 08:27:02 -0400 (EDT)
Subject: [tabler/tabler] [BUG] Radio button check not centered on HiDPI (Issue #1197)

**Describe the bug**

When browsing the [form elements](https://preview.tabler.io/form-elements.html) demo page, the checkmark in the center of the radio button is not perfectly centered.

It seems too far on the right and to the bottom.

**Device**

 - Browser: Chrome v104
 - OS: Windows 11
 - Screen size: 3840 x 2560, 150%

**To reproduce**

Steps to reproduce the behavior:
1. Go to [form elements](https://preview.tabler.io/form-elements.html)
4. See error

**Screenshots**

![Screenshot 2022-08-10 141726](https://user-images.githubusercontent.com/127185/183900581-533f0940-1c2a-4cb0-aa77-725d58fbe93d.jpg)



-- 
Reply to this email directly or view it on GitHub:
https://github.com/tabler/tabler/issues/1197

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by gladtoseeugo** [comment]
UNSCRIBE 



From: "Thomas Bolon" ***@***.***> 
To: "tabler" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Wednesday, August 10, 2022 4:27:02 AM 
Subject: [tabler/tabler] [BUG] Radio button check not centered on HiDPI (Issue #1197) 





Describe the bug 

When browsing the [ https://preview.tabler.io/form-elements.html | form elements ] demo page, the checkmark in the center of the radio button is not perfectly centered. 

It seems too far on the right and to the bottom. 

Device 

    * Browser: Chrome v104 
    * OS: Windows 11 
    * Screen size: 3840 x 2560, 150% 


To reproduce 

Steps to reproduce the behavior: 

    1. Go to [ https://preview.tabler.io/form-elements.html | form elements ] 
    2. See error 


Screenshots 

[ https://user-images.githubusercontent.com/127185/183900581-533f0940-1c2a-4cb0-aa77-725d58fbe93d.jpg ]

**Comment by ShubhamGoyal7125** [comment]
Hey @tbolon,
I just opened the form elements page and found the checkmark in the center of the radio button is centered.
Is there any other page, I am missing to see, or has the issue been resolved?
![image](https://user-images.githubusercontent.com/85388284/184530964-60959059-eacf-4824-8105-78cbbc11f2bc.png)

**Comment by ShubhamGoyal7125** [comment]
Hey @tbolon,
Can I work on this issue?
This is how I will be solving it - 
There will be some minor changes in the CSS to make the radio button checkmarks centred at 150%.

**Comment by tbolon** [comment]
Yes, I am not confident enough to work on this issue 😊 thanks.

**Comment by ShubhamGoyal7125** [comment]
So, can you assign me this issue?

**Comment by tbolon** [comment]
I am not responsible for this project and I can't assign issues. If you want to submit a fix, you should create a PR or wait for a maintainer to manifest here.

**Comment by ShubhamGoyal7125** [comment]
hey @codecalm,
Can you assign me this issue?

**Comment by rjd22** [comment]
@ShubhamGoyal7125 assigned the issue to you. Good hunting!

**Comment by ShubhamGoyal7125** [comment]
Hey @codecalm, 
I have corrected this issue by doing changes in "css/tabler.css" inside the ".tmp" folder. So just wanted to know, if is it the correct folder to make changes, as the changes are getting reflected on my localhost correctly but are not shown in the git status or if I have to make changes in some other folder.

**Comment by dheineman** [comment]
@ShubhamGoyal7125 the `css/tabler.css` file in the `.tmp` folder is generated based on the actual source files which are located in the `src` folder. The `.tmp` folder is excluded from git as it is only used during development.

⚠️ Make sure to backup you changes before applying your fix to the src files as everything in `.tmp` will be overwritten if `npm run start-plugins` is running.

**Comment by Vivyanne-504** [comment]
has this bug been fixed?

**Comment by ShubhamGoyal7125** [comment]
Yes, the bug has been fixed.

**Comment by ShubhamGoyal7125** [comment]
Hey @codecalm,
I have resolved the issue and made the pull request.
Thanks for assigning me the issue.
