### ISSUE TITLE
[BUG] Popover doesn't work with tabs.

### ISSUE THREAD

**Issue by jozefrebjak** [tabler/tabler#1199]
**Describe the bug**

Popover doesn't work with tabs. Popovers from docs:  https://preview.tabler.io/docs/popover.html works only on single page.

**Device**

 - Browser [All Browsers]
 - OS: [MacOS ]

**To reproduce**

**Comment by gladtoseeugo** [comment]
UnSubscribed
----- Original Message -----
From: Jozef Rebjak ***@***.***>
To: tabler/tabler ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Wed, 10 Aug 2022 08:44:07 -0400 (EDT)
Subject: [tabler/tabler] [BUG] Popover doesn't work with tabs. (Issue #1199)

**Describe the bug**

Popover doesn't work with tabs. Popovers from docs:  https://preview.tabler.io/docs/popover.html works only on single page.

**Device**

 - Browser [All Browsers]
 - OS: [MacOS ]

**To reproduce**


-- 
Reply to this email directly or view it on GitHub:
https://github.com/tabler/tabler/issues/1199

**Comment by gladtoseeugo** [comment]
UNSCRIBE 


From: "Jozef Rebjak" ***@***.***> 
To: "tabler" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Wednesday, August 10, 2022 4:44:07 AM 
Subject: [tabler/tabler] [BUG] Popover doesn't work with tabs. (Issue #1199) 





Describe the bug 

Popover doesn't work with tabs. Popovers from docs: [ https://preview.tabler.io/docs/popover.html | https://preview.tabler.io/docs/popover.html ] works only on single page. 

Device 

    * Browser [All Browsers] 
    * OS: [MacOS ] 


To reproduce

**Comment by rjd22** [comment]
Most likely this is not a Tabler bug. This has to do with re-initializing the popovers when changing the tabs since javascript possibly skips content that is not rendered.
