### ISSUE TITLE
Colour input on form page bleeds into middle column

### ISSUE THREAD

**Issue by alexbainbridge** [tabler/tabler#12]
On this page
https://tabler.github.io/tabler/form-elements.html when in slightly thin screen layout, the colour input bleeds into the middle column 
![colour_choice](https://user-images.githubusercontent.com/1144763/37917897-8edd1e70-3117-11e8-9fa2-091a2054b36a.png)

[Mac chrome]

Thanks! Alex

**Comment by codecalm** [comment]
thanks for feedback Alex!!
