### ISSUE TITLE
[BUG] Popover not opening correctly in beta-11

### ISSUE THREAD

**Issue by artknight** [tabler/tabler#1204]
**Describe the bug**

The Popover is not opening at the correct location starting in beta 11 release.

**Device**

 Chrome, Edge, FF

**To reproduce**

Open the popover

**Comment by kevinpapst** [comment]
I added the popover docs https://preview.tabler.io/docs/popover.html in https://github.com/tabler/tabler/pull/1157 but there were no functional changes made. 

Can you add expected and current status, so it is easier to verify?

**Comment by kikikiblue** [comment]
There is another bug in beta 11 release. (It is working well in beta 9)
If popover is set `data-bs-trigger="manual"`, and call 'toggle' call by javascript, the popver closes as soon as it opens.
but `show()` and `hide()` works well. 

```
<button type="button" id="example" class="btn btn-lg btn-danger" data-bs-placement="bottom" data-bs-trigger="manual" data-bs-toggle="popover" title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>

<script>
var popover = new bootstrap.Popover(document.querySelector('#example'), {});
popover.toggle(); //closes as soon as it opens
popover.show(); //works well
popover.hide(); //works well
</script> 
```
and the popover's location is always right. even though I set it bottom

**Comment by rjd22** [comment]
This seems to be fixed by now so I'm closing this. :)
