### ISSUE TITLE
[FEATURE] Two columns on vertical menu

### ISSUE THREAD

**Issue by Ajtak** [tabler/tabler#1206]
I would welcome a double vertical menu like in the picture, most left with blue color. Some templates allow you to have a two column left menu. I think it could be useful for other people as well. Would it be possible to add it? Thanks
![Zachycení webu_16-8-2022_221731_preview tabler io](https://user-images.githubusercontent.com/4963819/184978313-44253280-e772-458c-b3bf-56e11f7cc6b4.jpeg)
.

Some examples, here:
https://www.htmlelements.com/demos/page-templates/admin-template-3/introduction

**Comment by razaahmad333** [comment]
I think that could be more complex user experience

**Comment by rjd22** [comment]
Since this is a really user specific feature I would suggest making your own implementation. I will be closing this issue.
