### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by fy403** [tabler/tabler#1207]
How about supporting this style？
![火狐截图_2022-08-17T06-48-37 912Z](https://user-images.githubusercontent.com/51740518/185053227-31002d63-2c01-48f6-85c7-f9631ae5e9d2.png)

**Comment by kevinpapst** [comment]
The year 2000 says hello 😁 how does that fit into Tabler?

**Comment by rjd22** [comment]
Since I thing this is a really used specific function IMO I would suggest making your own implementation. For this reason I will be closing this one.
