### ISSUE TITLE
[QUESTION] Best way to adapt the dark theme to have a black-base rather than a blue base?

### ISSUE THREAD

**Issue by rathboma** [tabler/tabler#1221]
Firstly - Tabler is fantastic. Thank you so much for creating it.

I've noticed there are other discussions on the repo about css variables and using those for customization, but as things stand, not everything is a variable, and so customizing a whole site when using the `min.css` file is a bit tough on a limited time budget.

Question:
Does anyone have a template for how they've customized the tabler colors?

I'm using the dark theme, but need it to have a black-base rather than a blue-base. Something like the GitHub dark mode.

Bonus question:
- Have you considered selling a 'theme pack' for like $50. I'd buy it for sure if it came with some good themes and documentation on easily changing the colors.

**Comment by rjd22** [comment]
@rathboma if you use scss to build the theme you can just change the base theme color to black by changing the $dark variable:

```
$dark: #1e2329;
```
