### ISSUE TITLE
Problem with footer

### ISSUE THREAD

**Issue by PolMrt** [tabler/tabler#123]
When I was created a blank page, the footer doesn't put itself at the bottom of the screen. Nevertheless in the category page empty of the demo, the footer is good at the bottom of the screen.

![capture](https://user-images.githubusercontent.com/28253868/39416610-9e36b0fa-4c4e-11e8-99cb-0d77bff719c8.PNG)

**Comment by jonthomp** [comment]
@PolMrt you'll need to share a link to an example or your code so that we can try and see what the issue might be

**Comment by nustiueudinastea** [comment]
@PolMrt you probably don't have the correct nesting of classes. From my experimentation your top div should have class "page" and under that you can place the "footer". "page-main" is also under "page" and should contain the rest of your content.
