### ISSUE TITLE
slow when open a model window

### ISSUE THREAD

**Issue by HashenUdara** [tabler/tabler#1238]
When clicking on a modal window, it opens a bit slow, I think it's not a bug, the reason is the transition time.
Please reduce the transition time when opening the mode window.

**Comment by adolfoflores** [comment]
Actually if you guys try the modal in Safari and Chrome you will notice that Chrome is slower.

In Safari is smoother and faster, in Chrome looks kind of slow.

Tested in Mac.

**Comment by HashenUdara** [comment]
>
