### ISSUE TITLE
Problem with tags with icon

### ISSUE THREAD

**Issue by PolMrt** [tabler/tabler#124]
The icon of the tag is not align with the tag.
![tags beug](https://user-images.githubusercontent.com/28253868/39416996-8d08feb6-4c51-11e8-932b-5cc53585befe.PNG)

**Comment by jonthomp** [comment]
@PolMrt can you show us an example of the code you are using that causes this?

**Comment by PolMrt** [comment]
`<div class="tags">
   <div class="tag tag-orange">
      Client potentiel
      <span class="tag-addon"><i class="fe fe-target"></i></span>
   </div>
</div>`

**Comment by jonthomp** [comment]
Is there a chance that you are including some non-tabler bootstrap CSS? Would you be able to link to a demo page?
