### ISSUE TITLE
[FEATURE] - popup alerts in corners of browser

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#1240]
example: 
`
<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
  
  <div style="position: absolute; top: 0; right: 0;">

    
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <img src="..." class="rounded mr-2" alt="...">
        <strong class="mr-auto">Bootstrap</strong>
        <small class="text-muted">just now</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        See? Just like this.
      </div>
    </div>

    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <img src="..." class="rounded mr-2" alt="...">
        <strong class="mr-auto">Bootstrap</strong>
        <small class="text-muted">2 seconds ago</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        Heads up, toasts will stack automatically
      </div>
    </div>
  </div>
</div>
`

**Comment by dheineman** [comment]
@nejcdev can you please provide a proper description of what feature you are proposing? 

From the title i would guess you want notification toasts, but this is already implemented. (See the [tabler](https://preview.tabler.io/docs/toasts.html) and [bootstrap](https://getbootstrap.com/docs/5.2/components/toasts) documentation) Which i think you know as the example code you added seems to a tweaked sample on [toast placement](https://getbootstrap.com/docs/5.2/components/toasts/#placement) from the bootstrap docs.

**Comment by rjd22** [comment]
This can be done with toast indeed (I did this) but you will need to write the placement CSS yourself. Because this is really a user specific requirement I would recommend making your own implementation because it's impossible for us to cover all the wishes of all the users using tabler.
