### ISSUE TITLE
[BUG] Disabling BrowserSync service for non-development environments

### ISSUE THREAD

**Issue by baa-ableton** [tabler/tabler#1242]
**Describe the bug**

Hello, I am setting up a tabler instance for the analysts in my team. I wrote the commit involving the Docker image with alpine base, so I am using docker with the following command, taken from the Readme:

`docker run -p 127.0.0.1:3000:3000 -p 3001:3001 -v $(pwd)/src:/app/src -v $(pwd)/_config.yml:/app/_config.yml tabler`

Since the entrypoint is `npm run start-plugins`, and especially since I was not able to find an `npm` script definition nor any `gulp` task without starting Browsersync, Browsersync is running on my demo/user-testing environment.

I really don't want Browsersync as it's not useful for my purposes.

I am willing to work on this myself, but I will need direction from the tabler team, as there seems to be multiple ways to tackle this challenge (change script defs in `package.json` or change task defs in `gulpfile.js` ) . 

Please let me know what you think.

**Device**

 - Browser: N\A, not a UI issue
 - OS: Docker image - alpine
 - Screen size: N\A

**To reproduce**
1. Pull Tabler dev branch and navigate to project root
2. `docker build -t tabler .`
3. `docker run -p 127.0.0.1:3000:3000 -p 3001:3001 -v $(pwd)/src:/app/src -v $(pwd)/_config.yml:/app/_config.yml tabler`
4. Observe in the logs that Browsersync is active

**Comment by dheineman** [comment]
Hello @baa-ableton i am a little confused on what you are trying to achieve. As far as i am aware the docker image was created for the purposes of development given that the webserver it uses to serve the files is BrowserSync itself.

If you want to host your own version of https://preview.tabler.io/ in a docker container i recommend creating a DockerFile with multistage building. A stage to create the production static assets in a ruby container with `npm run build` and then copy the `demo` folder over to a apache/nginx container to serve them.

**Comment by baa-ableton** [comment]
@dheineman 
Thanks for getting back as quickly as you did.

It would be nice to have a multistage docker file for a non-dev build of tabler. However, I'm not sure if I would like to go for the final step you describe, namely the nginx/apache/webserver container part. I'm already managing NGINX on my environment and I would like to keep its management separate from the dockerfile for tabler.

I'll try to experiment on this a little bit. Hopefully I'll be able to make some progress with `npm run build` as opposed to `npm run start-plugins`, which is what I've been using as an entrypoint so far.

**Comment by baa-ableton** [comment]
Sorry, I said I would work on this last week but I was busy with other tasks. So I'll make the same promise for this week :D

**Comment by baa-ableton** [comment]
New update:

My team decided that Tabler is not a tool that they're considering anymore so I'll close this issue.

**Comment by Hokwang** [comment]
@baa-ableton BTW, which tool does your team choose, not tabler?

**Comment by baa-ableton** [comment]
@Hokwang we're trying out Apache Superset for the time being,
https://superset.apache.org/
