### ISSUE TITLE
[BUG] Disabled fields are barely noticeable

### ISSUE THREAD

**Issue by cavasinf** [tabler/tabler#1248]
**Describe the bug**
When fields are disabled (HTML attribute), it's hard to know which one is disabled or not..
Even harder when using `fieldset` !

![image](https://user-images.githubusercontent.com/25293190/189919358-f5666cce-2889-4945-809d-865b717c7551.png)

### Little game
Can you guess which one is disable ?
(Done on https://preview.tabler.io/)
<details>
  <summary>Answer</summary>

```
- Full name
- Company 🚫 
- Email 
- Phone number🚫 
- Select
- Select disabled 🚫 
- Checkbox 1
- Checkbox 2 🚫 
```
</details>

![image](https://user-images.githubusercontent.com/25293190/189919730-872b4700-6218-4daf-a27d-b2f9f2f81f89.png)

**Device**

 - Browser: FireFox 104.0.2 (64 bits)
 - OS: Windows 10
 - Screen size: 1920x1080

**Comment by H20220009** [comment]
Can you please assign me this issue, I want to work on it.

**Comment by rjd22** [comment]
Disabled fields are way more clear now. So closing this.
