### ISSUE TITLE
[BUG] Dropdown issue on tables

### ISSUE THREAD

**Issue by adolfoflores** [tabler/tabler#1249]
**Describe the bug**

Dropdown is not working correctly in tables.

**Device**

Tested in Chrome and Safari.

**To reproduce**

You can reproduce it in the demo page: https://preview.tabler.io

<img width="570" alt="CleanShot 2022-09-14 at 22 05 07@2x" src="https://user-images.githubusercontent.com/2294172/190304391-2bf19c97-dc8c-4b59-ac58-b5a07221e184.png">

**Comment by NageshMandal** [comment]
I want to work on this issue. Could you please assign it to me.

**Comment by adolfoflores** [comment]
> I want to work on this issue. Could you please assign it to me.

I think you can fix it and make a pull request.

**Comment by NageshMandal** [comment]
> > I want to work on this issue. Could you please assign it to me.
> 
> I think you can fix it and make a pull request.

Could you please explane the Dropdown issue In More Details

**Comment by adolfoflores** [comment]
> > > I want to work on this issue. Could you please assign it to me.
> > 
> > 
> > I think you can fix it and make a pull request.
> 
> Could you please explane the Dropdown issue In More Details

1. Go here: https://preview.tabler.io
2. Scroll down until the "Invoices" table.
3. Click on "Actions" dropdown.

You'll see how is not displaying correctly. Looks like a z-index issue, but is not.

<img width="235" alt="CleanShot 2022-09-14 at 22 54 42@2x" src="https://user-images.githubusercontent.com/2294172/190310246-f020a931-1148-45dc-81ab-2d06a1228688.png">

**Comment by fahad-islam** [comment]
@adolfoflores Do you want it like this one?

![Screenshot from 2022-09-15 08-41-46](https://user-images.githubusercontent.com/89579421/190316534-4abde5ee-f5b5-41af-a528-bd47423cd157.png)

**Comment by Santanu-dev** [comment]
This change needs to be done using boundary options
https://popper.js.org/docs/v2/utils/detect-overflow/#boundary
