### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by Alinux61** [tabler/tabler#125]
We are going to use Tabler theme in this project, in addition we are planning to sell this product as a single on teda envato platforms. Can we use your name in readme file or documentations because of your theme is licensed with mit or what would you prefer ?

**Comment by rtd62** [comment]
Bump -- am using this in a couple projects myself. Would love to make the attributions if needed

**Comment by beeman** [comment]
As @gonsalu says it's MIT licensed. You don't have to publicly mention you used Tabler but it's of course welcome to do so.

MIT requires that you leave the copyright and license info intact in the code, but does not require anything in the public part (or: derived product) of the project.
