### ISSUE TITLE
[BUG] 3 versions of dark theme?

### ISSUE THREAD

**Issue by ViovMedia** [tabler/tabler#1251]
**Describe the bug**

There is 3 versions of dark theme to choose from. It's a bit confusing, I assume Dark theme 3 is the latest shouldn't the demo folder be sync with either live or most recent updates?

Dark theme 1:
When you preview the dark theme on https://preview.tabler.io/ or use the cdn links.

Dark theme 2:
When you download latest Tabler repository and open the "demo" folder "index.html" file you are greeted with the following dark theme:
[Image](https://i.postimg.cc/TYQTzjGn/Demo.png)

Dark theme 3:
Building the repository with "npm run build" you now have this dark theme:
[Image](https://i.postimg.cc/Fzd0MFkL/Build.png)

**Comment by codecalm** [comment]
`npm run build` build latest version from dev branch. At this moment dev branch is developed strongly, so sometimes are differencies between dev and preview. When I'll release new version everything should be okay :)

**Comment by codecalm** [comment]
in version 1.0.0-beta12 should be fine eveythink :)
