### ISSUE TITLE
[BUG] Broken offcanvas

### ISSUE THREAD

**Issue by jozefrebjak** [tabler/tabler#1261]
**Describe the bug**

Offcanvas is broken after update to 1.0.0-beta12.

**Device**

 - Browser [Safari 16]
 - OS: [MacOS 12.6]
 - Screen size [1440x900]

**To reproduce**

Go to https://preview.tabler.io/offcanvas.html and try to open some offcanvas.

**Screenshots**
![CleanShot 2022-09-19 at 21 47 34@2x](https://user-images.githubusercontent.com/36922215/191103390-14c996cd-f1dc-455b-811d-4040a09118bd.png)

**Comment by codecalm** [comment]
fixed, thank you for help! :)
