### ISSUE TITLE
[BUG] .bg-opacity-xx class is not functioning at https://preview.tabler.io/

### ISSUE THREAD

**Issue by ipmeel78** [tabler/tabler#1262]
**Describe the bug**

The .bg-opacity-xx class is not functioning at https://preview.tabler.io/ 

**Device**

 - Browser [Google Chrome	105.0.5195.127 (Official Build) (64-bit)]
 - OS: [Windows 11]
 - Screen size [any]

**To reproduce**

1. Go to '[(https://preview.tabler.io/)'
2. Click on 'inspect any div element and apply any .bg- class and .bg-opacity'
3. No effect of '.bg-opacity-xx'
4. See the visual
5. Possible cause: The .bg-xxxx classes are two times defined in the CSS file

**Comment by codecalm** [comment]
fixed :)
