### ISSUE TITLE
[BUG] SVG icons are thicker when included as SVG files

### ISSUE THREAD

**Issue by skorokithakis** [tabler/tabler#1263]
**Describe the bug**

Icons included as SVG files (`<img src="file.svg" />`) are chonkier than SVG icons pasted in directly:
![image](https://user-images.githubusercontent.com/23648/191209879-967c6508-15d2-49ae-9ce4-8a7a62cf21b8.png)

**Device**

 - Browser: Vivaldi
 - OS: Linux
 - Screen size: 1080x1920

**To reproduce**

1. Paste the SVG source code in the HTML
2. Add the same icon, as a file this time
3. They look different

![image](https://user-images.githubusercontent.com/23648/191210161-747948e1-13d8-44d6-a7fc-05a3d9068dd0.png)

**Comment by skorokithakis** [comment]
Ah, thank you! Can I work around this somehow (e.g. by adding something to the icon's SVG) for now?

**Comment by codecalm** [comment]
just replace `stroke-width="2"` to `stroke-width="1.5"` :)

**Comment by skorokithakis** [comment]
Fantastic, thanks!
