### ISSUE TITLE
[BUG] TinyMCE Dark Mode is broken

### ISSUE THREAD

**Issue by FuryCraft** [tabler/tabler#1270]
**Describe the bug**

There is a line in the box

**Device**

 - Browser: Brave (Chromium 105)
 - OS: Windows 11
 - Screen size: 1920*1080

**To reproduce**

1. Go to settings page
2. Activate Dark Mode

**Screenshot**
![image](https://user-images.githubusercontent.com/44116544/191327260-a46674d7-7a24-45e6-9f03-a35dba950093.png)

**Comment by anayatkhan1** [comment]
hey @FuryCraft 
I would like to work on this bug
could you please assign me

**Comment by anayatkhan1** [comment]
hey @FuryCraft , i would like work on this bug
can you provide me where to find on source code

**Comment by FuryCraft** [comment]
Maybe https://github.com/tabler/tabler/blob/dev/demo/tinymce.html

**Comment by FuryCraft** [comment]
Or https://github.com/tabler/tabler/tree/dev/dist/libs/tinymce

**Comment by kanhaiya04** [comment]
hi @FuryCraft  I am able to find the issue and the code where changes are required, can you guide me little bit how to execute it.

![image](https://user-images.githubusercontent.com/93936630/194424340-a4b1dcf6-20e3-42e7-b024-e74b4e6517ba.png)


here option.content_css manages the color, but how to fix it i can't get it.

**Comment by FuryCraft** [comment]
Fixed
