### ISSUE TITLE
[BUG] datepicker background color broken.

### ISSUE THREAD

**Issue by adolfoflores** [tabler/tabler#1273]
**Describe the bug**

The background color of the date picker is broken.

Broken in Chrome (Mac)
Working good in Safari (Mac)

**To reproduce**
Enter to: https://preview.tabler.io/form-elements.html

**Screenshots**
<img width="589" alt="CleanShot 2022-09-21 at 23 20 01@2x" src="https://user-images.githubusercontent.com/2294172/191657783-6c970111-645d-4788-83b0-acd91b01046d.png">

**Comment by malyounes** [comment]
Also broken on Chrome (Windows). 
I'm going to take a stab at it and put up a PR.

**Comment by codecalm** [comment]
fixed :)
