### ISSUE TITLE
[BUG] Remove last border-right on progress bar

### ISSUE THREAD

**Issue by cavasinf** [tabler/tabler#1275]
**Describe the bug**

Last `progress-bar` item on `progress progress-separated` should not have `border-right`.
It makes the progress bar seems to not be fully completed event if one item at width 100%.

**To reproduce**

1. Have `progress progress-separated`
2. Add one item `progress-bar` at width 100%
3. See error

**Screenshots**

Current (on [preview.tabler.io](https://preview.tabler.io/index.html)):
![image](https://user-images.githubusercontent.com/25293190/191738977-87500171-9f51-45e3-a9ae-53627e329414.png)

Expected:
![image](https://user-images.githubusercontent.com/25293190/191739088-b94c882b-22c1-41b1-89be-19a7d5fcb2ce.png)

**Comment by cavasinf** [comment]
A simple `:not(:last-child)` should be enough on the border-right CSS, no ?

Le jeu. 22 sept. 2022, 17:57, Shubham Goyal ***@***.***> a
écrit :

**Comment by ShubhamGoyal7125** [comment]
Yes, that worked.
Great
