### ISSUE TITLE
[BUG] Color of Free space section in Progress bar should be same as it's labeled color

### ISSUE THREAD

**Issue by ShubhamGoyal7125** [tabler/tabler#1276]
The color of the Progress bar representing the free space should be same as the color of the box representing the meaning of the color.

**To reproduce**

1. Go to (https://preview.tabler.io)
2. Have `progress` `progress-separated`
3. See error

**Screenshots**

Current:
![image](https://user-images.githubusercontent.com/85388284/191756790-f0bb6075-4c77-4478-965b-845367d61f8c.png)

Expected:
![image](https://user-images.githubusercontent.com/85388284/191756958-9a058e18-bc5e-4971-82a1-074eeaeaa793.png)

**Comment by SUGARXUST** [comment]
I would like to have a look at this, you got any idea where to look for the code?
