### ISSUE TITLE
Order of SCSS

### ISSUE THREAD

**Issue by rufinus** [tabler/tabler#1278]
Bootstrap classes are loaded AFTER Tabler and so tabler changes are overwritten.
This happens since beta10.

I built via webpack:
admin.js:
```
import './common/js/tabler.js'
import '../vendor/cwd/grid-bundle/Resources/public/grid_bootstrap5';
import './admin/grid_delete_confirm.js'
import './admin/toast.js'
import './admin/search.js'
```

common/js/tabler.js:
```
import '@tabler/core/src/js/tabler'
import '@tabler/core/src/scss/tabler.scss'
import '../scss/tabler.scss' // custom overwrites
```

Example of font-size in a table. tabler uses 14px, Bootstrap defaults to 16px.
![beta12](https://user-images.githubusercontent.com/343160/191779302-d95f4796-6fb4-4128-95d9-bdb2b0a81d59.png)
![beta9](https://user-images.githubusercontent.com/343160/191779307-68530876-f805-4d29-92fa-2b2ff2fcf514.png)
![combined-css](https://user-images.githubusercontent.com/343160/191779798-99b8be4a-2a67-410f-a398-cd5a73395933.png)

What do I wrong, or how can this be changed?
TIA

**Comment by StenXP** [comment]
I have same problem and traced it to this  https://github.com/tabler/tabler/blob/8d6898ed268c851742e4acfd72a28ceb302da4b6/src/scss/utils/_colors.scss#L1

In latest commit its fixed...
