### ISSUE TITLE
Button border (beta12)

### ISSUE THREAD

**Issue by drop1down** [tabler/tabler#1283]
beta12 have many issues with button border colors

1) on hover, border is disappear (this do not happen on tabler website)
2) hover on color outline buttons turn to black border - looks bad
3) disabled button have darker color that non-disabled - looks bad

i was not able to fix easily, because my changes also change other buttons like filled buttons etc.

i tried to make a button group

https://user-images.githubusercontent.com/48416452/192093449-013bd41a-5b80-4feb-b153-90965fb2cf7d.mp4

**Comment by uday-kiranreddy** [comment]
i can fix thus issue

**Comment by codecalm** [comment]
its aleeady fixed

**Comment by moisesalmonte** [comment]
unsubscribe
