### ISSUE TITLE
Require.js problem using jquery.validate

### ISSUE THREAD

**Issue by jrcastro87** [tabler/tabler#129]
hi, i want to use jquery.validate to validate forms but require.js doesn't allow it a gives me an error on the browser console, and nothin works anymore, and it works when i remove the script in wich i'm calling the jquery.validate.......also the same thing happend when i've tried to use select2 library

**Comment by twooclock** [comment]
jquery.validate works just fine. Note that when using require.js you shouldn't have any extra <script> tags in your page. Add scripts (jquery.validate.min.js) to dashboard.js instead:
```
require.config({
    shim: {
...lines removed...
        'jquery.validate': ['jquery'],
    },
    paths: {
...lines removed...
        'jquery.validate': "js/jquery.validate.min",
    }
```

Then use in any page as following:
```
 requirejs(["jquery", "jquery.validate"], function () {
            $(document).ready(function () {

                $('#myform').validate({
                    rules: {
                    myfieldname: {
                    minlength: 5,
                    maxlength: 150,
                   ....
```

You may also need to add some css error classes to be able to see validation errors.
Hope it helps.

**Comment by dsznajder** [comment]
We won't include require.js in `v1`! :)
