### ISSUE TITLE
[BUG] Usage of '~' in imports is deprecated

### ISSUE THREAD

**Issue by asharnadeem** [tabler/tabler#1290]
**Describe the bug**

When importing tabler core into `styles.scss` in order to override colors, the styling breaks and warnings are thrown that the usage of tildes when importing is deprecated. Any help is appreciated. I can trudge onwards by just using the base theme colors, but would need to eventually override them with the brand colors.

**Device**
 - OS: MacOS

**To reproduce**

1. Create a new angular project
2. Add this line to `styles.scss`: `@import "@tabler/core/src/scss/tabler.scss";`
3. Run `ng serve`

**Screenshots**
![Screen Shot 2022-10-03 at 8 45 48 PM](https://user-images.githubusercontent.com/47264377/193710739-5ad0de40-bfef-42c5-96eb-eeb168d93d90.png)

**Comment by nerijunior** [comment]
Are you using webpack? If so you can configure an alias to solve it. I faced the same problem when using Vite, my solution was to import all tabler files manually and all bootstrap dependencies too.

**Comment by asharnadeem** [comment]
I am not using webpack. Are there plans to address this bug going forward without needing to manually import every file?

**Comment by nerijunior** [comment]
@asharnadeem did you solved or imported entirely?
