### ISSUE TITLE
[Bug] Sorting icon invisible in dark theme

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler#1292]
**Describe the bug**

On dark theme, the icon for sorting is invisible. Screenshot made using [demo site](https://preview.tabler.io/layout-navbar-sticky.html?theme=dark)
![obraz](https://user-images.githubusercontent.com/210980/194160127-c47c8d6a-2435-4363-9ffa-dd18e7cf3c4a.png)

**Device**

Firefox 105, Linux Manjaro, 1280x1024 / 1920x1200

**Comment by fixingitnow** [comment]
Can I take this issue on ?

**Comment by codecalm** [comment]
fixed, will be released in next package :)
