### ISSUE TITLE
[BUG] Active tabs are white in dark mode.

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler#1299]
In dark mode, active tabs are white but I feel they should be ~80% dark (in contrast to 100% dark for inactive tabs)

**Device**

 - Browser Firefox 105
 - OS: MacOS
 - Screen size 3456×2234

**Screenshots**

Taken on [demo site](https://preview.tabler.io/tabs.html?theme=dark)
<img width="186" alt="obraz" src="https://user-images.githubusercontent.com/210980/194636666-e756ddbc-6237-4d92-9c88-a449a81d650c.png">

**Comment by dekoza** [comment]
I'm sorry but the newest release makes things even worse
![obraz](https://user-images.githubusercontent.com/210980/196724575-4c8e546f-88ea-4f39-8d2a-315fae431556.png)

**Comment by codecalm** [comment]
I've fixed it in #1322 

@dekoza can you give it a try and see if it's ok? ->  https://tabler-git-dev-dark-mode-fixes-tabler-ui.vercel.app/

**Comment by kevinpapst** [comment]
So much better now!

**Comment by dekoza** [comment]
@codecalm Looks awesome!
