### ISSUE TITLE
[BUG] Disabled tab is not distinct enough in light mode

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler#1300]
Disabled tab is not distinct enough in light mode. In dark mode the text is dimmed nicely.

**Device**

 - Browser Firefox 105
 - OS: MacOS
 - Screen size 3456×2234
 
**Screenshots**

Made on [demo site](https://preview.tabler.io/tabs.html?theme=light)
<img width="271" alt="obraz" src="https://user-images.githubusercontent.com/210980/194646274-6b2cbc2e-39f3-4f0d-b240-db8c378710c6.png">

**Comment by dekoza** [comment]
With recent update in light mode it's OK but it got broken in dark mode:
<img width="448" alt="obraz" src="https://user-images.githubusercontent.com/210980/196887380-77c5a770-9db0-43ad-a800-1e18bcce4476.png">

<img width="419" alt="obraz" src="https://user-images.githubusercontent.com/210980/196887343-3f9202d9-fe15-456c-8557-94264a4dfa77.png">

Also, the active tab in dark mode looks OK while in light mode it's off colour.

**Comment by codecalm** [comment]
fixed :)

![Screenshot 2022-10-20 at 21 06 30](https://user-images.githubusercontent.com/1282324/197036121-aec97316-18f4-49c0-8854-cd8dcf70475f.png)
![Screenshot 2022-10-20 at 21 06 36](https://user-images.githubusercontent.com/1282324/197036127-e0a9a52b-d72b-4420-be9a-e6cb94b278fa.png)
