### ISSUE TITLE
[BUG] Code snippets in docs look bad in dark mode.

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler#1301]
In dark mode the code snippets have white background.

**Device**

 - Browser Firefox 105
 - OS: MacOS
 - Screen size 3456×2234

**Screenshots**

From [official documentation](https://preview.tabler.io/docs/tabs.html?theme=dark).
<img width="359" alt="obraz" src="https://user-images.githubusercontent.com/210980/194646789-0d38429d-0969-4bce-b7f7-8dcdf3a6e65b.png">

**Comment by codecalm** [comment]
fixed :)
