### ISSUE TITLE
[FEATURE] responsive view for settings page

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1304]
**Is your feature request related to a problem? Please describe.**

Activate mobile view on https://preview.tabler.io/settings.html

The settings navigation is gone - having a navigation that is invisible is the worst UX you can imagine 😁 

**Describe the solution you'd like**

Find a way to make it available in mobile.
E.g. a "burger" icon next to the title, so slide in/out the left navigation?

**Describe alternatives you've considered**

None, a navigation that disappears is a no-go IMO.

**Comment by dekoza** [comment]
I'd call the disappearing navigation a bug.

**Comment by evrifaessa** [comment]
I encountered the same problem today, and as a non-front-end guy, I honestly don't know how to fix it.

Does anybody possibly have a workaround? Thanks.

https://github.com/FOSSBilling/FOSSBilling/pull/761

**Comment by kevinpapst** [comment]
Fixed in https://github.com/tabler/tabler/pull/1587

Thanks @Saran-pariyar 👍
