### ISSUE TITLE
[FEATURE] different default link color for dark mode

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler#1305]
Currently the links in dark mode have too little contrast, they should be a bit brighter.
Right now the color is `rgb(32, 107, 196)`  and it should be rather `rgb(88, 166, 255)` - like in GitHub which has darker backgrounds which gives even better contrast.

This is how links inside table look like;  added class `text-decoration-none`:

![image](https://user-images.githubusercontent.com/210980/194770965-6db34165-5cff-4bb0-ab80-5d5fee489929.png)

**Comment by codecalm** [comment]
fixed :)
