### ISSUE TITLE
[FEATURE] - Switch from gulp / webpack to VITE

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1309]
i think will be good idea to switch from webpack or gulp to vite it's so much better 

[ttps://vitejs.dev/guide/why.html](https://vitejs.dev/guide/why.html)

What do you think @codecalm  ?

**Comment by Nejcc** [comment]
can anyone help ?

**Comment by codecalm** [comment]
it's good idea, but at this moment there are more important things to do :)
