### ISSUE TITLE
[Request] Sketch design file if possible

### ISSUE THREAD

**Issue by nhim175** [tabler/tabler#131]
In order for developer and designer to collaborate efficiently, I think we want to have a design file in whatever vector format (recommend .sketch). Thanks!

**Comment by roybarber** [comment]
Id be open to working on this

**Comment by Mdevgaonkar** [comment]
Yeah that would be great. Count me in for any work on that

**Comment by roybarber** [comment]
@beeman yes please

**Comment by beeman** [comment]
@roybarber I just saw your response. I create a [new repo here](https://github.com/tabler/tabler-sketch) and you should have an invite!

Closing this issue to the convo can be continued there :-)

**Comment by milosmatic** [comment]
We, at [30Hills](http://30hills.com) have created Tabler Sketch file with all controls and screens.

Here is the download link:
[http://30hills.com/tabler/tabler-ui.sketch-20180718.zip](http://30hills.com/tabler/tabler-ui.sketch-20180718.zip)

We will also make a PR to include this file into this repo.

**Comment by roybarber** [comment]
@milosmatic you will need to create a PR on this repo: https://github.com/tabler/tabler-sketch

Before then could you tidy up the Symbols?: 

<img width="629" alt="screen shot 2018-07-18 at 11 30 03" src="https://user-images.githubusercontent.com/2923782/42876279-118dd002-8a7e-11e8-8f18-906cb0eb17cb.png">

**Comment by milosmatic** [comment]
@roybarber I don't have permission to push to this repo and repo cannot be forked because it's empty.

**Comment by roybarber** [comment]
@milosmatic you should be able to fork now.

**Comment by krizanteme** [comment]
Can we have the sketch files please, it would be much easier for designers to collaborate with developers.
Thanks!

**Comment by interlucency** [comment]
Are there any updates on this? If I can get the original file from @milosmatic I would be more than happy to make the necessary changes.

**Comment by ckissi** [comment]
> @nhim175 @roybarber @Mdevgaonkar @beeman
> 
> We, at [30Hills](http://30hills.com) have created Tabler Sketch file with all controls and screens.
> 
> Here is the download link:
> http://30hills.com/tabler/tabler-ui.sketch-20180718.zip
> 
> We will also make a PR to include this file into this repo.

Can you reupload the file, please?
