### ISSUE TITLE
[BUG] Offcanvas: Incorrect display effect

### ISSUE THREAD

**Issue by haitanghuadeng** [tabler/tabler#1312]
You can click the [link](https://preview.tabler.io/offcanvas.html) to see what 'offcanvas' looks like, click the' Toggle start offcanvas' button, and the problem reappears.

**Comment by thakurprathya** [comment]
Can you please elaborate the issue?? And is anyone working on it?

**Comment by haitanghuadeng** [comment]
![test](https://user-images.githubusercontent.com/43346455/196076225-ece006d2-40db-41ea-8efd-b41d6f258b4f.png)
Pictures of the sample

**Comment by haitanghuadeng** [comment]
There seems to be something wrong with its display.In daytime mode, there are display problems.

**Comment by thakurprathya** [comment]
I think it's because of colour overlapping with the background try changing
div colour or class colour for proper visibility.

**Comment by haitanghuadeng** [comment]
If I change the background color while using it, I will lose visibility compatibility for day/night mode.

**Comment by haitanghuadeng** [comment]
If I change the background color while using it, I will lose visibility compatibility for day/night mode.

**Comment by haitanghuadeng** [comment]
So, for now, all I can do is temporarily give it a background color. But this is not very project friendly, and I hope it will be compatible in the next release of tabler.

**Comment by codecalm** [comment]
it's already fixed, will be released in next version 

https://dev.tabler.io/offcanvas.html :)

**Comment by brianglz** [comment]
Hello Paweł Kuna,
One query, you have the possibility to open Offcanvas like bootstrap does

<code>new bootstrap.Offcanvas(bsOffcanvas)</code>

**Comment by haitanghuadeng** [comment]
Thanks for your reply. This problem has been fixed and released in version 14.
