### ISSUE TITLE
[BUG] The 'table-striped' can appear abnormal in late night mode

### ISSUE THREAD

**Issue by haitanghuadeng** [tabler/tabler#1313]
You can click the [link](https://preview.tabler.io/tables.html?theme=dark) to add 'table-striped' to the table style, then toggle the late-night theme, and the question reappears.

**Comment by dekoza** [comment]
Duplicate of #1308 ?

**Comment by codecalm** [comment]
Duplicate of https://github.com/tabler/tabler/issues/1308
