### ISSUE TITLE
[FEATURE] tab scroll

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler#1316]
If I have a lot of tabs, I'd like them to be scrollable, not to form another row of tabs. If this is already possible, please add a demo of this.

**Comment by dekoza** [comment]
[Possible solution](https://github.com/SupernovaIC/scrollable-tabs-bootstrap-5)

**Comment by aarushisoni** [comment]
Hi i would like to resolve this issue

**Comment by abalter** [comment]
I would also like this.

**Comment by oceanofcode** [comment]
I want to fix tab scroll #1316
