### ISSUE TITLE
[BUG] Datagrid SCSS missing from latest release (1.0.0-beta13)

### ISSUE THREAD

**Issue by MarkusBansky** [tabler/tabler#1321]
**Describe**

Recently there was a release of an updated beta version of `v1.0.0-beta13` which had missing `.scss` for `datagrid`.

**Device**

Any

**To reproduce**

- Create a project
- Install package from npm
- Check the `scss` folder in `tabler/code` inside `node_modules` for `_datagrid.scss`

**Comment by codecalm** [comment]
fixed in `v1.0.0-beta14` :)
