### ISSUE TITLE
[BUG] Only one page is printed

### ISSUE THREAD

**Issue by JohnAxae** [tabler/tabler#1325]
**Describe the bug**
When printing a webpage, the first page of the full document is printed.

**Device**
 - Browser: Chrome 106.0.5249.119 & Firefox 106.0.1
 - OS: Windows 10
 - Screen size: 1920 x 1080
 - Version: 1.0.0-beta14

**To reproduce**
1. Go to any page
2. Print the page (works on preview.tabler.com)
3. Only 1 page is visible

**Screenshots**
How it is (beta12 and higher):
![image](https://user-images.githubusercontent.com/4102398/197157274-76d44294-2e2a-4b68-b340-e8c43b8d6d31.png)

How it should be (beta11 and lower):
![image](https://user-images.githubusercontent.com/4102398/197157514-7ad3a05a-babb-41f7-80e2-6aaf6ab4a944.png)

**Comment by codecalm** [comment]
@JohnAxae can you show me the code or url to this example?

**Comment by JohnAxae** [comment]
This is de code of the page, with latest version of tabler included:
https://gist.github.com/JohnAxae/3327aa6385cca3bc6231ff9a4ff63def

**Comment by JohnAxae** [comment]
It's okay. I found out with a colleague that some new lines in the stylesheet from tabler overwrote my print stylesheet.
