### ISSUE TITLE
[FEATURE] Color input should show different color for inner check symbol on white ellipse.

### ISSUE THREAD

**Issue by Virility** [tabler/tabler#1328]
**Is your feature request related to a problem? Please describe.**
White color shows white check instead something that indicates that it's selected. White on white = contrast == non-existent.

**Describe the solution you'd like**
It should show black

**Describe alternatives you've considered**
 or maybe a main accent color

**Comment by codecalm** [comment]
it was a bug, it should work. I've fixed it in #1362
