### ISSUE TITLE
[BUG] Form helpers do not work

### ISSUE THREAD

**Issue by mholt** [tabler/tabler#1341]
**Describe the bug**

Dev tools shows that no event handlers are event bound to the helper. The form helper may be rendered after the page loads. I assume Tabler is using a binding on <body> or similar, instead of selecting the individual elements just once?

Clicking a form helper in a modal does not do anything. Dev tools shows that no event handlers are event bound to the helper.

As mentioned [here](https://github.com/tabler/tabler/issues/756#issuecomment-1288221423), but I figured I should open a new issue.

**Device**

 - Chrome, Safari, and Firefox
 - OS: Mac and linux
 - Screen size: any/all

**To reproduce**

1. Put a form helper in a modal
2. Open the modal, click the form helper
3. Nothing happens

If applicable, add screenshots to help explain this problem.

https://user-images.githubusercontent.com/1128849/199105009-81e34d9c-763f-449d-b645-eaca94eb1328.mov

Form helpers work outside of modals.

**Comment by rjd22** [comment]
@mholt most likely you need to rebind the form helpers after the modal is open to make them work. Is the content of the modal in the DOM before you opened it?

Can you make a working example in jsfiddle?

**Comment by mholt** [comment]
I'll try to do that if I can make some time soon. Thanks for the idea.

Also just realizing that this might be more Bootstrap-related than Tabler. (I'm new to both.) If so, sorry for the noise and we can close this.

**Comment by laran** [comment]
This started working for me when I enabled Bootstrap popovers.

https://getbootstrap.com/docs/5.3/components/popovers/#enable-popovers
