### ISSUE TITLE
[BUG] Job listing is not responsive

### ISSUE THREAD

**Issue by alighasemzadeh** [tabler/tabler#1348]
![image](https://user-images.githubusercontent.com/26847446/200127176-dc820f00-caf2-48e1-bf29-2143ed119d84.png)
Job listing is not responsive.

**Comment by msboffl** [comment]
Can you please assign this to me, I will work

**Comment by alighasemzadeh** [comment]
@msboffl 
Check image please.

**Comment by rjd22** [comment]
@msboffl feel free to make an PR. Good luck!

**Comment by rjd22** [comment]
Thank you for merging @codecalm !
