### ISSUE TITLE
[BUG] Fix deprecation warning when Bootstrap releases version 5.2.3 by updating bootstrap

### ISSUE THREAD

**Issue by rjd22** [tabler/tabler#1352]
**Describe the bug**

Added this issue so we won't forget to update bootstrap soon to avoid deprecation warnings from SASS.

See: https://github.com/twbs/bootstrap/pull/37425

**To reproduce**

1. Build with SASS

**Screenshots**

![2022-11-10T14:27:30,415225961+01:00](https://user-images.githubusercontent.com/160743/201103967-6845e729-ac5e-4b75-99b1-5ad10e9864fa.png)

**Comment by codecalm** [comment]
it's fixed in https://github.com/twbs/bootstrap/pull/37425 
we're waiting for new bootstrap release

**Comment by codecalm** [comment]
fixed! :)
