### ISSUE TITLE
[BUG] Missing Font Sizes (fs-* classes)

### ISSUE THREAD

**Issue by paulchubatyy** [tabler/tabler#1355]
Bootstrap provides [utility classes](https://getbootstrap.com/docs/5.2/utilities/text/#font-size) to adjust the font size. Those are missing from default Tabler distribution `tabler.min.css`.

**Device**

- Not device specific

**To reproduce**

1. On tabler page add `fs-1`, `fs-2` or `fs-3` class to `<p>` element
2. Expected behavior: text actually changes size
3. Current behavior: text **doesn't** change size

**Comment by codecalm** [comment]
fixed, thank you ❤️
