### ISSUE TITLE
[BUG] Avatar stacked list is not staked anymore

### ISSUE THREAD

**Issue by robertsimionescu** [tabler/tabler#1370]
**Describe the bug**

Avatars do not overlap each-other when grouped in an avatar-list-stacked class. 

I've seen it both in [v1.0.0-beta15] and [v1.0.0-beta16]

**Device**

 - Browser: Chrome, Safari
 - OS: Mac OS 13
 - Screen size: any size

**To reproduce**

1. Go to 'https://preview.tabler.io/docs/avatars.html'
2. Scroll down to the end where 'Stacked List' paragraph is

**Screenshots**

<img width="716" alt="image" src="https://user-images.githubusercontent.com/3469630/201519712-36f21c59-7fc0-4e0e-a51a-264b7a535585.png">

**Comment by codecalm** [comment]
fixed! thank you :)
