### ISSUE TITLE
[BUG] Dark mode datatable sortable column header

### ISSUE THREAD

**Issue by neacon-ivalkenburg** [tabler/tabler#1373]
**Describe the bug**
Looks like sortable column header in dark mode is missing some theme specific styling. Selected column text color and sort icon fill color. Awesome project btw.

**Device**
- Chrome
- MacOSX

**To reproduce**
1. Go to: https://preview.tabler.io/datatables.html?theme=dark
2. Sort a column

**Screenshots**

<img width="440" alt="Screenshot 2022-11-15 at 15 49 25" src="https://user-images.githubusercontent.com/49307046/201950203-4baeb2a5-f87c-4374-a8f4-df1688adc771.png">

**Comment by kevinpapst** [comment]
Was fixed in beta 19:
<img width="730" alt="Bildschirmfoto 2023-05-22 um 18 18 25" src="https://github.com/tabler/tabler/assets/533162/1a33e22c-ccdf-4793-9d8d-a6f49624bf7f">
