### ISSUE TITLE
Outdated payment provider logos

### ISSUE THREAD

**Issue by evrifaessa** [tabler/tabler#1377]
Hey, thanks for this great project!

I've found out some payment provider logos are outdated.
Here is a list of what I've noticed at a first glance:
* Mastercard
* Maestro
* Cirrus
* Google Wallet
* Klarna

**Comment by aarushisoni** [comment]
hi i want to contribute to this issue . Can you please tell where exactly i have to look into for this issue

**Comment by evrifaessa** [comment]
> hi i want to contribute to this issue . Can you please tell where exactly i have to look into for this issue
> 
> 

The files are under `/src/img/payments`. That's all I know.

**Comment by H20220009** [comment]
Hi, I want to work on this issue. Can you please assign it to me?

**Comment by rjd22** [comment]
This is an issue meant for the tabler icons project. For that reason I'm closing this.
