### ISSUE TITLE
Anyone using this library in your project? If so, How?

### ISSUE THREAD

**Issue by lcherukuri** [tabler/tabler#138]
How to add this library to my existing project? Is there something like npm/bower dependency that I can add? or is there a cdn that I can put directly in my index.html page? My project uses grunt.js. So how to use this with Grunt? The installation documentation did not answer any of those questions. 

I am looking for a documentation that says something like, install this library in your project or put this Js/CSS links in your index.html page, or add these steps to your build process etc

**Comment by vshelke** [comment]
Hi @lokeshcherukuri , You can use my repo for stripped version of tabler directly. [tabler-static](https://github.com/vshelke/tabler-static)

**Comment by lokeshcherukuri** [comment]
@vshelke Thanks. You saved a lot of time man. I hope you repo all components that tabler has

**Comment by vshelke** [comment]
@lokeshcherukuri i have just stripped a few icons which i removed to reduce the overall size of the assets. If you want them you can simply copy the tabler.css from main repo and images folder. It will work with the same config in existing [tabler-static](https://github.com/vshelke/tabler-static) repo

**Comment by ansien12** [comment]
@vshelke This is amazing! Tabler desperately needed to have a version like this.

**Comment by twf-nikhila** [comment]
@vshelke @lokeshcherukuri anyone already using this in live projects?

**Comment by vshelke** [comment]
I have used this in my college project which you can find [here](https://github.com/vshelke/agrowell). Its a django based project. @twf-nikhila

**Comment by lokeshcherukuri** [comment]
when I placed tabler CSS files in my project, all my existing layout, color, fonts got overridden. Then I have to change a lot of my own CSS again. So I decided not to use this. Unless you are starting a new project, I don't think this library work well with existing projects.

**Comment by vshelke** [comment]
@lokeshcherukuri i have made a stripped out version of the existing tabler.css which does not support icons, plugins and require.js support. So for existing projects you can directly copy the original tabler.css and it should work fine. And if you are looking for JS support too then you can directly use the orignal tabler files.
