### ISSUE TITLE
Clickable card?

### ISSUE THREAD

**Issue by pdawczak** [tabler/tabler#139]
I've checked the documentation for the cards, and there are examples with links inside the card, but in my case, I wanted to make the whole card clickable:

```html
<div class="col-12">
  <a href="#">
    <div class="card">
      <div class="card-body">
        <div class="container">
          <div class="row">
            <div class="col-lg-6">
              Some Text                            
            </div>
            <div class="col-lg-6">
              Additional info
            </div>
          </div>
        </div>
      </div>
    </div>
  </a>
</div>
```

Unfortunately, it overrides the default text styles inside the card, so it looks like:

<img width="947" alt="2018-05-15_0759" src="https://user-images.githubusercontent.com/601110/40041564-5856454a-5816-11e8-8aee-2f6e9d1e10ee.png">

instead of expected:

<img width="946" alt="2018-05-15_0803" src="https://user-images.githubusercontent.com/601110/40041597-7d376ede-5816-11e8-999a-f5e89d2c264c.png">

Thank you for your help!

**Comment by craigrusgrieve** [comment]
A quick dirty fix you could try is adding:
`style="text-decoration:none; color:#495057;"`
to the:
`<a href="#">`

So you get:
`<a href="#" style="text-decoration:none; color:#495057;">`

**Comment by pdawczak** [comment]
Great! Thanks for your help @craigrusgrieve!
