### ISSUE TITLE
[BUG] Advanced Select should have a padding right

### ISSUE THREAD

**Issue by promatik** [tabler/tabler#1392]
**Describe the bug**

When there is no minimum width for an advanced select, the carret overlaps the text, like this;

![image](https://user-images.githubusercontent.com/1838187/204810655-c99fae92-2b3e-459a-9920-f5c4e5b2175a.png)

**Device**

 - Chrome 107 (but it happens everywhere)
 - Windows 10
 - 4k

**To reproduce**

Steps to reproduce the behaviour:
1. On demo, go to the forms page; https://preview.tabler.io/form-elements.html
2. Add a `width: fit-content;` to the "Select with flags" `form-select` element.

![image](https://user-images.githubusercontent.com/1838187/204811757-eb160965-5550-4753-beea-6412885774aa.png)

**Comment by promatik** [comment]
Added the fix on #1393.

**Comment by kevinpapst** [comment]
@promatik as both Tomselect and Tabler PRs were merged, you might wanna give it a try and close the issue if it works?!

**Comment by promatik** [comment]
Hi @kevinpapst!
Both PRs were merged, none was tagged 😅
Anyway, yes it works on dev, let's assume we'll have a v1 (non beta) soon 🎉

I'll close this one for now 👌
