### ISSUE TITLE
[BUG]  Dropdown Buttons are not working

### ISSUE THREAD

**Issue by mikebermel** [tabler/tabler#1400]
Dropdowns buttons have no action on click or hover.

I guess this bug is in tabler.io preview too. (https://preview.tabler.io/dropdowns.html) 

In the previous version, the same code worked perfectly.

**Device**

 - Browser: Firefox 107
 - OS: Linux Fedora 37
 - Screen size: 

**To reproduce**

Create a simple dropdown:
-----
```
<div class="dropdown" style="z-index: 100;">
    <button type="button" title="Ligações efetuadas / WhatsApp enviados" class="btn dropdown-toggle" data-toggle="dropdown" style="padding: 0px;color: white;">
    <i class="fas fa-phone-volume"></i> <span class="badge">10</span></button>
        <div class="dropdown-menu" style="width: 300px;">
        <form class="px-4 py-3 bg-light" action="visitasAction" method="POST" name="acao">
        <div class="form-group">
        <label for="desc">Descreva a ligação ou mensagem</label>
        <textarea class="form-control" id="desc" name="desc" placeholder="..." required>Contact...</textarea>
        </div>
        <button type="submit" class="btn btn-success"><i class="fas fa-phone-volume"></i> Salvar</button>
        </form>
        </div>
    </div>
```
-----

**Screenshots**

https://user-images.githubusercontent.com/33283755/205624984-2aa71510-4533-4363-a207-68b0acbce654.mp4

**Comment by mikebermel** [comment]
I found a possible solution:

Replace data-toggle="dropdown" to data-bs-toggle="dropdown".

**Comment by H20220009** [comment]
I want to work on this issue. Please assign me this issue if it's still open.

**Comment by rjd22** [comment]
This is because the dropdown was not configured correctly. You need `data-bs-foo` arguments now to make it work properly.
