### ISSUE TITLE
Support for editing JSON docs

### ISSUE THREAD

**Issue by getorca** [tabler/tabler#1403]
**Is your feature request related to a problem? Please describe.**
It can be difficult or impossible to define UI elements for dynamic json elements that you get in noSQL DBs like mongo, arrangoDB, or now even json objects in psql. The challenge of dynamic data arises more with large data, when humans need to review things in an admin interface. 

**Describe the solution you'd like**
Include an interface like https://github.com/josdejong/jsoneditor, to allow editing of json elements.

**Describe alternatives you've considered**
- adding the library myself... 
- showing json in raw text field (this can easily lead to errors when editing, and is difficult for large json docs)
- defining the interface to show each object in specific fields (difficult / not possible for dynamic json objects)

**Comment by kevinpapst** [comment]
This sounds like a feature request for an app, that uses the theme. 
How is this related to Tabler itself?

**Comment by rjd22** [comment]
I agree. This is really niche and better implemented by the users themselves. For that reason I'm closing this.
