### ISSUE TITLE
[FEATURE] Add animation when menu expand

### ISSUE THREAD

**Issue by xvzhenduo** [tabler/tabler#1406]
**Is your feature request related to a problem? Please describe.**
No, but this can make it look better(an example below)
![example](https://user-images.githubusercontent.com/74353173/206707150-c40a6fc3-c368-4b33-afd8-d2d7c45c0485.gif)

**Describe the solution you'd like**
use css transition and then change the hight of the menu

**Describe alternatives you've considered**
[fade effect in bootstrap](https://getbootstrap.com/docs/5.2/components/navs-tabs/#fade-effect)

**Comment by LiamAird** [comment]
Quick side question, is that a collapsing icon you have going besides your logo? 
Did you make it yourself, or is it just burried inside the docs?

**Comment by xvzhenduo** [comment]
> Quick side question, is that a collapsing icon you have going besides your logo? Did you make it yourself, or is it just burried inside the docs?

I mean when I click a item,It will show an animation to toggling the child item
![image](https://user-images.githubusercontent.com/74353173/206713196-989919a7-1f72-41ff-8c20-8d49e5572372.png)
