### ISSUE TITLE
[BUG] tom-select dropdown will be shaded in table-responsive

### ISSUE THREAD

**Issue by chenkovsky** [tabler/tabler#1409]
**Describe the bug**
if the select is in 
```
<div class="table-responsive"></div>
```
. dropdown will be shaded. if I remove table-responsive. it's ok.

and also the width of input changes when value is selected, or dropdown is shown.

**Device**

 - Browser Chrome/108.0.0.0
 - OS: Mac OS X 10_15_7

**To reproduce**
```
<div class="table-responsive">
  <table class="table table-mobile-md card-table">
    <thead>...</thead>
    <tbody>
      <tr>
        <td><select id="tom-select-input"></select></td>
      </tr>
    </tbody>
  </table>
</div>
```

**Screenshots**
<img width="369" alt="tom-select-table-responsive" src="https://user-images.githubusercontent.com/6762133/206996820-69c7d6dd-a243-4819-ac1d-c1192f993dc7.png">

**Comment by Mayuresh0072** [comment]
I want to work on this issue, please assign me. Thanx.

**Comment by codecalm** [comment]
fixed! :)
