### ISSUE TITLE
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

### ISSUE THREAD

**Issue by Mukeshgarg1984** [tabler/tabler#141]
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 2.4/rubyeventmachine (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve/live_reload_reactor.rb:4:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve/live_reload_reactor.rb:4:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:147:in `require_relative'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:147:in `register_reload_hooks'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:101:in `process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:93:in `block in start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:93:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:93:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby24-x64/bin/jekyll:23:in `load'
        from C:/Ruby24-x64/bin/jekyll:23:in `<main>'
npm ERR! code ELIFECYCLE

**Comment by dsznajder** [comment]
Hi @Mukeshgarg1984 

There has been a lack of activity here. If the issue still exists please open a new one with some reproduction/description as there is only copy pasted error.
