### ISSUE TITLE
[BUG] Toggle dark mode position

### ISSUE THREAD

**Issue by adilhyz** [tabler/tabler#1414]
**Describe the bug**

bug when i add nav-item class inside dark mode toggle div switch

sorry for my bad english

**Device**

 - Browser [Google Chrome]
 - OS: [Parros Os]
 - Screen size [1366 x 768]

**Screen Records**

https://user-images.githubusercontent.com/100203867/208287920-5e21c95d-0cbf-44c8-ab51-1041d2751d0b.mp4

**Comment by kevinpapst** [comment]
I don't see the bug here. The HTML structure must match the intended CSS classes.
For me this is a "Works as expected".
