### ISSUE TITLE
bg-light text-dark n dark-moded

### ISSUE THREAD

**Issue by vogelor** [tabler/tabler#1416]
In the dark-mode, if there is a element with .bg-light AND .text-dark

(
mine for example is:
&lt;a href="#" class="badge rounded-pill bg-light text-dark text-decoration-none"&gt;Reset&lt;/a&gt;
)
than you can't see the text, because bg-light is "dark" in dark-mode.
Dark text with dark background is not readable.

to fix this, i added

`@include dark-mode {
   .bg-light.text-dark {
        color: var(--tblr-body-color) !important;
    }
}`

to my own css.

But i think it is better, if YOU change this.

**Comment by codecalm** [comment]
fixed! :)
