### ISSUE TITLE
[CONTRIBUTE] Loading Modal

### ISSUE THREAD

**Issue by humbertleonardo** [tabler/tabler#1417]
I created a new modal that serves as a loading screen, as I could contribute to the project and officially add it to the Tabler package in Modals

 https://preview.tabler.io/modals.html

### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/57204453/209258503-c3702241-d812-4657-9a71-53d887658b59.gif)

**Comment by auroraisluna** [comment]
PR?

**Comment by rjd22** [comment]
I'm closing this since there is no PR made and it has been a while. If you still have the code feel free to make a PR so we can review it :).
