### ISSUE TITLE
Web Accessibility of the dashboard

### ISSUE THREAD

**Issue by cyberflamingo** [tabler/tabler#142]
Disclaimer: I'm not what would be considered impaired nor a web accessibility expert but I have bad eyes.

First of all, great dashboard! I'm sure we will see it pop up here and there in different projects.

More to the point, I was concerned about the web accessibility of this dashboard. Overall I was agreeably surprised but I think there are area where we could make it a little bit better.

I am aware this is a dummy and there would be improvement made by developers (I hope) on a final product. Still, I believe we could help get them started with several additions.

First, about the icon system. Most of them are accompanied with a text and are purely decorative and therefore don't need any addition, however some are just self-explanatory... if you can see with your eyes!
Especially:
- The notification menu's bell (which by the way seems inaccessible with a keyboard)
- "Like" heart
- Payment logo
- Cards options (toggle, delete)

Those icons would benefit of a `title="meaning"` tag.

**Pictures:**
Cards use a link with an image in `background-image=` style. Those would benefit of a `title="meaning"` as well (I recon this is a dummy but people tend to forgot to add it later).

**Text and colors:**
The design is awesome! Unfortunately it's hard to read for a lot of people. This is the toughest part I think. Trying to be compliant without killing the design is a task for a skilled designer.

Probably best to check ressources like [checkmycolours](http://www.checkmycolours.com/) to get started. The problem seems to be mainly the gray (`.text-muted`) texts' lack of contrast.

Finally, the search box may benefit from a `aria-label="Search"` label. Like the icons, it's self-explanatory only if you can see (and I don't think the placeholder is read by every accessibility software, but I may be wrong on this one).

I'd be glad to discuss about different point above and ask for everybody's opinion on the matter.

Thank you!

**Comment by FreexD** [comment]
I know it's been a long time :D but you made a great point. We'll be introducing better accessibility into tabler for sure in future versions. I've ran a wave accessibility check for Tabler preview - https://wave.webaim.org/report#/preview.tabler.io. - it's not perfect but we can definitelly fix that ;)

**Comment by cyberflamingo** [comment]
Wowow! Totally forgot about this issue!

Thanks for coming back! I'm glad accessibility is behind considered :-)
