### ISSUE TITLE
[BUG] TinyMCE in Modal Windows

### ISSUE THREAD

**Issue by mkleger** [tabler/tabler#1425]
**Describe the bug**

If I build the TinyMCE into a modal box, the pop-up windows don't work properly, they open but I can't enter anything in the text fields.

**Device**

 - Browser Microsoft Edge 108.0.1462.54
 - OS: Windows 11
 - Screen size 3840x1080

**Screenshots**
![image](https://user-images.githubusercontent.com/818390/211000125-337babe5-7830-4d07-b87d-e38fbd760cf3.png)

**Comment by rjd22** [comment]
Most likely you will need to reinitialize the tinymce fields after opening the modal. Since this is not a tabler specific error I'm closing this.
