### ISSUE TITLE
[BUG] TinyMCE drop down icon list transparent

### ISSUE THREAD

**Issue by mkleger** [tabler/tabler#1426]
**Describe the bug**

If the icon list is longer than the editor, a dropdown window will open, but the text behind it will be displayed, the window should not be transparent.

**Device**

- Browser Microsoft Edge 108.0.1462.54
- OS: Windows 11
- Screen size 3840x1080

**To reproduce**

1. Open the preview page https://preview.tabler.io/docs/tinymce.html
2. Reduce the window until the icon list is too long and click on the "..."

**Screenshots**
![image](https://user-images.githubusercontent.com/818390/211000679-3d479595-e30a-442d-868f-19b9de38180b.png)

**Comment by Mayuresh0072** [comment]
@beeman @tbolon @mkleger @ollym @eugene1g Hello , I want to work on this issue, please assign me this issue. Thanks

**Comment by Mayuresh0072** [comment]
@codecalm Hello , I want to work on this issue, please assign me this issue. Thanks.

**Comment by mkleger** [comment]
Would be new to me that I can assign an issue to someone.

**Comment by codecalm** [comment]
I've fixed it! :)
