### ISSUE TITLE
[BUG] Missing css s?

### ISSUE THREAD

**Issue by proyecto81** [tabler/tabler#1428]
Hello! :) 
I git clone dev code, and found that most of the main css files (tabler ones) are not included in the css directories.
Is that on purpose for being the development branch? Maybe I have missed something
![Captura](https://user-images.githubusercontent.com/1123229/211170016-32807412-7819-4b1e-8217-381e13bc784b.PNG)

I attached an image with the css file comparison list

Please excuse me if this bug is wrong or if this report is wrong.

Greetings and thank you very much!

**Comment by codecalm** [comment]
it was bug with compiled css, it's fixed now :)
