### ISSUE TITLE
[FEATURE] Step add icon

### ISSUE THREAD

**Issue by haitanghuadeng** [tabler/tabler#1432]
Can you add an icon to a step？
example:
<img width="37" alt="微信图片_20230113103116" src="https://user-images.githubusercontent.com/43346455/212223581-4da3d016-fb66-4806-8cd4-a916d226b2c1.png">

**Comment by Mayuresh0072** [comment]
@codecalm Hello, I want to work on this issue, Please can u assign me.Thanks.

**Comment by rjd22** [comment]
It's not really clear what is requested here. For now I'm closing this. Feel free to comment with a bit more information and I will reopen it.
