### ISSUE TITLE
[FEATURE] Add fold function to sidebar

### ISSUE THREAD

**Issue by haitanghuadeng** [tabler/tabler#1433]
Add fold function to sidebar？
example:
<img width="229" alt="微信图片_20230113103622" src="https://user-images.githubusercontent.com/43346455/212224361-be1cd49e-1913-4c77-89f8-838c30e03115.png">
to
<img width="76" alt="微信图片_20230113103652" src="https://user-images.githubusercontent.com/43346455/212224394-9a990aa3-6b6b-4693-880f-cfb3c5554e49.png">
The second image is a gitlab style cut

**Comment by Hussain0520** [comment]
Hey @haitanghuadeng are you working on this feature? If not I would like to contribute. Thanks!

**Comment by haitanghuadeng** [comment]
> 
Thanks, I won't implement this feature and will only suggest some help to tabler.

**Comment by Hussain0520** [comment]
Thanks, Is there someone who can assign me this?

**Comment by haitanghuadeng** [comment]
> 

This will have to wait for tabler's official allocation.

**Comment by Hussain0520** [comment]
@haitanghuadeng Do you know any official whom I can tag to get in his notice and get this assigned to me?

**Comment by Hussain0520** [comment]
@codecalm can you assign me this feature?

**Comment by abrahampe** [comment]
This is a must have! Great suggestion

**Comment by codecalm** [comment]
folded sidebar has been started develop in this PR: https://github.com/tabler/tabler/pull/1319

**Comment by Hussain0520** [comment]
Okay thanks!

**Comment by haitanghuadeng** [comment]
> 折叠侧边栏已在此 PR 中开始开发：#1319
> 
> @Hussain0520如果您想做出贡献，请分叉此 PR :)

thanks!

**Comment by abrahampe** [comment]
Any idea of release date of this Feature?

**Comment by kevinpapst** [comment]
I know your issue is older, but the other one links the original post by codecalm and we should concentrate all votes in one issue to highlight the importance of this (yet missing) feature.

Follow up here: https://github.com/tabler/tabler/issues/1803

Everyone who left a vote in here, please do so in #1803 as well!
