### ISSUE TITLE
[BUG]  Build failures with Beta 17

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1445]
**Describe the bug**

After upgrading to beta 17 I have a couple of build failures with node 19.2 /  node-sass 8.0. One of them is:

````
SassError: argument `$color-1` of `mix($color-1, $color-2, $weight: 50%)` must be a color
        on line 182 of node_modules/@tabler/core/src/scss/_variables.scss, in function `mix`
        from line 182 of node_modules/@tabler/core/src/scss/_variables.scss
````

Refers to 
````
$border-color-light: mix($text-muted, #ffffff, percentage($border-light-opacity)) !default;
````

Can be fixed by removing `!default` from:
```
$text-muted: mix($body-color, #ffffff, percentage($text-muted-opacity)) !default;
```

so this error goes away when line 182 looks like this:
```
$text-muted: mix($body-color, #ffffff, percentage($text-muted-opacity));
```

I have several other issues, like Tomselect using `$input-border-color` in a call like this:
`$select-color-dropdown-border-top: mix($input-border-color, $input-bg, 0.8) !default;` which fails as well, because a color is expected and not a `var()`: https://github.com/orchidjs/tom-select/issues/559

Some of these changes seem to be inspired by `"bootstrap": "5.3.0-alpha1"`. Really not sure if that is the the best choice for a beta17-pre-production.

Right now I am blocked and cannot update from beta16. Any idea?

**Comment by codecalm** [comment]
yes, it looks like a bug in `tom-select`, I'll override styles of it

**Comment by kevinpapst** [comment]
@codecalm Wait, maybe I understand that wrong. But if I remove Tomselect `@import '~tom-select/dist/scss/tom-select.bootstrap5';` from my build, it still fails because of the first problem with `$text-muted: ... !default`.

Do you have any idea if that is a node-sass issue? Do I have to use newer dependencies? 
To me it looks as if the sass function `mix` does not accept the `default!` part. Why does that work if you build it?
Sorry if that is not Tabler related!

**Comment by kevinpapst** [comment]
@codecalm I'd love to move forward to beta-17 or dev branch. Can we collaborate to fix these issues? Is that only my environment that stops building and other build tools just ignore thee problems?

**Comment by codecalm** [comment]
yes, sure. I'll check it today

**Comment by kevinpapst** [comment]
First part is my bad... 😁 could be resolved by importing files in another order:
```
@import "bootstrap/scss/functions";
@import "bootstrap/scss/mixins";
@import "@tabler/core/src/scss/mixins";
@import "@tabler/core/src/scss/variables";
@import "bootstrap/scss/variables";
```
instead of this, what I had before... strangely enough it worked before beta17:
```
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";

@import "@tabler/core/src/scss/variables";
@import "@tabler/core/src/scss/mixins";
```
We should have a documentation page "how to import Tabler into your project".

After that was out of the way, there was still Tomselect with 3 issues. I solved them (just to get the built up and running) with:
```
$select-color-dropdown-border-top: var(--#{$prefix}border-color);
$select-color-dropdown: #fff;
$input-border-width: $border-width;
```
This is obviously wrong, I hope you can come up with a better solution.

**Comment by kevinpapst** [comment]
Will this be fixed before 1.0 @codecalm ?
Otherwise using custom builds of Tabler is not possible in certain environments.
That wold be a sad, considering that you worked for so many years for 1.0 👍

**Comment by codecalm** [comment]
yes, definetly

**Comment by codecalm** [comment]
it you have any other issues that *must* be included in v1.0 give me know

**Comment by kevinpapst** [comment]
I'll check 😄 thanks for the offer! 

Can I support you with that release in any way? Testing?

**Comment by codecalm** [comment]
@kevinpapst yes, sure! I want to finally release version 1.0, I know there are probably a lot of bugs and improvements that could still be made, but I want to start the normal release process and not play around with beta versions. 

today I will be sitting down to the bugs that need to come out, if there are any that are necessary then please assume the issues

**Comment by codecalm** [comment]
you can also add milestone 1.0 to shuffles that must necessarily be repaired before 1.0

**Comment by kevinpapst** [comment]
Sure, I will look through the issues and help. 

And with 1.0 out of the door, you can even use a "auto release drafter" process. 
Since I added that to my project, releasing is just a matter of editing the automatically created release draft and clicking on "publish". The next version is calculated automatically and the changelog added to the release as well.

You just have to use PRs for all changes with the correct labels like "Bugfix" or "Feature request" (names are configurable), then it works really well. I can add send a PR to introduce such a workflow, which really makes a new release a matter of two minutes. Any bugfix can be pushed out immediately as new version.

I think we can leave out all these tiny CSS issues for 1.0, they can be fixed in any version. But I can currently not build the latest versions, due to the problems with the Bootstrap 5.3 incompatibilities. Not sure why I am the only, probably most people just used the pre-compiled files from the release instead of bundling their own ... or their builder is more error tolerant.

**Comment by asteinh** [comment]
You're (definitely) not the only one, I am trying to use tabler for a Flask app and wanted to make use of the bootstrap-5.3-dark-theme features... no chance. I would like to avoid excessive manual adaptations, such that I can do a simple replacement of my scss sources once a stable release is published.

Any progress or ideas on how to handle this? I would love a close-to-source solution (that is, no dependency in the build env and no fix based on a specific node.js package), such that it can also be used in other environments 😉

**Comment by codecalm** [comment]
@asteinh We started working on the dark theme before it was even available in Bootstrap, I know it doesn't work perfectly yet, but I'm working on making it all work and look like it does in Boostrap 🙂 .

**Comment by sadeghbarati** [comment]
I think `tint-color` or any sass function only accept sass variables not CSS variables

```log
[sass] $color2: var(--bs-gray-600) is not a color.
    ╷
207 │   @return mix(white, $color, $weight);
    │                      ^^^^^^
    ╵
  node_modules\bootstrap\scss\_functions.scss 207:11      tint-color()
  node_modules\bootstrap\scss\_variables-dark.scss 55:37  @import
```

https://github.com/tabler/tabler/blob/d0e090fd0aa8917ef30bf7d48472cd9b396de4e4/src/scss/_variables.scss#L313

https://github.com/twbs/bootstrap/blob/27954217168f5293391a7f672bec69d5b27ca4dd/scss/_variables-dark.scss#L55

```diff
- $code-color: var(--#{$prefix}gray-600) !default; 
+ $code-color: $gray-600 !default; 
```

**Comment by asteinh** [comment]
> @asteinh We started working on the dark theme before it was even available in Bootstrap, I know it doesn't work perfectly yet, but I'm working on making it all work and look like it does in Boostrap 🙂 .

I hope my remarks didn't sound like criticism, I highly appreciate your hard work! Also, I'm using it because I think you're doing an amazing job 👍

> @asteinh did you try the release branch https://github.com/tabler/tabler/pull/1494 ?

Ups, no, completely missed that one. Will try that and keep you posted 😉 

> I think tint-color or any sass function (calculating functions) only accept sass variables not CSS variables

Yeah, that's the pitfall. I like the idea of having a prefix though, so wouldn't want to fix this by removing the css variable...

**Comment by asteinh** [comment]
> @asteinh did you try the release branch #1494 ?

Just tried this PR, but no luck - though not surprising since I don't see any changes to the use of css' `var` in scss variables, that are later used in scss calc-functions (first failure is still with `$code-color`, which is supposed to be tinted to yield `$code-color-dark`)... 😢

**Comment by sadeghbarati** [comment]
@codecalm 

Thanks for `tabler` ❤️ 

BTW, bootstrap must be in "peerDependencies" not in "dependencies"

**Comment by kevinpapst** [comment]
Thanks to recent improvements in Tabler, I could ditch my tomselect adjustments.

The other error went away by reversing the order of imports.
