### ISSUE TITLE
[BUG] Scrollbar appears

### ISSUE THREAD

**Issue by haitanghuadeng** [tabler/tabler#1447]
When the page is low on content, the scroll bar appears.
<img width="399" alt="20230131111609" src="https://user-images.githubusercontent.com/43346455/215654179-09ebb61e-1412-4cb7-acb1-fd45c937c146.png">

**Comment by copulatrix** [comment]
I think this is a bug, but not for the reason stated.

**1.**
I think the scrollbar's "reserved" space is a design choice (which I support).
My guess is, so regardless of if there is a scrollbar or not, the width of the "document" doesn't change.

Like if content was lazy-loaded, or there was an accordion, or tabs, etc.. 

**2.**
In pervious builds, the scrollbar space on the side was more "separated" from the content and looked better (in my opinion).
There was a different background colour then the body.

**Current Style**
![new](https://user-images.githubusercontent.com/76273853/215745993-8db5cb30-75c9-4d4a-9302-656967bef76f.png)

**Old Style**
![old](https://user-images.githubusercontent.com/76273853/215746060-6cdc86a7-369c-435c-9448-68562f9511bd.png)

I'd really like @codecalm's input on this.


[1] [Old Build](https://tabler-git-dev-photogrid-tabler-io.vercel.app/blank.html?theme=dark)
[2] [Current Preview Build](https://preview.tabler.io/blank.html?theme=dark)
[3] [The commit that made these changes(?)](https://github.com/tabler/tabler/commit/acd5fe128433522622b29e4d03193f13194ec59d#commitcomment-94310753)

**Comment by codecalm** [comment]
fixed :)
