### ISSUE TITLE
[FEATURE] Update timelines documentation

### ISSUE THREAD

**Issue by laractive** [tabler/tabler#1448]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
With the new [1.0.0-beta17](https://github.com/tabler/tabler/commit/e73415687629ab229eb253ddbdba36581045cb98) version we lost some timelines example code. Indeed, the new ones are great but the old ones are great too :-) Can you please re-add the old ones in the new doc ? Thx!

**Describe alternatives you've considered**
For now we can use git version of the doc page.

**Comment by kevinpapst** [comment]
The beauty of open source is: everyone can do it.
You recognized the diff, you even know how to display the old version.
What about raising a PR @laractive ?

**Comment by kevinpapst** [comment]
Can you point to the missing parts via a commit hash @laractive , so someone else can do it?
