### ISSUE TITLE
[BUG] Version 17's sidebar has more padding than version 16's

### ISSUE THREAD

**Issue by haitanghuadeng** [tabler/tabler#1452]
Version 17's sidebar has more padding than version 16's.
![image](https://user-images.githubusercontent.com/43346455/216204570-e5e99b6f-e085-416e-8428-8f4ca593b15b.png)
![image](https://user-images.githubusercontent.com/43346455/216204649-2bdefd54-6df1-4c3c-962a-120dd9046f20.png)
The first picture is version 17 and the second picture is version 16.Personally, I think if this was designed specifically, it would look like a left-right imbalance. If it wasn't for design reasons, I think we could go back to version 16. Thanks!

**Comment by codecalm** [comment]
it's padding from scrollbar to prevent jumping on sidebar when scrollbar is visible/invisible
