### ISSUE TITLE
Can I use it to do？

### ISSUE THREAD

**Issue by TongDaDa** [tabler/tabler#146]
Just look at it official introduction, I think it can be said to be an HTML template system, But it was no advantage for the Vue or React, if full rendering HTML page, they can also do SSR, please tell me, when building web applications, the difference between this project and other framework implementations?Don't only applies to a single page?

**Comment by lupuxyz** [comment]
传统的 MVC 用这种静态模版不是美滋滋吗？为什么非要给你们集成 VUE 或者 React ？而且你完全可以自己去做这方面的事情，要 SSR 也好，要 SPA 也好，你都可以自己去实现。

**Comment by TongDaDa** [comment]
不是集成 VUE 和 React, 在传统的MVC上的项目使用它或者本身项目就是特别简单的展示型页面是可以用的再就是一些极其简单的活动页面了，貌似只有这几种情况，我想不出其他的使用场景，另外，还有一个地方我没听懂，我为什么要自己去做实现这方面的事情(ssr spa)自己玩有什么优势吗？？？
