### ISSUE TITLE
[BUG] Beta 17 broke timelines

### ISSUE THREAD

**Issue by mholt** [tabler/tabler#1462]
**Describe the bug**

It seems that beta 17 broke the way timelines are displayed:

Before (beta 16): (I have customized the thickness and color of the line)

![image](https://user-images.githubusercontent.com/1128849/217640491-69323a17-74f1-4a2b-a7fe-bc91c2472ec4.png)

After (beta 17):

![Screenshot from 2023-02-08 13-10-06](https://user-images.githubusercontent.com/1128849/217640532-83b7a541-889d-439c-a199-6eaad77cb704.png)

My markup is:

```
<ul id="timeline" class="list list-timeline">
	<li class="list-timeline-card-item">
		<div class="list-timeline-icon">
			...
		</div>
		<div class="list-timeline-content">
			<div class="list-timeline-time">
				...
			</div>
			<div class="list-timeline-content-container">
				...
			</div>
		</div>
	</li>
</ul>
```

My custom classes made minor adjustments to spacing/sizing, but no major structural changes AFAIK.

I wonder if it's related to https://github.com/tabler/tabler/pull/1288/commits/e8e4372da2a00484a3597efec3712f2c5f99a09b ?

**Comment by codecalm** [comment]
hi @mholt ! 
in beta.17 timelines was separated from list component. Look at new syntax: https://dev.tabler.io/docs/timelines.html :)

**Comment by mholt** [comment]
Ohh, I see. It's a whole new look!

I think I like my current look for my app, so I've copied the styles from beta 16 into my style sheet :no_mouth:

I like the new Tabler timeline look too; it just turns out that the old UI looks better for this particular part of my app. Keep up the good work!
