### ISSUE TITLE
[BUG] In beta 17, --tblr-bg-surface-secondary is the same as --tblr-body-bg

### ISSUE THREAD

**Issue by mholt** [tabler/tabler#1463]
**Describe the bug**

In light mode, at least, the vars --tblr-bg-surface-secondary and --tblr-body-bg are both #f1f5f9.

This means that any element with a "secondary surface" background displayed on the body looks transparent (so things like card caps, etc). I don't know if this was intentional. It looks weird in my app :)

In beta 16, --tblr-bg-surface-secondary is set to --tblr-light, which is #f8fafc.

In beta 17, it's set to --tblr-gray-100, which is #f1f5f9, the same as --tblr-body-bg.

**Screenshots**

Beta 16:

![Screenshot from 2023-02-08 14-04-35](https://user-images.githubusercontent.com/1128849/217650626-dbd208a5-04b0-452d-a96f-0a80ddce4566.png)

Beta 17:

![image](https://user-images.githubusercontent.com/1128849/217650604-3635903e-25f9-45b9-9653-719904562c61.png)

I am working around this by changing my use of --tblr-bg-surface-secondary to --tblr-card-cap-bg, which maybe is more fitting anyway. I just wanted to let you know that --tblr-bg-surface-secondary now look transparent in case that wasn't intended.

Thanks for Tabler!

**Comment by codecalm** [comment]
As I see on preview, `bg-surface-secondary` and `bg-surface-tertiary` are different 

![Screenshot 2023-02-11 at 15 20 37](https://user-images.githubusercontent.com/1282324/218263004-5f7ab940-fb85-410b-97ac-bbf713f9cbd6.png)
![Screenshot 2023-02-11 at 15 21 06](https://user-images.githubusercontent.com/1282324/218263009-cd913d16-4291-44a7-a92c-0c8e0332cff1.png)

**Comment by mholt** [comment]
Oh :thinking: I'm not sure why then; maybe the variable changes based on the context and I have mine in a different context.

Anyway, my workaround is fine. Thanks!
