### ISSUE TITLE
[BUG] In beta 17, avatars overlap transparently

### ISSUE THREAD

**Issue by mholt** [tabler/tabler#1464]
**Describe the bug**

Sorry for all the new issues :sweat_smile: 

In beta 17, avatar lists now overlap each other and have transparency and alignment issues.

Before, with beta 16:

![image](https://user-images.githubusercontent.com/1128849/217653711-ddcc00be-0fa3-42d8-86b2-1e5038536655.png)

Now, with beta 17:

![image](https://user-images.githubusercontent.com/1128849/217654046-746b69d5-b7e1-4ea8-abe0-5df413787326.png)

My markup is:

```
<div class="avatar-list avatar-list-stacked">...</div>
```

If I remove the `avatar-list-stacked` class, then I almost get the desired results, except there's too much space between avatars now:

![image](https://user-images.githubusercontent.com/1128849/217654317-53820136-bf42-4096-8a88-739d74199a6b.png)

It seems that `gap: var(--tblr-list-gap);` on the `.avatar-list` class is the culprit. I can override this with my own CSS but I thought I'd mention that I didn't find the extra spacing particularly desirable.

Is there a better way to restore the beta-16 look?

**Also:** Is there a way to have the avatars spread apart/magnify when you hover the .avatar-list-stacked? Bonus points if it only expands the hovered avatar and pushes the others out of the way, kind of like the macOS dock: https://cdn.wccftech.com/wp-content/uploads/2020/01/dock-magnifcation-effect-macOS-1030x801.png -- this is definitely just an extra feature request but I think it could be great for usability in the long-run!

**Comment by codecalm** [comment]
I've fixed it! :)

**Comment by mholt** [comment]
Awesome, thank you!
