### ISSUE TITLE
[BUG] @import "~bootstrap/scss/functions"; is broken

### ISSUE THREAD

**Issue by Dibbyo456** [tabler/tabler#1475]
**Describe the bug**

Creating new issue as requested by @tinyoverflow
Discussion: https://github.com/tabler/tabler/issues/1394#issuecomment-1434999073 

````
[plugin:vite:css] [sass] Can't find stylesheet to import.
  ╷
1 │ @import "~bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
````

**To reproduce**

Steps to reproduce the behavior: https://github.com/Dibbyo456/tabler-bug-report

**Comment by SyntaxJoker** [comment]
We will be fixing that in https://github.com/tabler/tabler/pull/1477

**Comment by Dibbyo456** [comment]
It works now. Thank you.

**Comment by twf-nikhila** [comment]
@harryqt @kevinpapst I used npm install tabler, using the latest version
"@tabler/core": "^1.0.0-beta20",
and facing this issue

Is this not released yet?

**Comment by harryqt** [comment]
No, you need to use the `dev` branch.

**Comment by twf-nikhila** [comment]
@harryqt how to use dev branch when installing using npm?

**Comment by harryqt** [comment]
`npm install git+https://github.com/tabler/tabler.git#dev`

**Comment by twf-nikhila** [comment]
> `npm install git+https://github.com/tabler/tabler.git#dev`

It's weird...still doesn't work...using Webpack does have to do something?
