### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zsaw** [tabler/tabler#1476]
https://tabler.io/ Chinese Mainland cannot download

**Comment by codecalm** [comment]
can you show me error or something?

**Comment by kevinpapst** [comment]
Maybe the Gumroad Download link is blocked from China?
Whatever this issue is about, I don't think you can do much about it.
I checked the download link (from Austria) and it works.

**Comment by ollym** [comment]
Probably because you closed this https://github.com/tabler/tabler/issues/1156 China banned tabler

**Comment by codecalm** [comment]
I've tested it by https://www.vpnmentor.com/tools/test-the-great-china-firewall/ and everything looks good

![Screenshot 2023-02-21 at 18 05 09](https://user-images.githubusercontent.com/1282324/220412259-135b5ace-89d4-48e9-801d-53c2d96d768a.png)

**Comment by codecalm** [comment]
Tabler is downloaded from https://github.com/tabler/tabler/archive/refs/heads/dev.zip, I've checked it and github is blocked in China unfortunately

![Screenshot 2023-02-21 at 18 07 15](https://user-images.githubusercontent.com/1282324/220412764-8080e861-070e-433f-b924-6d60a55b6617.png)

@kevinpapst, @ollym what do you think about it?

**Comment by ollym** [comment]
I think the easiest is if we amass an army and invade China liberating its people of a authoritarian regime and removing all censorship including github. It'll be way easier than re-hosting the zip on a different host like caching it with Cloudflare R2 https://developers.cloudflare.com/r2/data-access/public-buckets/

**Comment by kevinpapst** [comment]
Or you could upload each release to Gumroad. Just in case you even care... actually it's not your fault, so why even bother? Each and every project on GitHub is not reachable.

I guess Chinese developers who care enough, do know how to get around this censorship via VPN.

**Comment by codecalm** [comment]
I've added proxy from https://tabler.io/download so we'll see
