### ISSUE TITLE
UI Kit Preview for Tom-Select

### ISSUE THREAD

**Issue by kevyworks** [tabler/tabler#1480]
**Is your feature request related to a problem? Please describe.**
No, but advertised as using tom select.

**Describe the solution you'd like**
Form Multiple Select should be tom-select which is user can chose multiple items, also advertise the fix of height of it.

**Describe alternatives you've considered**
N/A

**Comment by kbonato** [comment]
Excellent feature, I use tom for the same function, but I have problems with the dark mode version of tabler using tom, if the tabler had something similar, it would be perfect.
currently depending on a select box with a search field.

**Comment by codecalm** [comment]
done! :)
