### ISSUE TITLE
[Question]Is this project active?

### ISSUE THREAD

**Issue by bloggervista** [tabler/tabler#149]
Just wanted to know whether the project is being maintained or not :)

Thanks

**Comment by beeman** [comment]
Hi @bloggervista, check the state of the [contributors](https://github.com/tabler/tabler/graphs/contributors) and make your judgement based off that.

**Comment by bloggervista** [comment]
I checked thats why may be many core contributers are busy and lot of prs
etc

**Comment by codecalm** [comment]
Hi guys, I'm changing my job and I have a lot of things to do. Next week I will have a lot of free time again so be ready for new commits

**Comment by gnpretorius** [comment]
Cheers @codecalm 

Let us know if we can help :)

G
