### ISSUE TITLE
[BUG] Empty variables in compiled CSS

### ISSUE THREAD

**Issue by cavasinf** [tabler/tabler#1490]
**Describe the bug**
Some parameters/variables are empty inside the `tabler.css` file
https://github.com/tabler/tabler/blob/main/dist/css/tabler.css

Search for `: ;` and 13 elements will be found:
- https://github.com/tabler/tabler/blob/main/dist/css/tabler.css#L3857
- https://github.com/tabler/tabler/blob/main/dist/css/tabler.css#L3971
- ...

**Comment by cavasinf** [comment]
Same case on bootstrap side -> https://github.com/twbs/bootstrap/issues/36595

Due to sass `null` value are compiled into CSS empty value.

**Comment by RishabhDixit1** [comment]
I want to work with this issue
