### ISSUE TITLE
[BUG] dots in table

### ISSUE THREAD

**Issue by kbonato** [tabler/tabler#1496]
Hi,

I'm trying to put the points dropdown inside a table, but when the table is small, it creates a scroll inside.

![image](https://user-images.githubusercontent.com/26029330/222541061-c0f07f66-c85b-4837-8075-716edd06c579.png)

**Comment by rjd22** [comment]
This is a known issue that cannot be fixed because of the limitations of CSS and the other features the overflow css fixes. Add a min-height to your table to accommodate the dropdown.
