### ISSUE TITLE
[FEATURE] allow 2 <tr> to merge visually / remove border-bottom 

### ISSUE THREAD

**Issue by nerdoc** [tabler/tabler#1497]
**Problem description**
When creating a table (with borders), sometimes it is necessary to have two rows having NO horizontal border between them. E.g. when creating rows for days in a month, and one day needs 2 lines/entries within the same day.
![grafik](https://user-images.githubusercontent.com/2955584/222955460-237a4c1d-d495-4dde-8d15-65ca56d0be3a.png)

There is a border-bottom-0 class, but this doesn't sesm to work in Tabler, even not in Bootstrap, as it may be only used for divs.

**Possible Solution**
I don't know how to realize this ttechnically, but it would be nice to have a class that removes the border between two rows, by not drawing the bottom border.

**Describe alternatives you've considered**
Not using tables, but `div`s with `class=row/col`. But for tabular data tables are best.

**Comment by dheineman** [comment]
Borders styles for a table are set on the cell. So by adding the `border-bottom-0` class to each `td` of a row you should get the desired effect.

![Screenshot 2023-03-06 at 09 24 36](https://user-images.githubusercontent.com/516028/223056322-d1e0dd10-cc76-4d24-9770-e70bc9e4bcb5.png)

**Comment by nerdoc** [comment]
OMG. Sorry for the spam... I could have seen that... Thanks.
