### ISSUE TITLE
 Problem with list view in safari

### ISSUE THREAD

**Issue by yh0438** [tabler/tabler#151]
I accessed from safari of mojave. When you view the list view, when you select additional options, the list view moves or the width changes.
file is video for understanding my issue.

[1111.mp4.zip](https://github.com/tabler/tabler/files/2096935/1111.mp4.zip)

**Comment by ckissi** [comment]
Already reported [here](https://github.com/tabler/tabler/issues/148).

Please try my temporary fix mentioned and let me know if it works for you or you experienced some other issues.

**Comment by yh0438** [comment]
do you have another way for solving this problem?
this way is all okay except full screen mode.

**Comment by ckissi** [comment]
Not yet, sorry. Hopefully, @codecalm will fix it soon.
