### ISSUE TITLE
[FEATURE] make hr-text-left/right direction aware

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1510]
**Is your feature request related to a problem? Please describe.**

https://preview.tabler.io/docs/divider.html

When using RTL languages, the classes `hr-text-left` and `hr-text-right` are troublesome.
They do not switch their direction, but always align as they are named, right or left.

When using the rtl CSS I would like to see the divider switch their direction automatically.

**Describe the solution you'd like**

I would like to see new classes that use the same naming and logic as Bootstrap for directions: 
`hr-text-start` and `hr-text-end`.

For BC sake, new classes should be added, while the old ones retaining their current logic. 

**Describe alternatives you've considered**

The least we should do is switch directions on RTL. But that would be misleading.

**Comment by kevinpapst** [comment]
Hey @BamaCharanChhandogi and welcome 👋 

No need for an "official assignment", you can start working on this topic and sent in a PR any time.

**Comment by BamaCharanChhandogi** [comment]
Hey, @kevinpapst  Should I remove the previous class hr-text left and hr-text-right?

**Comment by kevinpapst** [comment]
I would leave them for now, because they are in use. Maybe add a comment, that they are deprecated.
And you could adjust the demo to showcase the new classes https://preview.tabler.io/docs/typography.html

**Comment by kevinpapst** [comment]
Not stale afaik
