### ISSUE TITLE
[FEATURE] tabler is amazing icon lib, please support flutter totally, like as, support change thin weight stroke in flutter.

### ISSUE THREAD

**Issue by fee-studio** [tabler/tabler#1511]
Actually, I can use the table by tabler.ttf file in flutter, but I found that I can't change the icon thickness. I don't think .ttf files support this feature yet. In other words, there is no "thin/light version" of the .ttf file in the download files. I hope tabler will support this feature in flutter soon.

**Comment by kevinpapst** [comment]
Shouldn't that be posted in https://github.com/tabler/tabler-icons ?
