### ISSUE TITLE
[FEATURE] multi select tags

### ISSUE THREAD

**Issue by raulriera** [tabler/tabler#1514]
**Describe the feature**

It appears the tags and advanced tags examples are pretty much the same, it would be ideal if the advanced one had an option for multi select https://preview.tabler.io/form-elements.html#

![2023-03-25 20 57 32](https://user-images.githubusercontent.com/24159/227751105-2eae7ca2-d869-40da-8836-abf6d57fc7b9.gif)

**Describe the solution you'd like**
It could look something like this, pretty much a "tokenized" search (without the clearing of items of course)

![2023-03-25 20 58 39](https://user-images.githubusercontent.com/24159/227751131-f982cb38-5d24-4ad0-b14b-f28271d8ef22.gif)

**Describe alternatives you've considered**
Haven't considered anything else to be honest

**Comment by Ebuka636** [comment]
Awesome

**Comment by johnwilson** [comment]
@raulriera From the `package.json` file I see they're using https://tom-select.js.org/ . It shouldn't be hard to implement this feature using javascript seeing that the styling has already been done.

**Comment by codecalm** [comment]
added in https://dev.tabler.io/form-elements.html, section **Select multiple states**

![Screenshot 2023-04-24 at 19 29 51](https://user-images.githubusercontent.com/1282324/234072266-befe3624-e3ae-4704-9057-2ed33ee6d182.png)

**Comment by JobberRT** [comment]
I been waiting for this feature for so loooong and feel great to finally have it here!
This features can also be called as `Tags Input`. I just visit the dev preview page, and notice some minor issues:
1. It seems that selected item doesn't have a visually indicator of delete itself.
2. It seems that you can not input a new value and create a new tag.

I'm currently using tabler + [bootstrap5-tags](https://github.com/lekoala/bootstrap5-tags), and bs5-tags is fairly complete. Maybe you can check its code and get some idea?
