### ISSUE TITLE
[BUG] Table cell text offset bug

### ISSUE THREAD

**Issue by PeterKneale** [tabler/tabler#1521]
Table cells have text content misaligned when building a valid table structure that uses either multiple rows in the thead or using a rowspan in the tbody

**Device**

 - Browser Chrome Version 111.0.5563.147 (Official Build) (64-bit)
 - OS: Windows 10
 - Screen size Multiple Tested

**To reproduce**

- [Minimal reproduction here (https://codepen.io/peterkneale/pen/RwebdGm)](https://codepen.io/peterkneale/pen/RwebdGm)
- Observe the cells containing red text, each has an incorrectly offset value

**Screenshots**
![image](https://user-images.githubusercontent.com/710594/230109873-47ebba4d-2b5c-462c-a2be-3f9a5a5c1103.png)

**Comment by BamaCharanChhandogi** [comment]
Hey,  I want to contribute. Where does the table cell code have in the tabler project?

**Comment by PeterKneale** [comment]
If you have a look at the example where I have reproduced the issue you can see the classes involved. I'm not sure where they are in the project nor how to modify them. I'm a backend dev using this theme to display a report and observed that it is a little unpredictable when using colspan and rowspan.

**Comment by BamaCharanChhandogi** [comment]
Hey, I am used to padding properties in CSS. I am giving a screenshot.
<img width="837" alt="image" src="https://user-images.githubusercontent.com/69814563/231092958-9096d9e0-d3e1-4577-ba3b-700e432de88f.png">


But I cannot understand where I will be adding this code!
 Thanks.

**Comment by AnuragNishad12** [comment]
hey @BamaCharanChhandogi where u find this error ?
can u show me in from the project?

**Comment by PeterKneale** [comment]
Can anyone suggest a fix or a workaround. As you can see in the attached reproduction it makes tables look quite odd.

**Comment by BamaCharanChhandogi** [comment]
could I post the code here?

**Comment by PeterKneale** [comment]
Sure

**Comment by BamaCharanChhandogi** [comment]
I am giving a link for the check.
[https://codepen.io/BamacharanCh/pen/mdzRGgw](url)

**Comment by BamaCharanChhandogi** [comment]
@PeterKneale Can you join me in any discussion group of this project?

**Comment by PeterKneale** [comment]
Sorry im just a user of this library, I have no special permissions

**Comment by PeterKneale** [comment]
Closing this, removing the `card-table` class from the table fixes the issue
