### ISSUE TITLE
[BUG] btn-action <a>/<button> does not follow disabled state

### ISSUE THREAD

**Issue by nerdoc** [tabler/tabler#1524]
**Describe the bug**

When using disabled action buttons, they shoud not react to mouseover/show a hover effect, but they do.

**Device**

 - Browser: Firefox 111.0.1
 - OS: Linux/Manjaro current
 - Screen size 1600x900

**To reproduce**

Write a card or table td with an action button which is a dropdown, and the toggler is not an <a> element, but a <button>, which is valid bootstrap (and good if you don't want the user to easily see the link in the bottom of the browser when hovering).
This is a django template
```django
<button
    class="btn-action dropdown-toggle"
    type="button"
    id="dropdown-action-{{ day_entry.date.isoformat }}"
    data-bs-toggle="dropdown"
    aria-expanded="false"
    {% if not actions_enabled %} disabled{% endif %}
>
  <i class="bi bi-three-dots-vertical"></i>
</button>
<ul class="dropdown-menu" aria-labelledby="dropdown-action-{{ day_entry.date.isoformat }}">
  {% if day_entry.can_add_holiday %}
    <li><a class="dropdown-item" href="#">Request holiday</a></li>
  {% endif %}
</ul>
</div>
```

when using the <a> you'd have to use `class="... disabled"` instead of a `disabled` attribute, but it doesn't work neither.
The button does "highlight" on hovering.

However, the underlying function (dropdown) does work as intended (does not drop down) when disabled - as this is done by bootstrap.

Seems to be a simple CSS issue.

**Comment by BamaCharanChhandogi** [comment]
Hey @nerdoc, you can try adding a CSS rule for disabled buttons to remove the hover effect.

`.btn-action.disabled:hover {
  background-color: transparent !important;
  color: inherit !important;
}
`
Thanks

**Comment by nerdoc** [comment]
@BamaCharanChhandogi Thanks for the quick hint, but I suppose this should be fixed in tabler.io itself?

**Comment by rjd22** [comment]
You're missing the `btn` class. It needs to be `btn btn-action` to make disabled work properly.
