### ISSUE TITLE
[BUG] Bootstrap import issue in node_modules

### ISSUE THREAD

**Issue by levonmidoyan** [tabler/tabler#1527]
**Describe the bug**
When trying to import **_tabler.scss_** after installing _**@tabler/core**_ it throws an error that it couldn't import "_bootstrap/functions_" (Image 2). If I try to remove "**../../node_modules/**" part from import it work but it's not a solution.

Please take into account this fix and I think it is critical issue.

**Screenshots**
Image 1
![image](https://user-images.githubusercontent.com/57284189/230881761-fd1cf14d-7680-410e-a041-b8ba12a653a4.png)

Image 2
![image](https://user-images.githubusercontent.com/57284189/230881080-bdde20ae-bc64-475f-b62b-458b8ba2bbf5.png)

Image 3
![image](https://user-images.githubusercontent.com/57284189/230882195-59332448-b3c6-4f0c-a81b-7b30149e2368.png)

**Comment by AxxiD** [comment]
I have the same problem.
It can be fixed by removing the relative path as you said. One could use [patch-package](https://www.npmjs.com/package/patch-package) for the time being - but that's no good solution.

**Comment by kevinpapst** [comment]
This was fixed in https://github.com/tabler/tabler/pull/1477 and included in Beta 18/19.

**Comment by levonmidoyan** [comment]
Thanks @kevinpapst
