### ISSUE TITLE
[BUG] A dropdown menu in a row of a list.js table is not displayed correctly when using the search function

### ISSUE THREAD

**Issue by SirTom76** [tabler/tabler#1529]
**Describe the bug**

If you use a dropdown menu in a row of a list.js table and then restrict the data by using the search, then with little data the table height becomes so small that the dropdown menu creates scrollbars and is no longer displayed completely. As a current workaround, the only thing that helps is to specify a minimum height in the css.

**Device**

 - Browser: Edge 112.0.1722.34 and Safari 16.4 (18615.1.26.11.23)
 - OS: MacOS 13.3.1
 - Screen size: 2560 x 1600 Pixeln bei 227 ppi

**Comment by cavasinf** [comment]
Can be the same problem with table responsive and dropdown

See this comment: https://github.com/tabler/tabler/issues/1343#issuecomment-1308569481
