### ISSUE TITLE
Not Responsive when viewed in mobile

### ISSUE THREAD

**Issue by RogerioCarbonera** [tabler/tabler#153]
Hello 
I don't know what am I doing wrong, but tabler is not working when I access it from a mobile. When I use a mobile's browser simulator it works fine. 
When I use purely use the tabler's dist, it works normal. 
What am I forgetting ?

**Comment by RishabhSinghShekhawat** [comment]
hello Rojerio,
yes it will only work on desktop view. Working to solve this.

**Comment by thlbaut** [comment]
Any news ? 😀

**Comment by RogerioCarbonera** [comment]
I found the problem. 
Unfortunately , i forgot to put the meta tags inside the HEAD. 
After this, it works perfectly.
We can close this issue.
