### ISSUE TITLE
[BUG]  Class Overlapping Heading

### ISSUE THREAD

**Issue by AnuragNishad12** [tabler/tabler#1532]
I has identified an issue with the class overlapping the heading in the project. This is causing the heading to be partially obscured and is negatively impacting the website's overall design and user experience. U can Also see this from the screenshots

<img width="205" alt="Screenshot 2023-04-13 130141" src="https://user-images.githubusercontent.com/124987038/231688382-ddcc1e53-47b1-4e48-bc7f-99152702feeb.png">

**Comment by akhil888binoy** [comment]
can you please assign this to me?
