### ISSUE TITLE
[FEATURE] Imask like a external lib

### ISSUE THREAD

**Issue by vjmartins** [tabler/tabler#1535]
First, AWESOME work. I'm a fan of Tabler.  👍 😄 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Imask in libs folder

Easier to update and not increase tabler size.

**Comment by rjd22** [comment]
If you use tabler with NPM the imask library is already a peer dependency and not loaded unless requested. Packaged solutions we include all libraries so all functionality is working as expected.
