### ISSUE TITLE
[BUG] Checkbox `:indeterminate` CSS color

### ISSUE THREAD

**Issue by cavasinf** [tabler/tabler#1536]
**Describe the bug**

Checkbox CSS of `:indeterminate` state is not linked to the CSS tabler vars.
https://github.com/tabler/tabler/blob/e84ab993119879d26a9b9c30095e8a0a2bab8abd/dist/css/tabler.css#L2870-L2874

It should be like `:checked` behavior
https://github.com/tabler/tabler/blob/e84ab993119879d26a9b9c30095e8a0a2bab8abd/dist/css/tabler.css#L2860-L2863

**To reproduce**

1. Override `--tblr-primary` color
2. Add checkboxe
3. Set `indeterminate` to `true`
4. See wrong color

**Screenshots**
![image](https://user-images.githubusercontent.com/25293190/233008040-bbfdf2cb-60d1-4b92-8cac-4be31f7e97a9.png)

**Comment by codecalm** [comment]
@Saran-pariyar we should add to config:

```scss
$form-check-input-indeterminate-bg-color: var(--#{$prefix}primary) !default;
```
