### ISSUE TITLE
[FEATURE] List of Tabler.io examples

### ISSUE THREAD

**Issue by aliqasemzadeh** [tabler/tabler#1545]
I think it would be a good idea to have tabler.io and tabler-icons example pages.
A repository can be most easiest way to do this job.

@codecalm

**Comment by cavasinf** [comment]
You mean like this one https://preview.tabler.io/
And this one https://tabler-icons.io/
❓

**Comment by aliqasemzadeh** [comment]
@cavasinf 
No,  For example:
https://github.com/aliqasemzadeh/bap

**Comment by cavasinf** [comment]
OK, you need to be more specific in your title and description.

You can run this repository in the Docker env https://github.com/tabler/tabler#running-with-docker
If you want to test + modify code at will, this is a good first/fast way to go.

**Comment by rjd22** [comment]
Since there are ample examples in the demo I'm closing this. I understand the wish but maintaining it will cost time that can be used somewhere else.
