### ISSUE TITLE
[FEATURE] New release version

### ISSUE THREAD

**Issue by lvanstrijland** [tabler/tabler#1546]
Hi,

Do you guys plan on making a new release version soon? Currently I'm unable to build my project on the production environment because of this missing fix:

https://github.com/tabler/tabler/pull/1477

Kind Regards,
Laurens van Strijland

**Comment by haitanghuadeng** [comment]
Agree, I'm looking forward to seeing the fixes and new features of the last few months in version 18😀

**Comment by kbonato** [comment]
@codecalm any idea about release date for next version?

**Comment by haitanghuadeng** [comment]
> 知道下一个版本的发布日期吗？

I don't know yet, and I haven't seen a new version in many branches.😅

**Comment by kevinpapst** [comment]
Fix has been merged, a new release was published: https://github.com/tabler/tabler/releases/tag/v1.0.0-beta18
