### ISSUE TITLE
[FEATURE] New Tags component

### ISSUE THREAD

**Issue by codecalm** [tabler/tabler#1550]
## Description

We need to add a new Tag component to our project. The Tag component will be used to label and categorize content within the application.

The Tag component should also support the ability to add an avatar, flag, label, or dot inside each tag. These visual indicators can be used to provide additional context or information about the content associated with the tag.

The avatar can be an image or an icon that represents the tag. The flag can be used to highlight important or urgent tags. The label can be used to provide a short description of the tag. The dot can be used to indicate the status or progress of the content associated with the tag. These visual indicators should be optional and customizable for each tag.

In addition to the avatar, flag, label, or dot inside the tag, the Tag component should also support an optional close indicator. This indicator can be used to allow users to remove a tag from the content.

## Development

To ensure consistency and ease of customization, the Tag component should have configurable styling options for the border, background, shadow, and other visual elements. These styling options should be defined in a `_variables.scss` file, which can be easily accessed and modified by developers.

By using variables for styling options, we can ensure that the Tag component is consistent with the overall design of the application and any changes to the design can be easily applied across the entire application.

To ensure that the Tag component is organized and easy to maintain, the new component should be placed in the `src/scss/ui/_tag.scss` file. This will allow developers to easily find and modify the Tag component when necessary.

In addition, the CSS class name for the Tag component should be `.tag`. This will ensure that the class name is descriptive and easy to understand for other developers.

To showcase the functionality of the Tag component, a demo should be included in the tag.html file. This demo should demonstrate the various features and visual indicators that are available for the Tag component. It should also be visually appealing and consistent with the overall design of the application.

Finally, the Tag component should be added to the **Interface** menu so that it can be easily accessed by other developers. This will help ensure that the Tag component is used consistently throughout the application and can be easily modified and updated as necessary.

Let's ensure that the Tag component is developed and organized in a way that is consistent with the overall design of the application and follows established naming conventions and file structures.

## Design

<img width="800" alt="tags" src="https://user-images.githubusercontent.com/1282324/235361698-8cc315e5-93c1-4d17-b4e7-08742ac8a429.png">

<img width="800" alt="tags-annotations" src="https://user-images.githubusercontent.com/1282324/235361701-967e6e13-ce4f-42af-8523-e0fe5b00f7ea.png">

**Comment by kevinpapst** [comment]
Tomselect allows custom renderer and it has a "tagging" mode.
What exactly should this component provide? Do you plan to create an interactive JS component?

**Comment by codecalm** [comment]
I want to have independed tag component, which can also be rendered in `tom-select`. I have to create component similar to this:  https://dribbble.com/shots/19255413-Settings-Callout-AI-Powered-Content-Discovery

![image](https://github.com/tabler/tabler/assets/1282324/9accfd9c-b372-41dd-892f-541764dacf5b)

**Comment by kevinpapst** [comment]
Looking forward to see it. Tomselect is not ideal, but working for now...

**Comment by kevinpapst** [comment]
Its live: https://preview.tabler.io/tags.html - so this one can be closed.
