### ISSUE TITLE
[FEATURE] Add iDEAL as a payment method svg

### ISSUE THREAD

**Issue by rubenuijtdewilligen** [tabler/tabler#1552]
[iDEAL](https://en.wikipedia.org/wiki/IDEAL) is the most used payment method in the Netherlands and all Dutch webshops have an iDEAL icon placed on their website. It was also recently acquired by the European Payments Initiative [to become the standard in Europe](https://nltimes.nl/2023/04/25/dutch-payment-processor-ideal-become-european-standard). I think it would be great to add an svg logo of this major payment method to Tabler.

**Comment by kevinpapst** [comment]
Should be posted here: https://github.com/tabler/tabler-icons
