### ISSUE TITLE
Card Action Not Responsive

### ISSUE THREAD

**Issue by jay-shah-rushiinfotech** [tabler/tabler#156]
> https://tabler.github.io/tabler/docs/cards.html

Card Actions are not responsive. Buttons are not properly arranged.

**Comment by codecalm** [comment]
@jay-shah-rushiinfotech can you show any screenshot?

**Comment by jay-shah-rushiinfotech** [comment]
In Advanced Card section there is option for buttons.

If we add more buttons like 4+.

Then design doesn't look proper.

Buttons should be stacked from new row.

**Comment by codecalm** [comment]
@jay-shah-rushiinfotech in this situation dropdown should be better instead of 4 buttons :)

**Comment by jay-shah-rushiinfotech** [comment]
![screenshot from 2018-06-22 18-10-05](https://user-images.githubusercontent.com/26960005/41777260-5d1cb2a8-7648-11e8-9cfd-498104442d3f.png)
![screenshot from 2018-06-22 18-14-40](https://user-images.githubusercontent.com/26960005/41777264-5f46b3ee-7648-11e8-9f3e-8e9405993df7.png)

**Comment by jay-shah-rushiinfotech** [comment]
Ok

**Comment by jay-shah-rushiinfotech** [comment]
But not good for desktop preview.
For that we have to show or hide or manage for different display.
