### ISSUE TITLE
[BUG] modal.hide(); wont work

### ISSUE THREAD

**Issue by ImLoadingUuU** [tabler/tabler#1565]
**Describe the bug**
Modal.hide(); not works!
return undefined.
**Device**

 - Browser Firefox 113
 - OS: OS X
 - Screen size [e.g. 800x600]

**To reproduce**

```js
new bootstrap.Modal("#modal").hide();
```

**Comment by rjd22** [comment]
There is too little information to make this actionable. Most likely something is wrong in your code and not Tabler. For that reason I'm closing this.
