### ISSUE TITLE
[FEATURE] Variable for avatar-list-stacked gap size

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1567]
**Is your feature request related to a problem? Please describe.**

The gap between the avatars in the regular list is pretty large (too large for my use-case).
The `avatar-list-stacked` is too narrow.
See examples at https://tabler.io/docs/components/avatars

I would like to have something like this: 
<img width="283" alt="Bildschirmfoto 2023-05-14 um 19 56 06" src="https://github.com/tabler/tabler/assets/533162/c18068d6-03bf-45cb-b32b-f1bb67e80630">

I am currently overwriting the rule:
```
.avatar-list-stacked .avatar {
    margin-right: calc(var(--tblr-avatar-size)*-.1)!important;
}
```

Can we introduce a SASS variable for the default factor of `.5`, so we can change it at compile time?
https://github.com/tabler/tabler/blob/dev/src/scss/ui/_avatars.scss#L73

I can send a PR if you agree. Just need some feedback on the idea @codecalm

**Comment by rjd22** [comment]
This might be really usecase specific. I personally would like a bit more overlap (like 5px more) to make it clear to the user it's intentional:

![2023-05-26T11:41:10,627504864+02:00](https://github.com/tabler/tabler/assets/160743/8b3c0457-8275-4bdb-a84f-899f87d5bcf8)

**Comment by kevinpapst** [comment]
Like that: https://github.com/tabler/tabler/pull/1602 ?
