### ISSUE TITLE
[BUG] some variables missed in beta19

### ISSUE THREAD

**Issue by aliqasemzadeh** [tabler/tabler#1577]
Hi
I am using vite to build tabler in my project.
After I update to tabler beta19 I see some variables missed.

``-tblr-muted-dark``
``tblr-gap``
``tblr-rss-border-subtle``
``tblr-flickr-text-emphasis``
and lots of other variables.

My project repository is: https://github.com/aliqasemzadeh/bap

**Comment by kevinpapst** [comment]
The update to Bootstrap 5.3 brings expected BC breaks.

I had to swap some as well in my projects. 

But there are a lot of new variables, I would recommend to stick to the ones provided by Bootstrap and prefixed with `tblr` - read https://getbootstrap.com/docs/5.3/migration/ to find out about  the new `secondary`, `tertiary` and `emphasis` classes.

The `text-muted` class is also deprecated, if you change it now, you won't run into a update issue in the future.
