### ISSUE TITLE
[BUG] border-primary duplicate ??

### ISSUE THREAD

**Issue by vjmartins** [tabler/tabler#1578]
Hi,

Great job @codecalm 👍 

When i update from v1.07 to v1.0.19, a div with de class *border-primary* change.

In the tabler.css file i found:

.border-primary {
  border-color: #206bc4 !important;
}

.border-primary {
  --tblr-border-opacity: 1;
  border-color: rgba(var(--tblr-primary-rgb), var(--tblr-border-opacity)) !important;
}

Duplicate❓

**Comment by RishabhDixit1** [comment]
Is there open or someone is working on it...
