### ISSUE TITLE
[BUG] Important alert titles have the same color as their background

### ISSUE THREAD

**Issue by lovasoa** [tabler/tabler#1588]
**Describe the bug**

An `alert-title` inside an `alert-important` renders the alert title unreadable.

![image](https://github.com/tabler/tabler/assets/552629/b20cd40c-f4f3-4593-a4db-5fee5a97199d)

```html
<div class="
    alert
    alert-red
    alert-dismissible
    alert-important
" role="alert">
  <div class="d-flex">

    <div class="icon alert-icon">
      <i class="ti ti-alert-circle"></i>
    </div>

    <div>
      <h4 class="alert-title">Alert</h4>
      <div class="alert-description">SQLPage is entirely free and open source.</div>
          
    </div>

  </div>
    <a class="btn-close" data-bs-dismiss="alert" aria-label="close"></a>
</div>
```

**Comment by Nitz2611** [comment]
Can you assign me fo this?

**Comment by BamaCharanChhandogi** [comment]
Hey @lovasoa, This code is in which folder?

**Comment by lovasoa** [comment]
The snippet of code above was generated by sqlpage, it's not in any codebase.

**Comment by lovasoa** [comment]
I'm not sure I understand the question. The snippet of html in the original post reproduces the problem. The problem is that `alert-important` changes the background color, but not the color of the alert title, that becomes invisible.

**Comment by Nitz2611** [comment]
alert-title and alert-important both inherit same color from alert-red, thats why this problem occurs.

**Comment by Nitz2611** [comment]
#1610

**Comment by lovasoa** [comment]
thank you !

**Comment by allejo** [comment]
Was this fix pushed out in a new release and/or pushed to the documentation website?

<img width="722" alt="image" src="https://github.com/tabler/tabler/assets/1246453/d6c62f82-af3e-4de3-9501-67e7723177cf">
