### ISSUE TITLE
[FEATURE] Legend component

### ISSUE THREAD

**Issue by TheHadiAhmadi** [tabler/tabler#1590]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I like to use legend tag inside Fieldset, but styles are not what I expect.
![IMG-20230519-WA0000.jpg](https://github.com/tabler/tabler/assets/42554876/7ad7425c-74c1-4777-bea5-3c5c3d7a43ae)

As you can see font size is very large and doesn't fit in mobile screens, I like to have something like this: 
![Screenshot_20230520_185637_Chrome.jpg](https://github.com/tabler/tabler/assets/42554876/140fde4c-9d21-4dd2-bd6a-cf1252055b9a)

**Describe alternatives you've considered**
As alternative workaround I am writing CSS for legend tag myself.

Thanks for creating this beautiful library

**Comment by rjd22** [comment]
I would indeed recommend changing the margins of the legend tag in your own CSS, as this is a really user specific usage of the legend.

If you want a more similar working option I recommend looking at separating forms with the HR tag. These don't add margins to the form.
