### ISSUE TITLE
[BUG] Card header is too bright (lacks contrast)

### ISSUE THREAD

**Issue by mholt** [tabler/tabler#1592]
**Describe the bug**

The card header is too close to white. In Tabler beta 17 it was a more legible color.

**Device**

 - Browser [e.g. Chrome ver.22, Safari ver.10] Firefox, Chrome, and Safari
 - OS: [e.g. Windows 10] Linux, and Mac
 - Screen size [e.g. 800x600] 5120x1440 and others

**To reproduce**

Basically just using the `--tblr-card-cap-bg` variable

**Screenshots**

![image](https://github.com/tabler/tabler/assets/1128849/067c70bf-5e3f-4b45-9260-b46c0a0471f4)

I'm not sure if the lack of contrast is obvious on your screen, but on mine the two (`--tblr-card-cap-bg`, which evals to `--tblr-bg-surface-tertiary`, which is `--tblr-gray-50`, which is `#fcfdfe`; and `#fff`) are nearly identical. I was confused as to why my card headers suddenly became "white" but then I looked closely and it's actually a very very very very very light grey.

I wouldn't mind going back to whatever color Tabler beta 17 used, or at least something closer to it than white.

`#fcfdfe` is _extremely_ close to `#ffffff`, moreso than a variable named `--tblr-gray-50` would lead me to believe.

---

Thank you as always for Tabler, I'm happy to continue sponsoring. Really appreciate the work you're doing!

**Comment by mholt** [comment]
Actually, contrast seems to be poorer in beta 19 in general:

![image](https://github.com/tabler/tabler/assets/1128849/77ee3525-8ff9-499d-a2c0-fb6ff1a159a2)

This icon has class `.dropdown-item-icon` which used to be legible, now it's barely visible. I feel like the muted text below it which has class `.text-body-secondary` is also darker than it used to be in beta 17.

Any chance we could brighten those up a bit? :smiley:

**Comment by mholt** [comment]
Ah, looks like I'm not the only person who thinks the dark text is hard to read: https://github.com/tabler/tabler/issues/1570 (sorry for the duplication)

**Comment by Dev-Ravish** [comment]
Hey, 

Actually, I am new to this open-source world, so, would you please assign me this issue and help me out taking my first srtep?

**Comment by rjd22** [comment]
@Dev-Ravish you can just pick up any issue and work on it. We don't assign issues.

**Comment by SKeeneCode** [comment]
I just want to throw in my support that the contrast in general, especially the card headers should be increased.

Would be cool to see if the devs agree that the contrast needs adjusting as it's rather subjective.
