### ISSUE TITLE
[BUG] Inconsistency between input-group and input-group flat

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1594]
**Describe the bug**

Please see the screenshots, I have a missing border when using `input-group-flat`.

With `input-group`:
<img width="408" alt="Bildschirmfoto 2023-05-23 um 19 12 33" src="https://github.com/tabler/tabler/assets/533162/076d62ab-f06b-435a-881d-74f247724801">

With `input-group-flat` the right border is missing:
<img width="686" alt="Bildschirmfoto 2023-05-23 um 19 12 50" src="https://github.com/tabler/tabler/assets/533162/c4a62eee-2feb-44dc-af4b-1aabe697ce5f">

In both cases the HTML looks like that:
<img width="811" alt="Bildschirmfoto 2023-05-23 um 19 15 07" src="https://github.com/tabler/tabler/assets/533162/37bd6046-6f93-4872-b2b1-355f34675708">

Triggered by the hidden element  `litepicker-backdrop`

The bug is actually caused by this CSS rule:

<img width="358" alt="Bildschirmfoto 2023-05-23 um 19 15 59" src="https://github.com/tabler/tabler/assets/533162/800e1274-1433-4038-8da9-1029c87f5cec">

If I deactivate the rule this happens:

<img width="696" alt="Bildschirmfoto 2023-05-23 um 19 16 43" src="https://github.com/tabler/tabler/assets/533162/73555709-3469-4ac5-99a1-5a5b55115a90">

One border to much (at the dropdown in the right input).

Any ideas?

**Comment by rjd22** [comment]
The problem with input groups is that they try to detect elements on the left and right side and determine if a border is needed or not causing your issue here.

Because litepicker adds an extra element this code is triggered. Solving this in tabler is possible to would add a really specific case and might not work as expected. I would recommend solving this in your project so you have more control on the solution.

**Comment by kevinpapst** [comment]
I agree partially, but there is also the `input-icon` and `input-icon-addon` classes, which try to solve that problem:
https://preview.tabler.io/form-elements.html

![Bildschirmfoto 2023-05-26 um 13 36 53](https://github.com/tabler/tabler/assets/533162/a1c11a78-f760-465f-9ef0-c64810519d0e)

Using these classes the borders are perfect (so the problem is already solved somehow in Tabler) BUT these classes prevent that my icon (which is a a/link element) is clickable.

**Comment by rjd22** [comment]
@kevinpapst Would you be willing to make a specific fix for this in the litepicker.scss? To not remove the border when the last element is litepicker-backdrop or to re-add it?

https://github.com/tabler/tabler/blob/dev/src/scss/vendor/_litepicker.scss

**Comment by kevinpapst** [comment]
Sure, I just don't know how. 
I am okay with standard CSS, but all these extended features that codecalm applies are partially black-magic for me.

Can you point me in the right direction and I'll google the rest of it. 
Can the :not operator be chained, can it be used with classes?

**Comment by kevinpapst** [comment]
I solved it differently.

The `<div class="litepicker-backdrop" style="display: none; z-index: 9998;"></div>` is created by [Mobile friendly plugin](https://litepicker.com/docs/plugins/mobilefriendly/) for Litepicker. It inserts that node adjacent to the first litepicker initialized on the page (which is the actual problem here and also a bug if you use Litepicker in dropdowns!).

I solved the mentioned layout problem above, by moving the backdrop element to another parent in the `setup()` method of Litepicker:
```javascript
            options = {
                element: element,
                plugins: ['mobilefriendly'],
                autoRefresh: true,
                setup: (picker) => {
                    // only if mobile.friendly plugin is activated
                    if (picker.backdrop !== undefined) {
                        // the node needs to be moved, so the flat form layout works properly (e.g. for date types)
                        document.body.appendChild(picker.backdrop);
                    }
                },
                ...
            }};
```
