### ISSUE TITLE
[BUG] Alert backgrounds don't match dark theme

### ISSUE THREAD

**Issue by robertsimionescu** [tabler/tabler#1607]
**Describe the bug**

Seems that after the recent upgrade to not use class for dark theme but instead the data-bs-theme attribute, some elements were not upgraded. Alerts don't have the dark theme background because of this.

**Device**

 - Browser [e.g. Chrome 113, Safari 16.5]
 - OS: [e.g. MacOS 13.4]
 - Screen size [e.g. 800x600]

**To reproduce**

1. go to [preview.tabler.io](https://preview.tabler.io/)
2. Switch to dark theme
3. Inject some simple alert html like:
  ```
<div class="alert alert-success" role="alert">
    <div class="text-muted">Wrong white background!</div>
  </div>
```
4. See the background still white

**Screenshots**

<img width="1549" alt="image" src="https://github.com/tabler/tabler/assets/3469630/573603c7-63bf-461f-8c89-13c5f1d2604f">

**Comment by diomed** [comment]
isn't it point of alert to be very distinctive, so it warns you that something's off?

IMHO it shouldnt blend in but jump out, as it does

**Comment by robertsimionescu** [comment]
I consider this a bug because I haven't found any mention of it in the change log, and seems the white background is not specifically set as white on the dark theme but a simply inherited value. This used to be controled with the .theme-dark class like this:

<img width="565" alt="image" src="https://github.com/tabler/tabler/assets/3469630/95fa6436-73fe-4d3b-88d7-f61ba3116118">

**Comment by pixelbotme** [comment]
may I ask - what was the solution?

**Comment by beginor** [comment]
@pixelbotme  please try this style fix:

```css
[data-bs-theme=dark] .alert:not(.alert-important) {
  background-color: var(--tblr-bg-surface);
  color: inherit;
}
```

**Comment by codecalm** [comment]
it's already fixed in https://dev.tabler.io/alerts.html?theme=dark 🙂

**Comment by lovasoa** [comment]
Great ! Do you know when the fix will be released ?
