### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by lightyrs** [tabler/tabler#161]
Doesn't seem to be much activity here. As someone invested in tabler (https://github.com/lightyrs/tabler-rubygem), I would be grateful to hear of a status update from the devs. Is this still being actively developed and/or maintained?

**Comment by lightyrs** [comment]
cc @codecalm

**Comment by bloggervista** [comment]
He says he will work after week. I guess this repo need maintainers :)

**Comment by drale2k** [comment]
Typical risk with open source projects. You work on them if and when you can since they don't pay the bills. I hope the repo will find some maintainers since the theme is awesome but really needs some fixes and update (like support for vertical navigation, proper tabs in cards).

Fingers crossed

**Comment by codecalm** [comment]
Hi guys, I am sorry that I am not active in this project. I changed my job this month, and I don't have too much time to improve tabler. I have a lot of ideas, but day had only 24 hours. I did not expect such interest of this project, I know you have expectations from my side. 
If there is anyone who would like to help me continue to develop this project on a regular basis I will be very happy.

**Comment by shirshak786** [comment]
@codecalm  I am ready to help but only after exams which should be finished within 15 days :)

**Comment by JayaGaut** [comment]
@codecalm Hey, I am a Front-End developer and would like to be a maintainer for this project. Thanks

**Comment by DMW007** [comment]
@codecalm "continue to develop this project on a regular basis"
Does this mean that you're planning a completely move to Angular? I recently started using Tabler with ASP.NET Core...

**Comment by weedkiller** [comment]
@DMW007 any chance you can share some help on how you got this working with ASP Core
