### ISSUE TITLE
[BUG] - No Dark Theme

### ISSUE THREAD

**Issue by Derjyn** [tabler/tabler#1611]
**Describe the bug**

I recently started using Tabler for a small project. I have a very small layout, and wanted to utilize the dark theme. No matter what, the theme stays in light mode.

**Device**

 - Browser: Chrome Version 113.0.5672.127 (Official Build) (64-bit)
 - OS: Windows 10
 - Screen size: 1920x1080

**To reproduce**

1. Add `class="theme-dark"` to `body` tag.
2. Refresh page.
3. No dark theme.

**Screenshots**

![Screenshot 2023-06-02 190436](https://github.com/tabler/tabler/assets/648059/56a2c744-d866-4d99-a15c-e9beefb518e7)
![Screenshot 2023-06-02 190632](https://github.com/tabler/tabler/assets/648059/a3fbc121-ca12-4ee8-9c05-40d1b107e201)

**Comment by Derjyn** [comment]
It's not mentioned anywhere that I could find, but after more Google-fu, I found that applying following the Bootstrap approach _seems_ to work properly. Instead of adding `class="theme-dark"` on the `body` tag, you would add `data-bs-theme="dark"`.

This seems to be a hiccup with documentation.

**Comment by mholt** [comment]
Related: "auto" dark theme no longer works either. ("dark-auto")

It seems that Bootstrap does not have an equivalent for this?

**Comment by diomed** [comment]
did you guys try this new pull request, sent yesterday? maybe check it out and see if there's problems after it
