### ISSUE TITLE
[BUG] 'Uncaught TypeError: can't access property "classList", this._element is undefined'

### ISSUE THREAD

**Issue by davidsanchezpy** [tabler/tabler#1620]
When selecting a button or link to open a modal, I get an error message in the console.

'Uncaught TypeError: can't access property "classList", this._element is undefined'

**Device**

 - Mozilla Firefox for Developer v11.0b9 (64-bit)
 - OS: Windows 10

**Screenshots**

![img01](https://github.com/tabler/tabler/assets/6943839/2f14068a-8f92-4c55-bd45-adc771c1011b)

![img02](https://github.com/tabler/tabler/assets/6943839/c5243d00-1882-4f0e-9297-7a99da31a819)

**Comment by rjd22** [comment]
This is most likely a bug in your code and not tabler. Since we cannot replicate this locally I'm going to close is as non-actionable.
