### ISSUE TITLE
[BUG] Wrong input icon addon and is-invalid background icon positioning

### ISSUE THREAD

**Issue by esl51** [tabler/tabler#1630]
**Describe the bug**

Wrong input icon addon and is-invalid background icon positioning

**Device**

 - Browser: Chrome 114
 - OS: MacOS 13.4
 - Screen size: 2560x1440

**To reproduce**

```html
<div class="input-icon mb-3">
  <input type="text" value="" class="form-control is-invalid" placeholder="Search…">
  <span class="input-icon-addon">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path><path d="M21 21l-6 -6"></path></svg>
  </span>
</div>
```

**Screenshots**

<img width="360" alt="image" src="https://github.com/tabler/tabler/assets/3800914/ba43df7c-3f4e-4c08-a0cd-a2c3a2b95b15">

**Comment by jchine** [comment]
To solve it, creating a new style using the same padding applied to **.form-select.is-valid**

.input-icon .form-control:not(:last-child).is-valid,
        .was-validated .input-icon .form-control:not(:last-child):valid {
          padding-right:4.125rem;
          background-position:right 2.25rem center,center right 0.75rem;          
        }
        .input-icon .form-control:not(:last-child).is-invalid,
        .was-validated .input-icon .form-control:not(:last-child):invalid {
          padding-right:4.125rem;
          background-position:right 2.25rem center,center right 0.75rem;
        }
