### ISSUE TITLE
[BUG] badge-pill on Job listing not displayed in dark mode

### ISSUE THREAD

**Issue by jasonvriends** [tabler/tabler#1638]
**Describe the bug**

While in Light mode on https://tabler.io/demo/job-listing.html the experience required badges i.e., PHP, Laravel, CSS, Vue have a border. However, when changing to dark mode they just appear as text.

```
<div class="col-md-auto">
  <div class="mt-3 badges">
    <a href="#" class="badge badge-outline text-muted border fw-normal badge-pill">PHP</a>
    <a href="#" class="badge badge-outline text-muted border fw-normal badge-pill">Laravel</a>
    <a href="#" class="badge badge-outline text-muted border fw-normal badge-pill">CSS</a>
    <a href="#" class="badge badge-outline text-muted border fw-normal badge-pill">Vue</a>
    </div>
</div>
```

**Device**

 - Browser Edge
 - OS: Windows 11
 - Screen size 5120x1440

**To reproduce**

1. Go to 'https://tabler.io/demo/job-listing.html'
2. Click on 'Dark Mode'
3. See error

**Screenshots**

If applicable, add screenshots to help explain this problem.
<img width="700" alt="image" src="https://github.com/tabler/tabler/assets/36567972/6ffc0ddf-4854-4217-8250-0273b623ee2e">
![image](https://github.com/tabler/tabler/assets/36567972/3e2d9cd3-6f06-4e07-9142-d9549e5afdc5)

**Comment by siam1113** [comment]
This is my first contribution to any open-source and feeling very excited 😃

I gave a shot to resolve this with `border-primary`.

Now this is how it looks in dark mode:
![image](https://github.com/tabler/tabler/assets/81893922/0564c90e-3354-468e-b4b4-f758947d87db)

And this is how it looks in light mode:
![image](https://github.com/tabler/tabler/assets/81893922/9638e018-3dbd-4d85-9438-bbebd88d1439)
