### ISSUE TITLE
[BUG] npm install --save @tabler/core                                                

### ISSUE THREAD

**Issue by patch-work** [tabler/tabler#1639]
**Describe the bug**

Error returned by the installer.

**Device**

 - OS: Fedora Linux 38

**To reproduce**

npm install --save @tabler/core

**Log**

[2023-06-26T09_56_06_074Z-debug-0.log](https://github.com/tabler/tabler/files/11867455/2023-06-26T09_56_06_074Z-debug-0.log)

**Comment by rjd22** [comment]
I checked the log and this is most likely an NPM or some other package error. This seems not related to the tabler package itself.
