### ISSUE TITLE
[BUG] unpublished from NPM?

### ISSUE THREAD

**Issue by ceejayoz** [tabler/tabler#1651]
**Describe the bug**

Attempts to install @tabler/core fail with a 404 on repository.npmjs.org.

**Device**

 - Browser n/a
 - OS: n/a
 - Screen size n/a

**To reproduce**

`npm install @tabler/core`

https://www.npmjs.com/package/@tabler/core is still live, but https://registry.npmjs.org/@tabler/core returns a 404.

**Comment by rjd22** [comment]
Seems to be back again
