### ISSUE TITLE
add js file

### ISSUE THREAD

**Issue by asiz15** [tabler/tabler#166]
What is the correct way to add js code?

**Comment by imamdigmi** [comment]
Lets say you want to add your own js file e.g `app.js`:
add app dependency in shim and register the app.js path to `paths`

```javascript
require.config({
	shim: {
                // .......
               'app': ['bootstrap', 'jquery'],
	},
	paths: {
                // .......
		'app': 'js/app',
	}
});
```

and add `app` to array  in 
`require(['core', 'app']);`

it wotks for me

**Comment by rajkumarpb** [comment]
Hi, I try to do this along with requirejs.config({..}) script in dashboard to load an autocomplete plugin(dynamically). But it is not working and throwing error $ is not defined error.

Adding jquery related dependencies is really tough and it would be helpful if someone give some explanation.
