### ISSUE TITLE
[BUG] .table-responsive > Dropdown

### ISSUE THREAD

**Issue by debo900** [tabler/tabler#1662]
If the responsive table has a one or two rows (`<tr>`) then the dropdown-menu is going behind the div. Overflow issue. Tried to fix disabling overflow-x at parent, then the table looses its responsiveness. Any solution?

![table-issue](https://github.com/tabler/tabler/assets/28741916/f1a0210b-3735-48bf-9561-eeea1113bba0)
![table2](https://github.com/tabler/tabler/assets/28741916/4ef90aa6-7c27-4beb-92a7-07a27ba68d5c)

**Comment by rjd22** [comment]
This is not a bug. See: https://github.com/tabler/tabler/issues/1343#issuecomment-1308569481
