### ISSUE TITLE
Bootstrap modal close button shows twice

### ISSUE THREAD

**Issue by tpaksu** [tabler/tabler#167]
Hi, I can fix this problem but I wonder what's the correct way of doing this. 

When I open a bootstrap modal on this template, it shows like this:

![image](https://user-images.githubusercontent.com/3295/42867830-62392cd6-8a79-11e8-9ec2-3048c8034dd5.png)

Because of this code: 

```
.close:before {
    content: '\ea00';
    font-family: "feather";
}
```

The fix I think of is:
```
.modal-header .close:before {
   content: ''; // or display: none;
}
```

Am I thinking correctly?

**Comment by mrehayden1** [comment]
If you remove the symbol from your HTML it renders fine.
