### ISSUE TITLE
Did beta-19 CSS change?

### ISSUE THREAD

**Issue by mholt** [tabler/tabler#1678]
About 2 months ago I upgraded to Tabler beta 19, and then recently went back to work on my project and am using the preview.tabler.io site as a basis, and a lot of the styles are subtly different / not working for me.

I realized the tabler.min.css file -- also still on beta 19 -- is different now.

For example, when you hover dropdown items, they no longer have a light gray background (I think this is a bug, btw -- they should have some hover bg IMO). Lots of other hover interactions seem to have disappeared.

Is beta 19's tabler.min.css file the same now as it was 2 months ago?

**Comment by neacon-ivalkenburg** [comment]
I know for a fact the CDN link hasn't been updated for ages. For example the checkbox in the cdn are still small, while the preview shows they are way larger. After some investigation i noticed the CDN files have been updated for a long time.

**Comment by Kosire** [comment]
I just figured this out as well..
The tabler.min.css found on the preview.tabler.io site is not the same as the official released tabler.min.css found on GitHub, even though both files state that they are beta19.

**Comment by rjd22** [comment]
I'm going to close this as not actionable :). It's better for make separate issues for us with image examples for us so we can fix these issues on a case by case way.

**Comment by mholt** [comment]
Fair enough. I think the point of this issue is to clarify whether preview.tabler.io is running from HEAD or the latest tag; I suspect it may be HEAD. Thanks!

**Comment by rjd22** [comment]
http://preview.tabler.io is running from the latest tag as far as I know. But if you make an PR that will run from the latest HEAD.

**Comment by karimfromjordan** [comment]
This is really confusing. One more example where something doesn't seem right: The preview uses `#f6f8fb` for `--tblr-gray-50`, but the value you get if you use npm is actually `#fcfdfe` even though both are tagged to be `1.0.0-beta20`.
