### ISSUE TITLE
[BUG] Problem with with dropdown height, badges and styling

### ISSUE THREAD

**Issue by eThaffu** [tabler/tabler#1686]
Firstly, I have to use version **1.0.0-beta17** because after this version it started to get errors.
__________
![Bez tytułu](https://github.com/tabler/tabler/assets/15199646/9889a5b0-e2e9-47ee-92c1-a0c4cfdc4c49)
- This problem is that in newer versions the dropdown object broke and now its individual elements are higher than in older versions - it's not aesthetically pleasing.
- Why did the "--tblr-spacer" variable need to be changed from 1rem to 0.5rem?
_____
![Bez tytułu2](https://github.com/tabler/tabler/assets/15199646/e5b1c0e3-ff71-47dc-846a-b14591ff7005)
- Changing shade/color for tabler icons? What for?
- Variable "color: var(--tblr-icon-color);" i.e. "--tblr-icon-color: var(--tblr-gray-500);" that is "#6c7a91;" - in the old version. Now in the newer one we have "#929dab". Is it better darker or brighter?
_____
![Bez tytułu3](https://github.com/tabler/tabler/assets/15199646/7e28def2-a378-4486-901e-63adc894b13f)
- Since in the previous (my used) version the badges are legible, and in the new one I have some flowers, what should I do?
- For what purpose was this change made? I had to add "text-light" in my html code to make the numbers visible.
_____
![Bez tytułu4](https://github.com/tabler/tabler/assets/15199646/0c868266-3830-4f9d-9393-cfedb5d3df9f)
- I don't know if this problem has already been, but after sliding/showing Notifications on dropdown and hovering over the element, it goes completely pale and bright and white. Is this a bug or can this strange styling be resolved?

**Device**
 - Browser Opera 102 
 - OS: Windows 10
 - Screen size 1920x1080

**Comment by eThaffu** [comment]
I found another problem, this time regarding **tooltip**.
![Bez tytułu5](https://github.com/tabler/tabler/assets/15199646/77b29d04-83a6-453c-bf3a-5f9111931f94)
- Someone changed the height of the Y area for the tooltip again unlike previous versions. How to fix it? Where to look for it?
- I liked this modest, smaller version much better.

**Comment by eThaffu** [comment]
I found another problem, this time regarding **tooltip**.
![Bez tytułu5](https://github.com/tabler/tabler/assets/15199646/77b29d04-83a6-453c-bf3a-5f9111931f94)
- Someone changed the height of the Y area for the tooltip again unlike previous versions. How to fix it? Where to look for it?
- I liked this modest, smaller version much better.

**Comment by heeroyuiGO** [comment]
yes, why the color it's "--tblr-secondary" by default for the badge?

<img width="542" alt="Capture d’écran 2023-08-28 à 18 32 06" src="https://github.com/tabler/tabler/assets/35996646/ec0075cd-ed9c-4732-8f4f-68a2718d8ac4">

**Comment by heeroyuiGO** [comment]
and the "background-color" for .dropdown-item:focus not working

<img width="616" alt="Capture d’écran 2023-08-28 à 18 54 13" src="https://github.com/tabler/tabler/assets/35996646/3f1f48b3-05fd-45fb-85cd-a65c99bda40a">

**Comment by mholt** [comment]
Some of these issues (but not all) are addressed in https://github.com/tabler/tabler/pull/1684

**Comment by rjd22** [comment]
I'm closing this for now in favor for more specific tickets. As this is now it's non actionable after the fixes that were done.
