### ISSUE TITLE
[BUG] Flag changed

### ISSUE THREAD

**Issue by brunobacha** [tabler/tabler#1687]
**Describe the bug**

Flags were changed in version 20, I would like it to go back to how it was in version 19.

**Device**

 - Chorme 116.0.5845.96
 - OS: macOS 13.4.1
 - Screen size 3840 × 2160

**To reproduce**

Eg: Flag US
v19: https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta19/dist/img/flags/um.svg
v20: https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta20/dist/img/flags/um.svg

**Comment by heeroyuiGO** [comment]
> **Describe the bug**
> 
> Flags were changed in version 20, I would like it to go back to how it was in version 19.
> 
> **Device**
> 
> * Chorme 116.0.5845.96
> * OS: macOS 13.4.1
> * Screen size 3840 × 2160
> 
> **To reproduce**
> 
> Eg: Flag US v19: https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta19/dist/img/flags/um.svg v20: https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta20/dist/img/flags/um.svg

Now, new size class ;-)
<img width="261" alt="Capture d’écran 2023-08-28 à 18 25 04" src="https://github.com/tabler/tabler/assets/35996646/445270ec-1691-4ba6-a8e8-5d5f2f3a40c3">
<img width="686" alt="Capture d’écran 2023-08-28 à 18 25 12" src="https://github.com/tabler/tabler/assets/35996646/008b59b3-8e9b-4ef7-b37c-825cb25be2cb">

**Comment by brunobacha** [comment]
Yes, it already has sizes, but the flag design, in v20, became more "pixelized" and in v19 it is more "smoother".

**Comment by rjd22** [comment]
Most likely you're using the svg's wrong. Vector grapics scale to all sizes if used correctly. Check the documentation here to see how to use the flag svg's:

https://tabler.io/docs/plugins/flags
