### ISSUE TITLE
[BUG] Alert background transparent

### ISSUE THREAD

**Issue by vjmartins** [tabler/tabler#1688]
Alert background color not defined

![image](https://github.com/tabler/tabler/assets/827692/16a855ce-79e9-4ce5-9b37-5504b0af1f06)

**Comment by rjd22** [comment]
This should be fixed with the next version when we release it.

**Comment by rjd22** [comment]
@codecalm Would it be possible to release a new version? A lot of bugs have been fixed in that one.
