### ISSUE TITLE
[BUG] Slow modals

### ISSUE THREAD

**Issue by HenryckySentnella** [tabler/tabler#1690]
Recently I realized an immense slowdown in the use of modals, for no apparent reason. Even with the page containing only one modal, it takes time to open, insert the information, it seems to be crashing or lagging, it didn't happen before, I don't know if it could be a version or compatibility error.

**Device**

 - Browser [Google Chrome]
 - OS: [Linux on Ubuntu]

**To reproduce**

1. Add a modal in your website
2. Try to open and insert informations (can be a HTML form, for example)
3. Seems slow?

**Comment by unalkacar** [comment]
I'm experiencing this problem too. It doesn't seem to be an implementation issue. I leave the video attached. I couldn't figure out whether it was the configuration of macOS or another reason. Anyone have any ideas?

Google Chrome
macOS

Video:
https://github.com/tabler/tabler/assets/5397805/2b581e56-1442-4e0f-9df4-d19d21ea3c16

**Comment by unalkacar** [comment]
I deleted the modal-blur class and there is no problem with the fade effect.
