### ISSUE TITLE
[BUG] Broken dropdown item highlighting

### ISSUE THREAD

**Issue by jakubtobiasz** [tabler/tabler#1694]
**Describe the bug**

After updating the Tabler to beta20 hovering over dropdown items doesn't apply any visual effect. 

**Device**

Any

**To reproduce**

Install `tabler/tabler:1.0.0-beta19` and see the hovering over dropdown items works. Then update to `tabler/tabler:1.0.0-beta20` and you can notice the hover stops working.

**Screenshots**

n/a

**Comment by jozefrebjak** [comment]
@rjd22 where this was completed ? why it's closed and not merged ? Can you post me here PR where this issue was fixed Becuase PR #1713 is closed not merged? Thanks
