### ISSUE TITLE
[BUG] Inline players don't work

### ISSUE THREAD

**Issue by BG-Software-BG** [tabler/tabler#1704]
**Describe the bug**

Inline players from docs don't work. YouTube image is shown for a short while, but then they (both YT and Vimeo) turns into this:
![image](https://github.com/tabler/tabler/assets/73077398/fa63918a-7422-40c3-8a2c-6a83fc38849d)

**Device**

 - Browser: Chrome ver.116, Edge ver.116
 - OS: Windows 11

**To reproduce**

1. Go to [Inline player - Documentation](https://tabler.io/docs/components/inline-player)

**Comment by BG-Software-BG** [comment]
Range slider example doesn't work also.

![image](https://github.com/tabler/tabler/assets/73077398/6b280050-3f0e-409f-af93-d85c7724d05d)

**Comment by rjd22** [comment]
These seem to work again so closing this.
