### ISSUE TITLE
using tabler in python flask

### ISSUE THREAD

**Issue by azarezade** [tabler/tabler#171]
Is there a simple/clean way to use this dashboard in python flask.
Since python flask/Django use jinja for templating, is this bootstrap template can be converted to python-flask ready template, can somebody give a hint to do this.
thanks

**Comment by JustJunaid** [comment]
Have you figured this out coz im planning to do the same?

**Comment by azarezade** [comment]
No, I just used the build html files and worked with the cure html files.
Maybe, the clean solution is to serve the tabler frontend separately using Nginx for example, and use API call to flask to fill data in the dashboard.

**Comment by jiuri0624** [comment]
我也有打算把这个用在flask程序中作为前端和后端界面。 虽然直接把dist的文件放在static和template中可以使用。 但是不知道这样是否是合适的方式。
