### ISSUE TITLE
[BUG] Clicking button with href="#" in documentation causes opening main site inside iframe

### ISSUE THREAD

**Issue by BG-Software-BG** [tabler/tabler#1714]
**Describe the bug**

When you click a button with `href="#"` in example in the documentation, documentation site opens inside iframe.

**To reproduce**

1. Go to Documentation, e.g. Buttons.
2. Click on e.g. on any button in "Button variations" section.
3. Documetation site will open in the iframe of "Button variations" example.

**Screenshots**

![image](https://github.com/tabler/tabler/assets/73077398/1ae814c3-7eea-4fb4-91b9-4d5238ec2b2f)  
![image](https://github.com/tabler/tabler/assets/73077398/68cd2c4d-b500-4067-bd1a-d107ffb21e5e)

**Comment by coder-pink** [comment]
I would like to work on it. Please assign it to me.
