### ISSUE TITLE
[BUG] Not showing country flag icons

### ISSUE THREAD

**Issue by surendharnagarajan** [tabler/tabler#1723]
**Describe the bug**

**Dell Inspiron 15**

 - Browser:  Brave (Chromium - 117.0.5938.92)
 - OS: Windows 11

Issue:
1. Go to 'https://preview.tabler.io/flags.html'
2. You can see that the country flag is missing icons.

**Screenshots**
![flags](https://github.com/tabler/tabler/assets/40541316/a0436521-9f0c-4444-9e32-d5cd31366fc5)

**Comment by codecalm** [comment]
fixed! 🙂
