### ISSUE TITLE
[BUG] 404 page would be better if it were in the content center

### ISSUE THREAD

**Issue by surendharnagarajan** [tabler/tabler#1724]
**Describe the bug**

404 page would be better if it were in the content center

**Dell Inspiron 14**

 - Brave [Chromium - 117.0.5938.92]
 - Windows 11

**Modification**
Currently
in a class called .page
{
     display: flex;
     flex-direction: column;
     position: relative;
     min-height: 100%;
}

That is why when going to 404, 500 page it appears in content top in mobile responsive. It would be great if it appeared in the content center.

When there is no content on the page, you can create .error-page instead of .page class
{
     display: flex;
     position: relative;
     min-height: 100%;
}
Only you need to add.

1. Go to 'https://preview.tabler.io/error-500.html' or https://preview.tabler.io/error-404
![500](https://github.com/tabler/tabler/assets/40541316/5751b53f-5daf-4dd5-b8f7-c46213963dbd)
.html

**Screenshots**

If applicable, add screenshots to help explain this problem.
![500](https://github.com/tabler/tabler/assets/40541316/726d4231-56cf-4f62-8edb-4e93259a0ee6)
![modified-500](https://github.com/tabler/tabler/assets/40541316/7142a606-614a-41ff-b352-200c291e8a97)
![404](https://github.com/tabler/tabler/assets/40541316/f014efff-fe57-4e74-9dc1-97adc24cf2a9)
![modified-404](https://github.com/tabler/tabler/assets/40541316/d0e4683e-9efc-4f69-8ed1-eb5797acc8e1)

**Comment by codecalm** [comment]
fixed, thank you! 🙂
