### ISSUE TITLE
Dropdown Issue

### ISSUE THREAD

**Issue by abillits** [tabler/tabler#1726]
I'm having an issue where dropdowns within a datatable work correctly when the page is loaded but the dropdown opens in the wrong location after scrolling. It's as if the dropdown always opens where the button was located upon initialization.

Does anyone know of a fix for this issue?

![Screenshot (120)](https://github.com/tabler/tabler/assets/2138178/b615f32b-da6a-458c-ad6f-91c0b9106612)
![Screenshot (121)](https://github.com/tabler/tabler/assets/2138178/03dea153-f41b-43ba-abdf-13df1057b854)

**Comment by rjd22** [comment]
Can you make a jsfiddle with an example? If not I'm going to close this as not actionable. Without examples it's quite hard to find out your specific setup.

**Comment by abillits** [comment]
My apologies. I should have already closed this.

I discovered the issue is not with Tabler but rather an issue with Bootstrap dropdowns on Datatables when using server side data.
