### ISSUE TITLE
[FEATURE] Breadcrumbs

### ISSUE THREAD

**Issue by tacman** [tabler/tabler#1728]
I'm surprised that the demo doesn't include breadcrumbs, even as placeholders.  I'd like to see the page within the menu, e.g.

    Tabler > Interface > Charts

Obviously, I can add some from bootstrap, but I'm sure they'd look and fit better if you added them.

**Comment by vjmartins** [comment]
You can find in Steps page -> https://preview.tabler.io/steps.html

**Comment by tacman** [comment]
Yes, but putting it up in page header, below the navbar, and collapsing in mobile, floating where it should, etc.  

I can hack something in from the many examples on the internet, but I always end up with some funky spacing when I try to add my own elements.  

But yes, thanks, that's a nice, clean snippet.

**Comment by rjd22** [comment]
And example of breadcrumbs in page headers can be found here:

https://tabler.io/docs/layout/page-headers
