### ISSUE TITLE
[BUG] Dropdown action button in the tables doesn't show up properly if there is just one row in the table

### ISSUE THREAD

**Issue by oknsyl** [tabler/tabler#1729]
### Browser

Edge ver.117

### OS

Windows 11

### Screen size

1920*1080

### Describe the bug

If there is only one row in the last table (Invoices) at the tables page, the action dropdown button doesn't show up properly. 

### How to reproduce

You can test it using DevTools, delete all the <tr>'s in the table except one and click the button.

### Screenshots

![tabler-table](https://github.com/tabler/tabler/assets/6351161/efcde99a-1dee-4e33-b47a-4596c80295cc)

**Comment by sagarpardeshi** [comment]
Facing same issue

**Comment by rjd22** [comment]
This is expected behavior for responsive dropdowns:

https://github.com/tabler/tabler/issues/1343#issuecomment-1308569481
