### ISSUE TITLE
[FEATURE] Document Build process

### ISSUE THREAD

**Issue by tacman** [tabler/tabler#1730]
I would like to build the template, but npm run build is giving me errors.  At first it was jekyl, so I tried to install that, but ran into a variety of issues related to permissions (with the gem build).  

Is there documentation on what needs to be installed?  

In addition to enjoying the tabler library, I like your tabler.io website and am interested in how to compile the tsx pages.  I was looking for a landing page within the tabler demo (which lands on a dashboard), but it seems like the best landing page is, in fact, the landing page on talber.io.

Thanks again for a great theme.  Providing a landing page would be a good feature.

**Comment by rjd22** [comment]
You can find more info here:

https://github.com/tabler/tabler#-setup-environment
