### ISSUE TITLE
[BUG] Navbar uses invalid HTML element h1

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#1732]
### Describe the bug

Navbar logo uses a HTML element, which should be strictly reserved for content / page title.

This should not be a `<h1>` 🐛 

See https://github.com/tabler/tabler/blob/dev/src/pages/_includes/layout/navbar-logo.html#L7

Looks tiny, but it is indeed a huge SEO mistake.

**Comment by rjd22** [comment]
The problem is deeper than this. Page titles are h2 by default. If we want to fix this properly we should also move the page titles to h1 IMO.
