### ISSUE TITLE
[FEATURE] publish core and icons to npm

### ISSUE THREAD

**Issue by tacman** [tabler/tabler#1738]
I'd like to be able to install tabler as a module from a CDN, specifically jsdelivr, which I believe gets its packages from npm.

The existing published packages is 1.0-alpha8

https://www.jsdelivr.com/package/npm/tabler

I'm not familiar with the mechanics of publishing to npm, but as a user I like the benefits, even if tabler is still in beta.

Thanks.

**Comment by phasdev** [comment]
https://www.jsdelivr.com/package/npm/@tabler/core

**Comment by tacman** [comment]
Thanks!
