### ISSUE TITLE
[BUG] Apexchart radialbar type not working

### ISSUE THREAD

**Issue by arezascarlet** [tabler/tabler#1739]
### Browser

firefox 119.0b7

### OS

windows 10

### Screen size

1920 x 1080

### Describe the bug

the chart radial bar not showing with tabler template
![image](https://github.com/tabler/tabler/assets/49219720/6d939eab-cd11-4e2e-92c5-d89c443676e6)

but, if not use tabler template is working
![image](https://github.com/tabler/tabler/assets/49219720/aeadd3e4-c266-496a-ba66-3919264c61da)

### How to reproduce

2. Click on '...'
3. Scroll down to '...'
...

**Comment by rjd22** [comment]
This should be fixed now in https://github.com/tabler/tabler/pull/1751
