### ISSUE TITLE
Compile js into one file with gulp (?)

### ISSUE THREAD

**Issue by tonystatic** [tabler/tabler#174]
Hi,

I was going to use tabler template for my project and I'm trying to adapt it for my needs. My idea was to store all raw assets (tabler's `src` folder contents) in my `resources/assets` directory and use gulp to compile / move them to `public/assets`. While it's completely OK with styles, I am having some doubts about it being possible with js, because all the js assets are adapted for require.js. I've never used require.js myself, so my questions are: 
- Is it possible to combine all this js into one file? 
- If it is: how to do it properly?
- If it is: does it have sense, or I just better leave these scripts as they are and include them into my layout separately?

I am currently trying to compile scripts like that (using `gulp-requirejs`):
```javascript
gulp.task('scripts', function() {
    var requireJs = gulp.src(['resources/assets/js/require.min.js']),
        tabler = requirejs({
            baseUrl: 'resources',
            mainConfigFile: 'resources/assets/js/dashboard.js',
            out: 'script.js',
            name: 'assets/js/dashboard'
        });

    return streamqueue({ objectMode: true },
            requireJs, tabler
        )
        .pipe(concat('script.js'))
        .pipe(gulp.dest('public/assets/js/'));
});
```
This way the task doesn't fail, but I'm not sure that the compiled script (`script.js`) is OK (because I'm not quite familiar with require.js). The compiled script includes minified require.js, bootstrap and jquery-circle-progress scripts, then comes `core.js` contents and it finishes with these lines:
```javascript
require(['core']);
define("assets/js/dashboard", function(){});
```
But it's lacking jQuery, at least. So I guess I might be doing something wrong in `gulp-requirejs` config. I will appreciate any help on this matter. 

P.S.: I'm not using Jekyll for my project either. So yeah, I had to hardcode `window.tabler.colors` in `dashboard.js`.

Thanks in advance.

**Comment by codecalm** [comment]
done :)
