### ISSUE TITLE
[FEATURE] Datatables support rather than using list.js

### ISSUE THREAD

**Issue by geekz-reno** [tabler/tabler#1740]
**Is your feature request related to a problem? Please describe.**
Is there any alternative grid plugin like datatable that supports tabler? I know tabler has dropped jquery so datatables won't work, but the solution given is using list.js which does not support server-side pagination, searching, etc.

**Describe the solution you'd like**
Tabler will support datatables or jqgrid because it support server-side pagination, searching, etc.

**Comment by tacman** [comment]
Datatables only uses jQuery internally, so it works fine with tabler, as long as you're using the bootstrap 5 version of datatables.

**Comment by Adecom16** [comment]
Can you assign this to me and receive the pr immediately

**Comment by geekz-reno** [comment]
i manage to make datatables look like in the demo page using dom positioning, like this:

```js
dom: '<"dataTables_wrapper dt-bootstrap"<"card-body py-3"<"row"<"col-xl-7 d-block d-sm-flex d-xl-block justify-content-center"<"d-block d-lg-inline-flex me-0 me-md-3"l><"d-block d-lg-inline-flex"B>><"col-xl-5 d-flex d-xl-block justify-content-center"fr>>>t<"card-footer d-flex align-items-center"<"m-0 text-secondary"i><"pagination m-0 ms-auto"p>>>',
```

to wrap length, search box inside card header, and paging inside card footer

the result will like this

<img width="1316" alt="image" src="https://github.com/tabler/tabler/assets/2031382/348a764f-e0ac-4d39-86f2-b3970016f19b">

**Comment by dwamara** [comment]
> i manage to make datatables look like in the demo page using dom positioning, like this:
> 
> ```js
> dom: '<"dataTables_wrapper dt-bootstrap"<"card-body py-3"<"row"<"col-xl-7 d-block d-sm-flex d-xl-block justify-content-center"<"d-block d-lg-inline-flex me-0 me-md-3"l><"d-block d-lg-inline-flex"B>><"col-xl-5 d-flex d-xl-block justify-content-center"fr>>>t<"card-footer d-flex align-items-center"<"m-0 text-secondary"i><"pagination m-0 ms-auto"p>>>',
> ```
> 
> to wrap length, search box inside card header, and paging inside card footer
> 
> the result will like this
> 
> <img alt="image" width="1316" src="https://private-user-images.githubusercontent.com/2031382/275422058-348a764f-e0ac-4d39-86f2-b3970016f19b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDkzOTksIm5iZiI6MTcwNzgwOTA5OSwicGF0aCI6Ii8yMDMxMzgyLzI3NTQyMjA1OC0zNDhhNzY0Zi1lMGFjLTRkMzktODZmMi1iMzk3MDAxNmYxOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMDcyNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWVkYjNmNjZhNjRhYjAyM2YzN2RiNDQxOWRiNmFjZWIwZTJiZWMxZTlhYjA1NmU2MmJiMTA5NTA5N2ZlYTdhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JfAZPfe3UgKK2ALVaRxgbsCXIz96uYdJK0NAsE_zM2w">

Is it possible for you to put a sample of page using this? I am not very well versed in Javascript and it is the only thing that is preventing me up to now to properly use this template as my UI heavily rely on such tables. That will be much appreciated.

D.
