### ISSUE TITLE
[Question] How do I setup dark mode as the default mode instead of light?

### ISSUE THREAD

**Issue by yadakhov** [tabler/tabler#1743]
I want to make dark mode my site default. I tried:

```
<body class="theme-dark">
```

But it doesn't seem to work. I suspect there is something with the theme switcher making light as the default.

**Comment by datlechin** [comment]
Use `data-bs-theme="dark"` instead

**Comment by yadakhov** [comment]
I found the solution to my problem.

I was reference the `demo-theme.js` file. I needed to change the `defaultTheme` variable.

```
const defaultTheme = "light"

to 

const defaultTheme = "dark"

```
https://github.com/tabler/tabler/blob/80f5732d1a003f8df02c9b598bdcdc868b655605/src/js/demo-theme.js#L8
