### ISSUE TITLE
dropdown doesnt work

### ISSUE THREAD

**Issue by cserko93** [tabler/tabler#175]
I downloaded your pack from github then i upload it. When is try it on my website dropdowns and others doesnt work. When i try fix it i need to add bootsrap.min.js but the theme get wrong.

**Comment by samayo** [comment]
This is most likely an issue from your side or the way you installed and configured the sites. At least test the template on your local, if it works then start investigating the issue from there.

**Comment by cserko93** [comment]
its working on my localhost (xampp). **Thanks**

**Comment by samayo** [comment]
The the problem is not from this library. Inspect your console on your browser from your prod server

**Comment by cserko93** [comment]
What could be the problem? what is the reason of the problem?

**Comment by cserko93** [comment]
console shows this for me:

> assets/js/vendors/jquery-3.2.1.min.js:4 Uncaught SyntaxError: Unexpected end of input
assets/js/vendors/bootstrap.bundle.min.js:6 Uncaught SyntaxError: Invalid or unexpected token
core.js:23 Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (core.js:23)
    at i (jquery.min.js:2)
    at Object.add [as done] (jquery.min.js:2)
    at n.fn.init.n.fn.ready (jquery.min.js:2)
    at core.js:18
index.html:326 Uncaught TypeError: $ is not a function
    at index.html:326
    at Object.execCb (require.min.js:5)
    at b.check (require.min.js:5)
    at b.<anonymous> (require.min.js:5)
    at require.min.js:5
    at require.min.js:5
    at each (require.min.js:5)
    at b.emit (require.min.js:5)
    at b.check (require.min.js:5)
    at b.enable (require.min.js:5)

>

**Comment by samayo** [comment]
You need to include/import jquery error: `Uncaught TypeError: $(...).tooltip is not a function` means, jquery is probably not included or initialized

**Comment by macagoraga** [comment]
Seem like is missing Popper.js

**Comment by CyberSinister** [comment]
Does anyone know a fix to this?
