### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lampsea12** [tabler/tabler#1753]
### Browser

Chrome version

### OS

Windows 11

### Screen size

1920x1080

### Describe the bug

Text input type = "Search" not show clear button
On bootstrap 5 this button still show but when use Tabler, it gone!
How can i fix it? It very important with my project!

### How to reproduce

2. Click on '...'
3. Scroll down to '...'
...

**Comment by rjd22** [comment]
There is too little information here to figure out what you're asking. For that reason I'm closing this.

Please fill in all the requested fields so we can understand the problem better.
