### ISSUE TITLE
[BUG] Apex RadialBar doesn't work correctly

### ISSUE THREAD

**Issue by cesvdev** [tabler/tabler#1755]
### Browser

Chrome 118.0.5993.118

### OS

Windows 11

### Screen size

3440x1440

### Describe the bug

The RadialBar from Apexchart doesn't work correctly, all other charts works ok, but radialbar doesn't. Please, can you revise it?

### How to reproduce

Simply copy the text: 
![code](https://github.com/tabler/tabler/assets/118253705/43829c85-4a8c-4dd0-b142-01dfc66c498e)

### Screenshots

This should be shown:
![apexradialbar](https://github.com/tabler/tabler/assets/118253705/f71243c4-dfa5-43e3-80a6-3f86be1fc296)

But the real result is this:
![tabler](https://github.com/tabler/tabler/assets/118253705/3f80d99c-7f61-43c3-af19-db0a575bb54d)

### JSFiddle

<div class="card">
    <div class="card-body">
    <div id="chart-demo-radialbar" class="chart-lg"></div>
    </div>
</div>
								
<script>
document.addEventListener("DOMContentLoaded", function() {
    window.ApexCharts && (new ApexCharts(document.getElementById('chart-demo-radialbar'), {
          series: [70],
          chart: {
          height: 350,
          type: 'radialBar',
        },
        plotOptions: {
          radialBar: {
            hollow: {
              size: '70%',
            }
          },
        },
        labels: ['Cricket'],
 })).render();
});
</script>

**Comment by rjd22** [comment]
This should be fixed now bit the latest version is not released yet.
