### ISSUE TITLE
[BUG] map does not appear

### ISSUE THREAD

**Issue by surendharnagarajan** [tabler/tabler#1756]
### Browser

Brave

### OS

Windows 11

### Screen size

1366 x 768

### Describe the bug

Map does not appear (https://preview.tabler.io/maps.html). Unauthorized: you may have provided an invalid Map api appears in the console.

![image](https://github.com/tabler/tabler/assets/40541316/1892a68b-313b-4498-9703-25eb6057f077)
![image](https://github.com/tabler/tabler/assets/40541316/c60e5417-5af3-41f4-94be-5248ad2ed562)

### How to reproduce

1. Go to 'https://preview.tabler.io'
2. Click on 'Interface -> Map'
3. See you may find that map does not appear.

### Screenshots

![image](https://github.com/tabler/tabler/assets/40541316/1892a68b-313b-4498-9703-25eb6057f077)
![image](https://github.com/tabler/tabler/assets/40541316/c60e5417-5af3-41f4-94be-5248ad2ed562)

**Comment by GarvAgarwal26** [comment]
Hey, can u please assign this issue to me?
