### ISSUE TITLE
[FEATURE] Separating several CSS files

### ISSUE THREAD

**Issue by Lukmanern** [tabler/tabler#1770]
I have been using: ../demo/dist/css/tabler.min.css for a long time. In the past two years, I have worked on projects using this Tabler template, and it has greatly facilitated my work due to its perfect and comprehensive design and components, which align well with my needs.
However, there is one issue when I attempt to modify the tabler.min.css file on my Windows 10 laptop using VSCode+Prettier with 8GB RAM, 10th gen Core i5, it takes about 10-18 seconds to save the modifications css file.

Can there be one specific directory to serve separate CSS files like:
button.css containing CSS class for buttons,
color.css containing color-related CSS classes,
and so on?

Thankyou.

**Comment by datlechin** [comment]
Use sass

**Comment by rjd22** [comment]
What @datlechin said. Use the sass files. I'm closing this because this is outside of the scope of this project.

**Comment by Lukmanern** [comment]
Ah, I see. I just remembered, when I was learning CSS with Bootstrap and then switched to Tailwind, I skipped the Sass tutorial, hahahaha.

Thanks You so much Bro ! 
Best,
@datlechin  @rjd22
