### ISSUE TITLE
Dropdown button can't display in table while just have one row

### ISSUE THREAD

**Issue by gotounix** [tabler/tabler#178]
![123](https://user-images.githubusercontent.com/18606632/44136709-588a6e38-a0a0-11e8-8d7a-a0e17866b5c9.png)

**Comment by AaronCoplan** [comment]
@codecalm This issue is also affecting [tabler-react](https://github.com/tabler/tabler-react), so any resolution would be very helpful.

**Comment by Salamafet** [comment]
The bug is still present. Any news about this ?
