### ISSUE TITLE
[BUG]  tom-select dropdown will be blocked in bootstrap modal

### ISSUE THREAD

**Issue by Huangzc88** [tabler/tabler#1798]
### Browser

Microsoft Edge ver.120.0.2210.61

### OS

win10

### Screen size

1920*1080

### Describe the bug

tom-select is blocked when used in bootstrap5 modal.
I tried setting z-index, but it didn't work, please help fix it, thanks.

tabler version :  v1.0.0 - beta20

### Screenshots
![image](https://github.com/tabler/tabler/assets/31158857/82795e25-817d-4bf3-ae6d-bba05b62b1b1)
![image](https://github.com/tabler/tabler/assets/31158857/361f905a-5559-4108-bfa4-b081ef587954)

**Comment by ivalkenburg** [comment]
modal-body needs overflow-y: visible in such situations. 

bootstrap class `overflow-y-visible` on modal-body

**Comment by Huangzc88** [comment]
> modal-body needs overflow-y: visible in such situations.
> 
> bootstrap class `overflow-y-visible` on modal-body

Thanks for the reply, I'll see if it works.
