### ISSUE TITLE
Do you have plan to use vanilla js table library, alternative to DataTable?

### ISSUE THREAD

**Issue by phyozawtun** [tabler/tabler#1799]
**vanila js data table*
replace jQuery plugin with vanilla js library

**Describe the solution you'd like**
tabulator is none jQuery and alternative to DataTable.
Do you have plan to use vanilla js table library, alternative to Datatable

**Alternative**
gridjs.io is also vanilla js
* more light weight
* more minimilist

**Comment by rjd22** [comment]
None of what you said is factual and shows you did no research from your part. This is the PR implementing datatables showing what library were using to achieve it:

https://github.com/tabler/tabler/pull/1114/files
