### ISSUE TITLE
Template not work in IE 11

### ISSUE THREAD

**Issue by domenrogina** [tabler/tabler#18]
![image](https://user-images.githubusercontent.com/8709441/38081229-ce0ae1b2-3343-11e8-9441-59920b974c7d.png)

How can I fix that ..? Thank you :)

P.S.
This templete are awesome!

**Comment by noxify** [comment]
@domenrogina - (OT) Use a modern browser :D

**Comment by domenrogina** [comment]
@noxify yeah .. I use it :) but in our company are still some users who prefer IE ... (sad, angry) :) :)

**Comment by OmgImAlexis** [comment]
> Cross Browser: Our theme works perfectly with: Latest Chrome, Firefox+, Latest Safari, Opera, Internet Explorer 10+ and mobile browsers. We’re working hard to support them.

It should be working with IE10 and IE11 according to the docs.

**Comment by eugene1g** [comment]
FYI fixing layout issues in IE is quite easy  - I opened a PR to do this (#38), but if it takes a while to merge you can copy the same 7 lines directly into your projects.

**Comment by codecalm** [comment]
thanks @eugene1g for help! I've medged to master branch and made a new package. Grat job!
