### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ionutantohi** [tabler/tabler#1807]
Hi

It is possible make a new release with all the updates since the beta20 released in Aug last year? Also, the preview website seems to use the dev branch and we get a mismatch between the preview and installed version through npm.

Also, is there a path through v1.0?

Thanks

**Comment by ionutantohi** [comment]
@codecalm @rjd22 Any thoughts about the above?

**Comment by deanpcmad** [comment]
👍  to this

**Comment by SKeeneCode** [comment]
Also would be great if the developers could provide even a rough timeline/roadmap for an official 1.0 release.

**Comment by tacman** [comment]
beta-20 is almost 2 years old -- please consider beta 21, just to take advantage of the last 21 months of development.

**Comment by rjd22** [comment]
Only @codecalm knows how to build an release right now sadly, and he seems occupied with something else.

**Comment by twf-nikhila** [comment]
Yes, this needs to be updated. Please do it @codecalm

**Comment by codecalm** [comment]
new version is released

**Comment by rjd22** [comment]
@codecalm Thank you a lot for making a new release!
