### ISSUE TITLE
[BUG] Overlapping Top Border in Tabbed Cards

### ISSUE THREAD

**Issue by annahri** [tabler/tabler#1814]
### Browser

Chromium: 120.0.6099.199 (Official Build) (64-bit)

### OS

Manjaro 23.1.2

### Screen size

1600x900

### Describe the bug

When creating a tabbed card, a bug is observed where all `.card-body` elements, excluding the first one, within a `.tab-content` display an additional, overlapping top border.

**Expected Result:**
Consistent and non-overlapping top borders for each `.card-body` within the tabbed card.

**Actual Result:**
All `.card-body` elements, except the first one (#tab1), display an extra, overlapping top border.

**Temporary Fix:**
To address the issue, apply the `.border-top-0` class to the .card-body elements of tabs other than the first one.

### How to reproduce

1. Create tabbed card with multiple .card-bodies
```html
<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs" role="tablist">
        <li class="nav-item">
          <a class="nav-link" href="#tab1">Tab 1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#tab2">Tab 2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#tab3">Tab 3</a>
        </li>
      </ul>
    </div>
    <div class="tab-content">
      <div class="card-body tab-pane active show" id="tab1">
        Tab 1
      </div>
      <div class="card-body tab-pane" id="tab2">
        Tab 2
      </div>
      <div class="card-body tab-pane" id="tab3">
        Tab 3
      </div>
    </div>
  </div>
```
2. Click a tab other than the 1st

### Screenshots

![image](https://github.com/tabler/tabler/assets/30897918/9dabb1b9-b67a-4094-80af-0a0acb9abd0f)
![image](https://github.com/tabler/tabler/assets/30897918/87b7681c-cc71-45d9-bcac-480e773d31ce)
![image](https://github.com/tabler/tabler/assets/30897918/9ee22277-6dd8-4f50-b9c2-54d47049b062)

### JSFiddle

https://jsfiddle.net/nj5v4aer/28/

**Comment by rjd22** [comment]
@annahri It seems that you're not using tabs correctly. Please take a look at the samples on how formatting for tabs need to be done:

https://preview.tabler.io/tabs.html
