### ISSUE TITLE
Compatibility Issue with Bootstrap 5.3.2 and Tabler 1.0.0-beta20

### ISSUE THREAD

**Issue by raj-oeeai** [tabler/tabler#1819]
I've got an Compatibility Issue in my Ember 4.4 project with Bootstrap 5.3.2 and Tabler 1.0.0-beta20.
When attempting to build an Ember project with Bootstrap 5.3.2 and Tabler Beta 20, a syntax error is encountered during the build process. The error specifically points to a conflict in units within the node_modules/bootstrap/scss/vendor/_rfs.scss file, as illustrated below:
```
0.75em and 100% have incompatible units.
   ╷
70 │     @while ($remainder >= $divisor) {
   │             ^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap/scss/vendor/_rfs.scss 70:13                                  divide()
  node_modules/@tabler/core/src/scss/ui/_badges.scss 8:41                             @import
  node_modules/@tabler/core/src/scss/_core.scss 17:9                                  @import
  node_modules/@tabler/core/src/scss/tabler.scss 1:9                                  @import
  ../tmp/broccoli-14iMsHkIbk0vO/out-478-funnel_funnel_styles/app/styles/app.scss 3:9  root stylesheet
        at SassCompiler
```
Package Versions:
"@tabler/core": "1.0.0-beta20",
"bootstrap": "5.3.2",

Does someone have a solution idea?

**Comment by raj-oeeai** [comment]
I have a workaround for this Issue.
Setting the `$badge-font-size` and `$form-check-input-width` variables did the trick for the compilation issues.
This isn't a fix but I hope this helps others facing similar Issues!

**Comment by vickodin** [comment]
@kevinpapst The same issue for:
"@tabler/core": "^1.0.0-beta21",
"bootstrap": "^5.3.3",

```bash
18:04:43 css.1  | Error: 0.75em and 100% have incompatible units.
18:04:43 css.1  |    ╷
18:04:43 css.1  | 70 │     @while ($remainder >= $divisor) {
18:04:43 css.1  |    │             ^^^^^^^^^^^^^^^^^^^^^^
18:04:43 css.1  |    ╵
18:04:43 css.1  |   node_modules/bootstrap/scss/vendor/_rfs.scss 70:13       divide()
18:04:43 css.1  |   node_modules/@tabler/core/src/scss/ui/_badges.scss 8:41  @import
18:04:43 css.1  |   node_modules/@tabler/core/src/scss/_core.scss 17:9       @import
18:04:43 css.1  |   @tabler/core/src/scss/tabler.scss 1:9                    @import
18:04:43 css.1  |   app/assets/stylesheets/application.bootstrap.scss 9:9    root stylesheet
18:04:43 css.1  | error Command failed with exit code 65.
```

**Comment by kevinpapst** [comment]
And here it doesn't happen with 
"@tabler/core": "^1.0.0-beta21",
"bootstrap": "^5.3.3",

This is the line:
https://github.com/tabler/tabler/blob/dev/src/scss/ui/_badges.scss#L8C1-L9C1

Go check if you overwrite `$badge-padding-y` or `$badge-font-size` with an invalid unit.
