### ISSUE TITLE
[BUG] Terms of Service demo page is cut off

### ISSUE THREAD

**Issue by drok** [tabler/tabler#1820]
### Browser

Chrome 120

### OS

Win 10

### Screen size

1920x1080

### Describe the bug

The top side of the page https://preview.tabler.io/terms-of-service.html is cut off (item 1 is not visible at all)

### How to reproduce

1. Go to https://preview.tabler.io/terms-of-service.html
2. top of the page is missing, article 1 not visible

**Comment by AbdelrhmanSaid** [comment]
You just need to replace `.page-center` with `my-auto`
