### ISSUE TITLE
https://tabler.io/ is down

### ISSUE THREAD

**Issue by SKeeneCode** [tabler/tabler#1822]
Main site seems to be down.

@codecalm  @rjd22 for you attention :)

Thank you for all the great work you've done and continue to do with tabler!

**Comment by dorokhin** [comment]
probably dns resolution issue

<img width="679" alt="Screenshot 2024-02-06 at 14 30 21" src="https://github.com/tabler/tabler/assets/10822884/67506256-c80c-4a71-8adf-82b1daf2bea3">

**Comment by codecalm** [comment]
yes, we had small problems with website. Now everything should be fine 🙂
