### ISSUE TITLE
Bootstrap Modal and Other Elements ARIA duplicating elements on page

### ISSUE THREAD

**Issue by danieljsc** [tabler/tabler#183]
Hi,

I have been using Tabler for developing, and adding some non existent elements in the default template (bootstrap-modals, select2, bootstrap-notify).

I have been noticing some weird behaviours with elements that should not be visible to the user. Perhaps, in the modal header, where bootstrap documentation shows:
`<div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>`

Where it should only appear one cross to close the modal Window, both of the crosses are shown in the modal window. This on is quite straightforward as I can only remove `<span aria-hidden="true">&times;</span>`

The problem comes when using plugins such as Select2.js where the select is being changed and <span> elements are being added, then resulting with options of select appearing inside the select and outside the select as well.

`<div class="col-6">
                                                <label class="form-label">Item Units</label>
                                                <select class="form-control" name="ItemUnitsSelect"></select>
                                            </div>`

`var select2Data;
        var listReq = $.get("Items/GetSelect2ItemUnits");
        listReq.done(function(data) {
            select2Data = data;
            $("div#EditModal").find("div[name='ModalBodyContent']").find("select[name='ItemUnitsSelect']")
                .select2({
                    data: select2Data
                });
            //Open Modal Window
            $("div#EditModal").modal("toggle");
        });`

[select2 Image](http://prntscr.com/konmcg)

In the previous image you can also notice, that the close button in the modal header, appears twice. 

The bootstrap/notify plugin is getting the same problem as the modal window header, where the cross element is show twice.

[bootstrap/notify Image](http://prntscr.com/kono2l)

Can you help?
Thanks.

**Comment by danieljsc** [comment]
Any suggestions after 2 weeks?
Still trying to fix the modal close buttons and all the other things that are being duplicated and should't be visible to the user.
![image](https://user-images.githubusercontent.com/23213576/45590239-4c9f2d80-b92c-11e8-8274-991281f6e1d9.png)

This is the default and documented modal window from bootstrap.

**Comment by abponcio** [comment]
I think it far too late to answer but, either you remove the class close, or remove the x

**Comment by FreexD** [comment]
It's been a long time but I think that it's working fine now - https://codepen.io/freexd/pen/qBaEYGb .
