### ISSUE TITLE
Strategy

### ISSUE THREAD

**Issue by thiagorp** [tabler/tabler#184]
First of all thank you very much for the effort put into this project 😄

My question is about the plans for the future of the project. Do you plan to add more components or examples? Is there some sort of Roadmap?

Thank you very much.

**Comment by codecalm** [comment]
Hi @thiagorp 
I'm working on Tabler 1.0 version. Probably will be published until end of this year. New Tabler will be with dark theme, light/dark sidebar and with many, many improvements :)

**Comment by thiagorp** [comment]
@codecalm thanks a lot!

Just to share my use case and feelings: tabler has the highest quality among the templates I found. Considering paid and free ones. I tend to bootstrap a few projects but, even though I don't have any problems writing frontend code when it comes to designing things I suck. So having blocks that I can put together help VERY MUCH. That's why the most number of examples of what (and how) we can do, the most helpful for people like me it is 😄 

Thank you again for your work!

**Comment by alex-oleshkevich** [comment]
@codecalm, it would be nice to have a roadmap\overview of upcoming changes, new components and blocks.

**Comment by WebFactoryLtd** [comment]
Please don't turn it into one of those admin templates that have every single piece of JS ever made included in them :( Tabler's simplicity is one of its key advantages.
