### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cisorux** [tabler/tabler#1853]
### Browser

Edge

### OS

Windows 10 Pro

### Screen size

1920x1080

### Describe the bug

I present an error with offcanvas when I try to invoke it and that it is developed from js like:

new boostrap.Offcanvas("...")

if i do this:

                    bsOffcanvas.classList.add('show');

The offcanvas does not close with the close button or the ESC key

### How to reproduce

2. Click on '...'
3. Scroll down to '...'
...

**Comment by datlechin** [comment]
You must trigger offcanvas show/hide via Bootstrap API

https://getbootstrap.com/docs/5.2/components/offcanvas/#methods
