### ISSUE TITLE
Actions dropdown error

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#186]
Click
![image](https://user-images.githubusercontent.com/8596319/44876626-4b260200-acaa-11e8-9457-624419f8e98c.png)

Error
![image](https://user-images.githubusercontent.com/8596319/44876641-524d1000-acaa-11e8-8613-48c39ca29056.png)

**Comment by narwy** [comment]
I can confirm this is an error from a clean version.

**Comment by narwy** [comment]
@ZeoNish  - Looks like `dropdown-menu` is missing you will need to add that inside the `dropdown` class.
