### ISSUE TITLE
[BUG] General Inquiry email not found

### ISSUE THREAD

**Issue by tommysalt** [tabler/tabler#1866]
Email under Support on the Tabler web page @ https://tabler.io/support -> 'General Inquiry' is not found (`hello@tabler.io`). 
```
The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces.
```

**Comment by codecalm** [comment]
oh damn, now should works 🙂

**Comment by tommysalt** [comment]
👍 Awesome, I opened a discussion instead because it might be interesting for other users, too. Or should I test the email?
