### ISSUE TITLE
Changes in the row height in the table when calling the drop-down list

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#187]
Click
![image](https://user-images.githubusercontent.com/8596319/44895109-87358300-acfb-11e8-925d-ad67fe1380ce.png)

Look at the last row of the table.
![image](https://user-images.githubusercontent.com/8596319/44898567-f913c980-ad07-11e8-88aa-bf9440dd55eb.png)

 It's changing.
![123](https://user-images.githubusercontent.com/8596319/44895091-6a994b00-acfb-11e8-83aa-e4c9d4d03525.gif)

**Comment by codecalm** [comment]
fixed
