### ISSUE TITLE
Datepicker for Tabler

### ISSUE THREAD

**Issue by codecalm** [tabler/tabler#188]
I'm working of new version of Tabler, I am at the stage of choosing a datepicker. 
Which one do you recommend? 

Requirements:
- a lot/no dependency
- customizable
- many features (datepicker, timepicker, date/timepicker, etc)

I am asking for suggestions in the comments

**Comment by workgena** [comment]
I always struggle finding good picker with range.

I find the [Google Analytics](https://www.michaelwhitaker.com/2011/05/31/comparing-future-date-ranges-in-google-analytics/) datetime-picker user-friendly.

![img](https://www.michaelwhitaker.com/figs/uploads/2011/05/compare_to_past.png)

**Comment by workgena** [comment]
Pick ranges is common usecase for Admin-panels (dashboard, etc.). when you need filter some records by date period.

**Comment by ZeoNish** [comment]
https://felicegattuso.com/projects/datedropper/

**Comment by workgena** [comment]
**datedropper** looks fantastic.

But according to [guthub repo](https://github.com/felicegattuso/Datedropper3), last update was in 2017, and it has problems with [accessibility](https://github.com/felicegattuso/Datedropper3/issues/82) and some more :disappointed:

**Comment by ZeoNish** [comment]
I'm offering the best option that exists, that's all.

ps. Let the guys decide what they need in the project.

**Comment by akifyanbak** [comment]
Semantic UI Calendar can be adding with customizing.
https://github.com/mdehoog/Semantic-UI-Calendar

**Comment by alexjustesen** [comment]
When it comes to a jQuery (assumption is jQuery will be a dependency) my go to has been https://github.com/xdan/datetimepicker

As for a vanilla js / light weight implementation it's been https://github.com/flatpickr/flatpickr

**Comment by narwy** [comment]
`type="date"` no datepicker needed.

**Comment by jonthomp** [comment]
I would go with [react-dates](https://github.com/airbnb/react-dates), ticks all the boxes/

**Comment by ZeoNish** [comment]
http://t1m0n.name/air-datepicker/docs/index.html

**Comment by CaledoniaProject** [comment]
This one is fully compatible with BS4: http://www.daterangepicker.com/#example4

Also, please consider closing this one: https://github.com/tabler/tabler/issues/189

**Comment by tiagocassio** [comment]
I would go with http://amsul.ca/pickadate.js/

**Comment by nithi2023** [comment]
Please look at this also, if it is not too late : http://www.daterangepicker.com/#examples

**Comment by codecalm** [comment]
@nithi2023 new tabler will be with this package

**Comment by ZeoNish** [comment]
> @nithi2023 new tabler will be with this package

http://t1m0n.name/air-datepicker/docs/index.html

**Comment by Tairau** [comment]
@ZeoNish last update at three years ago

@nithi2023 https://github.com/flatpickr/flatpickr
