### ISSUE TITLE
[RELEASE] Tabler 1.0.0-beta21

### ISSUE THREAD

**Issue by wangkanai** [tabler/tabler#1887]
I think now is its a good time to release 1.0.0-beta21, because of all the fixes, changes, and features that have now update in the code base. A few little bugs is manage able with a beta release.

What do you think @codecalm ?

**Comment by SKeeneCode** [comment]
+1 

The team does seem to be aiming for a 1.0.0 release this year according to their 2024 blog:

https://tabler.io/blog/new-year-new-goals

Although this blog posts describes a level of communication between the developers and the users that we haven't really seen in 2024. I thought development might have essentially stopped until this happened: https://tabler.io/illustrations

Truly thankful for the work they've put into Tabler and I hope everything is okay with the devs <3

**Comment by kevinpapst** [comment]
@codecalm these long release cycles are causing quite a few challenges. Any chance you could trigger a new release?

**Comment by justinkruit** [comment]
The last release was almost a year ago, and it was a beta build. The last stable is almost 2 years at this point. Would love a 21 release just so my code matches the preview again as even the colors don't align anymore now since #1916

**Comment by twf-nikhila** [comment]
not sure why @codecalm not releasing a new update.

Can someone fork & release it?

**Comment by tacman** [comment]
Are there build instructions somewhere?

**Comment by twf-nikhila** [comment]
Meanwhile, Thanks to @codecalm 
There will be a new release today
![image](https://github.com/user-attachments/assets/a5d175fe-9200-44cc-a6b3-bef89dc048d2)

**Comment by kevinpapst** [comment]
And then probably setting up some kind of reliable release plan / cycle would be great. 
Or onboard a community member, so we can help with that. 
There were some reliable people around in the past...

**Comment by codecalm** [comment]
I've released latest version now 🙂

**Comment by twf-nikhila** [comment]
Thank you @codecalm.

Agree with @kevinpapst on having a community member & process to make table more reliable.
