### ISSUE TITLE
Full Calendar

### ISSUE THREAD

**Issue by coding-sunshine** [tabler/tabler#189]
I was just checking the code and saw there the full Calendar plugin is available in dev version, but couldn't find any example use. Can you please suggest?

**Comment by Isstum** [comment]
Sign!

**Comment by CaledoniaProject** [comment]
Use http://www.daterangepicker.com/

**Comment by lfdajr** [comment]
Just for the record. You can use something like this in the head.html

```javascript
require(['c3', 'jquery'], function (c3, $) {
    $(document).ready(function() {
        // Your code goes here
    });
```
});
