### ISSUE TITLE
[BUG] Table MultiSelect is not working 

### ISSUE THREAD

**Issue by ThatoFrancisMakola** [tabler/tabler#1894]
### Browser

Chrome Version 125.0.6422.61 (Official Build) (64-bit) and other browsers

### OS

Windows 11 Pro

### Screen size

1920 x 1200

### Describe the bug

Now when I click on the MultiSelect checkbox it throws the below exception:
Exception thrown: 'System.InvalidOperationException' in System.Linq.dll

### How to reproduce

1. Using C# blazor wih TabBlazor Theme at (https://tabblazor.com/docs/tables  even on this side the MultiSelect is not working)
2. In  a razor page have a table with list data and give it ShowCheckboxes Selectable="true" MultiSelect properties and 
3. run the app(in Visual Studio Community 2022 v17.9.3) and display the table list and click on the MultiSelect checkbox and
4. the Exception 'System.InvalidOperationException' in System.Linq.dll is thrown

**Comment by kevinpapst** [comment]
Are you in the wrong repo? Tabler has no MultiSelect addon, bug sounds not related, closing
