### ISSUE TITLE
.card break-word can make numeric figures look odd

### ISSUE THREAD

**Issue by simshaun** [tabler/tabler#19]
Opened up dev tools to look at the demo and immediately noticed the Today Profit box wraps oddly (`$652` becomes `$65\n2`)

![image](https://user-images.githubusercontent.com/379519/38105915-6983f4f0-335b-11e8-95a3-eaa2a371a564.png)

**Comment by Baril27** [comment]
Any recommendations on what the appropriate style should be so the text doesn't break the layout?

**Comment by codecalm** [comment]
@Baril27 try replace `.display-4` to `.h1` class. I'll fix it in demo pages soon.

**Comment by Baril27** [comment]
@codecalm Thoughts on maybe sizing down the text when that breakpoint is reached? Seems there are some other issues with these cards are on smaller widths.

**Comment by codecalm** [comment]
fixed
