### ISSUE TITLE
Suggestions for the use of libraries.

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#191]
jQuery lightgallery - http://sachinchoolur.github.io/lightGallery
WYSIWYG editor - https://alex-d.github.io/Trumbowyg
Plyr player  (Video,  Audio,  YouTube and Vimeo) - https://plyr.io

ps.  Good luck to your wonderful project !!!

**Comment by dsznajder** [comment]
@ZeoNish Thanks for the suggestion! We will discuss internally for some ideas and will get back with some announcements on road map
