### ISSUE TITLE
[BUG] footer background is white in dark mode.

### ISSUE THREAD

**Issue by xwlcn** [tabler/tabler#1922]
.footer background is white in dark mode, it should be --tblr-footer-bg to adapt to different theme colors.

**Comment by shreyakakkar03** [comment]
Can you share the screenshot please?

**Comment by shreyakakkar03** [comment]
I am sorry, but I think it might be related to system settings as in my system it's working well and adapting to the applied theme colors

**Comment by sorescalp** [comment]
Hello is this issue resolved?

**Comment by kevinpapst** [comment]
The footer is missing the class `footer-transparent`.
