### ISSUE TITLE
[BUG] ribbon-start radius wrong

### ISSUE THREAD

**Issue by xwlcn** [tabler/tabler#1923]
![20240711223410](https://github.com/tabler/tabler/assets/15356897/88c56f20-2571-47de-85f9-95694fccbafb)

Should add `border-radius` to `.ribbon-start`:
```
.ribbon-start {
    right: auto;
    left: calc(-1 * var(--tblr-ribbon-margin));
    border-radius: 0 var(--tblr-ribbon-border-radius) var(--tblr-ribbon-border-radius) var(--tblr-ribbon-border-radius);
}
```

**Comment by poswalsameer** [comment]
If any maintainer is seeing this, please assign this issue to me, so I can start working on it.

**Comment by rjd22** [comment]
Fixed in the PR and will merge it after the build.
