### ISSUE TITLE
[FEATURE] Hover to toggle tabs

### ISSUE THREAD

**Issue by xwlcn** [tabler/tabler#1924]
**Is your feature request related to a problem? Please describe.**
Can switch tabs on hover? I use `data-bs-trigger="hover"` didn't work.

**Describe the solution you'd like**
Hover to toggle tabs.

**Comment by kevinpapst** [comment]
You can use custom javascript:
https://getbootstrap.com/docs/5.0/components/navs-tabs/#via-javascript

I doubt that Bootstrap allows it by default, as hover is a desktop only event and it would be impossible to switch to that tab if only hover switches the views.

Anyway, this is a bootstrap question and not Tabler related.
