### ISSUE TITLE
[BUG] Nav tabs's z-index tops that of dropdown forms

### ISSUE THREAD

**Issue by yacoublambaz** [tabler/tabler#1933]
### Browser

Firefox

### OS

Mac OS

### Screen size

800x600

### Describe the bug

When using the following tree of elements: .card-tabs > .nav-tabs. The z-index is set to be 1000. However, this tops any dropdown form or component that could (should) live on top of it. 

Example (notice the Conversations, Marketing) tabs are living on top of the dropdown: 

![image](https://github.com/user-attachments/assets/23c8543c-63b4-4102-9bb5-ff65be6ddd25)

### How to reproduce

As above.

### Screenshots

![image](https://github.com/user-attachments/assets/c71998d3-5869-4df4-a8a0-1587438a0358)

**Comment by poswalsameer** [comment]
Hi @rjd22, can you assign this issue to me? I will start working on it asap.

**Comment by rjd22** [comment]
We don't assign issues. Just make an PR with the solution.

**Comment by poswalsameer** [comment]
Hi @rjd22, created PR #1953 which hopefully solves this issue, can you please review it? Thanks in advance!
