### ISSUE TITLE
[BUG] Dropdown page in preview not showing dropdowns

### ISSUE THREAD

**Issue by tacman** [tabler/tabler#1950]
### Browser

all

### OS

all

### Screen size

large

### Describe the bug

These are lists, not dropdowns

### How to reproduce

[[(https://preview.tabler.io/dropdowns.html#)](https://preview.tabler.io/dropdowns.html#)](https://preview.tabler.io/dropdowns.html#)](https://preview.tabler.io/dropdowns.html#)

### Screenshots

https://preview.tabler.io/dropdowns.html#

![image](https://github.com/user-attachments/assets/0fb3c2ca-3329-48bb-848f-290bed96145b)

**Comment by khanhicetea** [comment]
This page is the showcases of "Dropdown content", mean you need wrap them in in 'dropdown container' and 'dropdown trigger' like below Dropdown document

<img width="1687" alt="image" src="https://github.com/user-attachments/assets/aed477e7-ba95-453d-892d-d04904aa91fa">

**Comment by tacman** [comment]
Thanks, makes sense.  perhaps some documentation on that page or a link to https://tabler.io/docs/components/dropdowns would help.
