### ISSUE TITLE
[FEATURE] How to update data dynamically through http requests

### ISSUE THREAD

**Issue by shuaiyu-wang** [tabler/tabler#1963]
I have a background service, my data needs to be obtained through http request, how to achieve this requirement, can you provide a demo

Do I need to reintroduce any plug-ins, such as jquery, to use ajax?

If yes, please provide a demo to help me complete.

thanks

**Comment by clayheaton** [comment]
Tabler is not going to do this out of the box because it does not know how your backend is configured. Take a look at [HTMX](https://htmx.org), which makes this type of data fetching very simple.

**Comment by kevinpapst** [comment]
this question is out of scope for tabler
