### ISSUE TITLE
Bad work my custom JS script

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#198]
My additional js script does not always work adequately...

![image](https://user-images.githubusercontent.com/8596319/45377210-9cb38280-b602-11e8-9a33-3e0ad6d791d4.png)
![image](https://user-images.githubusercontent.com/8596319/45377219-a3da9080-b602-11e8-8498-cf29e137d75d.png)

Everything works very unstable. the jquery library does not always connect correctly.

**Comment by alexjustesen** [comment]
Are you loading the script with require js?

**Comment by ZeoNish** [comment]
> Are you loading the script with require js? If so make sure you're loading your script after dependencies needed.

I connected the script before < / body>

classic <script src="./assets/js/script.js"></script>

If you know how to fix the error then tell me more clearly.

**Comment by danieljsc** [comment]
well, with requirejs you can't just include your script after the </body> tag.
Requirejs manages all js scripts. You must include your script in requirejs config file.
assets\js\dashboard.js

**Comment by akifyanbak** [comment]
`require('jquery',function($){
$(document).ready(function(){});
})`

**Comment by ZeoNish** [comment]
thx

**Comment by akifyanbak** [comment]
You need to do the dependency settings. For instance:
`require.config({
    shim: {
        'myScript': ['jquery']
    },
    paths: {
        'myScript': 'assets/plugins/myScript/js/myScript.min',
    }
});`

**Comment by ZeoNish** [comment]
> You need to do the dependency settings. For instance:
> `require.config({ shim: { 'myScript': ['jquery'] }, paths: { 'myScript': 'assets/plugins/myScript/js/myScript.min', } });`

Thx Bro !!!
