### ISSUE TITLE
[BUG] Tabler-Icons search

### ISSUE THREAD

**Issue by nrose01** [tabler/tabler#1982]
### Browser

Chrome V:129

### OS

Windows 11

### Screen size

1920x1080

### Describe the bug

Firstly, love the app and the new UI! Looks great. 

The issue I am having is that the search only looks through the tags associated with each icon and even if you explicitly write in the icons name exactly, the search will return empty. Since most icons do not include their name in the tag it makes searching the icons incredibly difficult. It honestly makes the search almost useless at times. Trying to find the 'link' icon took me about 25 minutes because it only has one tag and that is 'zoom-filled'. I had to manually look through every category i thought might have the link icon. 

I think a simple script to append the name of the icon as a tag would solve this issue. 

Not sure if you're open source or a sole developer, but if there is anything I can do to help you out, let me know! I'm happy to give back. 

Thanks,
-Nate

### How to reproduce

1. Search for 'link' or any other common element
2. Scratch head

**Comment by gy8879** [comment]
can i try to solve this problem?

**Comment by plaimbock** [comment]
> can i try to solve this problem?

Yes, you don't even have to ask :smile:
If you want to submit a PR, please make sure it is against the 'dev' branch.

**Comment by BG-Software-BG** [comment]
@nrose01 - where do you search those icons? I tried to search for "link" on https://tabler.io/icons and the link icons is the 1st result

![image](https://github.com/user-attachments/assets/6272d8a1-c7f1-4810-b909-a81239756f66)

**Comment by nrose01** [comment]
Hey, so it seems this problem was solved. About two after I submitted the
issue I noticed it was working. It was something that came about with the
new UI. May have just been a small bug that was fixed that came up during
the change that was addressed by someone else.

Love this site btw.

Thanks for looking into it,
Nate

**Comment by nrose01** [comment]
*about two weeks

Nate Rose

**Comment by BG-Software-BG** [comment]
Great to hear that.
