### ISSUE TITLE
[LICENSE VIOLATION] TinyMCE copyleft license FORBIDS this to be licensed MIT

### ISSUE THREAD

**Issue by carlosmintfan** [tabler/tabler#1983]
### Browser

does not matter

### OS

does not matter

### Screen size

does not matter

### Describe the bug

TinyMCE is licensed GPLv2+ since the 7.x version, making it incompatible with permissively-licensed open source products like this one. Therefore, TinyMCE must be removed or Tabler switch to GPL, which would be really bad. Instead, I recommend you replacing TinyMCE with my [HugeRTE](https://github.com/hugerte/hugerte) fork. Thank you!

### How to reproduce

see above

**Comment by carlosmintfan** [comment]
Maybe this isn't even a license violation as MIT is GPL-compatible; however, people won't get the full freedom of the MIT license if they decide to include TinyMCE in their project.

**Comment by rjd22** [comment]
Since we're only suggesting to install TinyMCE and not bundling. This is as far as I know no license violation. For that reason closing this.
