### ISSUE TITLE
TABLER EMAIL - LIGHT THEME IS NOT WORKING IT IS SAME AS DARK THEME

### ISSUE THREAD

**Issue by GLACIER2007** [tabler/tabler#1990]
### Browser

Chrome

### OS

Android

### Screen size

Mobile device

### Describe the bug

I want to use blog post as a part of my website but the light theme is same as dark theme

### How to reproduce

2. Click on '...'
3. Scroll down to '...'
...

**Comment by samriddhibhattacharya** [comment]
can you please share the link
