### ISSUE TITLE
[PROPOSAL] Switch to actively maintained fork of dropzone

### ISSUE THREAD

**Issue by carlosmintfan** [tabler/tabler#1999]
Hi,
Thank you for you amazing work on Tabler. I just saw the dropzone library is not actively being maintained anymore, but there‘s a fork: https://www.npmjs.com/package/@deltablot/dropzone

**Comment by rjd22** [comment]
Same story as the other one. While we really appreciate that other people are continuing development on these libraries were careful with just adding forks to tabler. If the forks keep up the maintenance and mature a bit we might reconsider this.

Do understand that it doesn't mean that tablers doesn't support the fork. Chances are the scss that we use for Dropzone also works fine on the fork. We're just not planning to link to the fork just yet.
