### ISSUE TITLE
Working with icons

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#201]
![image](https://user-images.githubusercontent.com/8596319/45946972-3e6fa200-bffb-11e8-95d8-b68094f7d6df.png)

`$('li.icons-list-item i').click(function () {
    	
    var idClass = $(this).attr('data-original-title');	
   
    navigator.clipboard.writeText(idClass)
		.then(() => {
    		// copy!
		})
		.catch(err => {
    		console.log('Something went wrong', err);
		});
});
`

`li.icons-list-item:hover {
	    background: rgba(0, 0, 0, 0.025);
	    cursor: pointer;
}`

Add copy to clipboard class icons. Thx. 

ps. Yes! I'm very lazy >_<

**Comment by workgena** [comment]
I miss this feature too :scissors:

**Comment by ZeoNish** [comment]
> I miss this feature too

[https://chrome.google.com/webstore/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld](url)
