### ISSUE TITLE
[BUG] The official manual code does not display

### ISSUE THREAD

**Issue by stephenyaoshun** [tabler/tabler#2010]
### Browser

chrome

### OS

win10

### Screen size

1920*1080

### Describe the bug

All the code blocks on the official website's documentation page are blank. I tried all browsers, edge, firefox, chrome, and even the browser in a virtual machine couldn't display the code. Please fix it quickly.
![image](https://github.com/user-attachments/assets/236ad672-43a9-4b12-b700-f58481c42472)

### How to reproduce

2. Click on '...'
3. Scroll down to '...'
...

**Comment by graf0** [comment]
confirm - no examples and no code in docs. I'm using firefox - but also checked on edge, same result

**Comment by ahmadfarisfs** [comment]
Same here

**Comment by stephenyaoshun** [comment]
2 days have passed, the problem still exists, this is how you treat your work, I doubt the reliability of your product

**Comment by rjd22** [comment]
Closing because of duplicate of #2012
