### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by c41mrj** [tabler/tabler#2011]
### Browser

Microsoft Edge V. 131

### OS

Windows 10

### Screen size

1920*1080

### Describe the bug

In the section of Documentation in your website all the exmaples and the code are empty.
![image](https://github.com/user-attachments/assets/9a92fed4-8211-4193-acc4-e4f7b3a97293)
And this happend in all your webpage

### How to reproduce

1. Go to 'tabler.io'
2. Click on 'Documentation'
3. Go to any section
...
![image](https://github.com/user-attachments/assets/9a92fed4-8211-4193-acc4-e4f7b3a97293)

### Screenshots

![image](https://github.com/user-attachments/assets/9a92fed4-8211-4193-acc4-e4f7b3a97293)

**Comment by graf0** [comment]
confirm - no exmples, no code in docs
