### ISSUE TITLE
[BUG] website not working properly not showing code snippets

### ISSUE THREAD

**Issue by robinnarban8181** [tabler/tabler#2012]
### Browser

chrome Version 131.0.6778.140

### OS

Windows 10

### Screen size

1920x1080

### Describe the bug

website not working properly not showing code snippets
![image](https://github.com/user-attachments/assets/54995289-71a2-4a6d-ae8d-e0cecdb8ab28)
![image](https://github.com/user-attachments/assets/794bc0ad-dc15-4239-8379-54476e9b4519)
 

### How to reproduce

2. Click on '...'
3. Scroll down to '...'
...

### Screenshots

![image](https://github.com/user-attachments/assets/02f7f611-6565-4c0e-aa2f-71f1d747fdea)
![image](https://github.com/user-attachments/assets/9fc15a78-d5f2-42c3-a7d8-a0e1667ec0d2)

**Comment by rjd22** [comment]
This seems to be an edge specific bug. It works fine for me in Firefox. Does the same happen in chrome? I cannot test because I don't have an Windows machine.

**Comment by BG-Software-BG** [comment]
It's fixed now.
