### ISSUE TITLE
Can we get a CDN or npm installable package?

### ISSUE THREAD

**Issue by EliuTimana** [tabler/tabler#205]
is annoying downloading the project repository to build the project assets, I think you should provide us a compiled and raw versions of this great project.

**Comment by pdawczak** [comment]
Hey, I'm not super sure if there are any problems, but the NPM package is
available here: https://www.npmjs.com/package/tabler-ui which I was using
with success so far

**Comment by twf-nikhila** [comment]
@pdawczak Looks like the npm package is not updated from last 9 months? :( Or does it pull the latest?

**Comment by pdawczak** [comment]
@twf-nikhila Sorry, I'm not the best person to talk about it I'm afraid. I used Tabler for a side project, but I  didn't have time for working on it, and I didn't interact with Tabler since then 😬
