### ISSUE TITLE
bootstrap.bundle.min.js.map not found.

### ISSUE THREAD

**Issue by alihesari** [tabler/tabler#206]
When I run `yarn serve`, I get this error in terminal:

> [2018-10-03 12:47:26] ERROR `/assets/js/vendors/bootstrap.bundle.min.js.map' not found.

Please Fix this error.

**Comment by maxoyed-MS** [comment]
Just delete the `//# sourceMappingURL=bootstrap.bundle.min.js.map` in file `src/assets/js/vendors/bootstrap.bundle.min.js`

**Comment by fordarnold** [comment]
> Just delete the `//# sourceMappingURL=bootstrap.bundle.min.js.map` in file `src/assets/js/vendors/bootstrap.bundle.min.js`

Thanks a lot @maxoyed 💯

Someone should close the issue.
