### ISSUE TITLE
npm run serve is not working 

### ISSUE THREAD

**Issue by JustJunaid** [tabler/tabler#211]
Showing these Errors:-
-
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated public_suffix 3.0.3, but your Gemfile requires public_suffix 3.0.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:31:in `block in setup'
        from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:26:in `map'
        from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:26:in `setup'
        from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
        from /Library/Ruby/Gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from /Library/Ruby/Gems/2.3.0/gems/jekyll-3.8.4/exe/jekyll:11:in `<top (required)>'
        from /usr/local/bin/jekyll:22:in `load'
        from /usr/local/bin/jekyll:22:in `<main>'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 jekyll-serve: `jekyll serve --livereload`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.32 jekyll-serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/junaidchoudhary/.npm/_logs/2018-10-13T08_10_31_638Z-debug.log
ERROR: "jekyll-serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.32 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/junaidchoudhary/.npm/_logs/2018-10-13T08_10_31_785Z-debug.log

**Comment by ra7bi** [comment]
same here

**Comment by uitlaber** [comment]
+

**Comment by ra7bi** [comment]
Try 
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
sudo gem install nokogiri
bundle install

**Comment by JustJunaid** [comment]
@ra7bi Still not able to sort it out :(

**Comment by ra7bi** [comment]
> @ra7bi Still not able to sort it out :(

What error do you get ? 

First of things go to root directory of the theme `/tabler` and follow the steps below : 

before we start make sure your `package.json`  contain the following in the scripts  section 
```    "jekyll-serve": "bundle exec jekyll serve --livereload", ``` 

Before everything uninstall  `eventmachine` and reinstall it by the following command 

`sudo gem uninstall eventmachine`
`sudo gem install eventmachine --platform ruby`


im able to resolve the problem by installing

 `sudo gem install jekyll` 
 `sudo apt install ruby-bundler` 
`sudo gem install htmlbeautifier`
`sudo apt install gulp`
`sudo gem install nokogiri`
`bundle install`

and finally run the server
`npm run serve`

**Comment by JustJunaid** [comment]
Yay, finally satisfied and onto the project, thank you so much :)

**Comment by Nayananga** [comment]
i did 

> First of things go to root directory of the theme `/tabler` and follow the steps below :
> 
> before we start make sure your `package.json` contain the following in the scripts section
> ` "jekyll-serve": "bundle exec jekyll serve --livereload",`
> 
> Before everything uninstall `eventmachine` and reinstall it by the following command
> 
> `sudo gem uninstall eventmachine`
> `sudo gem install eventmachine --platform ruby`
> 
> im able to resolve the problem by installing
> 
> `sudo gem install jekyll`
> `sudo apt install ruby-bundler`
> `sudo gem install htmlbeautifier`
> `sudo apt install gulp`
> `sudo gem install nokogiri`
> `bundle install`
> 
> and finally run the server
> `npm run serve`

mine still same :(

**Comment by ra7bi** [comment]
> 
> 
> i did
> 
> > First of things go to root directory of the theme `/tabler` and follow the steps below :
> > before we start make sure your `package.json` contain the following in the scripts section
> > ` "jekyll-serve": "bundle exec jekyll serve --livereload",`
> > Before everything uninstall `eventmachine` and reinstall it by the following command
> > `sudo gem uninstall eventmachine`
> > `sudo gem install eventmachine --platform ruby`
> > im able to resolve the problem by installing
> > `sudo gem install jekyll`
> > `sudo apt install ruby-bundler`
> > `sudo gem install htmlbeautifier`
> > `sudo apt install gulp`
> > `sudo gem install nokogiri`
> > `bundle install`
> > and finally run the server
> > `npm run serve`
> 
> mine still same :(

What is the output of each ? is there any error ?

**Comment by Nayananga** [comment]
nayananga@nayananga-Aspire-E5-575G:~/Desktop/Link to htdocs/projects/scr2$ npm run serve

> tabler-ui@0.0.32 serve /opt/lampp/htdocs/projects/scr2
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/opt/lampp/htdocs/projects/scr2/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/opt/lampp/htdocs/projects/scr2/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/opt/lampp/htdocs/projects/scr2/gulpfile.js:42:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tabler-ui@0.0.32 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nayananga/.npm/_logs/2018-11-20T16_46_44_208Z-debug.log
nayananga@nayananga-Aspire-E5-575G:~/Desktop/Link to htdocs/projects/scr2$ 

i got this error only

**Comment by ra7bi** [comment]
> 
> 
> nayananga@nayananga-Aspire-E5-575G:~/Desktop/Link to htdocs/projects/scr2$ npm run serve
> 
> > tabler-ui@0.0.32 serve /opt/lampp/htdocs/projects/scr2
> > gulp build && npm-run-all --parallel gulp-watch jekyll-serve
> 
> assert.js:350
> throw err;
> ^
> 
> AssertionError [ERR_ASSERTION]: Task function must be specified
> at Gulp.set [as _setTask] (/opt/lampp/htdocs/projects/scr2/node_modules/undertaker/lib/set-task.js:10:3)
> at Gulp.task (/opt/lampp/htdocs/projects/scr2/node_modules/undertaker/lib/task.js:13:8)
> at Object. (/opt/lampp/htdocs/projects/scr2/gulpfile.js:42:6)
> at Module._compile (internal/modules/cjs/loader.js:688:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
> at Module.load (internal/modules/cjs/loader.js:598:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
> at Function.Module._load (internal/modules/cjs/loader.js:529:3)
> at Module.require (internal/modules/cjs/loader.js:636:17)
> at require (internal/modules/cjs/helpers.js:20:18)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the tabler-ui@0.0.32 serve script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/nayananga/.npm/_logs/2018-11-20T16_46_44_208Z-debug.log
> nayananga@nayananga-Aspire-E5-575G:~/Desktop/Link to htdocs/projects/scr2$
> 
> i got this error only

what operating system you are using ? my suggestion is to remove all required packages and re install them one by one and make sure when you install each one there is no error

**Comment by cankaya07** [comment]
i had a problem not exact but similar. working on macos 
here my log output:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'serve' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle tabler-ui@0.0.32~preserve: tabler-ui@0.0.32
6 info lifecycle tabler-ui@0.0.32~serve: tabler-ui@0.0.32
7 verbose lifecycle tabler-ui@0.0.32~serve: unsafe-perm in lifecycle true
8 verbose lifecycle tabler-ui@0.0.32~serve: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/cankaya/Desktop/tabler/node_modules/.bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle tabler-ui@0.0.32~serve: CWD: /Users/cankaya/Desktop/tabler
10 silly lifecycle tabler-ui@0.0.32~serve: Args: [ '-c',
10 silly lifecycle   'gulp build && npm-run-all --parallel gulp-watch jekyll-serve' ]
11 info lifecycle tabler-ui@0.0.32~serve: Failed to exec serve script
12 verbose stack Error: tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid tabler-ui@0.0.32
14 verbose cwd /Users/cankaya/Desktop/tabler
15 verbose Darwin 18.0.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
17 verbose node v10.15.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
23 error spawn ENOENT
24 error Failed at the tabler-ui@0.0.32 serve script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

what is the problem ? i cloned the project onto the my desktop. and installe the dependencies.
