### ISSUE TITLE
Questions to contribute

### ISSUE THREAD

**Issue by CoderSquirrel** [tabler/tabler#216]
Hi i add animations to the Card collapsing and am aiming to pull.
I'm reading the contributin.md and some questions appeared.
1. `Update the README.md with details of changes to the interface, this includes new environment variables, exposed ports, useful file locations and container parameters.`
Once i've onli improved the 'animation' and the fell for the card collaptions i dont think(please correct me if im wront) there's too much to add to the readme
2. Abuot the version, reading SemVer it says, Z is for bugs and Fix, and Y is for improvement, but once  tabler is in 0.0.32 i was quite afraid too change to 0.1.0

How i do proceed on it?
ps, awesome job guys

**Comment by MatthiasLohr** [comment]
Has this actually been merged to allow for collapsible cards? Can't find it, a short hint would be great...
