### ISSUE TITLE
What versions of d3 and c3 charts are you using?

### ISSUE THREAD

**Issue by alistairtweedie** [tabler/tabler#218]
What versions of d3 and c3 are being used? I don't see any documentation regarding the versions of the plugins that are being used in the 'src/assets/plugins' folder

**Comment by JustJunaid** [comment]
hey, can you help me integrate charts of this tabler.io in my project.
I have implemented the same jquery code as in the source code but there is one bug that im facing that goes like this,(tabler is not defined), i guess it's related to tabler.colors or something like that

**Comment by alistairtweedie** [comment]
> hey, can you help me integrate charts of this tabler.io in my project.
> I have implemented the same jquery code as in the source code but there is one bug that im facing that goes like this,(tabler is not defined), i guess it's related to tabler.colors or something like that

Some what unrelated to the issue above. It sounds like you already have an idea of the problem. Make sure you have integrated all of the original plugins and js. If you need more guidance I would join the Slack Group.

**Comment by alistairtweedie** [comment]
Does anyone have an update on this query?
