### ISSUE TITLE
Working with input files inside a form!

### ISSUE THREAD

**Issue by JustJunaid** [tabler/tabler#219]
So, when i upload a file using tabler classes, the name of the file is not displayed, like for example the label on uploading 'data.csv' file does not change and remain 'Choose File', i guess it's related to the css, but i'm not sure. Can someone help me regarding this?

**Comment by manuponce1993** [comment]
Hi, I was looking for a template to include in a project from my university and luckily I found this open source development. 
I think the problem is that there's no JS function that loads the name of the file attached to the input. Adding this function will do the magic!

```javascript
$(".custom-file-input").on('change',function() { 
	// Get the complete path and keep only the filename
        var filename = $(this).val().split('\\').pop();
        // Assign the filename to the associated label
	$(this).siblings(".custom-file-label").text(filename);
})
```

**Comment by FreexD** [comment]
@JustJunaid @manuponce1993 it's been a very long time :D but it now works natively in the browser - no need to add custom JS for handling that ;) Check out tabler 1.0.0-alpha.15 for it ;)
