### ISSUE TITLE
Uncaught Error: Script error for "c3"

### ISSUE THREAD

**Issue by JustJunaid** [tabler/tabler#221]
Facing problem in implementing charts, i have just cloned the repo, and this is the error in my console and also Uncaught Error: Script error for "datatables", this is also coming, can someone help me regarding this, i'm not able to work with charts sort of things in project using this tabler ui :( 
Thanks.

**Comment by dsznajder** [comment]
@JustJunaid 	We started implemetation of charts. It will be released in `v1`
