### ISSUE TITLE
assert.js:351

### ISSUE THREAD

**Issue by hsj86715** [tabler/tabler#225]
hushujundeMacBook-Pro:tabler hushujun$ npm run serve

> tabler-ui@0.0.32 serve /Users/hushujun/Documents/WorkSpaces/WebStormSpace/tabler
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/hushujun/Documents/WorkSpaces/WebStormSpace/tabler/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/hushujun/Documents/WorkSpaces/WebStormSpace/tabler/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/hushujun/Documents/WorkSpaces/WebStormSpace/tabler/gulpfile.js:42:6)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tabler-ui@0.0.32 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hushujun/.npm/_logs/2018-11-09T12_07_31_348Z-debug.log

**The log file content as below:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@6.4.1
3 info using node@v11.1.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle tabler-ui@0.0.32~preserve: tabler-ui@0.0.32
6 info lifecycle tabler-ui@0.0.32~serve: tabler-ui@0.0.32
7 verbose lifecycle tabler-ui@0.0.32~serve: unsafe-perm in lifecycle true
8 verbose lifecycle tabler-ui@0.0.32~serve: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/hushujun/Documents/WorkSpaces/WebStormSpace/tabler/node_modules/.bin:/usr/local/opt/libxml2/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/sphinx-doc/bin:/opt/local/bin:/opt/local/sbin:/Users/hushujun/bin:/Users/hushujun/Library/Android/flutter/bin:/Users/hushujun/Library/Android/sdk/ndk-bundle:/Users/hushujun/Library/Android/sdk/tools:/Users/hushujun/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle tabler-ui@0.0.32~serve: CWD: /Users/hushujun/Documents/WorkSpaces/WebStormSpace/tabler
10 silly lifecycle tabler-ui@0.0.32~serve: Args: [ '-c',
10 silly lifecycle   'gulp build && npm-run-all --parallel gulp-watch jekyll-serve' ]
11 silly lifecycle tabler-ui@0.0.32~serve: Returned: code: 1  signal: null
12 info lifecycle tabler-ui@0.0.32~serve: Failed to exec serve script
13 verbose stack Error: tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
14 verbose pkgid tabler-ui@0.0.32
15 verbose cwd /Users/hushujun/Documents/WorkSpaces/WebStormSpace/tabler
16 verbose Darwin 18.0.0
17 verbose argv "/usr/local/Cellar/node/11.1.0/bin/node" "/usr/local/bin/npm" "run" "serve"
18 verbose node v11.1.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
22 error Exit status 1
23 error Failed at the tabler-ui@0.0.32 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Telperin** [comment]
### Hello there!

Probably your **gulpfile.js** made for **Gulp 3 versions**, and it is not for **Gulp 4.0.0** format.
As I know, there are two possible solutions:

**1.** Local downgrade your **Gulp** to version **3.9.1** (the last one of 3rd version generation):

   $ `npm install gulp@3.9.1`

And your old **gulpfile.js** will work.

**2.** Rebuild your **gulpfile.js** into the **Gulp 4.0.0** new style:

   - Check the [Gulp 4.0.0 docs](https://github.com/gulpjs/gulp/tree/master/docs/getting-started) in the official page
   - Look at the [Sample](https://gist.github.com/jeromecoupe/0b807b0c1050647eb340360902c3203a) of **gulpfile.js** made by @jeromecoupe
   - You may need to install global **gulp-cli**: $ `npm i --g gulp-cli`

To know your version of Gulp: $ `gulp -v`

Good luck!
