### ISSUE TITLE
Error: File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.

### ISSUE THREAD

**Issue by bigxu** [tabler/tabler#228]
Error in plugin "sass"
Message:
    src/assets/scss/bundle.scss
Error: File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.
        on line 6 of src/assets/scss/bundle.scss
>> @import '~bootstrap/scss/bootstrap.scss';

➜  scss git:(dev) ✗ cat bundle.scss
/**
Dashboard UI
 */

@import 'variables';
@import 'bootstrap/scss/bootstrap.scss';
@import 'dashboard/dashboard';

**Comment by gaoqiang19514** [comment]
I also had this problem

**Comment by sigismund** [comment]
Duplicate of #226

**Comment by bigxu** [comment]
> Duplicate of #226

so i am closing this issue
