### ISSUE TITLE
Demo page link in README.md outdated Tabler-react Impacted

### ISSUE THREAD

**Issue by Greg-Hamel** [tabler/tabler#232]
Hi, 

The link to the demo page is broken in README.md. I believe the link should be `https://preview.tabler.io` instead of `https://tabler.github.io/demo`.

I see that the official website URLs have changed and that Tabler-React demo and docs are also impacted by this change.

**Comment by jonthomp** [comment]
I've set up http://tabler-react.com as a hopefully temporary solution, it should start working soon.
