### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by bhaskesaravanan** [tabler/tabler#233]
I developed UI using your previous documentation. In that, you had many elements and feature. so I used and developed But Now In your new documentation, many elements are not there. It's very hard to figure it out. I used tables, titles, cards, and many elements. could you tell when it gets fixed or is there any way to access the old one?

**Comment by bboydflo** [comment]
@bhaskesaravanan have you solved your issue? how?

**Comment by bhaskesaravanan** [comment]
Now, they fixed it. They updated their document.
