### ISSUE TITLE
I got this problème in running the app

### ISSUE THREAD

**Issue by ahmed37** [tabler/tabler#234]
Hi, i got this problem when runing the app :

Server running... press ctrl-c to stop.
#<Thread:0x0000000005feee58@C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/commands/serve/live_reload_reactor.rb:41 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.8.3/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
        6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:196:in `run'
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:562:in `run'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `ensure in run'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `each'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `block in run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `close': Bad file descriptor (Errno::EBADF)
jekyll 3.8.3 | Error:  Bad file descriptor.

Thank you for the help.

**Comment by dsznajder** [comment]
@ahmed37 If you still have an issue please open a new one with more details because I'm missing some of them currently. Thanks!
