### ISSUE TITLE
Readme is confusing

### ISSUE THREAD

**Issue by PrototypeXenon** [tabler/tabler#24]
The readme file could definitely use some rewording in order to make it easier to understand and be more correct. I could do it if you would like.

**Comment by codecalm** [comment]
Hi @PrototypeXenon, thanks for good feedback! 
I made tabler in free time for fun and I did not expect such a big response. If you can help us with it I will be grateful!

**Comment by PrototypeXenon** [comment]
Great! I'll make a PR when I'm done

**Comment by beeman** [comment]
@PrototypeXenon closing for now, happy to review/merge any PR's you have!
