### ISSUE TITLE
assert.js 350 gulp error

### ISSUE THREAD

**Issue by betzai** [tabler/tabler#242]
I have an error assert.js 350 I have no idea what could be wrong

**Comment by betzai** [comment]
I have this error, I have no idea what could be wrong, if you can help me with this I appreciate it 

C:\Users\Satellite\Desktop\bootstrap-template-init> npm start

> bootstrap-template-init@1.0.0 start C:\Users\Satellite\Desktop\bootstrap-templ
ate-init
> gulp

assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\Satellite\Desktop\bootstrap-template-ini
t\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\Satellite\Desktop\bootstrap-template-init\node_module
s\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Users\Satellite\Desktop\bootstrap-template-init\gu
lpfile.js:27:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-template-init@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-template-init@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Satellite\AppData\Roaming\npm-cache\_logs\2019-01-20T23_45
_04_951Z-debug.log

C:\Users\Satellite\Desktop\bootstrap-template-init>


**This is the gulpfile.js**


const gulp = require('gulp');
const browserSync = require('browser-sync');
const sass = require('gulp-sass');
//Este convierte el codigo de sass a CSS//
gulp.task('sass', () => {
  return gulp.src([
    'node_modules/bootstrap/scss/bootstrap.scss',
    'src/scss/*.scss'
  ])
  .pipe(sass({outputStyle: 'compressed'}))
  .pipe(gulp.dest('src/css'))
  .pipe(browserSync.stream());
});

//Este se encarga de tener los archivos javascript en mi carpeta//
gulp.task('js', () => {
  return gulp.src([
    'node_modules/bootstrap/dist/js/bootstrap.min.js',
    'node_modules/jquery/dist/jquery.min.js',
    'node_modules/popper.js/dist/umd/popper.min.js'
  ])
  .pipe(gulp.dest('src/js'))
  .pipe(browserSync.stream());
});
//Este se encarga de tener un servidor de desarrollo
gulp.task('serve', ['sass'], () => {
  browserSync.init({
    server: './src'
  });

  gulp.watch([
    'node_modules/bootstrap/scss/bootstrap.min.scss',
    'src/scss/*.scss'
  ], ['sass']);

  gulp.watch('src/*.html').on('change', browserSync.reload);

});
//Este se encarga de copiar a font awesome//
gulp.task('font-awesome', () => {
  return gulp.src('node_modules/font-awesome/css/font-awesome.min.css')
  .pipe(gulp.dest('src/css'));
})

gulp.task('fonts', () => {
  return gulp.src('node_modules/font-awesome/fonts/*')
    .pipe(gulp.dest('src/fonts'));
});

gulp.task('default', ['js', 'serve', 'font-awesome', 'fonts']);

**Comment by aginvlad** [comment]
It could be because of new gulp update: Gulp 4.0
Developers have changed a lot, you should reconfigure your gulp config, using new features.
