### ISSUE TITLE
ERROR `/assets/css/dashboard.css' not found.

### ISSUE THREAD

**Issue by mwilliams1188** [tabler/tabler#244]
I have the server running and the page loads, just with no styling. It looks like it can't find anything in the assets folder. Any ideas?

**Comment by kevinpapst** [comment]
You need to compile the assets first with `npm run gulp-build`.

**Comment by ccleve** [comment]
No. If you git clone the dev branch, npm run gulp-build generates this error:

Error in plugin "sass"
Message:
    src/assets/scss/bundle.scss
Error: File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.
        on line 6 of src/assets/scss/bundle.scss
>> @import '~bootstrap/scss/bootstrap.scss';

**Comment by ahmedanadi** [comment]
Hello, I have the same problem!!

**Comment by hooleahn** [comment]
Change line 6 in src/assets/scss/bundle.scss to:
`@import '../../../node_modules/bootstrap/scss/bootstrap.scss';`

**Comment by ahmedanadi** [comment]
> @import '../../../node_modules/bootstrap/scss/bootstrap.scss';

Thank you!! Now is Working!

**Comment by mattlindop** [comment]
I've got a similar problem and changing the @import statement as @hooleahn suggests hasn't fixed it. Problem seems to be dashboard.css isn't being found...?

/usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.0/lib/liquid/utils.rb:49: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
                    done in 2.04 seconds.
 Auto-regeneration: enabled for 'src'
LiveReload address: http://0.0.0.0:35729
    Server address: http://0.0.0.0:4000
  Server running... press ctrl-c to stop.
[2019-03-20 13:07:27] ERROR `/assets/css/dashboard.css' not found.
