### ISSUE TITLE
Help for installation

### ISSUE THREAD

**Issue by BarbaraDi** [tabler/tabler#248]
Dear community,

I wanted to try tabler and thus, I have installed downloaded the package (tabler-master, is it the right one?), Node, Ruby, Bundler and Jekyll.
I use Windows 10.

Apparently, I did something wrong, since I can not run the npm server. Here is the screenshot of the console:

![error](https://user-images.githubusercontent.com/13226574/52471576-80a41500-2b91-11e9-96f2-94fa596b4c03.png)

If anyone could help me, I'd be very thankful! :-)

Kind regards,
Barbara

**Comment by ahmetcangir** [comment]
Open Cmd
Type git clone, and then paste clone url of repository. Press Enter. 
Your local clone will be created. 

Full code shuold be like this:
git clone https://github.com/tabler/tabler.git

**Comment by ahmetcangir** [comment]
Download [ZIP](https://github.com/tabler/tabler/archive/master.zip) or Git Clone.

In order to clone git repository:
`git clone https://github.com/tabler/tabler.git`
