### ISSUE TITLE
Common Installation Errors and Warnings (Update README?)

### ISSUE THREAD

**Issue by fordarnold** [tabler/tabler#250]
So I finally managed to install Tabler, using instructions from the [README](https://github.com/tabler/tabler#setup-environment). But first, I ran into different warnings and errors that made me have to go digging the internet to look for solutions. 

I believe that by showing users the **common** roadblocks they might encounter as well as the possible solutions, we will be able to save a lot of time and improve the user experience.

Here are some issues I encountered during installation of Tabler on Ubuntu 18.04:

### Deprecated bundles warnings ~ `npm install`

![npm-warnings-deprecated_bundles](https://user-images.githubusercontent.com/1271441/52641346-4d3eee80-2ee1-11e9-9c79-144fce822976.png)
---
---
### Dependency errors ~ `npm install`

![npm-errors-missing_dependencies](https://user-images.githubusercontent.com/1271441/52641787-53819a80-2ee2-11e9-9acd-2f12f7ac4ffa.png)
![npm-errors-missing_dependencies_2](https://user-images.githubusercontent.com/1271441/52641798-5b413f00-2ee2-11e9-9019-69a2a5a59ea9.png)

#### Solution

![npm-errors-missing_dependencies-solved](https://user-images.githubusercontent.com/1271441/52642088-fa663680-2ee2-11e9-8a59-afbdf70405ea.png)
---
---
### Build errors ~ `npm run serve`

![npm-errors-build_sass](https://user-images.githubusercontent.com/1271441/52642312-6fd20700-2ee3-11e9-827b-4023415eefac.png)

#### Solution

![npm-errors-build_sass-solution](https://user-images.githubusercontent.com/1271441/52642623-0b637780-2ee4-11e9-83a4-54820004ef42.png)
---
---
### Bundler errors ~ `bundle install`
I'll update this part later...But i believe it's important.

**Comment by dchavours** [comment]
wow, excellent

**Comment by dchavours** [comment]
wow, excellent
