### ISSUE TITLE
Popover not working!!!!

### ISSUE THREAD

**Issue by chimsgraphic** [tabler/tabler#251]
Any time I add another Javascript file e.g vue.js to my header, the popover or drop-down immediately stops working.

Can this be this problematic Require.js or what. It has been so frustrating...!!!

**Comment by wenky** [comment]
Hi,
I'm also having the similar issue,is there any workaround for it?

**Comment by chimsgraphic** [comment]
You need to get rid of the require.js library reference completely and reference all other JavaScript dependences that come with the template, excluding require.js. 

Though you need to check require.js to see all the other JavaScript references. Stupid template! What were the creators thinking by adding require.js, it's a big spoiler.
