### ISSUE TITLE
custom select indicator disappeared

### ISSUE THREAD

**Issue by nkanaev** [tabler/tabler#253]
Since Chrome 72, `#` in data uris are invalid.

Would you consider changing the line below to escape the character in [_variables.scss]

from:

> $custom-select-indicator: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 5'%3E%3Cpath fill='#{$custom-select-indicator-color}' d='M0 0L10 0L5 5L0 0'/%3E%3C/svg%3E");

to:

> $custom-select-indicator: str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 5'%3E%3Cpath fill='#{$custom-select-indicator-color}' d='M0 0L10 0L5 5L0 0'/%3E%3C/svg%3E"), "#", "%23");

[_variables.scss]: https://github.com/tabler/tabler/blob/master/src/assets/scss/_variables.scss

**Comment by devsi** [comment]
Second this. I've had to retrofit `background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 5'%3E%3Cpath fill='%23999' d='M0 0L10 0L5 5L0 0'/%3E%3C/svg%3E");` in to a custom scss file to fix the problem.

**Comment by mohe2015** [comment]
> Since Chrome 72, `#` in data uris are invalid.
> 
> Would you consider changing the line below to escape the character in [_variables.scss](https://github.com/tabler/tabler/blob/master/src/assets/scss/_variables.scss)
> 
> from:
> 
> > $custom-select-indicator: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 5'%3E%3Cpath fill='#{$custom-select-indicator-color}' d='M0 0L10 0L5 5L0 0'/%3E%3C/svg%3E");
> 
> to:
> 
> > $custom-select-indicator: str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 5'%3E%3Cpath fill='#{$custom-select-indicator-color}' d='M0 0L10 0L5 5L0 0'/%3E%3C/svg%3E"), "#", "%23");

If doing something like that why not something like: https://gist.github.com/B-iggy/14da053d2cebf92e1930
that would make the svg more readable.

**Comment by devsi** [comment]
Hi all, was this closed because fixed?

**Comment by dsznajder** [comment]
@devsi Sorry, I've forgot to label it. We will handle this in `v1` version, but we have other task on it -> Web compatibility, so definitely will be fixed :)
