### ISSUE TITLE
请问dist文件夹里的文件是什么时候生成的？

### ISSUE THREAD

**Issue by li10217** [tabler/tabler#254]
当我运行npm run serve 之后，并没有生成dist里的文件。

我不需要预览，我只需要最终文件，所以我想删除"&& npm-run-all --parallel gulp-watch jekyll-serve"

"serve": "gulp build && npm-run-all --parallel gulp-watch jekyll-serve", =>
"serve": "gulp build"

但是这样只是重新生成了src/assets/css下的文件。

我想知道src/*.html是怎么变成dist/*.html?

**Comment by Eliepse** [comment]
你好，
为了问个问题，你要说英语。这里没有人听懂中文。可以翻译吗？
我不知道怎么帮你。再告诉我们你得麻烦（说英文）。

I think this issue can be closed. 
I indicated this person that he must speek English in order to hope any help.
