### ISSUE TITLE
Copyright licence

### ISSUE THREAD

**Issue by mhcifci** [tabler/tabler#256]
Please check this https://sloop.kampungdev.com/

**Comment by mhcifci** [comment]
https://www.codester.com/items/10793/sloop-bootstrap-4-admin-dashboard-template

**Comment by Jeckerson** [comment]
Well, its easier to write to codester support - https://support.codester.com/hc/en-us/requests/new about current situation...

**Comment by ahmetcangir** [comment]
Is not it allowed with a MIT licensed software to sell on commercial platforms? Just I want to clarify it.

**Comment by Jeckerson** [comment]
`A copy of the license and copyright notice must be included with the software.`

https://github.com/tabler/tabler/blob/dev/LICENSE

**Comment by mhcifci** [comment]
I'm not selling just saw there and wanted to ask is it right?

**Comment by kevinpapst** [comment]
What about opening an issue here? https://github.com/KampungDev/Sloop-UI

The LICENSE file is definitely not included in the repo. @codecalm

**Comment by tuyennguyen2906** [comment]
Hello 


Can I use this template for my PHP scripts and sell my script another clients?

**Comment by Jeckerson** [comment]
@tuyennguyen2906 Check license page

`This software and derivatives may be used for commercial purposes.`

https://github.com/tabler/tabler/blob/dev/LICENSE

**Comment by tuyennguyen2906** [comment]
@Jeckerson  thank you for your answer. I intend to change many things in HTML, CSS for my PHP script  and then sell my script to another clients. But i can remove the copyright in the footer page like this image: http://prntscr.com/n2425j and then change to My PHP project name. 
i also include the license file in source code. 

Please answer and tell your mind. Thanks

**Comment by ahmetcangir** [comment]
[MIT license](https://github.com/tabler/tabler/blob/dev/LICENSE) says that: 
1. Do whatever you want
2. But the license file will stay in the project folder. 

That means; MIT licensed parts will forever remain MIT licensed.

So, You are free to remove links or anything, provided that the license file stays there.

Note: If I am wrong, please someone correct it. Thanks 😊
