### ISSUE TITLE
HTML Table Filter

### ISSUE THREAD

**Issue by devjunior91** [tabler/tabler#257]
Hi guys, 

I’m new to development and was wondering if anyone can assist with this. I have a html table and I want to filter the table automatically to display certain rows based on a value. 

E.g. I only want to display rows where the word “volunteer” is present and hide everything else. 

Thanks

**Comment by CoderSquirrel** [comment]
h @devjunior91 you are using any js framework?
Cause it can depend on the framework you are using to render the content.
If you use simple html to render (eg. `<table><tr><td>content</td><td>value</td></tr></table>`) you can try @w3c exemple https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_filter_table
