### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by KiarashS** [tabler/tabler#26]

**Comment by codecalm** [comment]
good idea! thanks @KiarashS

**Comment by codecalm** [comment]
@KiarashS I've made a sample RTL mode page:
https://tabler.github.io/tabler/rtl.html

What do you think about it?

**Comment by KiarashS** [comment]
@codecalm Very thanks. 

There are some issues with position of dropdowns! 

![1](https://user-images.githubusercontent.com/1054134/38472244-74f7863c-3b92-11e8-82b1-2a144a0a0a6a.JPG)
![2](https://user-images.githubusercontent.com/1054134/38472245-75329416-3b92-11e8-9c88-98307a8b9ddf.JPG)
![3](https://user-images.githubusercontent.com/1054134/38472246-756d42b4-3b92-11e8-8589-4be971bcfd1e.JPG)

**Comment by MahdiMajidzadeh** [comment]
I make a pr for rtl https://github.com/tabler/tabler/pull/356

**Comment by FreexD** [comment]
RTL is available in @tabler/core `1.0.0-alpha.13` - https://preview.tabler.io/layout-rtl.html . I'm closing this issue ;)
