### ISSUE TITLE
Tabler Sponsorship - project maintenance offer

### ISSUE THREAD

**Issue by ollym** [tabler/tabler#260]
Hi @codecalm, we use tabler heavily at ventrata.com and it's become the main UI framework for our dashboard which is being actively updated and maintained by our whole front-end team.

One of our major concerns is the lack of activity within the core of the project, and I wanted to offer if we could sponsor the maintenance (either funding the project, or providing dev time).

I appreciate you're busy with new jobs etc. If you'd rather discuss this in private please reach out:
oliver@ventrata.com

Thanks

**Comment by codecalm** [comment]
@ollym I've send you email

**Comment by jonthomp** [comment]
@ollym if you could let us all know the outcome of this it would be great, I'm sure there are a few people here waiting to find out about the future of the project and I know some have unfortunately moved away from the Tabler altogether because of exactly this :(
