### ISSUE TITLE
Need To Fix Issue OF require.min.js while using in codeigniter framawork in PHP 

### ISSUE THREAD

**Issue by rusha29** [tabler/tabler#266]
![issue](https://user-images.githubusercontent.com/45932696/54977826-7c5a7c80-4fc4-11e9-96d8-7c92d459279d.png)
I have issue in this theme i need open an modal box for confirmation. it works on well on other page but when i pass some value in url then it shows require.min.js error. I am using this theme in codeigniter 3.0

**Comment by Clivern** [comment]
it is hard to expect the fix but it is clear that jQuery path is wrong (404 not found), it should be absolute i guess `/assets/js/....`

**Comment by rusha29** [comment]
Actually path is like /assests/js/...

**Comment by dsznajder** [comment]
@rusha29 	We dropped require.js in `v1` :)
