### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by frederikhors** [tabler/tabler#271]
Is there a changelog?

What changes from 0.0.32 to 0.0.34/35?

**Comment by dsznajder** [comment]
@frederikhors Unfortunately we can't actually track them but, new documentation will clarify every element that you are probably using in your project :)

**Comment by FreexD** [comment]
https://preview.tabler.io/changelog.html - we're now experimenting with documenting changelogs for 1.0 beta releases. From 1.0 major onwards the changelogs should be tracked consistently.
