### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by mfuentesg** [tabler/tabler#272]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/tabler-ui) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by dsznajder** [comment]
@mfuentesg We reduced everything from build now and I'm currently working on CDN's deploy :) Thanks for issue!

**Comment by FreexD** [comment]
Bundle size has been reduced drastically by now: https://bundlephobia.com/result?p=@tabler/core@1.0.0-alpha.12. We are actively working on removing unneded stuff even further. 

Tabler is now available via CDN - https://preview.tabler.io/docs/usage.html.

I'm closing this issue ;)
