### ISSUE TITLE
datatables extensions

### ISSUE THREAD

**Issue by Hanysamy25** [tabler/tabler#282]
I can't add datatables extensions like print buttons please how to configure it

**Comment by Tairau** [comment]
https://datatables.net/extensions/buttons/examples/print/simple

**Comment by ViKingQ** [comment]
I need the datatables extensions like 'datatables.responsive', but I don't know how to configure it via requirejs

**Comment by ViKingQ** [comment]
> https://datatables.net/extensions/buttons/examples/print/simple

How to configue it via requirejs, please
