### ISSUE TITLE
I want vertical layout for menu

### ISSUE THREAD

**Issue by saileshkush95** [tabler/tabler#288]
Different layout for menu like vertical

**Comment by codecalm** [comment]
in version 1.0 we'll publish sidebar navigation

![Screenshot 2019-06-07 at 16 06 11](https://user-images.githubusercontent.com/1282324/59109919-3fa0ef00-893e-11e9-9af4-93d7187d5e37.png)

**Comment by saileshkush95** [comment]
Thanks for your work

**Comment by taewookim** [comment]
hi. Is the vertical layout ready?

**Comment by GerryGe** [comment]
@codecalm How to add a toggle button in vertical layout to toggle sidebar collapse or expand? Thanks.

**Comment by behalp** [comment]
> @codecalm How to add a toggle button in vertical layout to toggle sidebar collapse or expand? Thanks.

need this function as well
