### ISSUE TITLE
License question about specific project

### ISSUE THREAD

**Issue by cangir** [tabler/tabler#292]
I used [tabler](https://github.com/tabler/tabler) in one of my projects and want to use it also in future projects. I want to be sure if there is a license problem. Could someone kindly check if there is a license problem? I have credited [tabler](https://github.com/tabler/tabler) and other vendors in the readme file.

**My main problem is:** I want to use some _scss files and js files of tabler-ui and other _scss and js files from other MIT licensed vendors. As end product, I will exclude/include some parts of tabler-ui and create a new UI according my needs. There will be one css and one js file for my themes. So do I have to include license link in every part of my UI or is it enough as I did in the credits link below.

Here is the project: [https://github.com/adraclub/adraclub.github.io](https://github.com/adraclub/adraclub.github.io)

and credits link is here: [Credits](https://github.com/adraclub/adraclub.github.io#credits)

I appreciate any reply.

**Comment by AbbyJanke** [comment]
https://github.com/tabler/tabler/blob/master/LICENSE

**Comment by twf-nikhila** [comment]
It uses MIT license, you're fine to use it.
