### ISSUE TITLE
Invoice page

### ISSUE THREAD

**Issue by madaovh** [tabler/tabler#294]
Hello,
it would be interesting to see an "Invoice" page in the theme,
Any plan to add it?
Thank you.

**Comment by codecalm** [comment]
done: https://preview.tabler.io/invoice.html :)

**Comment by keskinonur** [comment]
Last column is overflowing in mobile layout in beta 20. 

![image](https://github.com/tabler/tabler/assets/9061586/3ba4419a-24e4-4337-adbe-69296842901c)
