### ISSUE TITLE
Add new braches

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler#295]
I think need add branches: "v2 master", "v2 develop" and tag "v2" for issue/pr.

**Comment by dsznajder** [comment]
@WinterSilence We did not release `v1` yet! :D I'm pretty sure that `tags` are enough for people to download specific version. For future, we will handle it problably the same as now.

**Comment by WinterSilence** [comment]
@dsznajder I'm wrongly explained: you adds new PRs to `dev` branch, but some PRs with fixes/updates are relevant to `master` branch too. There are many differences between branches, therefore adding this PRs to both branches is sometimes problematic. Maybe create an intermediate branch (`v2` > `dev 0.4`) containing only fixes for `master` branch and updates of vendor libraries?
