### ISSUE TITLE
SCSS plugins compilation

### ISSUE THREAD

**Issue by codecalm** [tabler/tabler#296]
We need to compile tabler core (`tabler.scss`) and all tabler scss plugins like `tabler-*.scss`. 

All files like `.min.css`, `.min.css.map`, `css.map`, etc. also should be generated.

**Comment by dsznajder** [comment]
@codecalm I'm pretty sure that it's already done, but I will check it!

**Comment by dsznajder** [comment]
@codecalm They need to be compiled separatelly, but command is added and if next one will appear you need only copy add `css-compile-<name_of_plugin>` and `css-minify-<name_of_plugin>` with path.

PR is ready :)

**Comment by codecalm** [comment]
I think that we need to build plugins separately, like `tabler-charts`, `tabler-forms`, etc

**Comment by dsznajder** [comment]
@codecalm Yes, I've added a commands which will imitate next plugins when they appear :)

**Comment by codecalm** [comment]
okay, thanks

**Comment by codecalm** [comment]
done
