### ISSUE TITLE
Demo for dev branch

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler#299]
The `dev` branch has many differences with the `master` branch. Maybe create `dev-preview.tabler.io` for `dev` branch?

**Comment by dsznajder** [comment]
@WinterSilence Soon :) We need to be sure that everything that we are working on is working and looks in way that we wanted :) Just stay tuned :)

**Comment by codecalm** [comment]
https://preview-dev.tabler.io/ there will be dev branch
