### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Wipsly** [tabler/tabler#3]
Hi,

it would be awesome if you could write a documentation how to install this template. 

Thanks

**Comment by codecalm** [comment]
Hi Wipsly,
thanks for your feedback. I'm working on documentation, in a couple of days should be live.

**Comment by codecalm** [comment]
@Wipsly I've created few steps in README.md, co you can test app locally.
Check it out: https://github.com/tabler/tabler#getting-started

Any feedback is welcome ;)

**Comment by pajtai** [comment]
@codecalm how do you customize the admin? add / edit components?
