### ISSUE TITLE
Need fix package.json (dev branch, Windows)

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler#301]
Errors in strings:
~~~
"html-watch": "JEKYLL_ENV=development bundle exec jekyll build --watch",
"html-build": "JEKYLL_ENV=production bundle exec jekyll build",
"css-minify": "for i in dist/css/tabler*.css;do echo $i; N=`echo $i | sed -e 's/^dist\\/css\\///g' | sed -e 's/\\\\.css//g'`; echo $N; cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/$N.min.css dist/css/$N.css; done",
~~~
I fix "html-watch", "html-build", but cant fix problems with `sed` in "css-minify":
~~~
"html-watch": "set JEKYLL_ENV=development bundle exec jekyll build --watch",
"html-build": "set JEKYLL_ENV=production bundle exec jekyll build",
"css-minify": "for %i in (dist/css/tabler*.css);do echo %i;set N=`echo %i | sed -e 's/^dist\\/css\\///g' | sed -e 's/\\\\.css/g'`;echo $N;cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/$N.min.css dist/css/$N.css;done",
~~~

**Comment by codecalm** [comment]
@dsznajder we must replace `sed` with different app which works on windows

**Comment by WinterSilence** [comment]
@codecalm  sed work on Windows, i think problem in syntax. As u can see for/set too have other syntax. Why u dont use jekyll for this? [sass converter](https://github.com/jekyll/jekyll-sass-converter) +[html/css/js minifier](https://github.com/digitalsparky/jekyll-minifier)

**Comment by dsznajder** [comment]
@WinterSilence What's the problem with sed? I can't check it as I do not have Windows on my own for now. Could you share some error stack that you have?

**Comment by WinterSilence** [comment]
@dsznajder 
~~~
> rm -rf dist && mkdir dist && mkdir dist/css && mkdir dist/js
Error in command syntax.
~~~
fix: `rm` to `rmdir`
~~~
> rmdir -rf dist && mkdir dist && mkdir dist/css && mkdir dist/js
Cannot find the specified file.
~~~
oook, lets try `mkdir dist && cd dist && mkdir css && mkdir js`
~~~
~~~
 JEKYLL_ENV = development bundle exec jekyll build --watch
"JEKYLL_ENV" is not internal or external
command, executable program or batch file.
~~~
Bored... next fix
~~~
"html-watch": "set JEKYLL_ENV=development bundle exec jekyll build --watch",
"html-build": "set JEKYLL_ENV=production bundle exec jekyll build",
~~~
and what i see? White page in browser and errors in console
~~~
23:02:59.272 Content Security Policy: Page parameters have blocked the download of the resource inline («default-src»).
~~~
I say as self: ok, I'm Russian - we don't give up at beginning war :) and run `npm run build`
~~~
> for i in dist/css/tabler*.css;do echo $i; N=`echo $i | sed -e 's/^dist\/css\///g' | sed -e 's/\\.css//g'`; echo $N; cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/$N.min.css dist/css/$N.css; done
An unexpected occurrence: i.
~~~
Here I began to study sed manual - until then I'm use only php/ruby for scripts. i remove part wit sed and see other error and fix it
~~~
"for %i in (dist/css/tabler*.css);do echo %i; set N=`echo %i | sed -e 's/^dist\\/css\\///g' | sed -e 's/\\\\.css//g'`; echo $N; cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/$N.min.css dist/css/$N.css; done"
~~~
And now return to error with
~~~
$ echo tabler.css; set N=`echo tabler.css   | sed -e 's/dist\/css\///g'   | sed -e 's/\\.css//g'`; echo $N; cleancss --level 1 --format breakWith=lf --source-map --source-map-inline-sources --output dist/css/$N.min.css dist/css/$N.css; done
sed: -e expression # 1, symbol 11: unknown modifier to `s'
~~~
P.S. Maybe u learn `TravisCI`? loco can help u)))

**Comment by WinterSilence** [comment]
@dsznajder #320 fixed any problems
