### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by lailton** [tabler/tabler#304]
I am trying to compile without success.

MacBook:tabler lailton$ npm run serve
npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lailton/.npm/_logs/2019-07-10T21_02_05_324Z-debug.log
MacBook:tabler lailton$ cat /Users/lailton/.npm/_logs/2019-07-10T21_02_05_324Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'serve' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose stack Error: missing script: serve
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /Users/lailton/Repositories/tabler
6 verbose Darwin 18.6.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
8 verbose node v10.15.3
9 verbose npm  v6.4.1
10 error missing script: serve
11 verbose exit [ 1, true ]
MacBook:tabler lailton$

**Comment by codecalm** [comment]
@lailton try `npm run start` instead of `serve`

**Comment by lailton** [comment]
Hi @codecalm,

Thanks for reply.

If I do it, it open but look like something was not complete.
attached screenshot
<img width="1670" alt="Screen Shot 2019-07-11 at 11 05 46" src="https://user-images.githubusercontent.com/39895255/61057645-1acfe980-a3cc-11e9-9198-dafab4f4528c.png">
<img width="788" alt="Screen Shot 2019-07-11 at 11 05 31" src="https://user-images.githubusercontent.com/39895255/61057653-1e637080-a3cc-11e9-8919-8b65e8ae4fe3.png">

 results:

**Comment by codecalm** [comment]
which branch?

**Comment by lailton** [comment]
I am trying from the branch DEV

I have tested now the branch dev-layout-manager and master and your command works.
so I think that it is isolated only on DEV branch.

**Comment by codecalm** [comment]
it looks like you dont have the newest version, this screen looks like ~2 months ago

**Comment by lailton** [comment]
I think that I have.
I did a git fetch --all

so I think that I have everything, it say updated.

**Comment by codecalm** [comment]
git pull download the newest version

**Comment by lailton** [comment]
@codecalm,

I have deleted all files and started from scratch.

now after all commands called.

git clone https://github.com/tabler/tabler.git
cd tabler
npm install
gem install bundler
bundle install

and finally:

npm run start

> 
> > tabler-ui@1.0.0 start /Users/lailton/Repositories/tabler
> > npm-run-all --parallel browsersync watch html-watch
> 
> 
> > tabler-ui@1.0.0 browsersync /Users/lailton/Repositories/tabler
> > node build/browsersync.js
> 
> 
> > tabler-ui@1.0.0 watch /Users/lailton/Repositories/tabler
> > npm-run-all --parallel watch-*
> 
> 
> > tabler-ui@1.0.0 html-watch /Users/lailton/Repositories/tabler
> > JEKYLL_ENV=development bundle exec jekyll build --watch
> 
> 
> > tabler-ui@1.0.0 watch-css /Users/lailton/Repositories/tabler
> > nodemon --watch scss/ --ext scss --exec "npm run css-main"
> 
> 
> > tabler-ui@1.0.0 watch-js /Users/lailton/Repositories/tabler
> > nodemon --watch js/ --ext js --exec "npm run js-compile-standalone"
> 
> [Browsersync] Access URLs:
>  --------------------------------------
>        Local: http://localhost:4567
>     External: http://192.168.25.88:4567
>  --------------------------------------
>           UI: http://localhost:3001
>  UI External: http://localhost:3001
>  --------------------------------------
> [Browsersync] Serving files from: ./
> [Browsersync] Watching files...
> Configuration file: /Users/lailton/Repositories/tabler/_config.yml
>             Source: pages
>        Destination: tmp
>  Incremental build: disabled. Enable with --incremental
>       Generating...
> [nodemon] 1.19.1
> [nodemon] 1.19.1
> [nodemon] to restart at any time, enter `rs`
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: /Users/lailton/Repositories/tabler/js/**/*
> [nodemon] watching: /Users/lailton/Repositories/tabler/scss/**/*
> [nodemon] starting `npm run js-compile-standalone`
> [nodemon] starting `npm run css-main`
> 
> > tabler-ui@1.0.0 css-main /Users/lailton/Repositories/tabler
> > npm-run-all css-compile css-prefix
> 
> 
> > tabler-ui@1.0.0 js-compile-standalone /Users/lailton/Repositories/tabler
> > rollup --environment BUNDLE:false --config build/rollup.config.js --sourcemap
> 
> 
> /Users/lailton/Repositories/tabler/js/tabler.js → dist/js/tabler.js...
> 
> > tabler-ui@1.0.0 css-compile /Users/lailton/Repositories/tabler
> > node build/scss-compile.js
> 
> { [Error: ENOENT: no such file or directory, open 'dist/css/tabler-charts.css']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'dist/css/tabler-charts.css' }
> { [Error: ENOENT: no such file or directory, open 'dist/css/tabler-charts.css.map']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'dist/css/tabler-charts.css.map' }
> { [Error: ENOENT: no such file or directory, open 'dist/css/tabler-flags.css']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'dist/css/tabler-flags.css' }
> { [Error: ENOENT: no such file or directory, open 'dist/css/tabler-flags.css.map']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'dist/css/tabler-flags.css.map' }
> created dist/js/tabler.js in 401ms
> [nodemon] clean exit - waiting for changes before restart
> { [Error: ENOENT: no such file or directory, open 'dist/css/tabler.css']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'dist/css/tabler.css' }
> { [Error: ENOENT: no such file or directory, open 'dist/css/tabler.css.map']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'dist/css/tabler.css.map' }
> [Browsersync] Reloading Browsers...
> 
> > tabler-ui@1.0.0 css-prefix /Users/lailton/Repositories/tabler
> > postcss --config build/postcss.config.js --replace "dist/css/*.css" "!dist/css/*.min.css"
> 
> Input Error: You must pass a valid list of files to parse
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! tabler-ui@1.0.0 css-prefix: `postcss --config build/postcss.config.js --replace "dist/css/*.css" "!dist/css/*.min.css"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the tabler-ui@1.0.0 css-prefix script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/lailton/.npm/_logs/2019-07-11T23_29_08_052Z-debug.log
> ERROR: "css-prefix" exited with 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! tabler-ui@1.0.0 css-main: `npm-run-all css-compile css-prefix`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the tabler-ui@1.0.0 css-main script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/lailton/.npm/_logs/2019-07-11T23_29_08_079Z-debug.log
> [nodemon] app crashed - waiting for file changes before starting...
>                     done in 5.093 seconds.
>  Auto-regeneration: enabled for 'pages'
> [Browsersync] Reloading Browsers... (buffered 83 events)
> ^C                    Halting auto-regeneration.
>                     Halting auto-regeneration.
> 
<img width="1680" alt="Screen Shot 2019-07-11 at 20 28 43" src="https://user-images.githubusercontent.com/39895255/61092076-1e3e9180-a41b-11e9-9185-69bb2ab55acf.png">
<img width="1680" alt="Screen Shot 2019-07-11 at 20 33 28" src="https://user-images.githubusercontent.com/39895255/61092087-2a2a5380-a41b-11e9-8caa-58bea9542ac4.png">

**Comment by codecalm** [comment]
@lailton try now :)

**Comment by lailton** [comment]
@codecalm,

Excellent! now it is working ok.
Thank you and congratulation for the amazing work!
