### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by ghost** [tabler/tabler#307]
I found two thing on the dark theme that should be changed.

the mouse over ( to the links ) make the text dissapear.

and the Toast message in dark mode the content color is not good. maybe you should change it.

Thanks
<img width="343" alt="Screen Shot 2019-07-12 at 14 31 57" src="https://user-images.githubusercontent.com/39895255/61147322-7aa0c000-a4b2-11e9-9b89-e1eeaeb39d90.png">
<img width="583" alt="Screen Shot 2019-07-12 at 14 32 08" src="https://user-images.githubusercontent.com/39895255/61147324-7aa0c000-a4b2-11e9-8d21-95d90d94e7d0.png">

**Comment by zilveer** [comment]
@ghost where can I test the darkmode in the demo page ? Also I can see a side bar on your screenshot which isn't in the demo either ?

Regards

**Comment by MelvinManni** [comment]
Friendly ping @ghost!, has the issues been fixed ? if not i will love to work on it.

**Comment by mohe2015** [comment]
> Friendly ping @ghost!, has the issues been fixed ? if not i will love to work on it.

I don't know whether the issues have been fixed but @ghost is a deleted user as you can see from [their user page](https://github.com/ghost)

**Comment by codecalm** [comment]
I'm working hardly on Dark Mode. This is how it works at this moment. Still need work, but it's useful at this moment. Tommorow I will try to push it to main branch.

![localhost_3001_tmp-layout html (1)](https://user-images.githubusercontent.com/1282324/73691794-5832f600-46d3-11ea-866e-7fbc32ce96cb.png)

**Comment by codecalm** [comment]
Tabler will support dark mode and "auto dark mode" based on `prefers-color-scheme: dark` media

**Comment by zilveer** [comment]
@codecalm this looks promising !!!

**Comment by codecalm** [comment]
has been merged into dev branch :)
