### ISSUE TITLE
Dev documentation is not being updated

### ISSUE THREAD

**Issue by Oscarteg** [tabler/tabler#315]
The development documentation is not being updated anymore. I checked out the dev branch and can run it locally but when I try to create a build of this it doesn't reflect the dev branch.

**Comment by WinterSilence** [comment]
@Oscarteg u use Windows?

**Comment by Oscarteg** [comment]
No I tried it on mac. The steps I did was the following. 

```
git checkout dev
npm install
npm run build
```

And then I noticed that the `_site` directory is not created.

**Comment by WinterSilence** [comment]
@Oscarteg 
1. [Install Node.js](https://nodejs.org/download/), which we use to manage our dependencies.
2. Navigate to the root `/tabler` directory and run `npm install` to install our local dependencies listed in `package.json`.
2. Navigate to the root `/tabler` directory and run `npm install` to install our local dependencies listed in `package.json`.
3. [Install Ruby](https://www.ruby-lang.org/en/documentation/installation/), install [Bundler](https://bundler.io/) with `gem install bundler`, and finally run `bundle install`. This will install all Ruby dependencies, such as Jekyll and plugins.
3. [Install Ruby](https://ruby-lang.org/en/documentation/installation/), recommended version is [2.5.5](https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.5.tar.gz).
4. [Install Bundler](https://bundler.io) with `gem install bundler`, and finally run `bundle install`. This will install all Ruby dependencies, such as [Jekyll and plugins](https://jekyllrb.com).

**Comment by WinterSilence** [comment]
@Oscarteg > And then I noticed that the _site directory is not created.
`dev` create files in [/tmp](https://github.com/tabler/tabler/blob/dev/_config.yml#L2)

**Comment by Oscarteg** [comment]
@WinterSilence I have followed those steps and it is working for the dev environment but not for a production build of the `dev` branch. The HTML files are created in `tmp` but when I try to open them them it is missing the CSS and JS dependencies. 

What I am trying to achieve is to create a production build of `dev` branch. So just the JS/CSS/HTML files to be able to host it on a static hoster.

**Comment by WinterSilence** [comment]
@Oscarteg u can use [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from)

**Comment by dvasdekis** [comment]
It would be great to have some instructions for hosting it on a static host included. It's confusing for me

**Comment by dvasdekis** [comment]
For those who got stuck with static site deploys, mine worked on Netlify with:
```
Repository: github.com/tabler/tabler
Base directory: Not set
Build command: npm build
Publish directory: demo/
```
