### ISSUE TITLE
Docs link to 401 page demo links to 104 page instead

### ISSUE THREAD

**Issue by NateRadebaugh** [tabler/tabler#32]
https://tabler.github.io/tabler/104.html should be https://tabler.github.io/tabler/401.html

**Comment by beeman** [comment]
Hey @NateRadebaugh - they content of the dist folder will be automatically generated when a new build is created, so there is no need to update all the references here as the changes should be applied automatically.

**Comment by NateRadebaugh** [comment]
@beeman  I didn't see anything incorrect in the pre-generated files, but without running

**Comment by NateRadebaugh** [comment]
OK.
