### ISSUE TITLE
Left Side Admin Menu

### ISSUE THREAD

**Issue by jaydeepakbari** [tabler/tabler#328]
How to Create a left side menu like admin panel

**Comment by alighasemzadeh** [comment]
I think it is good idea.

**Comment by codecalm** [comment]
in version 1.0 side menu will be available

![localhost_3001_index html](https://user-images.githubusercontent.com/1282324/70823705-ddd7ab00-1de0-11ea-8214-8cac316982cf.png)

**Comment by codecalm** [comment]
in folded version too

![localhost_3001_index html (4)](https://user-images.githubusercontent.com/1282324/70823749-f47e0200-1de0-11ea-80f8-7728187f97de.png)

**Comment by jaydeepakbari** [comment]
@codecalm Thanks for sharing that, it looks really handy!
