### ISSUE TITLE
How to run in a pure js (jquery, ajax) environment

### ISSUE THREAD

**Issue by neozhu** [tabler/tabler#334]
How to run in a pure js (jquery, ajax,asp.net) environment

**Comment by WinterSilence** [comment]
@neozhu rewrite nodejs? good luck))

**Comment by neozhu** [comment]
jquery client html page，no server-side

**Comment by WinterSilence** [comment]
@neozhu tell me more, what are you doing?

**Comment by neozhu** [comment]
Thank you reply, I know how to do it.
