### ISSUE TITLE
Tabler with webpack

### ISSUE THREAD

**Issue by nasirkhan** [tabler/tabler#337]
I am using webpack on a project and wanted to use Tabler there. Right now is it using the basic bootstrap along with some other plugins. 

On the demo and downloaded source  code i found that Tabler is using Require js. Is there any doc available or can you please guide meto use it wilh webpack?

**Comment by kevin-jj** [comment]
Currently, Tabler can not be  able to work with webpack. cc @codecalm @dsznajder

**Comment by jartaud** [comment]
I'm using it with Laravel Mix (Webpack wrapper)
````
package.json:
    "tabler-ui": "0.0.34"

js:
    require('tabler-ui/dist/assets/js/vendors/bootstrap.bundle.min')
    require('tabler-ui/dist/assets/js/vendors/chart.bundle.min.js')
    require('tabler-ui/dist/assets/js/vendors/circle-progress.min.js')
    require('tabler-ui/dist/assets/js/vendors/jquery-jvectormap-2.0.3.min.js')
    require('tabler-ui/dist/assets/js/vendors/jquery-jvectormap-de-merc.js')
    require('tabler-ui/dist/assets/js/vendors/jquery-jvectormap-world-mill.js')
    require('tabler-ui/dist/assets/js/vendors/jquery.sparkline.min.js')
    require('tabler-ui/dist/assets/js/vendors/jquery.tablesorter.min.js')
    require('tabler-ui/dist/assets/js/vendors/selectize.min.js')

scss:
   @import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&subset=latin-ext');

   @import '~tabler-ui/dist/assets/css/dashboard.css';
   ...
````

**Comment by kevin-jj** [comment]
using webpack instead of gulp | grunt

**Comment by twf-nikhila** [comment]
I got it working with webpack & Laravel.

Install table using npm

`npm install tabler/tabler`

in your bootstrap.js

`
window.bootstrap = require('bootstrap');
require('tabler/js/tabler.js');
`

and in app.scss

`@import '~tabler/dist/css/tabler';
@import '~tabler/dist/css/tabler-buttons';
@import '~tabler/dist/css/tabler-payments';`

**Comment by MickaelTH** [comment]
@jartaud tabler-ui is stuck at version 0.0.34, maybe it will be updated with the 1.0.0? But this is missing a lot of new improvements from 1.0.0-alpha.7

@twf-nikhila unfortunately this is no longer working, when doing so it will display:

```
ERROR in ./resources/assets/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: ENOENT: no such file or directory, open 'file:///home/.../resources/assets/sass/tabler.css.map'
```
Also this will not include the dependencies like selectize, flatpickr, nouislider, etc.

If anyone has a tip on how to implement it with Laravel Mix, that would be very helpful. Or should we just copy all the CSS and JS files manually in the public folder? :smile: 

@codecalm Thank you for this wonderful work!

**Comment by jartaud** [comment]
@MickaelTH `npm i tabler `. Try yarn if npm is stuck.

**Comment by MickaelTH** [comment]
@jartaud It installs with npm but the issue is in the webpack. What I did is add this in webpack:

`require('tabler/js/tabler.js');`

But this seems to have no effect (for example the tooltip is not working). And I just added this in my app.scss:

`@import '~tabler/dist/css/tabler.css';
@import '~tabler/dist/css/tabler-buttons';
@import '~tabler/dist/css/tabler-flags.css';
@import '~tabler/dist/css/tabler-payments.css';`

Not sure that's the correct way but it is working.

**Comment by FreexD** [comment]
Tabler could definitely use better documentation on how to set it up with webpack.

**Comment by paqstd-dev** [comment]
For me it`s worked: 

`import '@tabler/core/dist/css/tabler.min.css'`
`import '@tabler/core/dist/js/tabler.min.js'`

For example, i`m use vuejs and it is necessary paste to main.js or main.ts.

**Comment by hamsterwork** [comment]
Well, I got working configuration.

Prerequisites: Laravel 8.*, Laravel Mix 6.*

`npm install @tabler/core choices.js litepicker nouislider`

Then in resources/js/bootstrap.js:
```
window.bootstrap = require('bootstrap');

import Choices from 'choices.js';
import Litepicker from 'litepicker';
import noUiSlider from 'nouislider';

require('@tabler/core');
```

If you need only compiled tabler css, then in resources/css/app.css

`@import '~@tabler/core/dist/css/tabler.min.css';`

If you need to change something in scss files, then create folder resources/scss (if not already created) and file app.scss

```
$primary: rgb(79, 70, 229); /* or any other changes you need, in my case only change primary color */

@import "~@tabler/core/src/scss/tabler";
```

Don't forget to change webpack.mix.js in this case:
```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/scss/app.scss', 'public/css', []);
```
Then just `npm run dev`. If sass libraries for mix are not installed, you will see promt about it and after installation just run command again.

Maybe, it will help ^__^

**Comment by rjd22** [comment]
Webpack compile works well now with v2 (I've been doing it for a year). You will need to make your own config because usecases differ.
