### ISSUE TITLE
Add documentation for select lists with selectize.js

### ISSUE THREAD

**Issue by DMW007** [tabler/tabler#338]
Hi,

I'm using tabler in a project where advanced lists with icons/image are required. The [form examples](https://preview.tabler.io/form-elements.html) shows some lists with those features, but I couldn't find it in [the documentation](https://preview.tabler.io/docs/index.html). Not in [the form section](https://preview.tabler.io/docs/form-components.html) as well as other sections. 

By looking in the source code, I found out that [selectize.js](http://selectize.github.io/selectize.js/) is used. This library seems to offer some more usefull features like fetching remote data with ajax. 

Could you please add some examples and maybe also refer to selectize.js so that it's easier to find out? Think this could be helpfull to others.

**Comment by rjd22** [comment]
Since selectize is replaced with tom-select this issue is now closed
