### ISSUE TITLE
npm bootsrtap dependency

### ISSUE THREAD

**Issue by bonekost** [tabler/tabler#339]
Hi @codecalm,
first at all thank you for great job with the tabler.

I am trying to implement tabler to one of our project and I got problem when I am using tabler dev version cause there is this line in package.json:
` "bootstrap": "twbs/bootstrap#fb475e9",` 

We are using bootstrap 4.3.1 in our project and there is some missing variables.

Is it possible in next iteration to use stable version of bootsrap?

Thank you

**Comment by WinterSilence** [comment]
@bonekost bootstrap dev in tabler dev - good solution. pls, dont try use tabler dev in production - this version have [bugs](https://github.com/tabler/tabler/issues/333)
