### ISSUE TITLE
[Request] Publish as ruby gem

### ISSUE THREAD

**Issue by drale2k** [tabler/tabler#34]
It would be great to have it as a gem to easily add it to any Rails app. I think it would help adoption a lot.

**Comment by Nilpo** [comment]
Gems are intended to be written in Ruby. This isn't a Ruby project.

**Comment by codecalm** [comment]
@drale2k do you have ideas how it should work with ruby gems?

**Comment by drale2k** [comment]
@codecalm Basically it would fix the problem described in this issue https://github.com/tabler/tabler/issues/35

It would properly link assets using asset helpers in Rails.

**Comment by klaustopher** [comment]
You could also integrate [webpacker](https://github.com/rails/webpacker) into your app and include the [tabler-ui npm package](https://www.npmjs.com/package/tabler-ui) there and use this to include the UI into your application.

**Comment by drale2k** [comment]
@klaustopher Thanks i am exploring that way now. I added the tabler-ui package and trying to figure out now how (and what, since it included everything from the dist folder, including the 404.html etc) to add it to the application. 

Do you have experience with rails and can give me a nudge in the right direction?

Thanks

**Comment by klaustopher** [comment]
I don't think that you can include the HTML pages this way. But the CSS and javascript should be compiled to you and exposed based on what you define in the webpack config. You include the CSS and JS files in your regular rails template in `layouts/application.html.erb` and then you have to build the views just like you used to.

**Comment by codecalm** [comment]
with @beeman we work to publish only css and js files via npm, if you have any ideas how do it better I'm open for any suggestions :)

**Comment by drale2k** [comment]
I don't want to include the HTML files :) I was saying that they are included in the npm package installed by yarn in this case.

Basically what i have now is a node_modules folder with "tabler-ui" in it, an inside that there is the "dist" folder from tabler. 

Additionally, i have a package.json file which defines tabler

```
"dependencies": {
    "@rails/webpacker": "3.4",
    "tabler-ui": "^0.0.21"
  },
```

So far so good, what i am trying to figure out is how to include the tabler css and js files now properly into rails. This is the webpack.yml https://gist.github.com/drale2k/3aab26f31e9d374cff52815ad2dfe89a

**Comment by klaustopher** [comment]
You can configure your packs to include the files from tabler and then use the pack in your rails layout. See https://github.com/rails/webpacker#usage

**Comment by drale2k** [comment]
I got around the issue by requiring all the js libs manually inside the application.js


./app/javascript/packs/application.js
```
import 'tabler-ui/dist/assets/css/dashboard.css'
import 'tabler-ui/dist/assets/js/vendors/chart.bundle.min.js'
import 'tabler-ui/dist/assets/js/vendors/circle-progress.min.js'
import 'tabler-ui/dist/assets/js/vendors/jquery-jvectormap-2.0.3.min.js'
import 'tabler-ui/dist/assets/js/vendors/jquery-jvectormap-de-merc.js'
import 'tabler-ui/dist/assets/js/vendors/jquery-jvectormap-world-mill.js'
import 'tabler-ui/dist/assets/js/vendors/jquery.sparkline.min.js'
import 'tabler-ui/dist/assets/js/vendors/jquery.tablesorter.min.js'
import 'tabler-ui/dist/assets/js/vendors/selectize.min.js'
```

It's doesn't feel right but it works. I spent too many hours already trying to get it to work so i will leave it like this for now and wait for a better solution.

Can be closed, thanks for the help.

**Comment by paicha** [comment]
@drale2k Any updates about import tabler in webpack?

**Comment by drale2k** [comment]
@paicha I am using this gem now https://rubygems.org/gems/tabler-rubygem
