### ISSUE TITLE
W3C validation

### ISSUE THREAD

**Issue by arnaud314315** [tabler/tabler#347]
Hello,

I find tabler a great initiatives and tools to build a powerful dashboard. I think it will be good to stick w3c validation as much as possible for code best pratices ? What do you think ? 

Please see below as example warning and error messages from w3c validator for login.html
![tablerw3c](https://user-images.githubusercontent.com/35598037/64920460-90c74700-d7a7-11e9-8664-025f5d1850c8.png)

**Comment by adam314315** [comment]
Is it a local bug then or are there any automated check process for w3c validation?

**Comment by codecalm** [comment]
fixed
