### ISSUE TITLE
Request: Calendar

### ISSUE THREAD

**Issue by cjbaezilla** [tabler/tabler#348]
Hello there, first of all, thank you for the great work,

Iit's the first time im doing this so i'm sorry if this is not the right channel to do it, but it was the only one i manage to get.

Is there a possibility to add a calendar layout, for booking or schedule, please?, or could you pleas ehelp me to integrate one without losing the look and feel of your theme, its awesome!!!

thank you guys, hope you can read this sometime, bests.

**Comment by codecalm** [comment]
done
