### ISSUE TITLE
Pure html/css version?

### ISSUE THREAD

**Issue by viraladmin** [tabler/tabler#359]
Is there any way to obtain this dashboard in pure html/css without the need for everything else required to install this? I love the look of this dashboard but calling it an html dashboard is not exactly correct. HTML does not have ruby requirements.

**Comment by premedios** [comment]
I was going to take a crack at this but this thing is using jekyll. Forget it! I'm going to keep working on Gentellela non Bootstrap version!

**Comment by harshalone** [comment]
pure html/css version is required for many reasons. Is that even possible of we more to another template?

**Comment by codecalm** [comment]
version 1.0 will be available in HTML only version, we will distribute it the same  like Bootstrap (via npm, cdn, etc)

**Comment by dhaval055** [comment]
ETA on version 1.0 ?

**Comment by viraladmin** [comment]
I just ended up using wget on the demo to obtain the html/css/js. Why it requires a new version is beyond me - I just think its sad its labeled as an html dashboard when its not distributed as such. Clearly i am not alone in this thought.

**Comment by codecalm** [comment]
@viraladmin the newest version of Tabler is build in 90% only with html and css, but a lot of features require JS to use. In v1 external libraries are not required excerpt bootstrap core. I try to replace JS libraries to CSS, but sometimes it's not possible.

**Comment by stephenlapointe** [comment]
@codecalm Thanks, Pawel, for your work on this library. This ticket and others allude to version 1 having CDN hosting. Services like cdnjs.com and jsdelivr.com are referenced. Do you know which CDN(s) you will use?

**Comment by viraladmin** [comment]
@codecalm If his works pure html than the installation instructions should be updated to reflect this instead of claiming ruby is a requirement. 

@stephenlapointe  I was not alluding to cdn hosting - I was alluding to requirements that are listed to install "pure html" - pure html has no requirements except a browser.

**Comment by codecalm** [comment]
@stephenlapointe I want to serve tabler via cdn, but we must release v1.0 firstly. I think that during one month we publish alpha version

**Comment by FreexD** [comment]
@viraladmin thanks for your suggestion! Tabler could definitelly need a better documentation! We'll try to polish that until version 1.0.0 is released :)

**Comment by Matt-Yorkley** [comment]
This issue can be closed now, right? There's an npm package and a CDN. :slightly_smiling_face:
