### ISSUE TITLE
RTL SCSS file not exit in npm version

### ISSUE THREAD

**Issue by ShirazCoders** [tabler/tabler#362]
Hello,
I try `npm i tabler-ui` but I can't find _rtl.scss file.

**Comment by permanaj** [comment]
`tabler-ui` last publish was 2019 April, so I think it is old version. Try to use `tabler`. Example: `npm i tabler`

**Comment by codecalm** [comment]
with version 1.0 we will move `tabler-ui` to `tabler` package

**Comment by codecalm** [comment]
duplicated #26
