### ISSUE TITLE
There are more than two genders

### ISSUE THREAD

**Issue by jamiebuilds** [tabler/tabler#37]
Only two binary genders are presented as options:

<img width="219" alt="screen shot 2018-04-03 at 1 20 15 pm" src="https://user-images.githubusercontent.com/952783/38273895-f9cc1f4e-3741-11e8-951e-4cfe8d334847.png">

Here is the relevant code:

https://github.com/tabler/tabler/blob/568950f0a4a62ed7b6c50da7365047ca439e185d/src/_includes/cards/form-all-elements.html#L175-L184

Allowing a third option along with a input would be more inclusive:

<img width="394" alt="screen shot 2018-04-03 at 1 34 05 pm" src="https://user-images.githubusercontent.com/952783/38274466-b5b211e0-3743-11e8-87b4-cb3aa068538c.png">

> **Note:** I used the `fe fe-more-horizontal` icon

This tends to be represented in data as:

```js
{
  gender: 'male' | 'female' | 'unspecified',
  genderTitle: string | null,
}
```

Which can be presented as:

```js
let genderStr = user.genderTitle || user.gender
```

If you are using pronouns in your content, a good way to handle it is:

```js
const PRONOUNS = {
  male: 'he',
  female: 'she',
  unspecified: 'they',
};

let pronoun = PRONOUNS[user.gender];
```

By making this change, you set a good example for the community

**Comment by Nilpo** [comment]
Fork it and add it. That's the beauty of Github.

**Comment by jamiebuilds** [comment]
I opened an issue and am waiting for a response from the maintainer. That's the beauty of GitHub.

**Comment by LasseRafn** [comment]
Very nice idea 👍

**Comment by codecalm** [comment]
@jamiebuilds, @LasseRafn  you are crazy guys, I'm open for any ideas ;)

**Comment by LasseRafn** [comment]
I might find time for such thing, but I mean if @jamiebuilds has the HTML already I think that could be implemented right away

**Comment by jamiebuilds** [comment]
I don't think you want my half-assed work in devtools. I just overwrote a bunch of inline styles

**Comment by luizbills** [comment]
these input are just examples.

**Comment by jamiebuilds** [comment]
@luizbills I recognise that, they still should be inclusive.

**Comment by beeman** [comment]
I tend to agree with @luizbills that it are just examples on how to work with `Icons input`.

That being said, I'm all for inclusivity. 

Maybe the solution should be a new `gender` form component that allows people to select their genders, and that is not based on this `Icons input`, as I'm not sure if icons are a inclusive way to select them; there might be better ways. 

Font awesome has a big selection in their set, would that work?

![image](https://user-images.githubusercontent.com/36491/38344733-c0999da4-3850-11e8-8372-e8b6ff626876.png)

**Comment by seleznevdev** [comment]
Please add my XXXL to this example

![screenshot from 2018-04-10 11-03-56](https://user-images.githubusercontent.com/5261079/38544019-e799b9f4-3cae-11e8-929c-1ed703e101f2.png)

**Comment by premedios** [comment]
I completely disagree with accommodating the transcended community with their radical left ideas! This project should not fall into that trap lest I fork this myself and take out that change on my fork!

**Comment by LasseRafn** [comment]
@seleznevdev There is a difference between gender, and size (one being discrimination and lack of understanding...). However if you feel like this is necessary, I think you should create another issue or even a pull request. In which case I think you should also add: XS, XXS, XXXS, XXXXL, XXL and so on.

Personally, I feel that the size example is broad enough, while gender is not. We don't even need a option for each gender, simply a "Other" field as suggested.

**Comment by Nilpo** [comment]
Am I the only one who remembers that this is a template? It's meant to be a starting point, not a complete working site. If you need more sizes or genders, add them to your own project. The samples don't need to account for every possible use case. They are, after all, just that--examples.

**Comment by seleznevdev** [comment]
@LasseRafn It's just the simple "Icons input" example, not the complete "Gender" field. You're free to add any icons or text fields in your project

**Comment by LasseRafn** [comment]
@seleznevdev and so are you, with your sizes. 👍

**Comment by seleznevdev** [comment]
@LasseRafn Exactly!

**Comment by Nilpo** [comment]
@LasseRafn He was being sarcastic.

**Comment by premedios** [comment]
Look guys don't turn this project into a platform for your political views. If you want to put those stuff, fork this library and create a separate branch on your fork. That way you can have the latest changes from the master and still have your own changes without everyone having to put up with your "sizes" thing or "gender" thing. That's what I'm going to do.

**Comment by premedios** [comment]
Look guys don't turn this project into a platform for your political views. If you want to put those stuff, fork this library and create a separate branch on your fork. That way you can have the latest changes from the master and still have your own changes without everyone having to put up with your "sizes" thing or "gender" thing. That's what I'm going to do.

**Comment by LasseRafn** [comment]
@nilpo I’m aware

**Comment by jamiebuilds** [comment]
Let's keep it on topic folks and keep the sarcastic comments to a minimum.

**Comment by mygithubalt** [comment]
The current binary gender options exclude people and that should be changed, no question there IMO. 

#74 removes the existing exclusion while keeping the _Icons Input_ example simple and clear. #73 is more actively inclusive of gender identity, to the detriment of the simplicity of the example.

Maybe a middle ground of having the inputs from #73 somewhere in the Form Elements page, while keeping something like #74 for the basic _Icons Input_ section?

**Comment by beeman** [comment]
The gender input element by @jamiebuilds is done in #73

**Comment by codecalm** [comment]
Sorry guys, as at the beginning, this discussion smiled me, now it seems to me that it is starting to go in the wrong direction. There is **icon input**, not **gender input**. 

If someone wants to make a reason to express their own views, please fork it to `tabler-with-gender-input` repo. All base components from tabler allows you do it.

I made tabler for people, for fun. I lose the urge to do anything when I hear such conversations. How will you use it, it's up to you.

I changed icons in **icons input** for weather icons. I'm sorry I did not include snow, hurricane and "I do not know what the weather is like" icon in it, because there were no such icons in icon-pack.

**Comment by seleznevdev** [comment]
@LasseRafn It should be definitely Nicolas Cage
