### ISSUE TITLE
Variables not found

### ISSUE THREAD

**Issue by darkalghul** [tabler/tabler#377]
I have encounter a lot of different errors when compiling the scss code here at some example:

Mixin button-size is missing argument $border-radius.

Variables not found:
$form-check-input-checked-bg-color
$form-check-input-checked-bg-image
$form-check-input-checked-bg-repeat
$form-check-input-checked-bg-position
$form-check-input-checked-border-color
$hr-height
$form-select-bg
$form-select-focus-border-color
$form-select-focus-box-shadow

I copy all of the scss folder into my project I tried to make a header and navbar, following the structure in the example but some classes like "page" does not exist.

I compare the scss code in the site and the css code generated by the scss files and is not the same at all.

**Comment by pLavrenov** [comment]
2 month ago...

**Comment by codecalm** [comment]
@darkalghul, @pLavrenov variables like `$form-check-input-checked-bg-color`, etc. are defined in bootstrap core. I don't have any errors with compilation. 
Which compiler do you use?

**Comment by pLavrenov** [comment]
"bootstrap": "twbs/bootstrap#46f086c",
