### ISSUE TITLE
Divider

### ISSUE THREAD

**Issue by kicaj** [tabler/tabler#403]
In documentation, section about Divider is signed as ended. But divider, mainly "or" word doesn't work as expect.

**Comment by codecalm** [comment]
@kicaj now should be better :)

**Comment by codecalm** [comment]
![Screenshot 2019-12-03 at 10 18 33](https://user-images.githubusercontent.com/1282324/70037090-48554380-15b6-11ea-8d4d-3883cb2a88ad.png)

**Comment by kicaj** [comment]
Yes, much better:)
