### ISSUE TITLE
Tabler Design Files

### ISSUE THREAD

**Issue by tanirmedya** [tabler/tabler#428]
Hi,

Can you share Tabler design files?

It doesn't matter (Sketch, Adobe XD, Figma)

Thank you!

**Comment by ismail0234** [comment]
I want too....

**Comment by ismail0234** [comment]
Finally, I'm selling.
Payment Method: Bitcoin.

![TenDollars](https://user-images.githubusercontent.com/20711301/73176820-74a4c080-411e-11ea-9a57-1be0ba594b13.png)

**Comment by ismail0234** [comment]
Why did you delete this?

**Comment by codecalm** [comment]
@ismail0234 Tabler is open source project, so if you can help us share your work for free. If you want sell it - no problem, but not here.

**Comment by ismail0234** [comment]
@codecalm  Okay, I got it. So why not answer for 1 month? I created this myself by trying. When I added you answered within 1 minute. Don't you care about us? Trust the community!  You can't be here without us.

Note: When will the beta end?

**Comment by codecalm** [comment]
@ismail0234 I work myself to create a Tabler, I don't have much time to create HTML version and additional design files. I'm happy to every contribution, but if you made Tabler design files share it with community. Sorry, but there is not place for selling your work.

**Comment by ismail0234** [comment]
This is another platform. I can sell it right here, right?

https://tabler.canny.io/feature-requests/p/tabler-design-files

**Comment by ismail0234** [comment]
Are you looking for a designer? Let me sell the files to you for $ 10. $ 10 for you. There was an increase in wages for other people.😂

**Comment by GeorgeGedox** [comment]
Can someone ban this guy and close this issue already? It's clear he's not helping the community in any way, shape or form.
