### ISSUE TITLE
Missing sidebar when mobile ?

### ISSUE THREAD

**Issue by zilveer** [tabler/tabler#442]
I cannot see any sidebar on the demo when using mobile Chrome 79?

See screenshot
![Screenshot_2020-01-01-09-39-41-291_com android chrome](https://user-images.githubusercontent.com/570164/71639664-e2beaa80-2c7a-11ea-9418-e5687b4677fa.jpg)

Regards

**Comment by codecalm** [comment]
fixed

**Comment by zilveer** [comment]
@codecalm it is visible now BUT sidebar is not triggered at all and is not visible when sidebar button is touched? This goes for all sidebar modes.

Regards

**Comment by codecalm** [comment]
@zilveer thank you, i'll check it

**Comment by zilveer** [comment]
@codecalm thx for a quick reply! :)

**Comment by zilveer** [comment]
Also, right sidebar looks very weird.
See screenshot
![Screenshot_2020-01-21-23-06-12-903_org mozilla firefox](https://user-images.githubusercontent.com/570164/72847349-a6430500-3ca2-11ea-91ae-b2b82ce5d3b7.jpg)

This is the same in FF and Chrome (latest versions)

**Comment by codecalm** [comment]
yeah, I just saw it
thank you

**Comment by codecalm** [comment]
fixed in https://github.com/tabler/tabler/pull/584

**Comment by zilveer** [comment]
Hi,
@codecalm is the sidebar removed.  Cannot find it now at all on the demo page?

Regards

**Comment by codecalm** [comment]
@zilveer no, it's available here: https://preview-dev.tabler.io/layout-vertical.html

**Comment by zilveer** [comment]
@codecalm 
Are you sure, attached is my view on FF 68.7 and Chrome 80 (mobile Android 10).

![Screenshot_20200419-201248_Chrome](https://user-images.githubusercontent.com/570164/79696031-6fb56000-827a-11ea-9785-4990ab154e46.jpg)

Regards

**Comment by zilveer** [comment]
@codecalm did you manage to sort out the vertical/sidebar menu ?

Regards

**Comment by zilveer** [comment]
@codecalm why is this closed?
sidebar is missing on mobile, it is a horizontal bar and not a sidebar when using smaller screens?
