### ISSUE TITLE
Payments plugin additional icons

### ISSUE THREAD

**Issue by kicaj** [tabler/tabler#455]
It will be nice to have more additional polish payment providers, like:
- Przelewy24 (przelewy24.pl)
- DotPay (dotpay.pl)
- TPay (tpay.com)
- Blik (as separate icon)
- BlueCash (bm.pl)

Now it's only PayU.

**Comment by codecalm** [comment]
@memorte03 look at this

**Comment by kicaj** [comment]
Resolved #459
