### ISSUE TITLE
Improve badges (early named as tags)

### ISSUE THREAD

**Issue by kicaj** [tabler/tabler#464]
Now, the new badges hasn't got something like `.tag-addon` class (https://preview.tabler.io/docs/tags.html#tag-addons) or `.tag-avatar` (https://preview.tabler.io/docs/tags.html#avatar-tag).

Let's say together, it's a bit poorer now:)

**Comment by kicaj** [comment]
Default `.badge` class (without class `.bg-*`) is very illegible.

**Comment by codecalm** [comment]
thank you for reporting, I'll see it
