### ISSUE TITLE
Missing text-inherit class

### ISSUE THREAD

**Issue by kicaj** [tabler/tabler#466]
There is class `text-inherit` in version 0.0.32 of tabler.

It is possible to added it in current 1.0-dev? It's was very helpfull.

**Comment by codecalm** [comment]
sure, done ;)

**Comment by kicaj** [comment]
Thanks a lot!

**Comment by kicaj** [comment]
It's was removed in alpha 4?

**Comment by codecalm** [comment]
@kicaj I've fixed it, in alpha 5 will be available

**Comment by kicaj** [comment]
Great!

**Comment by codecalm** [comment]
newest version of Bootstrap will have `.text-reset` class, so `text-inherit` shouldn't be used

**Comment by kicaj** [comment]
Okey:)
