### ISSUE TITLE
Fields disappear

### ISSUE THREAD

**Issue by shajanjp** [tabler/tabler#47]
To and Subject fields disappear after clicking body text area.
Page : https://tabler.github.io/tabler/email.html

**Comment by codecalm** [comment]
@shajanjp do you have any screenshots or video? Because I can't reproduce this bug.

**Comment by shajanjp** [comment]
@codecalm  It only happens when Grammarly browser plugin is turned on.
I'm using firefox 59.0 on ubuntu.
![Uploading Screenshot from 2018-04-04 17-12-07.png…]()

**Comment by codecalm** [comment]
thanks, it should help

**Comment by Baril27** [comment]
This to me seems like a bug in Grammarly. The `#grammarly-ghost` element is breaking outside of the `textarea` and overlapping the form elements above on render (see screenshot attached).

One solution is to wrap the `textarea` in a `.form-group`(per the Bootstrap docs) and add the class `.position-relative`. Like so:
```
<div class="form-group position-relative">
    <textarea rows="10" class="form-control"></textarea>
</div>
```
 This however feels like a hack. We would also need to do this for every textarea to mitigate the issue. Let me know thoughts on what a more stable fix could be for this issue.

![screen shot 2018-04-04 at 17 31 17](https://user-images.githubusercontent.com/1610249/38341561-0f2ac484-382e-11e8-9501-65c41c124eb9.png)
