### ISSUE TITLE
multi level menu

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#472]
please add a multi level menu...

**Comment by codecalm** [comment]
@ZeoNish i'm working on it now :)

**Comment by ZeoNish** [comment]
thx man

**Comment by Lasim** [comment]
Thank you @codecalm

**Comment by FreexD** [comment]
It's added in @tabler/core `1.0.0-alpha.13` - https://preview.tabler.io/ . I'm closing this issue.
![image](https://user-images.githubusercontent.com/7117869/99443162-b9525000-291a-11eb-83e3-562b5d80e684.png)
