### ISSUE TITLE
preview-dev bugs

### ISSUE THREAD

**Issue by eyelove** [tabler/tabler#484]
## datepicker bug

https://preview-dev.tabler.io/form-elements.html
![스크린샷 2020-02-10 오후 5 04 27](https://user-images.githubusercontent.com/286418/74131342-747ce880-4c27-11ea-9692-df2c32e4fe2a.png)

## Tags Input Multi Line AutoResize

https://preview-dev.tabler.io/form-elements.html
![스크린샷 2020-02-10 오후 5 05 28](https://user-images.githubusercontent.com/286418/74131400-91192080-4c27-11ea-9b6b-b2b5906866bb.png)

👍

**Comment by ollym** [comment]
@codecalm ^ these are still bugs on the latest build. Do you need help fixing them?

**Comment by codecalm** [comment]
i’m working on it, tommorow should be fixed
