### ISSUE TITLE
Can't navigate on mobile view.

### ISSUE THREAD

**Issue by okwudav** [tabler/tabler#516]
When it is been opened on mobile, the navigation pane tends to hide.

![responsive](https://user-images.githubusercontent.com/9608726/74879779-2a53df80-536a-11ea-84b2-ff662e20d853.jpg)

**Comment by okwudav** [comment]
@codecalm Any idea when this can be fixed?

Thank you.

**Comment by balbarak** [comment]
any update !

Thanks

**Comment by frknfndk** [comment]
Hello, 

This issue is very important, user cannot navigate from mobile phone. May you check it please?

Thank you.

Regards,
Furkan

**Comment by codecalm** [comment]
we'll be fixed in https://github.com/tabler/tabler/pull/584

**Comment by codecalm** [comment]
![Screenshot 2020-04-05 at 15 22 30](https://user-images.githubusercontent.com/1282324/78500460-c8530c00-7756-11ea-8f2a-a210c2e69d8b.png)

**Comment by codecalm** [comment]
![Screenshot 2020-04-05 at 16 03 13](https://user-images.githubusercontent.com/1282324/78500486-ff292200-7756-11ea-84e3-46f89b2afe44.png)

**Comment by frknfndk** [comment]
Thank you very much. Do you plan a release with these changes?

Regards,
Furkan

**Comment by codecalm** [comment]
yes, sure

**Comment by okwudav** [comment]
@codecalm We really can't thank you enough. I definitely will keep donating once this part is done.. Thanks once more

**Comment by okwudav** [comment]
@codecalm we really can't thank you enough. I definitely will keep donating once this part is done.. Thanks once more.

**Comment by frknfndk** [comment]
Hello @codecalm, we are planning to get live with this template and we need a release with this and #589 fix, please. 

Regards,
Furkan

**Comment by codecalm** [comment]
merged! 🎉👨‍🎨
