### ISSUE TITLE
Layout adjustment .form-check-input: checked

### ISSUE THREAD

**Issue by fernandolcardoso** [tabler/tabler#520]
Hello everyone, this is my first report here in the repository and I would like to inform you that there is a small layout problem in the .form-check-input: checked

![image](https://user-images.githubusercontent.com/16019127/74937617-27d5a200-53cb-11ea-8b82-6357106a65ab.png)

![image](https://user-images.githubusercontent.com/16019127/74937718-68cdb680-53cb-11ea-9f66-a087b81d2148.png)

When I disable "background-repeat" the layout is normalized.

![image](https://user-images.githubusercontent.com/16019127/74937770-86028500-53cb-11ea-911f-537a19973c55.png)

![image](https://user-images.githubusercontent.com/16019127/74937797-9155b080-53cb-11ea-8cc1-a85ce4b1a270.png)

Congratulations on the project

**Comment by codecalm** [comment]
fixed
