### ISSUE TITLE
Date Picker not working in dark theme

### ISSUE THREAD

**Issue by marcowira** [tabler/tabler#525]
Date picker didn't switch over to dark nicely. Hope it's just a small tweak to make it work.

![image](https://user-images.githubusercontent.com/788221/75365911-c43bf080-5872-11ea-8c3e-f5ddd773f8bd.png)

**Comment by TranDucKpop** [comment]
and
![DeepinScreenshot_select-area_20200301172010](https://user-images.githubusercontent.com/61401700/75623840-f46ff000-5be0-11ea-90e4-9076e287dd79.png)

**Comment by tranducit95** [comment]
and
![DeepinScreenshot_select-area_20200301172010](https://user-images.githubusercontent.com/26267956/75623854-11a4be80-5be1-11ea-81f3-0c5a2eb8299b.png)

**Comment by vedt69** [comment]
I'll work on the date picker issue.

**Comment by joseadame** [comment]
And..
![image](https://user-images.githubusercontent.com/1469133/77749911-25e2ac80-7023-11ea-824d-94a9027d7c40.png)

**Comment by codecalm** [comment]
I'll check it, thanks!

**Comment by marcowira** [comment]
@codecalm - are you able to fix these other elements too while you're at it?

[ ] Advanced select
[ ] Select with Avatars
[ ] Select with flags
[ ] Advanced select with validation state

![image](https://user-images.githubusercontent.com/788221/77829961-8be23900-70e2-11ea-9fce-08e4166c4f15.png)

**Comment by codecalm** [comment]
i've fixed it

**Comment by marcowira** [comment]
Thanks @codecalm - looks great!
