### ISSUE TITLE
Any plans to integrate with React/Vue?

### ISSUE THREAD

**Issue by muminoff** [tabler/tabler#53]
I am really impressed with UI's beauty. Awesome! 👍 

Do you have any plans to integrate this with SPA libraries, such as, React, Vue, etc?

**Comment by beeman** [comment]
Hey @muminoff - I'm currently working on an Angular integration [tabler/tabler-angular](https://github.com/tabler/tabler-angular). 

I'm sure @codecalm is open to more integrations, so if you're up to it feel free to get started. 

You can join the slack to discuss it :)

**Comment by Nilpo** [comment]
@muminoff You can't really make it reactive without knowing what you are building first. I'm using Vue.js. What would you like to see in terms of integration?

**Comment by muminoff** [comment]
@Nilpo When I said "integration" I meant implementing collection of React (or Vue.js) components using this UI kit. How about now, is it clear?

**Comment by muminoff** [comment]
I meant reusable components which user can install, import and use anywhere.

**Comment by beeman** [comment]
This is what I'm working on with the Angular version too.

It currently runs this 2 apps using shared components, the [demo](https://develop-tabler-angular-tabler.buddy.show/home) and the [docs](https://tabler.github.io/tabler-angular) sites.

**Comment by Nilpo** [comment]
I've started working on a Vue.js version.

**Comment by AaronCoplan** [comment]
@muminoff I've begun work on a [React port of tabler](https://github.com/AaronCoplan/tabler-react).  I've just started today so things are pretty basic at the moment but I'd love some help!

**Comment by beeman** [comment]
@Nilpo @AaronCoplan in terms of packaging the Tabler CSS/SCSS, could you shed a light on what works best for you? That way we can aim towards a generic working package in #64 .

**Comment by AaronCoplan** [comment]
@beeman For now I am doing something similar to you, I am importing the scss file or the compiled css from dist.  However, the best practice with React is to have a .css file for each React component (see [CSS FAQ](https://reactjs.org/docs/faq-styling.html) or [Style recommendations](https://reactjs.org/docs/dom-elements.html#style)).  As such, having plain CSS for each component would be nice

**Comment by beeman** [comment]
@AaronCoplan But is that also the case for global styles? Do you want to copy the Tabler CSS into the react codebase, or can you reference it?

In the Angular app I would only use the local css next to the component for overrides to the global styles. 

[Here](https://github.com/tabler/tabler/tree/dev/src/assets/scss/dashboard) is a list of the separate 'components' in the scss.

**Comment by Nilpo** [comment]
I'm basically doing something similar. In Vue, each component has it's own styling. I am putting component-specific styles there. Global CSS is loaded separately. Since it's based on Bootstrap, global styling will really be a minimum. This will also allow users to bring in the components while using their own global style.

**Comment by johnhorsema** [comment]
@Nilpo I would like to help with the Vue port. How can I get started?

**Comment by codecalm** [comment]
@johnhorsema we can create a tabler/tabler-vue repo if you want

**Comment by skmail** [comment]
What a nice UI  Many thanks to make it MIT ,  @AaronCoplan  i'd like to help with react port.

**Comment by AaronCoplan** [comment]
@skmail Currently it's located at https://github.com/AaronCoplan/tabler-react, any and all pull requests would be greatly appreciated!

**Comment by codecalm** [comment]
@AaronCoplan if you want we can create tabler/tabler-react repo for you

**Comment by jonthomp** [comment]
Just spotted this thread, I've been working on a set of React components too so will pop it up on Github shortly. I've been rebuilding the demo site from top to bottom turning everything into basic components as I go.

**Comment by AaronCoplan** [comment]
@codecalm That would be great!

**Comment by AaronCoplan** [comment]
@jonthomp I'm essentially doing the same thing - let's look into merging things together 👍 I think the biggest difference is that I am using Flow

**Comment by Nilpo** [comment]
I find the changes in #73 to be highly offensive and unnecessary as stated in #37.

I cannot, in good moral conscience, continue contributing to this project. I apologize for any inconvenience this causes.

**Comment by codecalm** [comment]
@Nilpo I'm sorry for that, I did not expect that it go in this direction.

**Comment by maracuja-juice** [comment]
@Nilpo see the new comment in #37

**Comment by Nilpo** [comment]
@codecalm I think you handled that in a very reasonable and mature manner.

@johnhorsema I am on a deadline for the next 1-2 weeks. If you're okay waiting until then, I'm happy to share what I'm working on and get you involved.

**Comment by codecalm** [comment]
thanks @Nilpo, nice to hear. Let me know if you need tabler/tabler-react repo, I can give you permissions.

**Comment by Nilpo** [comment]
@codecalm Please. I would like to keep everything in one place.

**Comment by codecalm** [comment]
@Nilpo I've send invitation

**Comment by AaronCoplan** [comment]
@Nilpo Are you working on vue or react?

**Comment by premedios** [comment]
I'm also making a react version of tabler.

**Comment by codecalm** [comment]
I've give @Nilpo admin rights to this repo.

**Comment by jonthomp** [comment]
@AaronCoplan I missed the comments before about your react version. How far along are you and how tied to using Flow are you?

**Comment by AaronCoplan** [comment]
@jonthomp At the moment I am still a bit behind you but I plan on working on it pretty intensely over the next couple days.  Unfortunately, I'd like to stick with Flow if at all possible - if that means I have to maintain my own repo then that's not the end of the world though - don't want to interfere with other peoples progress by being stubborn.

**Comment by premedios** [comment]
I'm going to work on mine. I can do a good job on it.

**Comment by jonthomp** [comment]
@AaronCoplan ha yeah I've just been hammering through as I have a project in mind I would like to use it on. I'm not anti-flow, I just didn't put it in to start with, not sure why really. What are your thoughts on mine otherwise/structurally, how would you feel teaming up on it if I spent some time adding flow? @premedios same goes for you, feels a shame us all working on separate versions?

**Comment by Nilpo** [comment]
@AaronCoplan I'm working on a Vue.js version.

@codecalm Can you make a tabler-vue repository?

**Comment by AaronCoplan** [comment]
@jonthomp Same here, I'm also building it to use in a couple of things I'm working on.  I like the structure of your project, I've actually just finished restructuring mine in a way that actually makes it a bit more similar to yours.  I'd definitely be happy to collaborate to integrate our two repositories together!

**Comment by codecalm** [comment]
done

**Comment by jonthomp** [comment]
@codecalm thanks!
@AaronCoplan how would you like to go about it, shall I just port mine over to the new tabler-react repository?

**Comment by AaronCoplan** [comment]
@jonthomp You could do that!  I think something we should decide first is whether we (and other people who will be looking at / using this) want tabler-react to use flow or not - if not then I think it would be best for you to port yours in and I'll just keep my repository separate.  However, if we want tabler-react to use flow then I think we should come up with a better plan for merging our two repos.

It might be easier/faster to continue this discussion in the Slack if you join - link is in the README of this repo.

**Comment by maracuja-juice** [comment]
That won't make it easier... especially for future users it's a lot better to have one repo with the official react components for tabler @roanvanbao

**Comment by marcrib** [comment]
For vuejs use vuestrap and create others components using in tabler (eq card)

**Comment by beeman** [comment]
@Nilpo not sure if you are still working on a Vue integration, but just as a heads-up, there are people asking for it here https://github.com/tabler/tabler-vue/issues/1 

Closing this issue as all integrations have a repo now. If not, give me or @codecalm a ping and you will get one!

**Comment by rahul2521991** [comment]
Can anyone help me out how to integrate tabler with laravel 5.7? Thank you in advance for your valuable suggestion.
