### ISSUE TITLE
Container wildcard selector class

### ISSUE THREAD

**Issue by mkhairi** [tabler/tabler#538]
seem like this selector universally apply to all class has word `container`

https://github.com/tabler/tabler/blob/4d7f77e099fa426367e86e1056fda1f1cd31242e/scss/layout/_navbar.scss#L122-L125

can we change to this?

```css
 [class^="container"] { 
 }
```

**Comment by codecalm** [comment]
fixed in https://github.com/tabler/tabler/pull/584

**Comment by zhongqf** [comment]
this happened again.

https://github.com/tabler/tabler/blob/cfe3ff1b27115c0541cea65b8e1369c9da410043/scss/layout/_navbar.scss#L282-L296

**Comment by codecalm** [comment]
done
