### ISSUE TITLE
Top navigation menu dropdown issue

### ISSUE THREAD

**Issue by nasirkhan** [tabler/tabler#539]
Dropdown part of the top navigation menu goes under the main navigation bar in the dev-preview (https://preview-dev.tabler.io/) 

![Screenshot_2020-03-06 Form elements - Tabler - Premium and Open Source dashboard template with responsive and high quality ](https://user-images.githubusercontent.com/396987/76088074-96c51480-5fe1-11ea-8d4f-f05f1e59d802.png)

**Comment by codecalm** [comment]
fixed
