### ISSUE TITLE
dev version not compatible with internet explorer 7

### ISSUE THREAD

**Issue by z0p12000** [tabler/tabler#540]
Hi,

The master version is completely compatible with internet explorer 7
->but the dev version on https://preview-dev.tabler.io/ is not compatible with internet explorer 7
    anymore.
->testing the website on internet explorer 7 is easy:
    ->install the IE Tab extenstion for chrome browser at: 
        https://chrome.google.com/webstore/detail/ie-tab/hehijbfgiekmjfkfjpbkbammjbdenadd
       ->then navigate to webpage being tested and click on the ie tab icon on chrome browser
           ->chrome renders the site in internet explorer 7 mode.

**Comment by codecalm** [comment]
we don’t support IE7
