### ISSUE TITLE
Add basic backend functionality

### ISSUE THREAD

**Issue by jarboz** [tabler/tabler#55]
Loving this, is there any plans to add backend functionality?

If not I'd love to to this for a school project.

**Comment by jarboz** [comment]
I've started taking dist, picking all the examples apart into modular php snippets that can be included/required.

Once I'm done with that I'm gonna add a database connector, making the dashboard part somewhat functional.

**Comment by Nilpo** [comment]
I'm currently building a backend for this powered by an API built on Slim.

**Comment by jarboz** [comment]
I've modularized the root example pages and some widgets. 
Added basic user functionality(register, login, logout)

**Comment by beeman** [comment]
In the Tabler Angular repo I've added an example on how to integrate with Firebase:

https://tabler-angular-fire.firebaseapp.com/

https://github.com/tabler/tabler-angular/tree/develop/apps/fire/src/app
