### ISSUE TITLE
Profile page avatar-md issue

### ISSUE THREAD

**Issue by joshi-chinmay** [tabler/tabler#56]
Hello, when I was browsing through your [demo website](https://tabler.github.io/tabler/) today. On the [profile-page](https://tabler.github.io/tabler/) I found this crunched-looking avatar.

![tabler-github-io](https://user-images.githubusercontent.com/16207311/38353056-e7872c92-38d2-11e8-899c-e6ccfbeace33.png)

I tried to look for the problem. But need to invest more time to get the right solution. What I have found right now is, `.media`-class is applying/affecting some class properties to the `.avatar` and `.avatar-md`.

**Comment by codecalm** [comment]
thanks! we fix it as soon as possible!

**Comment by ascii-dev** [comment]
Can I pick this up to work on? @codecalm

**Comment by codecalm** [comment]
@ascii-dev sure, thanks!

**Comment by codecalm** [comment]
see this PR: https://github.com/tabler/tabler/pull/54

**Comment by ascii-dev** [comment]
Seen @codecalm, Thanks! Should I work on your comment - "I read about it and I think should be better if we put .avatar into .media-object instead add margins"

**Comment by beeman** [comment]
@ascii-dev Happy to review / merge any of your PR's  that implement this!

**Comment by codecalm** [comment]
fixed
