### ISSUE TITLE
btn-secondary does not match the rest of the variants

### ISSUE THREAD

**Issue by codebykenny** [tabler/tabler#566]
I have noticed that the `btn-secondary` variant does not match the rest of the other buttons. `btn-secondary` has a gradient which gives it depth, while all other variants like `btn-primary` and `btn-warning` are flat.

It makes `btn-secondary` look out of place in comparison to the other buttons.

I do believe the gradient is better looking than the flat buttons but nonetheless I believe they should be uniform and match each other.

<img width="500px" src="https://user-images.githubusercontent.com/6720728/77779510-0484bf00-7029-11ea-9f48-9a9d79ddbacc.png" />

**Comment by codecalm** [comment]
I've opened PR for this issue: https://github.com/tabler/tabler/pull/599

**Comment by codecalm** [comment]
fixed :) thank you for your help! :)
