### ISSUE TITLE
New btn-danger seems more of a pink than a red

### ISSUE THREAD

**Issue by codebykenny** [tabler/tabler#567]
The new `btn-danger` variant in the development preview seems closer to a pink than it does to a red.

This may be a matter of taste or preference I suppose, but I do not believe the new `btn-danger` color conveys a sense of urgency. It seems closer to a "watermelon" candy color.

Old `btn-danger`:
![image](https://user-images.githubusercontent.com/6720728/77779678-44e43d00-7029-11ea-9a57-2fb08fada512.png)

New `btn-danger`
![image](https://user-images.githubusercontent.com/6720728/77779649-3d249880-7029-11ea-9a5b-e7a88cc27a3d.png)

![image](https://user-images.githubusercontent.com/6720728/77779846-7f4dda00-7029-11ea-8629-995bca4d79eb.png)

**Comment by codecalm** [comment]
fixed, thanks
