### ISSUE TITLE
Feature Request: Date Range Picker

### ISSUE THREAD

**Issue by marcowira** [tabler/tabler#570]
Hi @codecalm,

One of the challenges our team is facing is a date picker for date ranges on our dashboard. 
Would you mind considering building such a feature?

I think one of the best ones I've seen is this. Ideally just tapping on the date field would open this:  https://dribbble.com/shots/6804271-Date-Picker

There is this project on github (MIT license) that is also popular and I think has already implemented something very similar.

https://github.com/dangrossman/daterangepicker

**Comment by codecalm** [comment]
Hi @marcowira!
I wanted us it in tabler, but this library uses jQuery. And now I don't know what to do because the new Bootstrap doesn't use jQuery anymore and I'm confused that it's a good idea to use jQuery-based libraries.

**Comment by marcowira** [comment]
Makes sense @codecalm and I agree to keep it native to new Bootstrap. Would you feel comfortable using it for inspiration and instead build a your own bootstrap version of it for Tabler?

**Comment by codecalm** [comment]
sure! I'll try to make something of it :)

**Comment by marcowira** [comment]
Hi @codecalm! Any update? We're blocked on this feature and would absolutely love this.

**Comment by FreexD** [comment]
Hey @marcowira ;) we're researching datepickers that we could use for tabler. We'll be implementing this soon and definitelly for v1 ;)

**Comment by rjd22** [comment]
@codecalm  I would really recommend picking a date picker that does not need any jQuery.

Nowadays React or Vue is used often conflicting with the way jQuery works.

**Comment by FreexD** [comment]
@rjd22 @marcowira how about https://wakirin.github.io/Litepicker/ ?

**Comment by rjd22** [comment]
Looks like a good contender. It's actually quite concerning how little vanilla pickers can be found.

**Comment by FreexD** [comment]
https://wakirin.github.io/Litepicker/ is now integrated with tabler - it will be included in v1.0 :)
