### ISSUE TITLE
Dev, future request: separate elements/blocks

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler#574]
Separate components/blocks by directories:
1.1 name by main class or class prefix, ex.: `.navbar` in `/navbar`, `.card` in `/card`.
1.2 require files: 
+ `readme.html` or `readme.md` - [Jekyll page](https://jekyllrb.com/docs/pages/) contained: description, dummy template contained common classes, customization examples
+ `common.scss` - common classes, ex.: `.navbar`, `.navbar-brand`, `.navbar-nav`
+ `template.html` or `template.md` - [Liquid template](https://jekyllrb.com/docs/liquid/) includes to [pages](https://jekyllrb.com/docs/pages/)
+ `generator.js` Object to generate HTML code by settings:
~~~js
'use strict';
// %...% - placeholders
$tabler.generators.%component% = {
  label: 'Component name',
  baseUrl: null, // auto set
  settings: {
     'text':  {label: 'Text', control: 'text', value: ''},
    'checkbox':  {label: 'Checkbox', control: 'checkbox', value: false},
    'select':  {label: 'Select', control: 'select', value: 'value1',  options: {'value1': 'option 1'}}
  },
  generate() {
    return `<div class="%class% ${this.settings.%property%.value}">inner HTML</div>`;
  }
};
~~~
1.3 optional contains: 
+ `custom.scss` -  custom classes, ex.: `.navbar-primary`, `.navbar-dark`
+ `custom_*.scss` - separated customizations includes in `custom.scss`.
+ `template_*.html` or `template_*.md` - custom templates: `template_dark.md` 
+ `jquery.js` - [JQuery plugin](https://learn.jquery.com/plugins/basic-plugin-creation/)
+ `data.yml` or `data.json` - [datafile](https://jekyllrb.com/docs/datafiles/)

2. Global Tabler variable:
~~~js
$(function () {
    'use strict';
    window.$tabler = {
        settings: {},
        generators: {},
        helpers: {
            screenSize: function () {
                if (window.screen.width >= 1140) {
                    return 'xl';
                } else if (window.screen.width >= 720) {
                    return 'lg';
                } else if (window.screen.width >= 540) {
                    return 'md';
                } else if (window.screen.width >= 380) {
                    return 'sm';
                }
                return 'xs';
            },
        },
        constructor(settings = {}) {
            Object.assign(this.settings, settings);
        }
    };
});
~~~
3. `generator.js` collection

I can create JS/Jekyll/Liquid plugin(s) if needed.
Also, I can generate PHP/JS views/templates (native, Smarty, Twig, Liquid). 
I write lite PHP version for Jekyll using [cebe/markdown](https://github.com/cebe/markdown),  [kalimatas/php-liquid](https://github.com/kalimatas/php-liquid) + Smarty/Fenom, Twig/Mustache templates, [leafo/scssphp](https://github.com/leafo/scssphp) and [mrclay/minify](https://github.com/mrclay/minify) js/css

**Comment by rjd22** [comment]
Closing this since it doesn't seem relevant anymore. If you feel this is still relevant feel free to mention me.
