### ISSUE TITLE
element position/animation bug with navbar-expand

### ISSUE THREAD

**Issue by amshkv** [tabler/tabler#582]
when I open the mobile menu, the logo and menu button goes up.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23584933/78133506-35009a80-7427-11ea-931f-d3f8d6132768.gif)
[codepen](https://codepen.io/Keda37/pen/jOPJeyb)

**Comment by codecalm** [comment]
fixed in https://github.com/tabler/tabler/pull/584
