### ISSUE TITLE
Will Tabler migrate to Bootstrap 5 when it gets released? 

### ISSUE THREAD

**Issue by JayNathSF** [tabler/tabler#588]
I know it's not expected to be out for several months but wanted to see what your plans are if any.

Thanks!

**Comment by codecalm** [comment]
@JayNathSF the newest Tabler is build on Bootstrap 5 :)

**Comment by JayNathSF** [comment]
that's awesome! thanks for the quick response. so assuming no more support for IE correct?

**Comment by codecalm** [comment]
yes, Bootstrap 5 drop support to IE
