### ISSUE TITLE
Sidenav navigation position fall down to bottom

### ISSUE THREAD

**Issue by gbabook** [tabler/tabler#589]
it goes normal if delete logo element &lt;a class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal"&gt;...&lt;/a&gt;

**Comment by frknfndk** [comment]
Hello, we are planning to get live with this template and we need a release with this and mobile nav bar fix, please. 

Regards,
Furkan

**Comment by codecalm** [comment]
hi @frknfndk!
I'm working on this now :) Tommorow should be fixed

**Comment by frknfndk** [comment]
hello @codecalm , 

Thank you very much! It will be a good if you build on dev with #589 and #584

**Comment by codecalm** [comment]
merged! 🎉👨‍🎨
