### ISSUE TITLE
Undocumented components which deviate from Bootstrap

### ISSUE THREAD

**Issue by drale2k** [tabler/tabler#59]
In the demo there are fundamental classes like .page, .page-main and .header-nav which seems crucial for tabler but are not mentioned anywhere in the documentation. Is there a reason or has it just not been done yet? 

Since tabler is based on bootstrap, i was under the impression that anything not specifically documented just works with default bootstrap classes.

**Comment by codecalm** [comment]
@drale2k I made Tabler for fun and I did not expect such a big response. If you can help us with it I will be grateful :)

**Comment by drale2k** [comment]
Alright, I am glad you did :D 

As a side question, do you think it's necessary to introduce those new classes instead of using the boostrap defaults? It would make it much easier for sites which use bootstrap to switch to tabler.

**Comment by codecalm** [comment]
@drale2k I've made those structure to work with aside menu, etc. It's only plans, but tabler is ready to support it in near future.

**Comment by drale2k** [comment]
By aside menu you mean a vertical navigation on the left? That would be really useful actually

**Comment by codecalm** [comment]
yes, I had a few plans for the future and I did not make it yet through this popularity boom :)

**Comment by drale2k** [comment]
awesome :)
