### ISSUE TITLE
Drop down menus doesn't work properly in dev demo

### ISSUE THREAD

**Issue by frknfndk** [tabler/tabler#590]
Hello, 

I cloned dev branch. And in the demo, drop down menus(user dropdown in the top right e.g) doesn't work properly. You may check attached screenshot. Drop down menu shows in back. 

May you check?

Thanks.
![dropdown](https://user-images.githubusercontent.com/9401868/78721619-8ed5f880-7930-11ea-9a3d-54949f42f47a.png)

**Comment by codecalm** [comment]
I've fixed it in https://github.com/tabler/tabler/pull/584
