### ISSUE TITLE
Landing page(s) with tabler

### ISSUE THREAD

**Issue by davidokwudili** [tabler/tabler#591]
This is a humble request.

Can someone maybe help in creating a landing page with tabler, probably like the image below.
I am not good with css, so i cannot find my way around such.

This will be great.

Thank you.

![image](https://user-images.githubusercontent.com/9608726/78792001-77d2ed00-79a8-11ea-8a35-3179f0dbd5ee.png)

**Comment by pavandeore** [comment]
hey can you please send figma link for assets i would love to contribute to this project
