### ISSUE TITLE
Mobile view hamburger is missing for navigation

### ISSUE THREAD

**Issue by akhzarjaved** [tabler/tabler#592]
#### Tabler 1.0.0-alpha.4
![image](https://user-images.githubusercontent.com/50201631/78880876-77e9f000-7a6f-11ea-9f4f-d62fce61d202.png)

**Comment by frknfndk** [comment]
Hello,
@codecalm is fixing this issue and they are changing navigation completely. 

we are waiting for a release. 

@codecalm  can we get it this week? :)

Regards,
Furkan

**Comment by codecalm** [comment]
sure, tommorow should it be merged into `dev` branch

**Comment by frknfndk** [comment]
> sure, tommorow should it be merged into `dev` branch

@codecalm thank you!

**Comment by akhzarjaved** [comment]
@codecalm 
Thanks alot for your work
Loved this panel <3

**Comment by frknfndk** [comment]
> sure, tommorow should it be merged into `dev` branch

Hello @codecalm,

We are waiting for good news :)

**Comment by codecalm** [comment]
merged! 🎉👨‍🎨

**Comment by codecalm** [comment]
![localhost_3000_layout-navbar-dark html(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/1282324/79023330-5b89a880-7b80-11ea-8a54-bdfc9abcd291.png)
