### ISSUE TITLE
Preview Dev has menu closing issue on mobile

### ISSUE THREAD

**Issue by xtensions** [tabler/tabler#594]
Please see the video in tweet link below
https://twitter.com/xtensionsIn/status/1248723351981326337
There is a little delay when the menu is closed. Closing of menu is not as smooth as menu opening.

**Comment by ollym** [comment]
And this in iOS
https://twitter.com/emtei/status/1249001314731900928

It has the same effect in Chrome on desktop as well.

**Comment by codecalm** [comment]
fixed :)
