### ISSUE TITLE
z-index BUG demo dropdown

### ISSUE THREAD

**Issue by ZeoNish** [tabler/tabler#595]
![image](https://user-images.githubusercontent.com/8596319/79098708-3b6a0d00-7d6b-11ea-8aeb-e3137644cd61.png)

**Comment by amshkv** [comment]
![image](https://user-images.githubusercontent.com/23584933/79101578-7c652000-7d71-11ea-93fc-24962864bb77.png)
+ bug on overlays on sticky block

**Comment by ZeoNish** [comment]
> ![image](https://user-images.githubusercontent.com/23584933/79101578-7c652000-7d71-11ea-93fc-24962864bb77.png)
> 
> * bug on overlays on sticky block

Одни Русские >_< ... Only Russian :-)

**Comment by codecalm** [comment]
fixed,

Спасибо, я понимаю русский язык :)
