### ISSUE TITLE
modal events wont trigger.

### ISSUE THREAD

**Issue by superbyte23** [tabler/tabler#597]

**Comment by codecalm** [comment]
@superbyte23 any more info? or screenshot :)

**Comment by sparklings** [comment]
Hello, Could I toggle modal using javascript that $('#modal-info').modal('toggle')?
I met below error message,

![2020-07-15 00_25_55-Window](https://user-images.githubusercontent.com/7358584/87444594-f091b700-c631-11ea-901a-6d2069550cf1.png)

**Comment by yogasukma** [comment]
@sparklings did you find solution?

It seems Tabler didn't use modal plugin from Bootstrap, so .modal() won't work.

I personally use `$(".close").click()` to close modal.

It;s not very ideal i knew, but can't find  a way to close modal by JS code.

**Comment by dimitrist19** [comment]
Anyone got any idea on how to launch modal on page load?

**Comment by josiahke** [comment]
```
$('#modal-new-payee').on('show.bs.modal', function (e) {
            console.log(e);
 })
```

it does not log anything on the console

`<a class="dropdown-item" href="#" data-toggle="modal" data-target="#modal-new-payee" data-url="http://localhost:8600/edit/payees/1" data-name="test" data-phone="+254710000000" data-emp_no="test" data-id_number="test" data-gender="male" data-dob="1996-01-12">Edit</a>`

I want to able to parse the "data" to the modal

usually I do this 

```
<script>
        $('#edit-Pay-bill').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            $('#editPaybillForm').attr('action', button.data('url'));
            $('#name').val(button.data('name'));
            $('#number').val(button.data('number'));
        })
    </script>
```

**Comment by maciejbuchert** [comment]
Hey @codecalm. Did you reproduce the issue?

**Comment by DoriHp** [comment]
Anyone can launch modal with js?

**Comment by JosiaNganga** [comment]
i replaced the bootstrap js file with one from bootstrap but now am having an issue with menus, they are not closing when you click away

**Comment by codecalm** [comment]
fixed :)

**Comment by kikikiblue** [comment]
'bootstrap.bundle.js' file should be included if I want to use modal js function. right?
It it is right, please include it in the documentations.

**Comment by medeepaksaini** [comment]
@codecalm right now in [v1.0.0-beta17] we are unable to tigger modal using javascript as per below mention code.

`$('.modal').on('show.bs.modal', function (e) {
            console.log(e);
 })`
