### ISSUE TITLE
New color variables

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler#601]
https://primer.style/css/support/color-system
https://github.com/primer/css/blob/master/src/support/variables/color-system.scss
I think it's more useful then default BS4 colors.

**Comment by FreexD** [comment]
Tabler is based on Bootstrap and we primarily use Bootstrap color system ;) We are not planning to reimplement color scheme in tabler in the nearest future. Feel free to override bootstrap colors in your project that uses tabler if you need to. This issue is stale, I'm closing it ;)

**Comment by WinterSilence** [comment]
@FreexD 
> We are not planning to reimplement color scheme in tabler in the nearest future. 

We are voted to this? Can't find any signed issues, please post link

**Comment by WinterSilence** [comment]
@codecalm  I'm think @FreexD conceited

Compare colors: [Tabler](https://github.com/tabler/tabler/blob/dev/src/scss/_variables.scss) and [Bootstrap](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss)
