### ISSUE TITLE
Scrollable modal is broken

### ISSUE THREAD

**Issue by ollym** [tabler/tabler#604]
![image](https://user-images.githubusercontent.com/143771/79687405-44654d80-8247-11ea-92f9-7c5098a9fc78.png)

**Comment by FreexD** [comment]
![image](https://user-images.githubusercontent.com/7117869/99300855-68c0f100-284d-11eb-8a5c-c895679e47e7.png)

Fixed in 1.0.0-alpha.13 . I'm closing this issue ;)
