### ISSUE TITLE
Checkbox in lists are misaligned

### ISSUE THREAD

**Issue by ollym** [tabler/tabler#605]
https://preview-dev.tabler.io/lists.html

![image](https://user-images.githubusercontent.com/143771/79687450-9c03b900-8247-11ea-880d-21376f828760.png)

**Comment by WinterSilence** [comment]
@ollym browser + his version

**Comment by codecalm** [comment]
it look like a Chrome bug, when you resize browser tick "jumps" :/

**Comment by ollym** [comment]
Yea but the checkbox on the "Image Check" component doesn't have this bug,

**Comment by codecalm** [comment]
okay, I got it, fixed

**Comment by codecalm** [comment]
it was when input had `background-size: contain`

**Comment by ollym** [comment]
Good job 👍
