### ISSUE TITLE
Nested navigation is broken

### ISSUE THREAD

**Issue by ollym** [tabler/tabler#606]
Not sure if you intend to remove this, just creating this issue to track that it's broken currently

![image](https://user-images.githubusercontent.com/143771/79687471-c05f9580-8247-11ea-99c8-eb9cbad32756.png)

**Comment by FreexD** [comment]
![image](https://user-images.githubusercontent.com/7117869/99196637-f76e3900-278d-11eb-8350-5567c4349681.png)

It is fixed in `1.0.0-alpha.13`. I'm closing this issue :)
