### ISSUE TITLE
[BUG] Select with long option text

### ISSUE THREAD

**Issue by asaccaro** [tabler/tabler#611]
This problem appeared with alpha 6 and 7 versions, it was not present in alpha 5.

When the selected option text of a input select is too long, the height of the input select adapts to the content, mistaking the alignments with the other elements on the same row.

See screenshot for details.
<img width="1177" alt="bug select" src="https://user-images.githubusercontent.com/64075892/79858765-368f0400-83d0-11ea-9d55-2407b6b21b0e.png">

**Comment by rjd22** [comment]
This seems to be fixed now
