### ISSUE TITLE
[BUG] Flatpickr Styling

### ISSUE THREAD

**Issue by gryevns** [tabler/tabler#631]
Range & time options are not correctly styled via tabler.

**Device**

 - Browser [*]
 - OS: [*]

**To reproduce**

* Range Styles: https://jsfiddle.net/gn9801vo/
* Time Styles: https://jsfiddle.net/2oux4a7r/

**Comment by arezascarlet** [comment]
I have same trouble, and then i get solved this problem

you just need add style more 
<link href="./dist/css/tabler.min.css" rel="stylesheet"/>

//add this for styling css from vendor
<link href="./dist/css/tabler-vendors.min.css" rel="stylesheet"/>
