### ISSUE TITLE
How we should distribute new versions of tabler?

### ISSUE THREAD

**Issue by codecalm** [tabler/tabler#64]
Hi community!
For few days we repaired many fixes and added a lot of new code. 

Many questions were born after this week:
1. People want `.scss`, `.css` and `.js` files inside npm and composer packages. 
2. People want one package, instead using require.js. 
3. How often we should distribute new versions?
4. How we can add tabler to services like https://cdnjs.com, https://www.bootstrapcdn.com etc? 
 
My dream is publish packages with structure like:

```
css
|- tabler.css
|- tabler.min.css
|- tabler.rtl.css
|- tabler.rtl.min.css
|- etc.
scss
|- scss files
assets
|- important assets
js
|- tabler.js
|- tabler.min.js
|- tabler.slim.js (only most important modules, without plugins, etc)
```

I don't have much knowledge about that, but I would like to have it done well. Every help is appreciated! @beeman

**Comment by codecalm** [comment]
Btw, we have 5000 stars!! Thanks ❤️

![img1](https://user-images.githubusercontent.com/1282324/38428286-bc3c7238-39bb-11e8-9067-5248d311d3ef.png)

**Comment by sushant1221** [comment]
We can have something like that but still we will have to do many fixes. I see many things broken.
Broken means things out  of place.
I  would suggest that : 
Don't add anything new for now.
Let's make it perfect first.(no unresponsive,out of  place things)
After that we can modularize the code the way you have mentioned above.
And then we can have new features as need arises.

What do you think?

**Comment by sushant1221** [comment]
> People want .scss, .css and .js files inside npm and composer packages.
> People want one package, instead using require.js.
> How often we should distribute new versions?
> How we can add tabler to services like https://cdnjs.com, https://www.bootstrapcdn.com etc?


1. can be done but will take little time.
2. will have to check it.
3. Suggested on previous reply.
4. Since this is complete theme, Even if we add to cdn  will make no sense as particular html with classes will be required. Its better to drop the idea of point no. 4 as of now.

**Comment by tanepiper** [comment]
Hi there @codecalm is there any news on this?  I'd love to use Tabler on Stackshare as it allows URLs to static resources and ideally that would be on a CDN.

**Comment by BigChief45** [comment]
If minified CSS and JavaScript files could be distributed through a CDN that would be wonderful!

**Comment by pcgeek86** [comment]
Just tried searching the Tabler docs for a mechanism to reference Tabler via CDN, and couldn't find one. Consider this a +1!

**Comment by ansarbek** [comment]
<link href="https://tabler.github.io/tabler/assets/css/dashboard.css" rel="stylesheet">
    <script src="https://tabler.github.io/tabler/assets/js/dashboard.js"></script>
try something like this for your sandboxes
