### ISSUE TITLE
[BUG] Tags / Badges issue

### ISSUE THREAD

**Issue by akhzarjaved** [tabler/tabler#644]
**Describe the bug**

On previous version we had tags
![image](https://user-images.githubusercontent.com/50201631/83847468-bde8ca80-a725-11ea-8b7f-a1c635a460b6.png)
![image](https://user-images.githubusercontent.com/50201631/83847663-1029eb80-a726-11ea-8175-9d24202f567e.png)

On this version we have badges and it doesn't show correctly, Small and Not looking that good.
![image](https://user-images.githubusercontent.com/50201631/83847549-e2dd3d80-a725-11ea-9ea8-73cbc116adea.png)
![image](https://user-images.githubusercontent.com/50201631/83847631-056f5680-a726-11ea-97ed-e9646ca4c0b5.png)

**Device**

 - Chrome, Opera, Firefox
 - OS: Windows 10

**Comment by FreexD** [comment]
We should definitelly bring those tags back after version 1.0.0 is released :)
