### ISSUE TITLE
[BUG] No sorting icons in Datatable in tabler 1.0.0-alpha7

### ISSUE THREAD

**Issue by MickaelTH** [tabler/tabler#647]
**Describe the bug**

Datatable sorting icons are not showing.

**Device**

 - Chrome 83
 - Ubuntu 20.04
 - 1920x1080

**To reproduce**

1. Add Datatable to any page with sorting enabled
2. Sorting is working but no icons are showing

**Screenshots**

![image](https://user-images.githubusercontent.com/26375917/84905518-f64fb780-b0da-11ea-8b0c-cbc3bc6cb9de.png)

**Solution**

This is not really a solution, but here is how I worked around it:

1. Checked commit https://github.com/tabler/tabler/pull/136/commits/b00f928ec91e216315156b57231ce9c43a2a4117
2. Add new CSS rules:
`
.dataTables_wrapper{
    thead{
      .sorting{
        position: relative;
        &:after{
            position: absolute;
            right: 0;
            bottom: 5px;
            background-image: url('chevron-down.svg');
            content: '';
            background-size: 12px 12px;
            height: 12px;
            width: 12px;
            display: block;
        }
        &:before{
            position: absolute;
            right: 0;
            top: 5px;
            background-image: url('chevron-up.svg');
            content: '';
            background-size: 12px 12px;
            height: 12px;
            width: 12px;
            display: block;
        }
      }
      .sorting_desc{
        position: relative;
        &:after{
            position: absolute;
            right: 0;
            bottom: 5px;
            background-image: url('chevron-down.svg');
            content: '';
            background-size: 12px 12px;
            height: 12px;
            width: 12px;
            display: block;
        }
      }
      .sorting_asc{
        position: relative;
        &:after{
            position: absolute;
            right: 0;
            top: 5px;
            background-image: url('chevron-up.svg');
            content: '';
            background-size: 12px 12px;
            height: 12px;
            width: 12px;
            display: block;
        }
      }
    }
}
`
3. Add the images chevron up and chevron-down from https://feathericons.com/
4. Correct the path in the background-image if needed

![image](https://user-images.githubusercontent.com/26375917/84905565-05cf0080-b0db-11ea-8406-364e6f58ebbf.png)

Another solution would be to simply install the font feather, but it seems since 1.0.0-alpha7 all dependencies to the font feather are converted to SVG images, that's why I did not look at installing the fonts.

If anyone has a better solution, please let me know.

**Comment by FreexD** [comment]
Tabler has dropped support for dataTables in latest versions. It uses jQuery which we will be trying to remove as a dependency for Tabler v1.

**Comment by jonasva** [comment]
Any alternatives for something similar to datatables that would work with tabler?
