### ISSUE TITLE
Remove scroll from login and similar pages

### ISSUE THREAD

**Issue by sushant1221** [tabler/tabler#65]
Hi @codecalm  just reviewed the css.
found two body tag in dashboard.css.
But anyways for now, can you please change
` overflow-y:scroll `  
to 
`overflow:auto `
in dashboard.css body tag line number 9518.

Thanks and regards
Sushant Kumar

**Comment by codecalm** [comment]
This is especially done. If you move from one page of a site without a scrollbar to another with a scrollbar, you'll see a slight layout shift as things squeeze inward a bit to make room for the scrollbar.

**Comment by sushant1221** [comment]
But that scroller doesn't look good in login page. We need to think about different approach .
