### ISSUE TITLE
New profile cards: Bug or intentional?

### ISSUE THREAD

**Issue by fiedl** [tabler/tabler#651]
The profile card on https://preview.tabler.io/profile.html looks very nice:

<img width="534" alt="Bildschirmfoto 2020-06-28 um 19 32 06" src="https://user-images.githubusercontent.com/1679688/85954199-0dfa2c00-b976-11ea-9213-2f81e903bee0.png">

On https://preview-dev.tabler.io/profile.html, the avatar and the background image have been removed from this card:

<img width="551" alt="Bildschirmfoto 2020-06-28 um 19 33 45" src="https://user-images.githubusercontent.com/1679688/85954230-4a2d8c80-b976-11ea-8881-e0872d7b8622.png">

This might be related to https://github.com/tabler/tabler/commit/c76f1dd184183b718be34615daed4f210e629852.

I was wondering whether this change is intentional, or if this might be a bug. I would very much like to use the first kind of profile card with avatar and background image.

Thanks very much for this great template! 🎉

**Comment by colorninja** [comment]
I noticed that as well. Seems like this project is no longer maintained. Please correct me if I am wrong, @codecalm.

**Comment by fiedl** [comment]
@colorninja As a workaround, I've [added the previous css](https://github.com/fiedl/your_platform/blob/09e312fdb23a2243a30d3d87eae367c836776992/app/assets/stylesheets/bootstrap_layout.sass#L8-L25) back.

```sass
// sass

// Profile-avatar fix
// https://github.com/tabler/tabler/issues/651
//
.card-profile-img
  width: 6rem
  height: 6rem
  left: 50%
  transform: translate(-50%, 0)
  margin-top: -5rem
  margin-bottom: 1rem
  border: 3px solid #fff
  border-radius: 100%
  box-shadow: 0 1px 1px rgba(0, 0, 0, .1)
  background-color: #fff
.card-profile
  .card-header
    height: 9rem
    background-size: cover
```

I'm using this corresponding markup:

```haml
- # haml

.card.card-profile
  .card-header{style: "background-image: ..."}
  .card-body.text-center
    %img.card-profile-image{src: "..."}
    %h3 John Doe
```

I also think this project is still actively maintained. The [last update](https://github.com/tabler/tabler/commit/b078f7f13bf79250998323138c9b3d957bf7fc27) has been in May and I've received a [tabler-email](https://tabler.io/emails/) promotion mail in August.

**Comment by FreexD** [comment]
Tabler has dropped support for profile cards in latest version. We will not be bringing that back in v1. You can use profile cards available here: https://preview.tabler.io/widgets.html :)
![image](https://user-images.githubusercontent.com/7117869/100277284-35741580-2f63-11eb-987c-b8e141082550.png)
