### ISSUE TITLE
jQuery dependency 

### ISSUE THREAD

**Issue by gayanhewa** [tabler/tabler#652]
Curious about the jQuery dependency with the Bootstrap v5 upgrade. Is this still required or is the jquery dependency optional?

**Comment by gerardojbaez** [comment]
It would be great if jQuery dependency is dropped now that Tabler is using Bootstrap 5. 👀

**Comment by codecalm** [comment]
only a few more libraries use jQuery, in the next versions we will get rid of all components based on it
