### ISSUE TITLE
[FEATURE] Toggle sidebar in vertical layout

### ISSUE THREAD

**Issue by GerryGe** [tabler/tabler#659]
**Is your feature request related to a problem? Please describe.**
Now vertical layout cannot manual collapse sidebar.
How to add a toggle button in vertical layout to toggle sidebar collapse or expand? 
Docs of layout/menu/sidebar is missing also.

**Describe the solution you'd like**
https://adminlte.io/themes/v3/

Thanks.

**Comment by codecalm** [comment]
done :) https://preview.tabler.io/layout-vertical.html

**Comment by rrjanbiah** [comment]
@codecalm I can't seem to find the toggle option in https://preview.tabler.io/layout-vertical.html Refer screenshot below

![screencapture-preview-tabler-io-layout-vertical-html-2021-02-10-23_17_12](https://user-images.githubusercontent.com/4907427/107549764-375e8400-6bf6-11eb-994c-527ac10bfd8d.png)

**Comment by gerryge** [comment]
@codecalm Where is it bro?🙂

**Comment by ncullen93** [comment]
+1 for this.. seems to have been reverted

**Comment by behalp** [comment]
I can't find toggle function for vertical menu as well

**Comment by ARehmanMahi** [comment]
@codecalm HI, there is no toggle button there. Weird, been 4 years no reply on this.

**Comment by bessone** [comment]
Reviving this old conversation: has anyone made a toggle for the sidebar?
