### ISSUE TITLE
[BUG] Undefined $table-cell-padding

### ISSUE THREAD

**Issue by gayanhewa** [tabler/tabler#660]
**Describe the bug**

There seems to be a bug with a missing cell-padding variable. This happens when I try to build tabler.scss

<img width="1022" alt="Screen Shot 2020-07-07 at 1 22 21 am" src="https://user-images.githubusercontent.com/1681406/86610252-6d001680-bff0-11ea-94ff-0f22d8842dde.png">

I am on ` "tabler": "tabler/tabler#b078f7f13bf79250998323138c9b3d957bf7fc27",`

**Comment by just-Kaine** [comment]
Could be fixed by replacing **scss/ui/_tables.scss:58**
`padding: $table-cell-padding !important;`
with
`padding: $table-cell-padding-x $table-cell-padding-y !important;`

Those vars are defined in bootstrap 5's  **scss/_variables.scss:480** and **scss/_variables.scss:481**.

**Comment by colorninja** [comment]
Closed by ff6cda207e3e048f350cfe6b43c1a78a6b454aa8

**Comment by codecalm** [comment]
fixed :)
