### ISSUE TITLE
[BUG] JQuery dependency needs an update

### ISSUE THREAD

**Issue by MickaelTH** [tabler/tabler#662]
**Describe the bug**

Cross-Site Scripting (XSS) found (see screenshot below).

**Device**

N/A

**To reproduce**

1. npm audit

**Screenshots**

![image](https://user-images.githubusercontent.com/26375917/87272677-2daa5c00-c501-11ea-97ba-4520cea17d68.png)

**Comment by FreexD** [comment]
Thanks for heads up :) Bootstrap v5 does not use JQuery anymore. We will be deleting the JQuery dependency for v1 of Tabler :)

**Comment by codecalm** [comment]
jquery has been removed in #774 :)
