### ISSUE TITLE
Mobile notifications

### ISSUE THREAD

**Issue by simonschaufi** [tabler/tabler#67]
Thank you for this great theme!
I would be really happy of you could also provide mobile notifications (currently hidden in mobile and visible next to the profile avatar in the top menu). I imagine something like facebook layout: full width container. The same like the hamburger menu dropdown container, just for notifications 💚

See in action: https://touch.facebook.com/?soft=notifications

**Comment by simonschaufi** [comment]
@codecalm why did you close it?

**Comment by simonschaufi** [comment]
@codecalm why did you close it?

**Comment by codecalm** [comment]
@simonschaufi we are not currently planning on doing so
