### ISSUE TITLE
Can I integrate tabler into bootstrap-vue?

### ISSUE THREAD

**Issue by daniel-lij** [tabler/tabler#68]
Tabler is a nice bootstrap style. I would like to use a tabler in my recent projects, but I find that the tabler cannot be well compatible with bootstrap-vue. I would like to know when I can use the bootstrap-vue-tabler. Thank you

**Comment by beeman** [comment]
Hi @daniel-lij, the Vue support is being discussed in this issue: https://github.com/tabler/tabler/issues/53
