### ISSUE TITLE
How does tabler work with firewalls

### ISSUE THREAD

**Issue by linuxaos** [tabler/tabler#683]
I am sorry if this is a stupid question but here goes.

Dashing/Smashing uses Server-send requests which are blocked by my firewalls.
So, I cant use that. But, I really like tabler!

How does the tabler client (Chrome) communicate with the server (e.x. port 3000) ?
Is the update request from the client or does the server push somehow ?

Again, I am sorry if this a dupe or just dumb. I just need this info.

-George

**Comment by colorninja** [comment]
I am assuming you are taking about https://github.com/Smashing/smashing.

If that is the case, you have to create a template for it using the Tabler assets.

**Comment by FreexD** [comment]
I think that this can be somehow related to https://github.com/tabler/tabler/issues/720. It would be nice to create an example setup of how that could be made to work.
