### ISSUE TITLE
[BUG] Icons are not aligned correctly inside buttons when using the tabler-icons icon font

### ISSUE THREAD

**Issue by DanielGibbsNZ** [tabler/tabler#686]
**Describe the bug**

When using the tabler-icons icon font, the icons inside a button are not vertically aligned correctly. 

When using an SVG icon, the following styles are applied:

```
.btn svg.icon {
    width: 1em;
    height: 1em;
    stroke-width: 1.75;
}
```

However when using an icon font icon, those styles aren't applied, resulting in the icon having a `width` and `height` of `1rem` (from the `.icon` class) which causes the icon to be misaligned within the button (see screenshot below).

**Device**

 - **Browser:** Version 85.0.4183.83 (Official Build) (64-bit)
 - **OS:** macOS 10.15.4 (19E287)
 - **Screen size:** 1920x1080

**To reproduce**

Steps to reproduce the behaviour:

1. Include the tabler-icons icon font in your file
2. Add the following HTML:

```
<a class="mt-4 btn btn-primary btn-block"><i class="icon ti ti-user"></i>Manage users</a>
```

**Screenshots**

![tabler-button-icon-alignment-issue](https://user-images.githubusercontent.com/2750246/93385951-139f4800-f8bb-11ea-98a2-646f219b4373.png)

**Comment by codecalm** [comment]
fixed :) 

![Screenshot 2020-11-08 at 22 50 36](https://user-images.githubusercontent.com/1282324/98485193-d7ca9400-2214-11eb-8820-1183ccefe262.png)
![Screenshot 2020-11-08 at 22 50 13](https://user-images.githubusercontent.com/1282324/98485195-d8fbc100-2214-11eb-9bb6-c03bf6b8157b.png)

**Comment by FreexD** [comment]
It's working in version 1.0.0-alpha.13 - I'm closing this issue ;)
