### ISSUE TITLE
tabler.js:21 Uncaught ReferenceError: bootstrap is not defined

### ISSUE THREAD

**Issue by pph17383** [tabler/tabler#688]
/**
	 * Bootstrap4 dropdown plugin.
	 * @link https://getbootstrap.com/docs/4.4/components/dropdowns/
	 */
	let dropdownElementList = [].slice.call(document.querySelectorAll('[data-toggle="dropdown"]'));
	dropdownElementList.map(function (dropdownToggleEl) {
		let options = {};
		**return new bootstrap.Dropdown(dropdownToggleEl, options);**
	});
bootstrap 5 or 4.4??

**Comment by colorninja** [comment]
It's was bootstrap 5 until ff6cda207e3e048f350cfe6b43c1a78a6b454aa8.
It you are using `1.0.0-alpha.7` it's pre-alpha bootstrap 5

**Comment by pph17383** [comment]
i just load like that
**const bootstrap = window.bootstrap = require('bootstrap');**
and it's ok now... 
ty for ur response
