### ISSUE TITLE
Fullcalendar in Tabler?

### ISSUE THREAD

**Issue by isaacdarcilla** [tabler/tabler#689]
Is there  a way to implement Fullcalendar in Tabler?

**Comment by akhzarjaved** [comment]
@isaacdarcilla 
I'm using this release https://github.com/tabler/tabler/releases/tag/1.0.0-alpha.7
It has full Calendar in it
https://preview-dev.tabler.io/calendar.html

**Comment by colorninja** [comment]
This is normal. For some reason, the dev version is miles ahead from the latest released version. I have already opened an issue about that in #691

**Comment by isaacdarcilla** [comment]
> @isaacdarcilla
> I'm using this release https://github.com/tabler/tabler/releases/tag/1.0.0-alpha.7
> It has full Calendar in it
> https://preview-dev.tabler.io/calendar.html

Wow thanks

**Comment by FreexD** [comment]
Fullcalendar has recently shipped v5 where they rewrote their entire css. We will not be able to implement Fullcalendar in v1 of Tabler but it's definitelly something that we hope to do in the future. In the meanwhile Pull Requests are welcome in that area :)

**Comment by rjd22** [comment]
Since we have a calendar in tabler v2 I'm closing this one.
