### ISSUE TITLE
angular version

### ISSUE THREAD

**Issue by MetaiR** [tabler/tabler#69]
Hi,
since this is a very nice UI dashboard, I want to know do you have any plan for greate frameworks like angular (version > 2), react and etc?

**Comment by beeman** [comment]
Hey @MetaiR - I'm currently working on an Angular integration of Tabler.

Please go to this repo for the progress: [tabler/tabler-angular](https://github.com/tabler/tabler-angular). For any questions about that version, please ping me in the slack channel!

**Comment by MetaiR** [comment]
it is a good news. :+1:
