### ISSUE TITLE
[FEATURE] Publish new releases more frequently

### ISSUE THREAD

**Issue by colorninja** [tabler/tabler#691]
**Is your feature request related to a problem? Please describe.**
To people who have not used Tabler for a while it can be really confusing how the preview is different than what they get when they do `npm i tabler` or `yarn add tabler`, esspecially when `dev` is the main branch of the repo

**Describe the solution you'd like**
Release new versions more often so all of the features in preview-dev.tabler.io are available. In my opinion there is a ton of differences between the `tabler-alpha0.7` release and the `dev` branch.

Why not use the `next` tag for development?

**Describe alternatives you've considered**
Well, there are only two options at the moment:
1. Download locally, build and move compiled assets into another project.
2. Fork the repo, write a deployment script and start your own versioning by publishing to npmjs repo.  Example: [@colorninja/tabler](https://www.npmjs.com/package/@colorninja/tabler)

I have chosen the second version as I wanted to build a React TypeScript version of Tabler. There is `tabler-react` repo in the tabler namespace, but development of the TypeScript 2 version seems to be completely stopped.

I am using tabler-react in another project and it has couple of minor bugs that can be easily fixed. Also typings detected in PhpStorm are pretty non-existent for that repo.

**Comment by codecalm** [comment]
we have new forces on board, we will now publish new versions more often :)
