### ISSUE TITLE
Jekyll dependency

### ISSUE THREAD

**Issue by janschloss** [tabler/tabler#7]
Hey,

the Jekyll dependency makes this project very hard to actually use in a real project.

Are there any plans to make this CSS and HTML available as a standalone version?

**Comment by codecalm** [comment]
Hi @janschloss!
I'm newbie and this is my first open-source project. I don't have a lot of experience with this topic. 
I'm open to any suggestions. If you have any idea how to do this better I can change the code to make it more useful.

**Comment by noxify** [comment]
@janschloss - correct me if I'm wrong, but the `standalone` version is available in the `dist` directory.

**Comment by noxify** [comment]
Maybe some alternatives:
* http://assemble.io/
* https://www.staticgen.com/

**Comment by noxify** [comment]
Or maybe the simple way via https://handlebarsjs.com/ and https://www.npmjs.com/package/gulp-handlebars

**Comment by codecalm** [comment]
I would like to host static assets on https://cdnjs.com/ 
Demo files will be hosted on Github Pages from `dist/` directory

**Comment by noxify** [comment]
BTW. I have tested it with assemble. 

Yes it works, but, for me, there are some „limitations“.

For example:

In the header partial you have currently a `assign` method to get a user from the `users.yml`.

With assemble i was not able to get it work.
Also in the error templates. I had to pre-define the object ... maybe some small stuff, but requires some refactoring.

I have it currently only at my local repo but will push it tomorrow in my fork.

Maybe it’s a good startpoint or helps you to find a alternative :)

**Comment by codecalm** [comment]
@noxify Jekyll files are only for generate demo data. You can use your own backend framework to generate your dashboard. The idea was that only css and js files are required.

**Comment by stoutZero** [comment]
can you at least list the dependencies (with version) in `package.json`  
people that know webpack can do lots of stuff from the information in `package.json`  
and people that have the time to contribute can do so with relative ease :)

thanks :D

**Comment by Nilpo** [comment]
No need to overcomplicate things. Grabbing the html files and the assets folder is not that difficult. All the dependencies are self-contained except for Bootstrap and Font Awesome which are both hard-coded for CDN.

We're all devs, right? We can make a little effort to make the project our own if we're going to use it.

**Comment by stoutZero** [comment]
@Nilpo wow... dismissive...  
I gave two reasons for wanting versions, then you came and pissed & pooped all over the place... nice bruh
whatever lol

**Comment by codecalm** [comment]
@stoutZero can you make pull request with your ideas?

**Comment by stoutZero** [comment]
@codecalm I'll just go ahead and make a prototype of a webpack flow using laravel-mix over the weekend  
gonna have to reacquaintance myself with Jekyll

**Comment by codecalm** [comment]
@stoutZero it's awesome, I'll wait for you feedback! :)

**Comment by Alanaktion** [comment]
I've made a derivative project based on this called [proboot](https://github.com/Alanaktion/proboot), which might cover your use case. It's a stripped down version that only includes the SCSS, designed to be easier to integrate into standard Bootstrap 4 projects. I'd love to see this project more cleanly installable as a dependency eventually, but for now this was my solution.
