### ISSUE TITLE
[BUG] responsive menu between mobile and desktop

### ISSUE THREAD

**Issue by lafeber** [tabler/tabler#702]
The menu performs strange when the screen is a certain width. See screenshot.

**Device**
 - Screen width: 786px - 1023px 

**To reproduce**
- Go to: e.g. 'combined layout'
- Change screen width.

**Screenshots**

<img width="936" alt="Screenshot 2020-10-28 at 10 24 30" src="https://user-images.githubusercontent.com/37751/97417804-63d0e780-1908-11eb-886a-c9212176108d.png">

**Comment by colorninja** [comment]
What browser and OS are you using?

I cannot reproduce on Ubuntu 20.04 with Firefox 82.0 and Chrome 86.0.4240.111

**Comment by lafeber** [comment]
I'm using OSX, same versions of Firefox and Chrome (latest)

The issue only occurs with `demo/layout-combo.html` (dev branch) and screen width: 786px - 1023px.

**Comment by codecalm** [comment]
fixed, thank you! :) <3
