### ISSUE TITLE
Flatpickr issue

### ISSUE THREAD

**Issue by geamba93** [tabler/tabler#703]
Hi,
I use tabler in a django project and I have faced with some problems within forms. I have date field and time field in my forms. When I'm adding new object to database and select date it working great but the problem is when I open an object for editing, date field show 2020-01-01 instead my saved date. How can I show the saved date into that field?
In my form definition, I have:
    **date = forms.DateField(input_formats=['%Y-%m-%d'], widget=forms.DateInput(
            attrs={'class': 'form-control flatpickr-input', 'type': 'text', 'data-toogle': 'flatpickr'})**
With this setting, date field in editing form shows 2020-01-01 instead 2020-08-23(database value).
Date field was initialized with **flatpickr("#id_date", {});** and I already include the css and js of flatpickr.
Could anyone help me with this issue or I miss something?
Thanks in advance!

**Comment by FreexD** [comment]
I'll look into that and get back to you ;)

**Comment by FreexD** [comment]
Flatpicker has been replaced with `Litepicker` which will be the supported datepicker for Tabler v1.0
