### ISSUE TITLE
Tabler 1.0.0-alpha.9 and beyond is deprecated in NPM

### ISSUE THREAD

**Issue by DanielGibbsNZ** [tabler/tabler#707]
I've been using the `tabler` package version `1.0.0-alpha.7` via NPM and when I went to upgrade to a newer version (`alpha.9` and beyond), the package contains only the contents of https://github.com/npm/deprecate-holder.

Is this intentional?

**Comment by codecalm** [comment]
weird, I'm looking for it

**Comment by codecalm** [comment]
we'll move `tabler` and `tabler-ui` packages to `@tabler` scope

**Comment by FreexD** [comment]
`tabler` package has been moved to `@tabler/core`. `1.0.0` major version is now in active development. To get the latest `alpha` version run:
```sh
npm install @tabler/core@alpha
```

@DanielGibbsNZ the package has proper contents and should work fine now.
