### ISSUE TITLE
SCSS does not compile [BUG] 

### ISSUE THREAD

**Issue by den-vk** [tabler/tabler#708]
**Describe the bug**

I try to compile tabler.scss from scss folder, but it failure in two compilers.

**Device**
WIN7 with last KOALA 2.3.0
And siblime 3 sass compiler/

`Error: $color: "var(--tblr-btn-color, 32, 107, 196)" is not a color for 'rgba'
        on line 16 of C:\_tabler11/src/scss/ui/_buttons.scss
        from line 15 of C:\_tabler11/src/scss/_tabler-core.scss
        from line 1 of C:\_tabler11\src\scss\tabler.scss

Backtrace:
C:/_tabler11/src/scss/ui/_buttons.scss:16
C:/_tabler11/src/scss/_tabler-core.scss:15
C:\_tabler11\src\scss\tabler.scss:1
C:/Program Files/Koala/rubygems/gems/sass-3.5.2/lib/sass/script/tree/funcall.rb:315:in 'reformat_argument_error'
C:/Program Files/Koala/rubygems/gems/sass-3.5.2/lib/sass/script/tree/funcall.rb:162:in 'rescue in _perform'
C:/Program Files/Koala/rubygems/gems/sass-3.5.2/lib/sass/script/tree/funcall.rb:132:in '_perform'
C:/Program Files/Koala/rubygems/gems/sass-3.5.2/lib/sass/script/tree/node.rb:50:in '
![2020-11-11_000250](https://user-images.githubusercontent.com/74270094/98733262-50feee00-23b1-11eb-940f-26f99fbef038.png)
perform'
`

**Comment by FreexD** [comment]
I'll try reproducing this locally on windows. In the meanwhile try upgrading sass to the version required in dependencies.

**Comment by codecalm** [comment]
@den-vk KOALA 2.3.0 users old sass compiler, which can't compile css variables.  
`$color: "var(--tblr-btn-color, 32, 107, 196)"` is proper code, older compilators does'n understand it.
