### ISSUE TITLE
SCSS wrong value [BUG] 

### ISSUE THREAD

**Issue by den-vk** [tabler/tabler#709]
**Describe the bug**

Compiling error:

Error: 720%*% isn't a valid CSS value.
        on line 164 of C:/_tabler11/src/scss/bootstrap/scss/_functions.scss
        from line 41 of C:/_tabler11/src/scss/_tabler-core.scss
        from line 1 of C:\_tabler11\src\scss\tabler.scss

In _fubction.scss:
`
@function theme-color-lighter($color, $transparent: false) {
  @if ($transparent) {
    @return rgba($color, .1);
  } @else {
    @return tint-color($color, 90%);
  }
}
`

90% must be number like 9, not percents.

See bootstrap _variables.scss:
$blue-100: tint-color($blue, 8) !default;

**Comment by FreexD** [comment]
Can you try again compiling again on 1.0.0-alpha.13 version? What version of sass do you have installed locally?

**Comment by codecalm** [comment]
```
@function tint-color($color, $weight) {
  @return mix(white, $color, $weight);
}
```

tint-color users `mix` functions, which need `$weight` in percentage. This code is proper, you use older code or older compiler
