### ISSUE TITLE
Wrong SCSS files [BUG] 

### ISSUE THREAD

**Issue by den-vk** [tabler/tabler#711]
Not correct working css styling of controls like checkboxes, options, switches, selects etc. See screenshots

Version: alpha 11

![2020-11-13_152929](https://user-images.githubusercontent.com/74270094/99079489-170c3280-25d1-11eb-927c-1c6fc714ea17.png)

![2020-11-13_153013](https://user-images.githubusercontent.com/74270094/99079157-977e6380-25d0-11eb-837f-92236c8546dd.png)
![2020-11-13_162733](https://user-images.githubusercontent.com/74270094/99079161-98af9080-25d0-11eb-9229-0f0306aa189d.png)
![2020-11-13_162748](https://user-images.githubusercontent.com/74270094/99079164-98af9080-25d0-11eb-9cd7-22859fac4a00.png)

**Comment by FreexD** [comment]
@den-vk where do these screenshots come from? 
https://preview.tabler.io/form-elements.html - all looking fine to me there

![image](https://user-images.githubusercontent.com/7117869/99298996-e1727e00-284a-11eb-8a28-8f482a43e456.png)
