### ISSUE TITLE
[BUG] Alert close icon 

### ISSUE THREAD

**Issue by akhzarjaved** [tabler/tabler#712]
**Describe the bug**

Dismissible alerts close icon not on correct location

**Device**

 - Browser [Firefox v82.0.3]
 - OS: [Windows 10]
 - Screen size [1366x768]

**To reproduce**

Just open the alerts page https://preview.tabler.io/docs/alerts.html and scroll down to `Dismissible alerts`

**Screenshots**

![image](https://user-images.githubusercontent.com/50201631/99149869-72fab800-26b2-11eb-84e7-0c7eeb4a0b6d.png)

**Fix**
![image](https://user-images.githubusercontent.com/50201631/99149887-9a518500-26b2-11eb-803a-2998425a5e9e.png)

**Comment by codecalm** [comment]
fixed :)
