### ISSUE TITLE
Tabler.io- problem with npm run start

### ISSUE THREAD

**Issue by cnnnnc** [tabler/tabler#717]
Hi- I am getting this issue after trying to run the npm run start command from the tabler root directory.
The error log is below. Any guidance to solving this issue would be appreciated.

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @tabler/core@1.0.0-alpha.13~prestart: @tabler/core@1.0.0-alpha.13
6 info lifecycle @tabler/core@1.0.0-alpha.13~start: @tabler/core@1.0.0-alpha.13
7 verbose lifecycle @tabler/core@1.0.0-alpha.13~start: unsafe-perm in lifecycle true
8 verbose lifecycle @tabler/core@1.0.0-alpha.13~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\christopher\Documents\WDB-V2\tabler\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Java\jdk-14\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Ruby27-x64\bin;C:\Ruby26-x64\bin;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.3.3\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\christopher\AppData\Local\Microsoft\WindowsApps;C:\Users\christopher\AppData\Local\GitHubDesktop\bin;C:\Users\christopher\AppData\Local\Microsoft\WindowsApps;C:\Users\christopher\AppData\Roaming\npm;C:\Users\christopher\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle @tabler/core@1.0.0-alpha.13~start: CWD: C:\Users\christopher\Documents\WDB-V2\tabler
10 silly lifecycle @tabler/core@1.0.0-alpha.13~start: Args: [ '/d /s /c', 'gulp start' ]
11 silly lifecycle @tabler/core@1.0.0-alpha.13~start: Returned: code: 1  signal: null
12 info lifecycle @tabler/core@1.0.0-alpha.13~start: Failed to exec start script
13 verbose stack Error: @tabler/core@1.0.0-alpha.13 start: `gulp start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @tabler/core@1.0.0-alpha.13
15 verbose cwd C:\Users\christopher\Documents\WDB-V2\tabler
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error @tabler/core@1.0.0-alpha.13 start: `gulp start`
22 error Exit status 1
23 error Failed at the @tabler/core@1.0.0-alpha.13 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by FreexD** [comment]
Try upgrading node and npm and running
```
npm cache clean --force
npm install
npm run start 
```

**Comment by cnnnnc** [comment]
Still getting the same error after upgrading both node and npm and running your suggestions

**Comment by FreexD** [comment]
Try removing node_modules and reinstalling. If it doesn't work I'll try to reproduce this on windows and get back to you. This looks like a problem with running gulp though. Please also make sure you don't have any of tablers dependencies installed globally with incorrect versions (especially gulp).

**Comment by cnnnnc** [comment]
Got it working after doing a bundle install.
Thanks for the help!
