### ISSUE TITLE
[BUG] No user(data) on vertical layout when full screen

### ISSUE THREAD

**Issue by xciser77** [tabler/tabler#718]
**Describe the bug**

When you use the vertical layout, there is no user avatar with user option available when you use full screen. When you resize to a smaller windows, the navigation move to the top of the screen and a user avatar with menu is available.

**Device**

 - Browser: Edge, Chrome, Firefox
 - OS: Windows 10 
 - Screen size 1920 x 1080 fullscreen, 981x 1080 when navigation move to the top and avatar is available

Open layout-vertical.html, resize screen to smaller size.

**Screenshots**
![vertical-resize](https://user-images.githubusercontent.com/18699752/99266756-69449200-2823-11eb-8cc5-ec21696400e9.PNG)
![vertical-fullscreen](https://user-images.githubusercontent.com/18699752/99266763-6a75bf00-2823-11eb-8e0b-a74fadbd9a83.PNG)

**Comment by codeinaja-dev** [comment]
![image](https://user-images.githubusercontent.com/74450857/99910152-0e2d0680-2d1f-11eb-8d53-264dc9b23a81.png)
You can try on https://preview.tabler.io/layout-combo.html

**Comment by FreexD** [comment]
@xciser77 agreed with @codeinaja-dev here ;) Layout combined is what you're looking for. You can easily make top nav dark as well If you need by adding `navbar-dark` class to it.

![image](https://user-images.githubusercontent.com/7117869/100273661-68b3a600-2f5d-11eb-8c73-32fef6c7837e.png)

**Comment by aditya5660** [comment]
@FreexD , can tabler serve for combined navbar sticky and vertical sidebar ?

**Comment by FreexD** [comment]
@aditya5660 yes! Besides adding `navbar-dark` to the top nav in Layout combined, add `sticky-top` class as well ;) That worked for me ;)

![image](https://user-images.githubusercontent.com/7117869/102685904-2a1fad00-41e4-11eb-82a6-283bd552e795.png)
