### ISSUE TITLE
[FEATURE] Please display icon name for find

### ISSUE THREAD

**Issue by jet10000** [tabler/tabler#719]
https://preview.tabler.io/icons.html

Please display icon name for find.

**Comment by FreexD** [comment]
We will be shipping official `@tabler/icons` website soon - you would be able to find icons by name there.

**Comment by anhhtz** [comment]
How cloud I use simple like that 
```html
<i class="fa fa-user" />
```

**Comment by akhzarjaved** [comment]
> 
> 
> How could I use simple like that
> 
> ```
> <i class="fa fa-user" />
> ```

@anhhtz 
You need to add font awesome cdn for that. Tabler doesn't come with fontawesome.
Adding cdn will allow you to use icons like `<i class="fa fa-user"></i>`

**Comment by codecalm** [comment]
@jet10000 check now :) 
https://preview.tabler.io/icons.html 

thank you for great idea! <3
