### ISSUE TITLE
Add datepicker, timepicker, datetimepicker, datatables

### ISSUE THREAD

**Issue by akhileshdarjee** [tabler/tabler#72]
All the above libraries are must and basic requirements for an admin template.
Thanks for contributing such a beautiful template, I loved it :)

**Comment by davismiculis** [comment]
datepicker, timepicker, datetimepicker as 1 library or 3 different libraries?

**Comment by codecalm** [comment]
it will be probably one library
I'm working with new inputs on http://tabler.codecalm.net/new-inputs/form-elements.html

**Comment by akhileshdarjee** [comment]
Bootstrap datepicker like below:
https://eonasdan.github.io/bootstrap-datetimepicker/

You can also find the timepicker on the same page. A different and convenient timepicker would be good :)

Datatables:
https://datatables.net

Integrating all the above libraries with tabler theme layout.

For Datepicker, you can decorate it with the layout of calender from your page:
https://tabler.github.io/tabler/sample-cards.html

**Comment by simioluwatomi** [comment]
You forgot to include [Select2](https://select2.org/) and [Typeahead](https://github.com/twitter/typeahead.js) in your list.

**Comment by rtd62** [comment]
For those needing to add DataTables - add the following lines to the files below (was actually way easier than anticipated):

**dashboard.js**

`shim: {
'datatables': ['bootstrap', 'jquery'],
},
paths: {
'datatables.net': "assets/jquery.dataTables.min",
'datatables' : "assets/dataTables.bootstrap4.min"
}`

**The file you're using the table in**
`<script type="text/javascript">
requirejs(["datatables"], function() {
  var oTable= $('#users').dataTable({
  });
});
</script>`

_Also, don't forget to add the CSS in the header. Save the files where you would like and make sure they are called to those places in the paths._

**Comment by rtd62** [comment]
Actually, now that I mention it, I am missing something -- the tables are not responsive. Did anyone get a workaround for that?

**Comment by lucasmaldonado** [comment]
@codecalm Hello, what is the status of the datepicker?. It is highly needed. I went to check the new inputs http://tabler.codecalm.net/new-inputs/form-elements.html but the datepicker is not working.

Thank you very much!

**Comment by dsznajder** [comment]
Hi all, We started `v1` version. We will add it as a feature request to vote which part should be applied before / right-after release. Stay tuned!
