### ISSUE TITLE
[FEATURE] I need a simple tabler page to get started

### ISSUE THREAD

**Issue by linuxaos** [tabler/tabler#720]
The tabler demo is great but does anyone have a simple demo with maybe a navbar and a simple chart. I need something that I can build on and the demo is very complex. I am sure I can figure it out but a simple start would be priceless.

Now, I am reverse engineering the demo so I can create what I need. I promise to post my results. I am just getting started with tabler. Please don't judge me.

Thanks in advance.

**Comment by codecalm** [comment]
@linuxaos did you try http://localhost:3000/empty.html ? :)

**Comment by FreexD** [comment]
Tabler could use a set of examples to help developers start working with it quicker. That can be done after we finish working on version 1.0.0. In the meanwhile propositions about the form of those examples are welcome ;)

**Comment by linuxaos** [comment]
I think I could help with that since I am working through it myself. I would love to create a simple example and walk through a bit more advanced. I think I need some more time though. I am just getting started.

**Comment by Nejcc** [comment]
I found best was to use form-elements  couse in 80% u need inputs and outputs...   so  delete everything inside and you are left with  header footer and navbar :)    if you start with blank page it's a little bit hard to proper add all css in proper order.
