### ISSUE TITLE
[BUG] Vertical navigation issue on double column

### ISSUE THREAD

**Issue by akhzarjaved** [tabler/tabler#722]
**Describe the bug**

Navigation bar issue on vertical layout (Bug occurred after alpha 12)

**Device**

 - Browser [Firefox 83.0]
 - OS: [Windows 10]
 - Screen size [e.g. 1920x1080]

**Screenshots**

![image](https://user-images.githubusercontent.com/50201631/99625614-75626680-2a52-11eb-908b-e55f75cac149.png)

**Comment by codecalm** [comment]
fixed, thank you for help! :)
