### ISSUE TITLE
[BUG] Search input is not aligned properly on tablet size version

### ISSUE THREAD

**Issue by colorninja** [tabler/tabler#723]
**Describe the bug**

The search bar is show on the left side of the mobile buttons, instead of over them.

**Device**

 - Browser: Firefox 83.0 and Chrome 87.0.4280.66
 - OS: Ubuntu 20.04
 - Screen size: 576px wide - 768px wide

**To reproduce**

1. Go to preview.tabler.io
2. Resize your screen to 600px width

**Screenshots**

![image](https://user-images.githubusercontent.com/32983864/99883516-e5721780-2c1f-11eb-93ae-8d66bcfa148c.png)

**Comment by codecalm** [comment]
fixed, thank you! :)
