### ISSUE TITLE
[FEATURE] Dark mode toggle

### ISSUE THREAD

**Issue by lafeber** [tabler/tabler#724]
**Is your feature request related to a problem? Please describe.**
I love tabler dark mode - a pity that there's only page in the demo.

**Describe the solution you'd like**

The following code in the top nav bar:

        <label class="form-check form-switch nav-link">
          <input class="form-check-input  mr-1" type="checkbox" onclick="document.querySelector('body').classList.toggle('theme-dark')">
          <span class="form-check-label">Dark mode</span>
        </label>

![image](https://user-images.githubusercontent.com/37751/99970731-88e83700-2d9c-11eb-8794-e12a26dbd8f3.png)

**Describe alternatives you've considered**
A more complex solution that persists the mode in a cookie. This requires more javascript and I love the fact that tabler doesn't require any js (besides bootstrap) to work.

**Comment by FreexD** [comment]
Hi @lafeber ;) Great proposition :) This cannot fit into Tabler v1 roadmap but we will definitelly add it in future versions. In the meanwhile Pull Requests in that area are welcome :)

**Comment by kevinpapst** [comment]
A toggle is being added in #950 (changing icon in the top navbar)

**Comment by codecalm** [comment]
fixed :)
