### ISSUE TITLE
[BUG] margin-side classes not in the dist css files

### ISSUE THREAD

**Issue by alex-bello** [tabler/tabler#734]
On the [demo site](https://preview.tabler.io/), the linked css file includes classes for setting the side margin, such as `ms-1`, `ms-2`, `ms-3`, `ms-4`, `ms-5`, and `ms-auto`. However, the classes do not appear in any of the included css files in either the `@tabler/core` or `@tabler/core@alpha` npm packages.

**To reproduce**

1. Install either package above using `npm -i @tabler/core` or `npm -i @tabler/core@alpha`.
2. Navigate to the file `node_modules/@tabler/core/dist/css/tabler.min.css`.
3. Search for any of the classes listed above.
4. No results

Or

1. Navigate to `https://github.com/tabler/tabler/blob/v1.0.0-alpha.16/dist/css/tabler.css`.
2. Search for any of the classes listed above.
3. No results

**Question**
Are these classes being deprecated or are they located elsewhere? Chrome Dev Tools says the classes are located in the file `tabler.min.css`, so I'm fairly sure they're not somewhere else.

**Comment by dhimaskirana** [comment]
I have the same issue. There no class from `.me-1`, `.me-2`, `.me-3`, `.me-4`, `.me-5`, and `.me-auto`

**Comment by codecalm** [comment]
@alex-bello @dhimaskirana try newest (v1.0.0-alpha.17) version :)

**Comment by dhimaskirana** [comment]
@codecalm thank you :)

**Comment by alex-bello** [comment]
@codecalm Thanks for the quick fix!
