### ISSUE TITLE
[FEATURE] Add Bootstrap accordion

### ISSUE THREAD

**Issue by woto** [tabler/tabler#736]
**Is your feature request related to a problem? Please describe.**
Hi, I was surprised that [Bootstrap accordion](https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example) was not included in Tabler. Is there a reason? I'm trying to implement something like this https://help.admitad.com/ru/

**Describe the solution you'd like**
Add accordion to Tabler :)

**Comment by FreexD** [comment]
Hi @woto . You can implement that with ;) Everything that bootstrap has, you can do in tabler as well - but for some reason it's not included in the demo maybe ;) Please refer to https://codepen.io/freexd/pen/gOwRBbL for how you can make that work ;) We will try and add documentation on how to use accordion in Tabler as well!

**Comment by woto** [comment]
Hi, thanks. Yeah I know. But seems tabler should have some css styles for accordion. Because by default accordion looks ugly in tabler theme

**Comment by codecalm** [comment]
Hi @woto!
 
I accidentally didn't include bootstrap accordion styles to tabler, so it didn't work. I've fixed it! :) 

![Screenshot 2020-12-19 at 14 16 51](https://user-images.githubusercontent.com/1282324/102690323-dffaf380-4204-11eb-9818-78a0459dae8e.png)


Thank you for help! :)

**Comment by codecalm** [comment]
demo here: https://preview.tabler.io/accordion.html :)
