### ISSUE TITLE
Calendar page not found

### ISSUE THREAD

**Issue by mcunha98** [tabler/tabler#738]
https://preview.tabler.io/calendar.html

**Comment by codecalm** [comment]
foxed, thank you! :)

**Comment by blikblum** [comment]
As of today https://preview.tabler.io/calendar.html is not found.

This component was removed?

**Comment by benjamin-antupit** [comment]
Any updates on calendar component @codecalm? I see that https://preview.tabler.io/calendar.html is returning `404`. I'm open to submitting a PR if there's work to do on it.
