### ISSUE TITLE
[FEATURE] Documentation concerning charts

### ISSUE THREAD

**Issue by JohannesPertl** [tabler/tabler#742]
The [chart documentation](https://preview.tabler.io/docs/charts.html) is missing. 

A quick example on how to implement a basic chart would be nice.

**Comment by FreexD** [comment]
Hi @JohannesPertl ! Thanks for pointing that out ;) Tabler uses https://apexcharts.com/ library for charts. Please refer to their documentation for now. We are currently working on adding any missing documentation so feedback is much appreciated ;)

**Comment by FreexD** [comment]
It's back! 

![image](https://user-images.githubusercontent.com/7117869/116927296-c5796200-ac5b-11eb-97e3-d44230d12e1c.png)
