### ISSUE TITLE
[BUG] Yarn install fails

### ISSUE THREAD

**Issue by EdoardoLopez** [tabler/tabler#745]
**Describe the bug**
I am trying to install tabler from npm but i have problems as seen in ss, i tried install with nodejs 10.18.0, 12.20.0, 14.15.0 and fails in all cases .

**Device**

 - Browser: --
 - OS: Debian GNU/Linux 10 (buster)
 - Screen size: --

1. Try install with `yarn add @tabler/core`
2. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/11698234/102851809-bf8c8e00-43ea-11eb-8a47-2884dced3dac.png)

**Comment by FreexD** [comment]
Hi @EdoardoLopez. We're using bootstrap commit tags instead of version names in our alpha releases to be as up to date as we can ;) Maybe it is a problem with github? I've just tried it and it worked. I have the same yarn version but on Mac OS Big Sur. 

Can you also try `yarn add @tabler/core@alpha` ?

**Comment by EdoardoLopez** [comment]
Hi @FreexD thanks for your reply, don't work `yarn add @tabler/core@alpha` command i get the same error, here i paste the complete log that i get https://paste.ubuntu.com/p/2DDp89kXtz/, and happends the same error when i try add directly the github url into `pacakge.json` file like this:

`"tabler": "https://github.com/tabler/tabler#dev"`
`"tabler": "https://github.com/tabler/tabler#v1.0.0-alpha.21"`
`"tabler": "https://github.com/tabler/tabler#e7141220e328041d63f7933b1650a113e62e6774"`

**Comment by FreexD** [comment]
Looks like more of a local thing. Have you tried https://stackoverflow.com/a/62035150 ?

**Comment by EdoardoLopez** [comment]
Yep you right, was a local issue, i only clean yarn cache with `yarn cache clean`, and tried install again, and magickally worked!. Thanks!

**Comment by FreexD** [comment]
No problem ;)
