### ISSUE TITLE
[BUG] Toasts not closing

### ISSUE THREAD

**Issue by ronaldtveen** [tabler/tabler#747]
In the [preview documentation](https://preview.tabler.io/docs/toasts.html) the toast visuals are there, but not the functionality of closing (both manually or auto closing) them. 

I'm running v1.0.0-alpha.21\
If you go to the Tabler [Toast documentation](https://preview.tabler.io/docs/toasts.html) you can click on the `x` close button, nothing happens.\
If you go go the Bootstrap 5 [Toast documentation](https://getbootstrap.com/docs/5.0/components/toasts/) the `x` close button is actually functional.

Am I missing something here?

**Comment by FreexD** [comment]
Hi @ronaldtveen. Thanks for reporting the bug ;) I'll check that.
