### ISSUE TITLE
Datatables not working ?

### ISSUE THREAD

**Issue by radenvodka** [tabler/tabler#749]
![image](https://user-images.githubusercontent.com/5636480/103160391-1b01b600-4807-11eb-9676-99b28d0462aa.png)

how to using datatable ?

**Comment by FreexD** [comment]
Tabler is getting rid of datatables for version 1.0 because they have jQuery dependency. We'll be looking into some vanilla JS alternatives to include instead ;) As a workaround you can integrate tabler table styles into jQuery datatables by yourself in your project. I'll leave the topic of new datatables implementation open here - anyone interested please propose existing vanilla JS datatables implementations to include in tabler ;)

**Comment by lastingrewind** [comment]
Just include jQuery and Datatable. :)

![table-datatable](https://user-images.githubusercontent.com/76596545/103172225-f9e3a880-488c-11eb-9675-4d0dd0477976.PNG)

**Comment by radenvodka** [comment]
> Datatable

you can send me version jquery and datatable ?

**Comment by radenvodka** [comment]
okey , i solved https://github.com/Mobius1/Vanilla-DataTables

**Comment by DMW007** [comment]
The Vanilla-DataTables project is unmaintained for over 2,5 years, it's last commit is from 2018! I definitely wouldn't use that for new projects any more. But they recommend an official fork: https://github.com/fiduswriter/Simple-DataTables Simple-DataTables doesn't have a large community like jQuery DataTables but it seems to be actively maintained

**Comment by DMW007** [comment]
> 
> 
> Tabler is getting rid of datatables for version 1.0 because they have jQuery dependency. We'll be looking into some vanilla JS alternatives to include instead ;)

Generally this is a good thing: Vanilla JS got more and more standardized and usable, so there is become less demand for jQuery.
But this statement looks like if tabler just has dropped jQuery and jQuery.DataTables without having an compareable alternative? I don't see this a good thing cause jQuery.DataTables is very powerfull and it's dependency to jQuery is the only reason why I started including jQuery in my new project again. 

jQuery 3.5 has only 88KB of size, so if it just can be dropped without loosing features I'd do so, but a few KB doesn't hurt anybody and wouldn't be a reason for me to cause problems by dropping it.

I'll try Simple-DataTables if it has enough features for me, but I'd wish that there are equivalent replacements for such standard tools are found and documented before jQuery is actually dropped. Also with having in mind that jQuery.DataTables has a big active community. This would be a criteria for me cause with such features comes third-party plugins with their risks, as you can see on Vanilla-DataTables. If anybody has integrated it in the past, he has to search for alternatives and migrate to them (which can be a noticeable amount of work, depending on the project and how much it is used).
