### ISSUE TITLE
Suggestion: Move dependencies only needed for specialized functionality to optionalDependencies

### ISSUE THREAD

**Issue by rjd22** [tabler/tabler#752]
At this moment when installing tabler a lot of dependencies like full calendar, apex charts and jquery are installed while these are only needed for certain functionality that an developer might not use when installing tabler with npm.

Wouldn't it be a good idea to move most dependencies that don't have to do with the overal workings of tabler to optionalDependencies and only keeping bootstrap and other required dependencies in the required deps field?

It would make it easier for developers to avoid conflicting dependencies because of cascading dependency graphs.

What are your thoughts?

**Comment by FreexD** [comment]
Hi @rjd22 :) That's a great suggestion. I'll take a look at it before we release the first major :) I'll keep you updated here :)

**Comment by rjd22** [comment]
This now has been merged! :tada:
