### ISSUE TITLE
[FEATURE] Megamenu / Multi-categories full-width with images and submenus

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#754]
can you make menu like in this examples ?  https://codepen.io/AndreusCafe/pen/MmzLLR

**Comment by FreexD** [comment]
Hi @nejcdev! Tabler is based on bootstrap and in bootstrap 5.0 dropdowns are simple HTML elements! You can create dropdown with any content that you need by yourself! Look at some more advanced menu content examples here: https://getbootstrap.com/docs/5.0/components/dropdowns/#menu-content . They also have an example of embedding a form in a dropdown: https://getbootstrap.com/docs/5.0/components/dropdowns/#forms . Feel free to use all the power of bootstrap (+ the looks of tabler) to make your megamenu - I'm sure it's possible. In case it is something you might want to share with the community, PRs are much welcome! :)
