### ISSUE TITLE
[BUG] Problem with masonry cards

### ISSUE THREAD

**Issue by Marcolino92** [tabler/tabler#767]
Hello. i have a problem with masonry cards. As in my example picture, very often the cards overlap like this.

Here is the code I use, as in the Tabler documentation.

```
<div class="row row-cards" data-masonry='{ "percentPosition": true }'>
    <div class="col-sm-4 col-md-4 col-lg-3 d-block h-auto">
           <div class="card card-sm">
                  ..........
```

https://ibb.co/P9mhyr8

**Comment by FreexD** [comment]
Hi @Marcolino92 . Can you reproduce that in a codepen? It will be easier for me to help you :)
