### ISSUE TITLE
[FEATURE] JSON file with icons (name and svg)

### ISSUE THREAD

**Issue by JanoLampaertTechnGO** [tabler/tabler#769]
Hy,
Would it be possible to include a JSON file with the icons?

`{
    "2fa": "<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M7 16h-4l3.47 -4.66a2 2 0 1 0 -3.47 -1.54" /><path d="M10 16v-8h4" /><line x1="10" y1="12" x2="13" y2="12" /><path d="M17 16v-6a2 2 0 0 1 4 0v6" /><line x1="17" y1="13" x2="21" y2="13" /></svg>"
}`

and so on...

Greatings, Jano

**Comment by FreexD** [comment]
Hi @JanoLampaertTechnGO . The icons are available in https://github.com/tabler/tabler-icons . They are distributed in many different forms (fonts, sprite, svgs, pngs). If you need another one, PRs are welcome there :)

**Comment by JanoLampaertTechnGO** [comment]
@FreexD Thanks for your answer.
