### ISSUE TITLE
Laravel Version

### ISSUE THREAD

**Issue by ServerJunge** [tabler/tabler#77]
Hi,

does anybody has a working Laravel Version with Laravel Mix?

Thanks!

**Comment by beeman** [comment]
Hi @ServerJunge, integrations with other frameworks are discussed here #53 . I don't think Laravel has been mentioned yet, but someone might be working on it.

**Comment by takielias** [comment]
This is the Latest Laravel Admin Dashboard Scaffolding Package with built-in Auth https://github.com/takielias/tablar
