### ISSUE TITLE
[BUG] Form Helpers do not work

### ISSUE THREAD

**Issue by ronaldtveen** [tabler/tabler#772]
**Describe the bug**

Form Helpers do not work at all.

**Tabler**

 - v1.0.0-alpha.21

**To reproduce**

1. Go to https://preview.tabler.io/docs/form-helpers.html or https://preview.tabler.io/form-elements.html
2. Click/hover on the &#9432; icon
3. Nothing happens, with no errors in the console

**Comment by FreexD** [comment]
Duplicates #756

**Comment by FreexD** [comment]
Fixed :)
