### ISSUE TITLE
[FEATURE] assests compact  in one file  (for  css, js) 

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#773]
is there an options to put for development purpes  all css  to one  app.css  and  app.js ? 

If you use index or blank or form-e.  html file and you dont have  right order of css  the page broke   same for js   if it's possible to marge all files to one    will be really helpfull 

thank you!

**Comment by FreexD** [comment]
Hi @nejcdev. The main tabler css file is in `dist/css/tabler.css`. It contains all bootstrap overrides. You only need that one file to make any bootstrap based page look like tabler. If you want to override styles for more sophisticated components (like selectize or apexcharts) you should import `dist/css/tabler-vendors.css`. If you need flag or payment icons import `dist/css/tabler-flags.css` or `dist/css/tabler-payments.css`. If that's not the case, tabler provides all of it's `*.scss` files in the npm package in `src/scss` directory. You can use sass compiler to compile them into one file if you need so :)

JS files are not bundled together but they are present in the package. Practically all you need is to import bootstrap's javascript and (if you need so) other needed dependencies javascripts (like apexcharts for example). Tabler JS provides only "plugins" functionalities and initializes some bootstrap components and it's present in `dist/js.tabler.js`. 

The configuration of imports is a one time deal for every project, and you can practically just copy-paste the imports from preview - https://preview.tabler.io/ . If you would like that functionality, tabler is welcoming PRs ;)

**Comment by rjd22** [comment]
This seems to be nicely answered so closing this issue.
