### ISSUE TITLE
[BUG] Flatpicker month and year not rendering properly on firefox

### ISSUE THREAD

**Issue by rjd22** [tabler/tabler#775]
**Describe the bug**

When opening the flatpickr the month and year select are wrapped. Disabling `.flatpickr-current-month { position: absolute; width: 75%; }` makes it work properly. Eg:

Broken
```
.flatpickr-current-month {
	position: absolute;
	width: 75%;
	left: 12.5%;
	padding: 7.48px 0 0 0;
	line-height: 1;
	height: 34px;
	display: inline-block;
	text-align: center;
	-webkit-transform: translate3d(0,0,0);
	transform: translate3d(0,0,0);
}
```
Working properly
```
.flatpickr-current-month {
	left: 12.5%;
	padding: 7.48px 0 0 0;
	line-height: 1;
	height: 34px;
	display: inline-block;
	text-align: center;
	-webkit-transform: translate3d(0,0,0);
	transform: translate3d(0,0,0);
}
```

**Device**

 - Browser [e.g. Firefox 84.0.2 (64-bit)]
 - OS: [e.g. Ubuntu 20.10]
 - Screen size [e.g. 2560x1080]

**To reproduce**

1. Go to https://preview.tabler.io/form-elements.html
2. Open de datepicker on firefox by clicking on the input field
3. See the month and year are below eachother and not next to each other

**Screenshots**

![Screenshot from 2021-01-13 09-45-08](https://user-images.githubusercontent.com/160743/104428291-96dc5c00-5584-11eb-8792-fd06143086d6.png)

**Comment by FreexD** [comment]
Same on chrome after the latest update.

**Comment by FreexD** [comment]
@rjd22 we've switched to litepicker for version 1.0 - it now initializes correctly https://preview.tabler.io/form-elements.html
