### ISSUE TITLE
[BUG] NPM Package @tabler/core version does not match latest release

### ISSUE THREAD

**Issue by alex-bello** [tabler/tabler#776]
The @tabler/core NPM package is version 1.0.0-alpha.12, but the latest release is 1.0.0-alpha.22.

Our company prefers that we use packages from npmjs.org directly rather than github repos it works better with our CI tools. Is there a way to automate the publishing of new releases to npm using Github Actions?

**Comment by FreexD** [comment]
@alex-bello try @tabler/core@alpha. We're currently publishing under alpha tag since 1.0.0 is in active development and we're now releasing alpha versions currently

**Comment by FreexD** [comment]
@alex-bello you can specify `alpha` tag in your `package.json` dependencies list - look https://docs.npmjs.com/cli/v6/configuring-npm/package-json#dependencies for more details. Please, come back to me with the info whether it worked for you or not ;)

**Comment by alex-bello** [comment]
That worked! Thanks for the very quick response!
