### ISSUE TITLE
Inherit color when using buttons for card-options

### ISSUE THREAD

**Issue by JoeDawson** [tabler/tabler#78]
Hello,

When using buttons for card-options, can I suggest using the inherited color for the buttons? Since currently if I was to use a `btn-primary` class on my button the color is overwritten here;

https://github.com/tabler/tabler/blob/dev/src/assets/scss/dashboard/_cards.scss#L242

Meaning my primary button which should have white text, currently has grey.

Thanks!

**Comment by JoeDawson** [comment]
Here's an example when using `btn-primary` for a card option (via the Tabler demo).
 
![screen shot 2018-04-12 at 12 39 11](https://user-images.githubusercontent.com/1009696/38675088-937608ea-3e4e-11e8-8757-9908ae39c842.png)

**Comment by codecalm** [comment]
thanks @JoeDawson for feedback, fixed :)

**Comment by JoeDawson** [comment]
Thanks @codecalm!
