### ISSUE TITLE
[BUG] Select options in preview / docs no longer working

### ISSUE THREAD

**Issue by ronaldtveen** [tabler/tabler#781]
**Describe the bug**

Many of the elements aren't currently working. I get the following console error when visiting any of the pages of https://preview.tabler.io (including docs page):

`POSThttps://o484108.ingest.sentry.io/api/5536918/envelope/sentry_key=8e4ad02f495946f888620f9fb99fd495&sentry_version=7   [HTTP/1.1 429 Too Many Requests 109ms]`

**Devices**

 - Brave `Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)`
 - FireFox `84.0.2 (64-bit)`
 - MacOS 11.1

**To reproduce**

1. Go to https://preview.tabler.io/form-elements.html
1. Scroll down to 'Select with flags'
1. The select options are not working like they should:

<img width="1275" alt="Screenshot 2021-01-20 at 17 04 05" src="https://user-images.githubusercontent.com/7911547/105201830-996d2180-5b41-11eb-8db1-c48993779354.png">

**Comment by FreexD** [comment]
Looking good right now ;) 
![image](https://user-images.githubusercontent.com/7117869/112752882-6e85ca80-8fd5-11eb-85c1-8d5bcd774c9c.png)
