### ISSUE TITLE
Multi language support[FEATURE] 

### ISSUE THREAD

**Issue by chengzhangzuji** [tabler/tabler#782]
1、I can't find where to change other language
2、Which file can I modify to meet multil language support?

**Comment by FreexD** [comment]
@chengzhangzuji tabler does not support multi languages. It does support RTL however if you need it: https://preview.tabler.io/layout-rtl.html .  To enable it add `dir="rtl"` attribute to your `<html>` tag

**Comment by twf-nikhila** [comment]
@FreexD, when using with npm, will adding `dir="rtl"` attribute to your `<html>` tag automatically apply the design of tabler.rtl.css? Or how does it work?
