### ISSUE TITLE
Consider declaring the variables inside _variables.scss with !default

### ISSUE THREAD

**Issue by gnpretorius** [tabler/tabler#79]
This allows the developer to create a custom variables file to tweak some of the basic properties. 

Example: `$font-family-base: 'Source Sans Pro', -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif !default;`

The custom file would be included before the `bundle.scss` file. 

If there is a better / different way of doing it, let me know
Cheers

**Comment by codecalm** [comment]
okay, I will try to fix it quickly. Thanks for feedback!

**Comment by simonmilz** [comment]
+1

**Comment by tanshiqi** [comment]
+1
