### ISSUE TITLE
[FEATURE] - theme color options to have many color schemes

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#790]
Is this  duable in short release ?

**Comment by FreexD** [comment]
Hi @Nejcc - tabler has 2 main color schemes - light (https://preview.tabler.io/) and dark (https://preview.tabler.io/layout-dark.html). We are not planning to add new ones right now. Clone the tabler repo, modify sass variables and compile it into you own theme! Many tabler components come in different color variants - buttons for example (https://preview.tabler.io/buttons.html) - if that works for you instead :) If you come up with a nice theme that you would like to share with the community, PRs are much welcome!
