### ISSUE TITLE
Navigation missing in Documentation

### ISSUE THREAD

**Issue by xpacio** [tabler/tabler#800]
Hi, navigation is accesible in: Interface>Navigation;  but doesn't have a place in Documentation>Components>navigation.

**Comment by FreexD** [comment]
@xpacio thanks for letting us know! Please use the Interface>Navigation for now as an example-based documentation source.  Or find bootstrap navbar (which tabler derives from) documentation here: https://getbootstrap.com/docs/5.0/components/navbar/ . We'll try to add a documentation on our side!
