### ISSUE TITLE
Vertical Sidebar ~992px Layout Error 

### ISSUE THREAD

**Issue by htmldev29** [tabler/tabler#802]
So I was trying to use the vertical layout of Tabler; however, on ~992px, I have to dropdown the vertical sidebar. When I dropdown the layout is messed up. The profile picture if on the middle of the left side of the sidebar and the nav elements on the right side. This problem is not longer there when screen size reaches ~332px and goes back to what it was suppose to be. I'm sorry if this wasn't a good explanation, please check it out. https://preview.tabler.io/layout-combo.html

**Comment by brylocode** [comment]
@htmldev30 i can't repeat this layout behavior, can you add screenshot your doubt? because I would like to understand you perfectly

**Comment by rjd22** [comment]
Since there was not response I'm closing this
