### ISSUE TITLE
[FEATURE] support both litepicker as flatpickr

### ISSUE THREAD

**Issue by rjd22** [tabler/tabler#803]
In commit https://github.com/tabler/tabler/commit/9f107202de0c5a8df945146464ef1385a123294c flatpickr is replaced by litepicker. While litepicker is a good alternative it's not a complete replacement for flatpickr when the datepicker requires you to navigate multiple years for example.

Maybe it would be better to support both the datepickers. Because if someone of 50 years old would want to select his age now he would need to click the left arrow 600 times. ^^".

**Comment by cognvn** [comment]
Litepicker has [dropdowns option](https://litepicker.com/docs/options#dropdowns-1021)
![image](https://user-images.githubusercontent.com/45615929/108189014-db8a8280-7142-11eb-9dd1-f8058d729f0a.png)

**Comment by rjd22** [comment]
@cognvn ah that is good to see. Thx!
