### ISSUE TITLE
[BUG] Tooltips disappears

### ISSUE THREAD

**Issue by allydevper** [tabler/tabler#804]
**Describe the bug**

When the mouse is passed several times over any element, for example a button, the tooltip can disappear

**Device**

 - Test in google and edge

**To reproduce**

Hover over an item multiple times

**Screenshots**

![ezgif-4-532c3eb218f1](https://user-images.githubusercontent.com/28413681/107918875-75caaa80-6f38-11eb-9625-cb6a0b31ad4c.gif)

**Comment by FreexD** [comment]
This is a bootstrap issue... https://getbootstrap.com/docs/5.0/components/tooltips/ - check here. Maybe submit an issue there as well?

**Comment by allydevper** [comment]
> This is a bootstrap issue... https://getbootstrap.com/docs/5.0/components/tooltips/ - check here. Maybe submit an issue there as well?

I understand, Gracias.
