### ISSUE TITLE
[FEATURE/BUG] - Wider boxed layout

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#811]
can you make wider boxed layout ?   container-xl not working properly   something between container-fluid and container  will be nice to have

**Comment by nejcdev** [comment]
@brylocode  Can you make something like   max-width: 1480px; ?

**Comment by brylocode** [comment]
@nejcdev  the sizes of the containers are taken from the bootstrap :)  btw you can fork this repo and make your unlimited changes ;)
