### ISSUE TITLE
[BUG] Toggle sidebar in vertical layout - Feature #659 not found

### ISSUE THREAD

**Issue by rrjanbiah** [tabler/tabler#812]
**Describe the bug**

Feature #659 is either not working or reverted

**Device**

 - Browser: Chrome Version 88.0.4324.182 (Official Build) (64-bit)
 - OS: Ubuntu 16.04
 - Screen size: 1440x900

**To reproduce**

https://preview.tabler.io/layout-vertical.html

**Screenshots**

https://github.com/tabler/tabler/issues/659#issuecomment-776893822

**Comment by JORAWARSINGHSAINI** [comment]
I would like to work on the issue. Can I start working on it?

**Comment by FreexD** [comment]
@JORAWARSINGHSAINI sure!

**Comment by gerryge** [comment]
@JORAWARSINGHSAINI  Any updates?

**Comment by oranyero** [comment]
The same thing happens to me, it doesn't work.

**Comment by LiamAird** [comment]
Any update or am I blind? :)

**Comment by halimkilic** [comment]
Any update?
