### ISSUE TITLE
[BUG]  Sidebar in "Vertical Right" layout covers the content

### ISSUE THREAD

**Issue by alejandrodemiquel** [tabler/tabler#821]
**Description**

In the demo, the sidebar in the "Right vertical" layout covers part of the content. The sidebar is in the right side of the screen, as it should, but the content is in the same place as it is when the sidebar is on the left side.

**Device**

 - Browser Chrome version 88.0.4324.190
 - OS: Windows 10
 - Screen size: 1280x720

**To reproduce**

Just open this link: https://preview.tabler.io/layout-vertical-right.html

![tabler-bug](https://user-images.githubusercontent.com/26907188/109745443-bca6e880-7c38-11eb-8db7-5316ec143b11.png)

**Comment by codecalm** [comment]
it's fixed :)
