### ISSUE TITLE
tabler integration with Rails 6 + webpacker

### ISSUE THREAD

**Issue by wojtasss** [tabler/tabler#822]
I know it may be offtopic of this project but I have seen that in Docs you are recommending Ruby so maybe someone will now how to fully integrate tabler with webacker in Rails 6?

**Comment by divadvo** [comment]
I'm trying to use tabler with Rails 6 too. So far I'm just loading tabler's css and js from a CDN and using the generate HTML to create the layouts and pages in rails. 
Any documentation or guide would be helpful. If anyone has successfully integrated tabler into Rails 6, it would be great if you could share a guide with the community. 

Both of the following gems have not been updated in over a year. 
- https://github.com/lightyrs/tabler-rubygem
- https://github.com/resitcl/rails-tabler-webpacker-boilerplate

**Comment by kikikiblue** [comment]
I am also a newbie for webpacker & tabler. 
I had a same issue so I googled and could load tabler successfully. 
hope it can be helpful 

first, add tabler with yarn.

`yarn add @tabler/core`

add below two line at app/javascript/packs/application.js

```
import tabler from "@tabler/core"
import "../stylesheets/application"
```

from rails6, they say that we can import stylesheets with webpacker. so, 

`mkdir app/javascript/stylesheets/`

add app/javascript/stylesheets/application.scss file and add below line. 

`@import "@tabler/core";`

finally, edit layout file. app/views/layouts/application.html.erb

stylesheet_link_tag => stylesheet_pack_tag
add 'defer: true' to javascript_pack_tag if you are using turbolink.  
```
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

```

That's all.

**Comment by FreexD** [comment]
@wojtasss did @kikikiblue solution work for you? can we close this issue?
