### ISSUE TITLE
Return to Selectize.js!

### ISSUE THREAD

**Issue by JanoLampaertTechnGO** [tabler/tabler#824]
Please return back to Selectize.js instead of Choices.js in V1.0-Beta.

**Comment by ollym** [comment]
The issue was Selectize still depends on jQuery which Bootstrap v5 dropped, it doesn't therefore make sense for tabler to add a dependency that requires jQuery to be added back.

**Comment by JanoLampaertTechnGO** [comment]
Ok, thanks for the answer.
