### ISSUE TITLE
[BUG] [v1.0.0-beta2] Status badges does not seem middle

### ISSUE THREAD

**Issue by afbora** [tabler/tabler#827]
**Describe the bug**

Badges that looked correct in Beta 1 were broken in Beta 2.

**Device**

 - Chrome 89.0.4389.90
 - Windows 10
 - 1920x1080px

**To reproduce**

1. Go to https://preview.tabler.io/
2. Scroll to `Invoices` table
3. See issue

**Screenshots**

![screen-capture-901-Dashboard - Tabler - Premium and Open Source dashboard template with respon_-preview tabler io](https://user-images.githubusercontent.com/3393422/112829108-50819e00-9099-11eb-9139-bfc53eec51a9.png)

**Comment by afbora** [comment]
As workaround, i can fix the position of badge with `align-baseline` class.

````html
<span class="badge bg-success me-1 align-baseline"></span>
````

**Comment by codecalm** [comment]
fixed :)
