### ISSUE TITLE
[BUG] multi navbar menu - when using vertical sidemenu

### ISSUE THREAD

**Issue by medeepaksaini** [tabler/tabler#834]
When using a vertical sidebar, we have to use multiple navbar-nav, one for desktop and one for mobile.

this is a duplicate of code, we can use only one navbar-nav in the header and make it fixed top in the mobile menu.

also we can add a vertical menu into the body tag so, on desktop, it appears on the side along with the collapse feature, and on mobile, it fully collapses and appears from left/right (depend upon styling) when clicking on the toggle menu.

_`It's a bug & feature request!`_

**Comment by rathboma** [comment]
I also need to do this, but I think it's probably already possible with the right combo of stuff right?

**Comment by rjd22** [comment]
This doesn't seem to be the case anymore so I'm closing this.
