### ISSUE TITLE
Button's style different from Bootstrap 4 one.

### ISSUE THREAD

**Issue by ghost** [tabler/tabler#84]
I'm new to Tabler and Bootstrap. Maybe I'm writing nonsense.

In Bootstrap 4 site (http://getbootstrap.com/docs/4.1/components/buttons/) I have this **button's style**:

![image](https://user-images.githubusercontent.com/21275217/38730563-4b53dfbe-3f17-11e8-8c0b-9244055d0b0b.png)

Why in the Tabler site (https://tabler.github.io/tabler/docs/buttons.html) I have another button's style?

![tablerbuttons](https://user-images.githubusercontent.com/21275217/38730579-604c63d2-3f17-11e8-8d44-ea6dcdd95dd5.PNG)

What I think is changing is the font, right?

**Why this change**? The **Bootstrap 4 font-family is amazing**... doesn't it?

**Comment by KiarashS** [comment]
I agree with @johnunclesam

**Comment by entoil** [comment]
It is different because this is Tabler, and not Bootstrap 4.

If you want Bootstrap 4 that looks like Bootstrap 4, you should use Bootstrap 4.
If you want Bootstrap 4 that looks like Tabler, you should use Tabler.
