### ISSUE TITLE
Sticky Footer Navbar

### ISSUE THREAD

**Issue by ikramsyakir** [tabler/tabler#842]
Hi, 

How to do the footer always at the bottom of the page? Currently my footer is like this

![Screenshot 2021-04-18 at 11 30 21 PM](https://user-images.githubusercontent.com/17622728/115151133-215dbb80-a09e-11eb-87db-1db831b6663b.png)

As i know, the preview also show like this. (https://preview.tabler.io/blank.html)

Is there any solution to this? Thanks :)

**Comment by brylocode** [comment]
Check this => https://css-tricks.com/couple-takes-sticky-footer/ ;)

**Comment by ikramsyakir** [comment]
can you give some sample by using the preview?

**Comment by FreexD** [comment]
add `position: fixed; bottom: 0;` to your footer styles - https://www.w3schools.com/howto/howto_css_fixed_footer.asp . Tabler does not have a class for this.
