### ISSUE TITLE
List of deprecated tools

### ISSUE THREAD

**Issue by icdindia** [tabler/tabler#85]
Just forked and installed it and saw the following issues.
Any road map for an update?
`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`
`npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js`
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
`npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
`npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js`
`npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.`

**Comment by dsznajder** [comment]
@icdindia Thanks for the issue.

We are currently working on `v1`! I added this one to our wish-list before release. Closing for now to cleanup repository as there is no discussion ongoing :)
