### ISSUE TITLE
[FEATURE] - Adding page of changes for new releases

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#850]
Can someone add the page of changes of all partials or components that was changed or affected by new release?

This will really help visualy and quickly get the ideas of what is new or updated.

like. updates/beta-3.html,...

**Comment by FreexD** [comment]
https://preview.tabler.io/changelog.html - we're currently experimenting with updating the changelog manually. We'll probably try to create some sort of automated changelog in the future on that page. For now please use the release history in: https://github.com/tabler/tabler/releases
