### ISSUE TITLE
[BUG] Menu with sub menu does not open

### ISSUE THREAD

**Issue by MarksEliel** [tabler/tabler#852]
Operating system: Windows 10
Browser: Last version new edge, chrome, vivaldi
When accessing the demo itself, in any layout you can go to:
Interface -> Authentication and the sub menu will not open.

I'm using bootstrap 5

Just go to the demo site https://preview.tabler.io/

If you try to go to the sub menu:
Interface -> Authentication

it will not work.

print: https://prnt.sc/12opcq3

**Comment by MarksEliel** [comment]
> I can solve this

like? Would you help me?

**Comment by ak1410** [comment]
Yes

**Comment by MarksEliel** [comment]
> Yes

like?

what's the best way to fix this?

**Comment by FreexD** [comment]
@ak1410 are you currently working on the fix? Are you willing to submit a PR?

**Comment by arezascarlet** [comment]
you can fix with jquery 
`$('.dropend a.dropdown-toggle').on('click', function(e) {
    var $subMenu = $(this).children(".dropdown-menu");
    $subMenu.toggleClass('show');

    return false;
  });`

**Comment by AliTajari** [comment]
> > I can solve this
> 
> like? Would you help me?


Hey guys.
To fix this problem, Find the following code in the "tabler.js file" on line "5895".
> Dropdown.clearMenus();

You must place the above command inside the condition. like :
> if(
> 	!this._element.parentElement.classList.contains(CLASS_NAME_DROPEND)	&&
> 	this._element.parentElement.parentElement.classList.contains(CLASS_NAME_DROPEND)
> ){
> 	Dropdown.clearMenus();
> }

"Note that the tabler.min.js file is used in the demo by default."
thanks.

**Comment by AliTajari** [comment]
Hello guys.
You can use this solution to fix the problem for one more level of the sub-menu.
In the **tabler.js** file on line **5895**. put the following code snippet into the if command.
> Dropdown.clearMenus();

Like :
```
if(
	!this._element.parentElement.classList.contains(CLASS_NAME_DROPEND)	&&
	this._element.parentElement.parentElement.classList.contains(CLASS_NAME_SHOW$6)
){
	Dropdown.clearMenus();
}
```

Note that the "**tabler.min.js**" file is used in the demo.

**Comment by AliTajari** [comment]
Hello guys.
You can use this solution to fix the problem for one more level of the sub-menu.
In the **tabler.js** file on line **5895**. put the following code snippet into the if command.
`Dropdown.clearMenus();`

Like :
```
if(
	!this._element.parentElement.classList.contains(CLASS_NAME_DROPEND)	&&
	this._element.parentElement.parentElement.classList.contains(CLASS_NAME_SHOW$6)
){
	Dropdown.clearMenus();
}
```
Note that the "**tabler.min.js**" file is used in the demo.
