### ISSUE TITLE
Feature needed: Sidebar

### ISSUE THREAD

**Issue by iamkallolpratim** [tabler/tabler#86]
Hi @codecalm  ,  Can you add a sidebar on this template

**Comment by johnunclesam** [comment]
Please, PR.

**Comment by beeman** [comment]
Duplicate of #83

**Comment by neerajsinghsonu** [comment]
Hi, You can find a [demo here](https://github.com/tabler/tabler/issues/83#issuecomment-531470052)

Thank you :)
