### ISSUE TITLE
[BUG]  Alerts are not readable in dark theme

### ISSUE THREAD

**Issue by ravexina** [tabler/tabler#860]
Basically when you have an alert in dark mode, it's not readable.

**Device**
Any device.

**To reproduce**

- add `dark-theme` class to `<body>` tag. 
- add an alert to the page: `<div class="alert alert-warning>some message</div>`

**Screenshots**

![bug](https://user-images.githubusercontent.com/26504186/119024489-5bc9b980-b9b8-11eb-8652-2f0fd98c6353.png)
![hl](https://user-images.githubusercontent.com/26504186/119024500-5f5d4080-b9b8-11eb-8acc-8e6ecd6beb44.png)

What it should look like:

![fixed](https://user-images.githubusercontent.com/26504186/119024524-65ebb800-b9b8-11eb-9fd2-bf29efa75902.png)

I fixed the issue by setting `background` of `alert` to `transparent` in dark mode. I'm not an expert in front-end but I think adding `.alert` to these selectors (in `_dark.scss`) would fix the issue:

```
  .table thead th,
  .input-group-text {
    background: transparent;
  }
```

**Comment by Hei5enberg44** [comment]
Hi.
You have to put your message in a `div` with the class `text-muted` :
https://preview.tabler.io/docs/alerts.html
