### ISSUE TITLE
[FEATURE] & BUG in select suggestion - bootstrap select implemetation 

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#861]
is possible somehow implement this feature in the project [https://developer.snapappointments.com/bootstrap-select/](https://developer.snapappointments.com/bootstrap-select/) or any kind of simular select with search in it.   The problem is. if u have large collection of dropdown it's hard to find right selection / pick 

thank you

**Comment by kevinpapst** [comment]
As Tabler now demonstrates tomselect, I think this can be closed. What do you say @Nejcc ?
I have quite some experience with select2 and can tell you: tomselect is currently probably the best available select replacement - always depends on your use-case.
tomselect has a mode where you can only show 50 options from 1000 available and the other ones just show up after entering some search text. 
See https://tom-select.js.org

**Comment by codecalm** [comment]
@kevinpapst sure :)
