### ISSUE TITLE
[BUG] Tooltip init after AJAX call

### ISSUE THREAD

**Issue by Hei5enberg44** [tabler/tabler#862]
**Describe the bug**

In the previous version of Tabler, i could init a toast or a tooltip after an ajax call with this script :
```javascript
let tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
tooltipTriggerList.map(function (tooltipTriggerEl) {
    let options = {
        delay: {show: 50, hide: 50},
        html: true,
        placement: 'top'
    }
    return new bootstrap.Tooltip(tooltipTriggerEl, options)
})
```

Now, with Tabler 1.0.0-beta3 it's not working.
Is there another way to do it in this version ?

**Screenshots**

This is the error I get in the console :
![image](https://user-images.githubusercontent.com/46035253/119873795-317e7b80-bf25-11eb-8229-7d019c768c19.png)

**Comment by ashleyconnor** [comment]
Dupe? https://github.com/tabler/tabler/issues/820

**Comment by Hei5enberg44** [comment]
You are right! I build Tabler adding :
```javascript
import * as bootstrap from 'bootstrap';

window.bootstrap = bootstrap;
```

in `tabler.js` and now it works.
Many thanks!
