### ISSUE TITLE
SVG Donut, Pie Charts and Line Charts without javascript dependency

### ISSUE THREAD

**Issue by m5o** [tabler/tabler#87]
Hi @codecalm 👋 

For rendering the satisfaction donut chart and all other charts a 3rd party js library is needed. 
SVG Donut and also Pie Charts or Line charts could be easily rendered without javascript.  

🍩 https://medium.com/@heyoka/scratch-made-svg-donut-pie-charts-in-html5-2c587e935d72
📈 https://codepen.io/team/css-tricks/pen/Zbervy
📊 https://css-tricks.com/how-to-make-charts-with-svg/

What do you think? 🌻

**Comment by IbidunO** [comment]
Those resources are seem very useful.
