### ISSUE TITLE
Bootstrap's Custom File Input not showing selected file name

### ISSUE THREAD

**Issue by farhod111** [tabler/tabler#88]
When I choose file with fileinput it doesnt show me selected filename

**Comment by Eliepse** [comment]
It seems that this feature doesn't exist.
The way the file input is implemented doesn't allow to see the browser's default behaviour.
It has to be added with JavaScript.

**Comment by alejandrofloresm** [comment]
Has there been any update on this?

**Comment by matt-daneshvar** [comment]
Looks like Bootstrap itself doesn't ship with this functionality. According to [Bootstrap's docs](https://getbootstrap.com/docs/4.3/components/forms/#file-browser), they're using an additional plugin ([bs-custom-file-input](https://www.npmjs.com/package/bs-custom-file-input)) to handle this even on the documentation page demo itself.
