### ISSUE TITLE
[BUG] Color missmatch on Chats in Dark mode

### ISSUE THREAD

**Issue by jom1337** [tabler/tabler#889]
**Describe the bug**

Color missmatch on Chats in Dark mode

**Device**

 - Browser [e.g. Chrome ver.91]
 - OS: [e.g. macOS 11.4]
 - Screen size [e.g. 1920x1080]

**To reproduce**

1. Go to 'https://preview.tabler.io/layout-dark.html'
2. Hover over the top charts

![Bildschirmfoto 2021-07-08 um 04 10 30](https://user-images.githubusercontent.com/2494687/124851527-00bd4780-dfa3-11eb-907a-cc29d3a57a1d.png)

**Comment by kevinpapst** [comment]
Will be fixed by #950

**Comment by codecalm** [comment]
fixed
