### ISSUE TITLE
Can i use this in my django projects?

### ISSUE THREAD

**Issue by Hoohaha** [tabler/tabler#89]
Looks like this is very nice. How can i integrate tabler in django template?

**Comment by codecalm** [comment]
Hi @Hoohaha!
we delivery only js and css/scss files, html files are only for demo, you can use tabler in your own way

**Comment by Clivern** [comment]
@Hoohaha it is easy to use tabler with django, i already started to use it on one of my projects. It is still in dev but tabular integrated with django 
https://github.com/Clivern/Kevin/tree/issue/dev-%2326

**Comment by hendrikschneider** [comment]
just drop the assets from the dist folder in the static folder and you are good to go.

**Comment by dsznajder** [comment]
@Hoohaha Closing, as there is a lack of activity and answer appeared.
