### ISSUE TITLE
[BUG] table-striped in dark mode has incorrect colors

### ISSUE THREAD

**Issue by dheineman** [tabler/tabler#893]
**Describe the bug**

The striped table in dark mode does not have a dark accent color for the even rows which means they use the light mode color.

**Device**

 - Browser: Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)
 - OS: MacOS 11.2.3
 - Screen size: 2560×1440

**To reproduce**

1. Go to  https://preview.tabler.io/layout-dark.html
2. Find one of the tables on the page in element inspector and add the `table-striped` class

**Screenshots**
![Screenshot 2021-07-14 at 09 40 51](https://user-images.githubusercontent.com/516028/125582882-2d7f6ecb-9a49-459d-8d6d-a63dfdefcf84.png)

**Comment by rjd22** [comment]
This seems to be fixed now
