### ISSUE TITLE
SCSS Breaking Change: Slash as Division

### ISSUE THREAD

**Issue by ronaldtveen** [tabler/tabler#894]
When I compile SCSS I get the follow error (one of many):

```
   ╷
40 │ $line-height-lg: (1.5rem/$font-size-base) !default;
   │                   ^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@tabler/core/src/scss/_variables.scss 40:19  @import
    node_modules/@tabler/core/src/scss/_config.scss 3:9       @import
    node_modules/@tabler/core/src/scss/_tabler-core.scss 1:9  @import
    node_modules/@tabler/core/src/scss/tabler.scss 1:9        @import
    resources/sass/app.scss 5:9                               root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(24rem, 16)

More info and automated migrator: https://sass-lang.com/d/slash-div
```
> : 93 repetitive deprecation warnings omitted.

According to [Breaking Change: Slash as Division](https://sass-lang.com/documentation/breaking-changes/slash-div) this should be fixed before the release of Dart Sass 2.0.0

**Comment by nclavaud** [comment]
I think commit https://github.com/tabler/tabler/commit/3d6cbe85a7475cb82144e6e265bcb37383ac2f21 fixed it, so these warnings should disappear when upgrading to version `1.0.0-beta4`.

**Comment by codecalm** [comment]
fixed in https://github.com/tabler/tabler/commit/3d6cbe85a7475cb82144e6e265bcb37383ac2f21 :)
