### ISSUE TITLE
Floating point bug on Store page

### ISSUE THREAD

**Issue by zaguini** [tabler/tabler#9]
The floating point is not getting rendered correctly: https://tabler.github.io/tabler/store.html

**Comment by codecalm** [comment]
hi @zaguini 
could you send me any screenshot of this bug?

**Comment by zaguini** [comment]
apparently it's fixed 🤔 couldn't reproduce it again

**Comment by codecalm** [comment]
Sometimes I fix bugs when I see it. It probably was one of them ;)
thanks for feedback!
