### ISSUE TITLE
Integrating into NodeJS/ExpressJS asset pipeline

### ISSUE THREAD

**Issue by slavkobojanic** [tabler/tabler#90]
I’m having some issues with require.js in my expressjs environment, it seems to extend my public directory to the subdirectory of my application.

e.g. it’ll work if the current URL is localhost:3000/ but not on localhost:3000/dashboard/ since it’s trying to locate /dashboard/public/css rather than /public/css

![screen shot 2018-04-15 at 2 03 11 am](https://user-images.githubusercontent.com/914906/38770130-33d4ec58-4051-11e8-9f36-0579f8d11776.png)

Any ideas on how to fix the issue or would it be easier to just add the assets on a case by case basis

**Comment by opgrsankkar** [comment]
This does not seem like a **`tabler`** related issue.
Plus you probably did not follow `require.js` recommendations, which ask you to include baseURL in the require config.
Please refer: [http://requirejs.org/docs/api.html#jsfiles](http://requirejs.org/docs/api.html#jsfiles)

I'm just a beginner. Please forgive if I overstepped or anything.
