### ISSUE TITLE
[BUG] is-invalid-lite class is not working under 'was-validated' form class. is this inteded?

### ISSUE THREAD

**Issue by kikikiblue** [tabler/tabler#900]
**Describe the bug**

form-validation class 'is-invalid-lite' is working well in normal case. 
But if I add a class 'was-validated' to form, it does not work. (looks like 'is-invalid')
sometimes it needs to use form class 'was-validated' for showing validation of edit action or something. 
I just want to know if it is inteded or not.

**Device**

 - Chrome 92.0.4515.131 
 - OS: macOS Big Sur v11.4
 
**To reproduce**

just add a bootstrap class 'was-validated' to parent form of input.

**Comment by codecalm** [comment]
fixed :)
