### ISSUE TITLE
[BUG] Dropdown close when clicked inside

### ISSUE THREAD

**Issue by AashishChakravarty** [tabler/tabler#908]
**Describe the bug**

Dropdown with Inside click functionality is not working. dropdown menu is closed when clicking inside dropdown menu.

i have tried with `data-bs-auto-close="outside"` flag but not working.

**Device**

 - Browser Chrome Version 93.0.4577.63
 - OS: Ubuntu 20.04

**Comment by rjd22** [comment]
@AashishChakravarty What did you put the data flag on? I tried to add the `data-bs-auto-close="outside"` data flag on the button and it seems to be working correctly for me.

**Comment by rjd22** [comment]
Closing because it seems this is working without issues for me.
