### ISSUE TITLE
[feature request] Forum

### ISSUE THREAD

**Issue by ghost** [tabler/tabler#91]
Would be really cool if you can provide a forum layout on tabler theme.

Please see example site http://popforums.com/Forums
Where discussions are on a board then view topics for discussion and then view the post for the topic.

Visit the link you will understand what I mean.

**Comment by dsznajder** [comment]
Thanks for the issue.

We are currently working on `v1`! I can't check the example because of error. If anyone has some preview of this feature please add it as a new issue.
