### ISSUE TITLE
[BUG] Search bar is missing in combined view

### ISSUE THREAD

**Issue by Kdecherf** [tabler/tabler#917]
**Describe the bug**

The combined view lets the search form in the topbar.

In mobile view, this search input is missing.

**Device**

 - Browser: Firefox 93 with simulated mobile view
 - OS: [e.g. Windows 10]
 - Screen size: 428x926 (Iphone 12 Pro Max)

**To reproduce**

1. Go to https://preview.tabler.io/layout-combo.html
2. Enable mobile view (_can be done with Ctrl+Shift+M on Firefox_)

**Screenshots**
![2021-10-17-105723_425x760](https://user-images.githubusercontent.com/226063/137619908-5cb87464-ea3f-43b2-b21a-68880155a7b3.png)
![2021-10-17-105729_426x753](https://user-images.githubusercontent.com/226063/137619910-0f233c01-49a4-497f-b63b-2d8bf055ddf1.png)

**Comment by Aribaskar-jb** [comment]
i can work on this ..bug

**Comment by rayhanganteng23** [comment]
actually there are many ways to fix this bug, but maybe this help fix this bug
![code li](https://github.com/tabler/tabler/assets/103421171/2eb9959a-6c4f-4285-8f91-63ed5295c33f)
first you add the same searchbar form to the unordered list from layout-combo.html file.
![code](https://github.com/tabler/tabler/assets/103421171/d648dcde-4d49-4ac8-92a2-a6eb5da22a99)
secondly, add mediascreen to help you make searchbar disappear in certain size, in this code is min-width, when it exceeds the size, it will become disappear as it.
