### ISSUE TITLE
How can I install/use it manually without Node/NPM ?

### ISSUE THREAD

**Issue by mousaab1** [tabler/tabler#92]
Hi everyone

I've basic understadning of html/css/js, I know nothing about node or npm or ruby.
I just download the zip file and It seems hard to use it as I don't see css with each html file.

I get this error 

`npm ERR! path /Users/x/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/x/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/x/.npm/_logs/2018-04-14T18_55_44_112Z-debug.log
x-MacBook-Pro:~ x$ npm run serve
npm ERR! path /Users/x/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/x/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/x/.npm/_logs/2018-04-14T21_59_31_416Z-debug.log
x-MacBook-Pro:~ x$ 

please help

**Comment by jonthomp** [comment]
Hey @mousaab1 everything you should need you can find in the /dist folder, that contains all the html examples, css and javascript ready for you to use in your project.

All the node/npm/ruby stuff you mention is for if you want to actually contribute to this project and make changes to the source code to be released to the world which it sounds like you don't :)
