### ISSUE TITLE
Bootstrap integration

### ISSUE THREAD

**Issue by emanuelmutschlechner** [tabler/tabler#93]
Hi - I really like the look and feel of tabler!

Is there a specific reason for Bootstrap source code being in `src/assets/scss/dashboard/bootstrap`?

`src/assets/scss/bundle.scss` imports Bootstrap from `node_modules`. To ensure that the exact same package gets installed on every device I would suggest:

- use [Yarn ](https://yarnpkg.com) on top of npm. It creates a file called `yarn.lock`.
- or remove `package-lock.json` from `.gitignore` if you want to stick with npm.

Bootstrap [v4.1.0](https://github.com/twbs/bootstrap/releases/tag/v4.1.0) was released at April 9th. Potentially some compatibility issues?

**Comment by codecalm** [comment]
hi @emanuelmutschlechner!
I don't have a lot of experience with npm, yarn, etc. I'm UI dev :D 
I remove bootstrap from source code and move it to package.json
Check is it okay now, please. :)
