### ISSUE TITLE
[FEATURE] Page & Modal file manager

### ISSUE THREAD

**Issue by arisdevx** [tabler/tabler#930]
I just think the admin template would be more complete if there was a file manager UI..

Thank you.

**Comment by jaikt** [comment]
It seems a good thought, but it is not necessary. You might wanna build yourself! Btw, I'm working on one like that currently (50% done). Hope someone will implement it in future

**Comment by Nejcc** [comment]
just as a feature will be nice to have as option or module that come with same template

**Comment by kevinpapst** [comment]
Is that a mockup @hitaloramon or real existing code?

**Comment by hitaloramon** [comment]
no, it works, browse folders, files, zip, unzip, copy, paste... does it all...

**Comment by arisdevx** [comment]
wow cool.. looks like web control panel..

**Comment by hitaloramon** [comment]
> wow cool.. looks like web control panel..

Yes, it is a control panel, to create websites and many other things, it has a page editor with drag and drop, visit statistics, license system, permission system, user management, backups and several other features.

**Comment by jaikt** [comment]
um i wanna test it, can you share a URL? or a demo account?

**Comment by hitaloramon** [comment]
I don't have any demos available, all the ones that are hosted are in use by my customers

**Comment by jaikt** [comment]
Atleast A url? Is it paid?

**Comment by arisdevx** [comment]
> I made a basic model, but it would be awesome to see an interface already integrated
> 
> ![msedge_fL0uE4zyLy](https://user-images.githubusercontent.com/12436779/145470328-5209de49-9c86-4cb3-9484-8a8d35db0a8f.png) ![msedge_PE3nCJs5MR](https://user-images.githubusercontent.com/12436779/145470333-e16bf89c-084b-46ef-85f5-901e4bbd514c.png) .

does it use custom css or use bootstrap completely?
