### ISSUE TITLE
Version displayed on preview.tabler.io is wrong

### ISSUE THREAD

**Issue by nclavaud** [tabler/tabler#932]
Hi there! :wave: 

I do highly appreciate this lib and the work done so far, thanks a lot!

Lately I have been fighting with unexpected changes while upgrading to the latest beta (like font-size changes or background color changes that have been reverted later). I am completely fine with such changes, this is still in beta after all.

What makes it hard to investigate is that preview.tabler.io shows `v1.0.0-beta4` but this is actually the `dev` branch that is released. In my case (changes in `beta4` that have been reverted in `dev`), this is pretty hard to tell what is wrong (my code, or the lib).

Maybe preview.tabler.io should stick to the latest release, so the version displayed is correct?

**Comment by codecalm** [comment]
Hi @nclavaud!
I've already fixed it. Now preview shows date od last build :)
