### ISSUE TITLE
When I download, the layout is different from the preview.

### ISSUE THREAD

**Issue by raulpacheco2k** [tabler/tabler#933]
Why is the project that we can download from the official website out of date? 

I'm trying to use tabler.io in a Laravel project, however, it's not a very easy process to use with NPM, after using Laravel Mix, it ends up distorting some files and changing some colors, it would be good for the whole community if we could download the updated files.

In other words, the file we [downloaded here](https://codecalm.gumroad.com/l/tabler) differs from the [official website's layout](https://preview.tabler.io/).

**Comment by rjd22** [comment]
@raulpacheco2k tabler 2 is still in beta and not officially released. You can download these releases here:

https://github.com/tabler/tabler/releases
