### ISSUE TITLE
Unable to run | Startup Error

### ISSUE THREAD

**Issue by deepak1725** [tabler/tabler#94]
I am greeted with Error on first initial setup after all instruction well followed, :

`You have already activated public_suffix 3.0.2, but your Gemfile requires public_suffix 3.0.0. Prepending bundle exec to your command may solve this. (Gem::LoadError)`

Solved this by modifying `package.json`
"jekyll-serve": "bundle exec jekyll serve --livereload",

Kindly modify source code.

**Comment by trojano31** [comment]
+1, this fix works for me as well

**Comment by mohe2015** [comment]
The second option is to bump the version in the Gemfile and run bundle update

**Comment by dsznajder** [comment]
@deepak1725 Hi, Thank you for the issue. 
We are currently working on `v1`! I've added it to our wish-list.
