### ISSUE TITLE
Create a new (beta) release

### ISSUE THREAD

**Issue by dheineman** [tabler/tabler#949]
Hey @codecalm Is there any chance of getting a new (beta) release of tabler soon? 

There are a bunch of nice fixes in the the dev branch that i would like to have in my project and unfortunately i cannot use a git commit/branch in my environment so i have to wait for npmjs.com versions.

**Comment by codecalm** [comment]
hi, tommorow I’ll make it :)

**Comment by rjd22** [comment]
@dheineman please be patient for a moment. A lot of dark mode fixes are incoming.

**Comment by dheineman** [comment]
Yes, I spotted the merge request. No problem that is definitely worth the wait 👍

**Comment by codecalm** [comment]
@dheineman you can download now newest version :)
