### ISSUE TITLE
User movable cards on a dashboard at any time (feature request)

### ISSUE THREAD

**Issue by wille-io** [tabler/tabler#96]
All cards on the tabler dashboard are currently statically placed. It would be very useful to have the user move their cards at any time. The layout should reorganise itself after or while moving cards around on the dashboard. So that overlapped cards move away from the spot where a different card is currently hovering to.

**Comment by dsznajder** [comment]
@wille-io We will add it as a feature request and together decide if this will be included in v1 or right after. Stay tuned!
