### ISSUE TITLE
[FEATURE] - full width menu (mega menu)

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#972]
is there any good way to make mega menu to open as full width?  boxed or fluid state

**Comment by dheineman** [comment]
You have asked this before about a year ago in https://github.com/tabler/tabler/issues/754 and i think the reply from back then still stands. 

Tabler and Bootstrap are essentially UI toolkits and you can use their elements and your own custom code to create a "mega menu". There are even some examples of this online already, for example: https://bootstrap-menu.com/detail-megamenu.html.
