### ISSUE TITLE
[BUG] ".fw-..." ".fs-..." is missed

### ISSUE THREAD

**Issue by woto** [tabler/tabler#973]
Hi, may I ask a question? For me it seems a bug, but I'm not really sure that this idea correlate with "tabler.io". Today I've updated to lasted commit from main branch in hope to use relatively new "Bootstrap" classes like .fs-{X} .fw-{X} and etc and was surprised that they are absent in Tabler. Is it a bug? Or they are intentionally not included in Tabler?

I mean I need to understand "the Tabler way". It is:
1. Appending new features / stylizing bootstrap styles.
2. Removing / excluding some bootstrap classess + (point 1.)

Should I bug report in case of missed classes from official Bootstrap documentation?

Also disappointed in overriding bootstrap default styles for example I don't need capitalized badges. I always can add capitalize class. But it much harder to me to "remove" this behavior with all that "initial", "inherit", "unset", "revert", "!important" instead of just adding .text-uppercase near the .badge

#### Bootstrap
![image](https://user-images.githubusercontent.com/146704/146154933-7180b694-32c4-48ce-9882-c90832079864.png)

#### Tabler
![image](https://user-images.githubusercontent.com/146704/146155022-be1af3ad-8e77-45d2-9a9f-a029134e0dfc.png)

It is ok with styles, but it is not ok with force uppercase because I use it for displaying something like "Microsoft LLC".

Thank you.

**Comment by codecalm** [comment]
hi @woto, i've fixed it :) 

Tabler is supposed to extend the functionality and look of Bootstrap, but sometimes when overwriting core some things don't work like the original from Bootstrap. If you find such bugs, please create an issue for it :)

**Comment by woto** [comment]
Cool! Thanks @codecalm, will check later after big refactoring on the project :)
