### ISSUE TITLE
[FEATURE] Helper classes for animated icons

### ISSUE THREAD

**Issue by dheineman** [tabler/tabler#974]
**Is your feature request related to a problem? Please describe.**
I spotted on [tabler-icons.io](https://tabler-icons.io/i/alert-triangle) that the demo page shows some animated icons using the `icon-pulse` and `icon-tada` classes but i cannot find these in the tablers source so i assume they are custom code for the icons site. 

It would be a nice function to transplant these classes (and keyframes) to tabler itself as they would provide a easy utility to animate icons.

**Describe the solution you'd like**
Implement the following (and possibly more) helper classes to provide animation for icons
- icon-pulse 
- icon-tada
- icon-rotate/spin

**Describe alternatives you've considered**
Bootstrap has a spinner class for rotation but that does not allow for custom icons and if this i not something to be added to the tabler core i will add them as custom (s)css classes in my own code.

**Comment by paulftw** [comment]
that seems like a feature request for https://github.com/tabler/tabler-icons
for example font awesome includes spin animations with their CSS.

**Comment by dheineman** [comment]
tabler-icons itself does not have any distributed (s)css though, it is just a set of icons (in my project i only use the tabler sprite svg for example).

Also by implementing the helpers in tabler itself it does not limit the functionality to just projects that also use tabler-icons. Users with other icon sets or their own custom icons can then also take advantage of the helpers.
