### ISSUE TITLE
[FEATURE] Breadcrumb example

### ISSUE THREAD

**Issue by kevinpapst** [tabler/tabler#975]
We are [currently discussing](https://github.com/kevinpapst/TablerBundle/issues/21) how to implement bread crumbs in the tabler symfony bundle.

There are some [breadcrumb examples](https://preview.tabler.io/docs/breadcrumb.html) available in the docs, but I couldn't spot any usage on the demo page. 

@codecalm do you have any idea/opinion how to use them? Do you have a live example or can share your thoughts about where to place them?

@cavasinf came up with some screenshots

`Exclusive breadcrumbs looks ok`
![image](https://user-images.githubusercontent.com/25293190/145976527-76df4e0a-762d-4d4f-9511-48e1c45f97ec.png)

But everything else, if we mix buttons and breadcrumb, looks weird to me:

`Button with breadcrumb (simple example)`
![image](https://user-images.githubusercontent.com/25293190/146005209-f2be2d2b-0cc2-4678-a6e0-609d59754c96.png)

`Below title`
![image](https://user-images.githubusercontent.com/25293190/145990640-29a7480d-f150-44a6-af8b-a4407f76f23b.png)

`Above buttons`
![image](https://user-images.githubusercontent.com/25293190/146364781-f7137751-b206-4283-9912-e3c56d9e2af9.png)

`Below buttons` 
![image](https://user-images.githubusercontent.com/25293190/146364698-ef3ad114-f2a5-4811-a817-9dd0697a86bb.png)

`Left to buttons`
![image](https://user-images.githubusercontent.com/25293190/146365100-542b9740-18e9-400d-83b8-15ac0aff04fc.png)

`Right to buttons`
![image](https://user-images.githubusercontent.com/25293190/146365230-bb221769-c09e-4bdd-8a62-4b10bfc3d74f.png)

Any input is highly appreciated!

**Comment by dheineman** [comment]
my two cents: website layouts are generally constructed using a top to bottom or outside-in hierarchy and breadcrumbs are used to indicate your current location in this hierarchy. Given that they stop at the page you are currently on they should not be below the/part of the layer they indicate.

Take Github for example which provides "natural breadcrumbs". It would not make sense to add a `Home > tabler/tabler > issues > 975` below the issue subject as the further down/deeper in the page you go the more fine grained information you expect.
![Screenshot 2021-12-16 at 13 42 58](https://user-images.githubusercontent.com/516028/146375326-3738bffa-5f20-4b67-97d3-68633540242f.png)

I am not sure if i am explaining this properly as this is hard to put in words but in my personal opinion none of the provided examples show a logical placement for them. The following examples would be more appropriate.

#### As part of the header
By using the `page-pretitle`
![Screenshot 2021-12-16 at 13 27 18](https://user-images.githubusercontent.com/516028/146371951-4323c671-7679-4520-a27d-649ed1bae67e.png)
Or making the breadcrumbs part of the `page-title` (but then with no`page-pretitle`)
![Screenshot 2021-12-16 at 14 03 05](https://user-images.githubusercontent.com/516028/146377030-35936d0f-521d-46f4-b370-71db63aa47ba.png)


#### Outside of the `page-wrapper`
By moving the search elsewhere
![Screenshot 2021-12-16 at 13 13 18](https://user-images.githubusercontent.com/516028/146371721-89420cda-19a9-4d37-be14-c5adb18db928.png)
Or creating a new submenu
![Screenshot 2021-12-16 at 13 35 44](https://user-images.githubusercontent.com/516028/146373234-0f30ea2e-868b-47b7-bf5d-636525184e19.png)

**Comment by rjd22** [comment]
@kevinpapst In de documentation you can find examples of headers with the breadcrumbs.

https://preview.tabler.io/docs/page-headers.html#header-with-breadcrumb-and-actions

**Comment by kevinpapst** [comment]
@dheineman Yeah, my gut feeling was to put it in the `pretitle as. I am fan of flat structures where possible, so having the need for longer breadcrumbs is already an indication of a "bad" or "unnatural" menu design.

@rjd22 And it looks as if you propose that as well 😁 (I missed that doc, should be replicated in the breadcrumbs docs page). Thanks for the link 👍
