### ISSUE TITLE
[FEATURE] Set tabs disabled more visible/differenciable 

### ISSUE THREAD

**Issue by cavasinf** [tabler/tabler#977]
**Is your feature request related to a problem? Please describe.**

When using light mode and having tabs.
It's nearly impossible to differentiate tab "accessible" or not: 
![image](https://user-images.githubusercontent.com/25293190/146519522-37eface3-bbc6-4784-95a7-483e13a80b19.png)

```html
<li class="nav-item">
   <a data-bs-toggle="tab" class="nav-link disabled" href="#tabs-disabled">Disabled</a>
</li>
```

But it's look good on dark mode:
![image](https://user-images.githubusercontent.com/25293190/146519992-4c941ce4-9405-452f-a5fb-a0d616ca302f.png)

**Describe the solution you'd like**

If you tweak a little bit the color to be more bright, it can look like this.
![image](https://user-images.githubusercontent.com/25293190/146519635-e36f9785-67a1-426a-80dc-6f98d38d79a9.png)

**Describe alternatives you've considered**
You can override the CSS from your app.

But I think it should be a default "feature"

**Comment by codecalm** [comment]
fixed
