### ISSUE TITLE
Dropdown in card as card-options visual issue

### ISSUE THREAD

**Issue by drale2k** [tabler/tabler#98]
Using a dropdown in cards as a card-options is broken. The down-arrow is not showing and the ::hover  background on items is overlapping. See Screenshot

<img width="272" alt="bildschirmfoto 2018-04-16 um 18 16 01" src="https://user-images.githubusercontent.com/271416/38821998-764b480a-41a2-11e8-8a65-a003ff673cc2.png">

**Comment by fixr** [comment]
Bumping as I'm also running into this issue. I find it quite useful to have dropdown buttons on a `card-options`, for instance, having links or checkboxes to filter table results.

**Comment by codecalm** [comment]
fixed
