### ISSUE TITLE
[BUG] Dropdown arrow of the sidebar menu doesn't look good

### ISSUE THREAD

**Issue by dhymasriyanto** [tabler/tabler#982]
**Describe the bug**

 I'm using tabler on nuxt. I import tabler and tabler icons from nuxt plugin.
I just copy the element (sidebar) from the online documentation.
And then I can't figure out why the dropdown arrow of the sidebar menu doesn't look good.

**Device**

 - Browser: Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
 - OS: Arch Linux, Windows
 - Screen size: 1920x1080

![image](https://user-images.githubusercontent.com/32106219/147291799-40e0834d-3523-464c-8560-9ede788cebf7.png)

**Comment by dhymasriyanto** [comment]
sorry, i already fixed this. actually the css was replace with other css from bootstrap vue
I fix this with disable bootstrap-vue on my nuxt.config.js. thanks all

**Comment by rafaeldcf** [comment]
I found the same issue... What is wrong? There are two arrows for a Dropdown menu in Navbar.

<img width="298" alt="Screenshot 2023-10-29 at 10 18 53" src="https://github.com/tabler/tabler/assets/4015219/2309eeee-1e2a-4df5-816d-ae9503dcbe1a">

**Comment by dhymasriyanto** [comment]
it is probably u have 2 or more css library in ur project. in my case, i have bootstrap-vue and tabler...
