### ISSUE TITLE
[BUG] Card Header Not Dark

### ISSUE THREAD

**Issue by alighasemzadeh** [tabler/tabler#983]
head of card is not dark.

**Screenshots**
![image](https://user-images.githubusercontent.com/26847446/147358117-97357a61-bed9-4340-99d9-313c6b88f69c.png)

**Comment by kevinpapst** [comment]
They look dark to me: https://preview.tabler.io/cards.html?theme=dark

**Comment by alighasemzadeh** [comment]
Fixed.
