### ISSUE TITLE
Suggestion: Increase size of timeline-badge item

### ISSUE THREAD

**Issue by drale2k** [tabler/tabler#99]
I find it hard to distinguish between colors with the current size of timeline-badge items in timelines. I would like to suggest to increase the size to from 0.4375rem to 0.5375rem.

Before

<img width="113" alt="bildschirmfoto 2018-04-16 um 18 29 15" src="https://user-images.githubusercontent.com/271416/38822667-6ffbf88a-41a4-11e8-864d-d1746a8f0c87.png">

After

<img width="120" alt="bildschirmfoto 2018-04-16 um 18 28 58" src="https://user-images.githubusercontent.com/271416/38822680-781b0984-41a4-11e8-8ae7-26d38c227636.png">

**Comment by Jaskaran12** [comment]
i would like to solve this

**Comment by FreexD** [comment]
Timelines are available in @tabler/core 1.0.0-alpha.13 only with icon items. That makes each timeline badge color (and icon) a lot more distinguishable. Look at https://preview.tabler.io/docs/timelines.html for reference. I'm closing this issue ;)
