### ISSUE TITLE
[FEATURE] border colors consistent with background and button colors

### ISSUE THREAD

**Issue by glennbach** [tabler/tabler#990]
**Is your feature request related to a problem? Please describe.**
I'd like to take advantage of your additional background colors, but I often have to use those in conjunction with nearby borders, so they have to match. As it stands now, I'm forced to just stick with the standard bootstrap colors or define my own classes.

**Describe the solution you'd like**
It would be useful to have border colors equivalent to the background colors like border-blue, border-cyan, etc. like you have for bg-blue, bg-cyan...

**Comment by rjd22** [comment]
@glennbach I personally think this is a really user specific feature. I'm not sure many others would really need it. @codecalm what do you think?

**Comment by MaoShengXiaoXiao521** [comment]
I also need this feature!

**Comment by codecalm** [comment]
done! :)

**Comment by glennbach** [comment]
thanks!
